### PR TITLE
kafka(ticdc): support gssapi for kafka go

### LINKED ISSUE #8246: kafka sink v2 support SASL and GSSAPI
* [ ] sasl-user
* [ ] sasl-password
* [ ] sasl-mechanism
* [ ] sasl-gssapi-auth-type
* [ ] sasl-gssapi-keytab-path
* [ ] sasl-gssapi-kerberos-config-path
* [ ] sasl-gssapi-service-name
* [ ] sasl-gssapi-user
* [ ] sasl-gssapi-password
* [ ] sasl-gssapi-realm
* [ ] sasl-gssapi-disable-pafxfast

### PR DESCRIPTION
**Pull request by sdojjy**
### What problem does this PR solve?

Issue Number: close #8246

### What is changed and how it works?
support gssapi for kafka go

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Review by nongfushanquan — COMMENTED** [review]
any unit tests for the gssapi.go?

**Review by nongfushanquan — APPROVED** [review]

**Pull request merged**
