### PR TITLE
security(engine): add tls support for mysql connection

### PR DESCRIPTION
**Pull request by gozssky**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/6630

### What is changed and how it works?

Add TLS support for MySQL connection.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
https://github.com/pingcap/tiflow/pull/6913 should turn on TLS for MySQL meta store to test this feature.

BTW, please help review https://github.com/pingcap/tidb/pull/37479

**Comment by lance6716** [comment]
I forget what test I should add in https://github.com/pingcap/tiflow/pull/6913 😂

**Comment by gozssky** [comment]
@lance6716 Configuration is added in https://github.com/pingcap/tiflow/pull/6989.

**Comment by lance6716** [comment]
should be replaced by https://github.com/pingcap/tiflow/pull/7091

**Pull request closed without merging**
