### PR TITLE
api(ticdc): refactor api packages

### LINKED ISSUE #5551: TiCDC Open API v2: refactor api packages

### PR DESCRIPTION
**Pull request by sdojjy**
### What problem does this PR solve?

Issue Number: close #5551

### What is changed and how it works?
refactor api directory

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
What does `private` mean? It confuses me. Also I prefer to move the validator into  `validator` package  instead of util.

**Comment by sdojjy** [comment]
> What does `private` mean? It confuses me. Also I prefer to move the validator into `validator` package instead of util.

`private` means not an open API,  what's your suggestion?

**Review by hi-rustin — APPROVED** [review]
rest LGTM

**Pull request merged**
