### PR TITLE
binlog_filter: use table name instead of table id as cache key

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: ref #4287 

### What is changed and how it works?
- use schema/table name as cache key to filter binlog

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]
daily upstream_switch GitHub CI will test the result

**Review by buchuitoudegou — APPROVED** [review]

**Pull request merged**
