### PR TITLE
engine: fix duration not updated

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: ref #7115

### What is changed and how it works?
- introduced by https://github.com/pingcap/tiflow/pull/7711, which cause `existUnitState` not inited, so duration is not calculated

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by okJiang** [comment]
please fix the test

**Review by lance6716 — APPROVED** [review]

**Review by maxshuang — APPROVED** [review]

**Review by okJiang — APPROVED** [review]

**Pull request merged**
