### PR TITLE
test(master/scheduler): migrate test-infra to testify for master/scheduler pkg 

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/2164

### What is changed and how it works?
migrate test-infra from gocheck to testify

### Check List 

Tests 

 - Unit test

Code changes

 - None

Side effects

 - None

Related changes

 - None

### Release note 

```release-note
None.
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by Ehco1996 — APPROVED** [review]
lgtm but lint failed

**Pull request merged**
