### PR TITLE
syncer(dm): Add unit test and integration test for multi-schema change when encountering "invalid connection" error

### LINKED ISSUE #4689: dm-worker keeps retrying to execute ddl when encounter "invalid connection" error
### What did you do?

1. Replicate data from one MySQL to TiDB. 
2. Execute ddl on upstream MySQL:
```sql
ALTER TABLE xxx MODIFY COLUMN xxx SMALLINT(4) NOT NULL DEFAULT _UTF8MB4'0'
```

### What did you expect to see?

No error is reported.

### What did you see instead?

DM encountered "invalid connection" error and keeps retrying to execute ddl for every 5 minutes.

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
v2.0.6
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by lyzx2001**
<!--
Thank you for contributing to TiFlow! 
Please read MD's [CONTRIBUTING](https://github.com/pingcap/tiflow/blob/master/CONTRIBUTING.md) document **BEFORE** filing this PR.
-->

### What problem does this PR solve?
<!--
Please create an issue first to describe the problem.

There MUST be one line starting with "Issue Number:  " and 
linking the relevant issues via the "close" or "ref".

For more info, check https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/contribute-code.html#referring-to-an-issue.
 -->

Issue Number: ref #4689 

### What is changed and how it works?
I have added unit test and integration test for multi-schema change when encountering "invalid connection" error, as additional tests for #6848. The running results have proved that the current logic works correctly for the multi-schema change situation as well.

According to experiments, the behavior of DM and TiDB is slightly different for multi-schema change.
Suppose we execute `ALTER TABLE gbk.invalid_conn_test2 MODIFY i SMALLINT NOT NULL DEFAULT '0', MODIFY j SMALLINT NOT NULL DEFAULT '0'` in DM and manually in TiDB separately.

For DM:
```
mysql>  ADMIN SHOW DDL JOBS;
+--------+---------+--------------------+-----------------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
| JOB_ID | DB_NAME | TABLE_NAME         | JOB_TYPE                          | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE  |
+--------+---------+--------------------+-----------------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
|   1140 | gbk     | invalid_conn_test2 | modify column                     | public       |      1102 |     1135 |         0 | 2022-09-15 19:13:25 | 2022-09-15 19:13:25 | 2022-09-15 19:13:27 | synced |
|   1139 | gbk     | invalid_conn_test2 | modify column                     | public       |      1102 |     1135 |         0 | 2022-09-15 19:13:22 | 2022-09-15 19:13:22 | 2022-09-15 19:13:25 | synced |
| ...                                                                                                                                                                                                    |
+--------+---------+--------------------+-----------------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+--------+
10 rows in set (0.01 sec)
```

```
mysql> ADMIN SHOW DDL JOB QUERIES LIMIT 10 OFFSET 0;
+--------+----------------------------------------------------------------------------------------------------------------------------------------+
| JOB_ID | QUERY                                                                                                                                  |
+--------+----------------------------------------------------------------------------------------------------------------------------------------+
| 1140   | ALTER TABLE `gbk`.`invalid_conn_test2` MODIFY COLUMN `j` SMALLINT(4) NOT NULL DEFAULT '0'                                              |
| 1139   | ALTER TABLE `gbk`.`invalid_conn_test2` MODIFY COLUMN `i` SMALLINT(4) NOT NULL DEFAULT '0'                                              |
| ...                                                                                                                                             |
+--------+----------------------------------------------------------------------------------------------------------------------------------------+
10 rows in set (0.00 sec)

```

The multi-schema change DDL would be separated into two or more single DDL, and are executed by order one by one.

For manually operated in TiDB:
```
mysql> ADMIN SHOW DDL JOBS;
+--------+------------------+--------------------+---------------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------------+
| JOB_ID | DB_NAME          | TABLE_NAME         | JOB_TYPE                        | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE         |
+--------+------------------+--------------------+---------------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------------+
|   2273 | gbk              | invalid_conn_test2 | alter table multi-schema change | none         |      2204 |     2271 |         0 | 2022-09-16 19:43:36 | 2022-09-16 19:43:36 | 2022-09-16 19:43:43 | synced        |
|   2273 | gbk              | invalid_conn_test2 | modify column /* subjob */      | public       |      2204 |     2271 |         0 | NULL                | NULL                | NULL                | done          |
|   2273 | gbk              | invalid_conn_test2 | modify column /* subjob */      | public       |      2204 |     2271 |         0 | NULL                | NULL                | NULL                | done          |
| ...                                                                                                                                                                                                                  |
+--------+------------------+--------------------+---------------------------------+--------------+-----------+----------+-----------+---------------------+---------------------+---------------------+---------------+
18 rows in set (0.01 sec)

```

```
mysql> ADMIN SHOW DDL JOB QUERIES LIMIT 10 OFFSET 0;
+--------+-------------------------------------------------------------------------------------------------------------------+
| JOB_ID | QUERY                                                                                                             |
+--------+-------------------------------------------------------------------------------------------------------------------+
| 2273   | ALTER TABLE gbk.invalid_conn_test2 MODIFY i SMALLINT NOT NULL DEFAULT '0', MODIFY j SMALLINT NOT NULL DEFAULT '0' |
| ...                                                                                                                        |
+--------+-------------------------------------------------------------------------------------------------------------------+
10 rows in set (0.01 sec)
```
The multi-schema change DDL would be separated into two or more subjob. The history returned by `ADMIN SHOW DDL JOBS` would contain both the subjobs and the original multi-schema change job. The history returned by `ADMIN SHOW DDL JOB QUERIES LIMIT 10 OFFSET 0` would only contain the original multi-schema change job but not the subjobs.

I have added a unit test to test the manual TiDB situations since other unit tests have already covered the DM situations. I have added several integration tests to test the DM situations.

### Check List <!--REMOVE the items that are not applicable-->

#### Tests <!-- At least one of them must be included. -->

 - Unit test
 - Integration test

#### Questions <!-- Authors should answer these questions and reviewers should consider these questions. -->

##### Will it cause performance regression or break compatibility?
No.
##### Do you need to update user documentation, design documentation or monitoring documentation?
No.
### Release note <!-- bugfixes or new feature need a release note -->

```release-note
Fix the issue that dm-worker keeps retrying to execute ddl for every 5 minutes when encountering "invalid connection" error (works for multi-schema change as well).
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
/hold

waiting refine tests and codes

**Comment by lance6716** [comment]
/hold

need to fix CI

**Pull request merged**
