### PR TITLE
test(dm): fix some unstable tests

### LINKED ISSUE #5732: GENERATED ALWAYS AS(`id`+2) VIRTUAL count: 0 != expected: 1
### Which jobs are flaking?

shardddl2 DM-043

### Which test(s) are flaking?

DM-IT
release-6.1

### Jenkins logs or GitHub Actions link

```log
[2022-06-01T13:02:09.329Z]                         "conflictMsg": "[code=11111:class=functional:scope=internal:level=medium], Message: fail to try sync the optimistic shard ddl lock test-`shardddl`.`tb`: there will be conflicts if DDLs ALTER TABLE `shardddl`.`tb` ADD COLUMN `new_col1` INT GENERATED ALWAYS AS(`id`+1) VIRTUAL are applied to the downstream. old table info: CREATE TABLE `tbl`(`id` INT(11) NOT NULL, PRIMARY KEY (`id`)) CHARSET UTF8MB4 COLLATE UTF8MB4_BIN, new table info: CREATE TABLE `tbl`(`id` INT(11) NOT NULL, `new_col1` INT(11) GENERATED ALWAYS AS (`id` + 1), PRIMARY KEY (`id`)) CHARSET UTF8MB4 COLLATE UTF8MB4_BIN, Workaround: Please use `show-ddl-locks` command for more details."
```
https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/6423/pipeline/

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### LINKED ISSUE #5733: ERROR 1146 (42S02) at line 1: Table 'sharding_seq_tmp.t1' doesn't exist
### Which jobs are flaking?

sequence_sharding_optimistic

### Which test(s) are flaking?

DM-IT
release-6.1

### Jenkins logs or GitHub Actions link

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/6418/pipeline/

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### LINKED ISSUE #5807: flaking test ALTER TABLE `shardddl`.`tb` ADD COLUMN `new_col1` INT DEFAULT -1
### Which jobs are flaking?

DM-037

### Which test(s) are flaking?

DM-IT

### Jenkins logs or GitHub Actions link

```log


[2022-06-08T12:48:56.057Z] command: query-status test ALTER TABLE `shardddl`.`tb` ADD COLUMN `new_col1` INT DEFAULT -1 count: 0 != expected: 1, failed the 9-th time, will retry again

[2022-06-08T12:48:57.957Z] {

[2022-06-08T12:48:57.957Z]     "result": true,

[2022-06-08T12:48:57.957Z]     "msg": "",

[2022-06-08T12:48:57.957Z]     "sources": [

[2022-06-08T12:48:57.957Z]         {

[2022-06-08T12:48:57.957Z]             "result": true,

[2022-06-08T12:48:57.957Z]             "msg": "",

[2022-06-08T12:48:57.957Z]             "sourceStatus": {

[2022-06-08T12:48:57.957Z]                 "source": "mysql-replica-01",

[2022-06-08T12:48:57.957Z]                 "worker": "worker1",

[2022-06-08T12:48:57.957Z]                 "result": null,

[2022-06-08T12:48:57.957Z]                 "relayStatus": null

[2022-06-08T12:48:57.957Z]             },

[2022-06-08T12:48:57.957Z]             "subTaskStatus": [

[2022-06-08T12:48:57.957Z]                 {

[2022-06-08T12:48:57.957Z]                     "name": "test",

[2022-06-08T12:48:57.957Z]                     "stage": "Running",

[2022-06-08T12:48:57.957Z]                     "unit": "Sync",

[2022-06-08T12:48:57.957Z]                     "result": null,

[2022-06-08T12:48:57.957Z]                     "unresolvedDDLLockID": "",

[2022-06-08T12:48:57.957Z]                     "sync": {

[2022-06-08T12:48:57.957Z]                         "totalEvents": "1",

[2022-06-08T12:48:57.957Z]                         "totalTps": "0",

[2022-06-08T12:48:57.957Z]                         "recentTps": "0",

[2022-06-08T12:48:57.957Z]                         "masterBinlog": "(dm-integration-test-go1180-6634-8856f-drp91-bin.000001, 53837)",

[2022-06-08T12:48:57.957Z]                         "masterBinlogGtid": "8fbd1901-e728-11ec-9dd6-1292de8d5fed:1-247",

[2022-06-08T12:48:57.957Z]                         "syncerBinlog": "(dm-integration-test-go1180-6634-8856f-drp91-bin.000001, 52345)",

[2022-06-08T12:48:57.957Z]                         "syncerBinlogGtid": "8fbd1901-e728-11ec-9dd6-1292de8d5fed:1-241",

[2022-06-08T12:48:57.957Z]                         "blockingDDLs": [

[2022-06-08T12:48:57.957Z]                         ],

[2022-06-08T12:48:57.957Z]                         "unresolvedGroups": [

[2022-06-08T12:48:57.957Z]                         ],

[2022-06-08T12:48:57.957Z]                         "synced": false,

[2022-06-08T12:48:57.957Z]                         "binlogType": "remote",

[2022-06-08T12:48:57.957Z]                         "secondsBehindMaster": "0",

[2022-06-08T12:48:57.957Z]                         "blockDDLOwner": "mysql-replica-01-`shardddl1`.`tb1`",

[2022-06-08T12:48:57.957Z]                         "conflictMsg": "[code=11111:class=functional:scope=internal:level=medium], Message: fail to try sync the optimistic shard ddl lock test-`shardddl`.`tb`: there will be conflicts if DDLs ALTER TABLE `shardddl`.`tb` ADD COLUMN `new_col1` INT DEFAULT 0 are applied to the downstream. old table info: CREATE TABLE `tbl`(`id` INT(11) NOT NULL, PRIMARY KEY (`id`)) CHARSET UTF8MB4 COLLATE UTF8MB4_BIN, new table info: CREATE TABLE `tbl`(`id` INT(11) NOT NULL, `new_col1` INT(11) DEFAULT 0, PRIMARY KEY (`id`)) CHARSET UTF8MB4 COLLATE UTF8MB4_BIN, Workaround: Please use `show-ddl-locks` command for more details."
```

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/6634/pipeline

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #5732 close #5733 close #5807

#### Tests 

 - No code

##### Will it cause performance regression or break compatibility?
 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by WizardXiao — APPROVED** [review]

**Comment by lance6716** [comment]
PTAL @Ehco1996

**Review by Ehco1996 — APPROVED** [review]

**Pull request merged**
