### PR TITLE
test(cdc): fix incompatible duplicate entry error message of tidb

### LINKED ISSUE #7409: CDC: incompatible `duplicate entry` error message of tidb fails the `tidb-mysql-test` tests
### What did you do?

Run cdc integration test `tidb-mysql-test`

### What did you expect to see?

Run successfully

### What did you see instead?

Run fail because following result is not the same:
```
DROP TABLE IF EXISTS t;
CREATE TABLE t (c1 int, c2 integer, c3 int, c4 int, primary key(c1));
INSERT INTO t (c1, c2, c3) VALUES(11, 22, 33);
INSERT INTO t (c1, c2, c3) VALUES(11, 22, 33);
Error 1062: Duplicate entry '11' for key 'PRIMARY'
```

This is caused by the pr: https://github.com/pingcap/tidb/commit/9743a9a2d2c626acbd7e13d4693cca9c58f329b7

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
9743a9a2d2c626acbd7e13d4693cca9c58f329b7
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
master
```

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve?

Issue Number: close #7409 

### What is changed and how it works?
add table name to 'duplicate entry' error message for tidb-mysql-test to compatible with pr https://github.com/pingcap/tidb/commit/9743a9a2d2c626acbd7e13d4693cca9c58f329b7

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

**Review by nongfushanquan — APPROVED** [review]

**Comment by maxshuang** [comment]
The tidb pr that causes the incompatible problem is on the master but not in release-6.3 or other release

**Pull request merged**
