### PR TITLE
pulsar (ticdc): add pulsar integration test 1

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve?

Issue Number: ref #9782 

### What is changed and how it works?
This pull request add 41 integration test cases for pulsar sink feature.

#### Tests 

 - Integration test
 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by asddongmen** [comment]
ping @CharlesCheung96 PTAL

**Review by 3AceShowHand — APPROVED** [review]

**Review by sdojjy — APPROVED** [review]

**Pull request merged**
