### PR TITLE
processor/sinkmanager(ticdc): refine error handle and skip empty event

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/7674

### What is changed and how it works?
[processor/sinkmanager(ticdc): fix error handle bug](https://github.com/pingcap/tiflow/commit/2a6919f09326379c0e26599d83f9ca17d8a324a6)

[processor/sinkmanager(ticdc): fix error filtered events bug](https://github.com/pingcap/tiflow/commit/a1e21e0a61041829689a24faf3767ffd23ed4f46)

[processor/sinkmanager(ticdc): fix data race in event sorter](https://github.com/pingcap/tiflow/commit/a5ea8b5ff09ee5a28930506cde6201a7c262a0a3)
#### Tests 

 - Unit test

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
None
```

### CODE REVIEW

**Review by nongfushanquan — APPROVED** [review]

**Comment by hi-rustin** [comment]
@ti-chi-bot wake up~

**Pull request merged**
