### PR TITLE
docs/media(ticdc): update cdc architecture

### LINKED ISSUE #4564: Update cdc architecture picture
Remove deprecated incermental backup and experimental Pulsar support.

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: close #4564

### What is changed and how it works?

Update cdc architecture

### Check List 

Tests 

 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by amyangfei — COMMENTED** [review]
Seems `incremental backup` is deprecated now.

**Comment by leoppro** [comment]
LGTM

**Review by leoppro — APPROVED** [review]

**Pull request merged**
