### PR TITLE
sink(ticdc): remove pulsar sink

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/7087

### What is changed and how it works?
remove pulsar sink.

#### Tests 

 - Unit test

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
See: https://github.com/pingcap/docs-cn/pull/11112
### Release note 

```release-note
Delete the deprecated pulsar sink
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/hold

PLEASE DO NOT MERGE THIS PR.

**Review by hi-rustin — COMMENTED** [review]
Self check

**Review by nongfushanquan — APPROVED** [review]

**Comment by leoppro** [comment]
LGTM

**Review by asddongmen — APPROVED** [review]

**Review by leoppro — APPROVED** [review]

**Pull request merged**
