### PR TITLE
sink(ticdc): reduce log print when using CDC sync data to Kafka with nil values in column 

### LINKED ISSUE #11537: The log prints too much when using CDC sync data to Kafka with nil values in column
### What did you do?

As described in https://asktug.com/t/topic/1031144.
The following warning logs are printed at a rate of 4G per minute.
```
[2024/08/21 09:48:31.344 +08:00] [WARN] [sink.go:488] [“meet nil column data, should not happened in production env”] [cols=“[{"column_id":1,"value":2594073387516685639},{"column_id":2,"value":"NDIzZThmMTE5YjU5YzI3MmJkMWNjN2JlZDUxZmYwOGE="},{"column_id":3,"value":"MTMxNTM1NDky"},{"column_id":4,"value":"MjAyMw=="},{"column_id":5,"value":"NDQwMzA2MTE3MDE2NzIz"},{"column_id":6,"value":"OTE0NDAzMDBNQTVESEs2UjQ3"},null,{"column_id":8,"value":"5rex5Zyz5biC5aSn5qKB5Zu95Yib56eR5oqA5pyJ6ZmQ5YWs5Y+4"},{"column_id":9,"value":"MjAyM+W5tOW6puaKpeWRig=="},{"column_id":10,"value":"MjAyNC0wOC0xMg=="},{"column_id":11,"value":null},{"column_id":12,"value":null},{"column_id":13,"value":null},{"column_id":14,"value":"MTM1MTA0OTIzMjE="},{"column_id":15,"value":"MTA0NjQ5NDIwNEBxcS5jb20="},{"column_id":16,"value":null},{"column_id":17,"value":null},{"column_id":18,"value":null},{"column_id":19,"value":null},{"column_id":20,"value":null},{"column_id":21,"value":"5rex5Zyz5biC5a6d5a6J5Yy65rKZ5LqV6KGX6YGT5aOG5bKX5Y2O576O5bGFM+agizIwMDg="},
``` 

### What did you expect to see?

maybe we can consider setting cols data at the debug level.

### What did you see instead?

All column data was printed.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):
v8.1

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by wk989898**
### What problem does this PR solve?

Issue Number: close #11537 

### What is changed and how it works?
As title.

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Review by lidezhu — APPROVED** [review]

**Comment by wuhuizuo** [comment]
> @wuhuizuo: The label(s) `?` cannot be applied. These labels are supported: `duplicate, bug-from-internal-test, bug-from-user, ok-to-test, needs-ok-to-test, affects-5.4, affects-6.1, affects-6.5, affects-7.1, affects-7.5, affects-8.1, affects-8.3, may-affects-5.4, may-affects-6.1, may-affects-6.5, may-affects-7.1, may-affects-7.5, may-affects-8.1, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.3, question, release-blocker, wontfix, MariaDB`.

@wk989898 cc

**Pull request merged**
