### PR TITLE
metrics(ticdc): adjust lag bucket

### LINKED ISSUE #7497: adjust lag bucket
adjust lag bucket

### PR DESCRIPTION
**Pull request by sdojjy**
### What problem does this PR solve?

Issue Number: close #7497

### What is changed and how it works?
adjust lag bucket, use a smaller bucket distance

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Review by overvenus — COMMENTED** [review]
Could you also change buckets in scheduler package and others?

**Comment by sdojjy** [comment]
> scheduler

OK

**Review by nongfushanquan — APPROVED** [review]

**Pull request merged**
