### PR TITLE
cli(ticdc): update cli changfeed-statistics by calling openapi without manipulating etcd

### LINKED ISSUE #5511: TiCDC Open API V2: support cli changefeed statistics
add changefeed statistics api v2 which will be called in cli changefeed statistics command

### PR DESCRIPTION
**Pull request by crelax**
### What problem does this PR solve?

Issue Number: close #5511

### What is changed and how it works?
In cli changfeed-statistics, directly get the statistics by calling openapis, and avoid manipulating etcd.

#### Tests 

 - Unit test
 - Integration test

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
update cli changfeed-statistics by calling openapi without manipulating etcd
```

### CODE REVIEW

**Review by sdojjy — APPROVED** [review]

**Review by nongfushanquan — COMMENTED** [review]
whether  some checks about connection between the cli and API server are needed ?

**Comment by crelax** [comment]
> 

maybe not necessary? cuz on connection failures, errors will be thrown.

**Comment by crelax** [comment]
> whether some checks about connection between the cli and API server are needed ?

maybe not necessary? cuz on connection failures, errors will be thrown.

**Review by asddongmen — APPROVED** [review]

**Pull request merged**
