### PR TITLE
chaos(engine): pin version of busybox to avoid dns lookup failure

### LINKED ISSUE #7845: nslookup check failed in init containers
### What did you do?

run chaos test
ref: https://github.com/pingcap/tiflow/actions/runs/3641102008/jobs/6146634936

### What did you expect to see?

_No response_

### What did you see instead?

Start to fail since 2022/12/08

```go
Name:	chaos-metastore-mysql.default.svc.cluster.local
Address: 10.96.157.132

** server can't find chaos-metastore-mysql.svc.cluster.local: NXDOMAIN

** server can't find chaos-metastore-mysql.cluster.local: NXDOMAIN

** server can't find chaos-metastore-mysql.svc.cluster.local: NXDOMAIN


** server can't find chaos-metastore-mysql.cluster.local: NXDOMAIN

** server can't find chaos-metastore-mysql.1m11ukoxijiufdinwkebapu55f.dx.internal.cloudapp.net: NXDOMAIN

** server can't find chaos-metastore-mysql.1m11ukoxijiufdinwkebapu55f.dx.internal.cloudapp.net: NXDOMAIN

waiting for mysql
```

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

master@2022/12/08

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: close #7845

### What is changed and how it works?

Pin docker image version of busybox in server-master/executor to fix nslookup failure

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by amyangfei** [comment]
chaos test passed: https://github.com/pingcap/tiflow/actions/runs/3644959064

**Review by CharlesCheung96 — APPROVED** [review]

**Pull request merged**
