### PR TITLE
sinkv2(ticdc): stop waiting for a batch for non-batched protocol

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/7353

### What is changed and how it works?
stop waiting for batch for non-batched protocol.

#### Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
Improving performance for Kafka's non-batched protocol
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
canal-json benchmark result:
image
image

**Review by hicqu — APPROVED** [review]

**Review by zhaoxinyu — APPROVED** [review]

**Pull request merged**
