### PR TITLE
sink/mysql(ticdc): clean up old values of table

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/4464

### What is changed and how it works?

old table values cleaned in Barrier. More details: https://github.com/pingcap/tiflow/issues/4464#issuecomment-1085385382

### Check List 

Tests 

 - [x] Unit test
 - [x] [Automation test](https://tcms.pingcap.net/dashboard/executions/plan/722775)

Code changes

 - Has exported function/method change

Side effects

None

Related changes

 - [x] Need to cherry-pick to the release branch

### Release note 

```release-note
Fix chengefeed getting stuck when tables are repeatedly scheduled in the same node
```

### CODE REVIEW

**Review by overvenus — COMMENTED** [review]
Could you add a case to tests/move_table?
Rest LGTM

**Review by overvenus — APPROVED** [review]

**Review by sdojjy — APPROVED** [review]

**Comment by hi-rustin** [comment]
/hold

I will try to add a back and forth scheduling integration test.

**Pull request merged**
