### PR TITLE
chore: support specify the branch for downloading dependencies through env variable

### PR DESCRIPTION
**Pull request by purelind**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/11575

Related to this PR: https://github.com/PingCAP-QE/ci/pull/3111

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - [x] No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by wk989898** [comment]
Need to modify the part involved in the download-Integration-test-binaries.sh https://github.com/pingcap/tiflow/blob/4ccbc94a2dad710e30c94464bcb87a3e18cbded6/Makefile#L606-L608

https://github.com/pingcap/tiflow/blob/4ccbc94a2dad710e30c94464bcb87a3e18cbded6/tests/integration_tests/README.md?plain=1#L6

**Comment by purelind** [comment]
> prepare_test_binaries

No modifications are needed. The `prepare_test_binaries` in the Makefile is for community users to download, and this modification still retains that functionality (downloading from a public address instead of an internal address).

**Comment by purelind** [comment]
> Need to modify the part involved in the download-Integration-test-binaries.sh
> 
> https://github.com/pingcap/tiflow/blob/4ccbc94a2dad710e30c94464bcb87a3e18cbded6/Makefile#L606-L608
> 
> https://github.com/pingcap/tiflow/blob/4ccbc94a2dad710e30c94464bcb87a3e18cbded6/tests/integration_tests/README.md?plain=1#L6

The modifications of this PR are mainly to configure changes on the CI side(https://github.com/PingCAP-QE/ci/pull/3111), supporting the passing of environment variables in tiflow CI to specify dependent branches.

**Review by wk989898 — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Pull request merged**
