### PR TITLE
sink(ticdc): output column id as the unique flag for each column

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/9360

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

**Review by Lloyd-Pottiger — APPROVED** [review]

**Review by nongfushanquan — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Comment by Lloyd-Pottiger** [comment]
@CharlesCheung96 will add it into changefeed config file be a better choice? In this way, we may also need to adjust cloud ui.....

**Pull request merged**
