### PR TITLE
ddl(ticdc): fix query splitting issue by using TiDB parser

### LINKED ISSUE #11774: [CDC:ErrTiDBUnexpectedJobMeta]unexpected `job_meta` from tidb
### What did you do?

1. Create MySQL sink changefeed
2. Use lighting tidb mode to import thousands of tables.

### What did you expect to see?

CDC changefeed should be normal

### What did you see instead?

CDC changefeed run into error.
```
# /cdc cli changefeed --server http://127.0.0.1:8301 list
[
  {
    "id": "cdc-ddl-coverage-sync-1",
    "namespace": "default",
    "summary": {
      "state": "failed",
      "tso": 453921084696952885,
      "checkpoint": "2024-11-14 08:05:20.603",
      "error": {
        "time": "2024-11-14T08:21:30.057114566Z",
        "addr": "upstream-ticdc-1.upstream-ticdc-peer.cdc-testbed-tps-7682205-1-226.svc:8301",
        "code": "CDC:ErrTiDBUnexpectedJobMeta",
        "message": "[CDC:ErrTiDBUnexpectedJobMeta]unexpected `job_meta` from tidb"
      }
    }
  }
]
====
[2024/11/14 08:11:37.143 +00:00] [ERROR] [ddl_puller.go:397] ["the number of queries in `Job.Query` is not equal to the number of `TableInfo` in `Job.BinlogInfo.MultipleTableInfos`"] [Job.Query="CREATE TABLE IF NOT EXISTS `coms`.`PK_MULTI_COL_522` (`COL1` VARBINARY(10) NOT NULL,`COL3` DECIMAL(55,0) NOT NULL,PRIMARY KEY(`COL1`(5), `COL3`) /*T![clustered_index] CLUSTERED */) ENGINE = InnoDB DEFAULT CHARACTER SET = UTF8 DEFAULT COLLATE = UTF8_BIN; CREATE TABLE IF NOT EXISTS `coms`.`PK_MULTI_COL1983STROBJSTROBJ` (`COL2` ENUM('JSDTB58=RHX=OT80NEI8:9Z_3DE_AX:V^PVKQIS@TA8C4EB7RCXTYDW<:>KD=PUGN_Y1E_YL?JIGL5VV??A7SB6_HZEVYX=GQ1OABH60Z[4^@1`]LXJO','IRG','I0G7YKT;J9YWDXXPNYNNF','SRXFIDYUC_2EWMNLESI:ZOHS@R9Y_3SU\u001aKII`Z1NXWKN0M>0B@P_LMB:FL4QQHIEPRSD@Y`Y[21FUFDF5','9O5DE:ATDW04TPZCUCWKOV<HZSBMWN^<V2WXYT`EAHDOX','O>W2ET@7ZNT^YOK0Z3D0Z;DZWIAJOCA4GP:OHDL]=KM^8I?P32W','ZWS;ML64UQFBQMX4<QIA9Y@C?X92DI>JU7LOAUNB]T0CBMLF5E<XXNTRNQNXEMV:_PCAV`]JMR]TOM]JQ74B]U','BOBI9<QVSCVX>NX^DBEOWXT1CWI6[WHR<^VE7MSE5?C2XX32Q0KZCX2SGYI5:A','71DW8HTIJU`D=3;ZQ7;PP=QLNAIZ5TPNZ_FE;HDZ_HKF8VBCHGS?A5U3VFP3','@D;L=NL_5CAWE>3BYA0') COLLATE utf8mb4_general_ci NOT NULL,`COL3` TINYINT(50) NOT NULL,PRIMARY KEY(`COL2`, `COL3`) /*T![clustered_index] CLUSTERED */) ENGINE = InnoDB DEFAULT CHARACTER SET = UTF8MB4 DEFAULT COLLATE = UTF8MB4_GENERAL_CI;"] [Job.BinlogInfo.MultipleTableInfos="[{\"id\":10601,\"name\":{\"O\":\"PK_MULTI_COL_522\",\"L\":\"pk_multi_col_522\"},\"charset\":\"utf8\",\"collate\":\"utf8_bin\",\"cols\":[{\"id\":1,\"name\":{\"O\":\"COL1\",\"L\":\"col1\"},\"offset\":0,\"origin_default\":null,\"origin_default_bit\":null,\"default\":null,\"default_bit\":null,\"default_is_expr\":false,\"generated_expr_string\":\"\",\"generated_stored\":false,\"dependences\":null,\"type\":{\"Tp\":15,\"Flag\":4227,\"Flen\":10,\"Decimal\":0,\"Charset\":\"binary\",\"Collate\":\"binary\",\"Elems\":null,\"ElemsIsBinaryLit\":null,\"Array\":false},\"state\":5,\"comment\":\"\",\"hidden\":false,\"change_state_info\":null,\"version\":2},{\"id\":2,\"name\":{\"O\":\"COL3\",\"L\":\"col3\"},\"offset\":1,\"origin_default\":null,\"origin_default_bit\":null,\"default\":null,\"default_bit\":null,\"default_is_expr\":false,\"generated_expr_string\":\"\",\"generated_stored\":false,\"dependences\":null,\"type\":{\"Tp\":246,\"Flag\":4099,\"Flen\":55,\"Decimal\":0,\"Charset\":\"binary\",\"Collate\":\"binary\",\"Elems\":null,\"ElemsIsBinaryLit\":null,\"Array\":false},\"state\":5,\"comment\":\"\",\"hidden\":false,\"change_state_info\":null,\"version\":2}],\"index_info\":[{\"id\":1,\"idx_name\":{\"O\":\"PRIMARY\",\"L\":\"primary\"},\"tbl_name\":{\"O\":\"\",\"L\":\"\"},\"idx_cols\":[{\"name\":{\"O\":\"COL1\",\"L\":\"col1\"},\"offset\":0,\"length\":5},{\"name\":{\"O\":\"COL3\",\"L\":\"col3\"},\"offset\":1,\"length\":-1}],\"state\":5,\"backfill_state\":0,\"comment\":\"\",\"index_type\":1,\"is_unique\":true,\"is_primary\":true,\"is_invisible\":false,\"is_global\":false,\"mv_index\":false,\"vector_index\":null}],\"constraint_info\":null,\"fk_info\":null,\"state\":5,\"pk_is_handle\":false,\"is_common_handle\":true,\"common_handle_version\":1,\"comment\":\"\",\"auto_inc_id\":0,\"auto_id_cache\":0,\"auto_rand_id\":0,\"max_col_id\":2,\"max_idx_id\":1,\"max_fk_id\":0,\"max_cst_id\":0,\"update_timestamp\":453921183199395886,\"ShardRowIDBits\":0,\"max_shard_row_id_bits\":0,\"auto_random_bits\":0,\"auto_random_range_bits\":0,\"pre_split_regions\":0,\"partition\":null,\"compression\":\"\",\"view\":null,\"sequence\":null,\"Lock\":null,\"version\":5,\"tiflash_replica\":null,\"is_columnar\":false,\"temp_table_type\":0,\"cache_table_status\":0,\"policy_ref_info\":null,\"stats_options\":null,\"exchange_partition_info\":null,\"ttl_info\":null,\"revision\":0},{\"id\":10602,\"name\":{\"O\":\"PK_MULTI_COL1983STROBJSTROBJ\",\"L\":\"pk_multi_col1983strobjstrobj\"},\"charset\":\"utf8mb4\",\"collate\":\"utf8mb4_general_ci\",\"cols\":[{\"id\":1,\"name\":{\"O\":\"COL2\",\"L\":\"col2\"},\"offset\":0,\"origin_default\":null,\"origin_default_bit\":null,\"default\":null,\"default_bit\":null,\"default_is_expr\":false,\"generated_expr_string\":\"\",\"generated_stored\":false,\"dependences\":null,\"type\":{\"Tp\":247,\"Flag\":4099,\"Flen\":116,\"Decimal\":0,\"Charset\":\"utf8mb4\",\"Collate\":\"utf8mb4_general_ci\",\"Elems\":[\"JSDTB58=RHX=OT80NEI8:9Z_3DE_AX:V^PVKQIS@TA8C4EB7RCXTYDW\\u003c:\\u003eKD=PUGN_Y1E_YL?JIGL5VV??A7SB6_HZEVYX=GQ1OABH60Z[4^@1`]LXJO\",\"IRG\",\"I0G7YKT;J9YWDXXPNYNNF\",\"SRXFIDYUC_2EWMNLESI:ZOHS@R9Y_3SU\\u001aKII`Z1NXWKN0M\\u003e0B@P_LMB:FL4QQHIEPRSD@Y`Y[21FUFDF5\",\"9O5DE:ATDW04TPZCUCWKOV\\u003cHZSBMWN^\\u003cV2WXYT`EAHDOX\",\"O\\u003eW2ET@7ZNT^YOK0Z3D0Z;DZWIAJOCA4GP:OHDL]=KM^8I?P32W\",\"ZWS;ML64UQFBQMX4\\u003cQIA9Y@C?X92DI\\u003eJU7LOAUNB]T0CBMLF5E\\u003cXXNTRNQNXEMV:_PCAV`]JMR]TOM]JQ74B]U\",\"BOBI9\\u003cQVSCVX\\u003eNX^DBEOWXT1CWI6[WHR\\u003c^VE7MSE5?C2XX32Q0KZCX2SGYI5:A\",\"71DW8HTIJU`D=3;ZQ7;PP=QLNAIZ5TPNZ_FE;HDZ_HKF8VBCHGS?A5U3VFP3\",\"@D;L=NL_5CAWE\\u003e3BYA0\"],\"ElemsIsBinaryLit\":null,\"Array\":false},\"state\":5,\"comment\":\"\",\"hidden\":false,\"change_state_info\":null,\"version\":2},{\"id\":2,\"name\":{\"O\":\"COL3\",\"L\":\"col3\"},\"offset\":1,\"origin_default\":null,\"origin_default_bit\":null,\"default\":null,\"default_bit\":null,\"default_is_expr\":false,\"generated_expr_string\":\"\",\"generated_stored\":false,\"dependences\":null,\"type\":{\"Tp\":1,\"Flag\":4099,\"Flen\":50,\"Decimal\":0,\"Charset\":\"binary\",\"Collate\":\"binary\",\"Elems\":null,\"ElemsIsBinaryLit\":null,\"Array\":false},\"state\":5,\"comment\":\"\",\"hidden\":false,\"change_state_info\":null,\"version\":2}],\"index_info\":[{\"id\":1,\"idx_name\":{\"O\":\"PRIMARY\",\"L\":\"primary\"},\"tbl_name\":{\"O\":\"\",\"L\":\"\"},\"idx_cols\":[{\"name\":{\"O\":\"COL2\",\"L\":\"col2\"},\"offset\":0,\"length\":-1},{\"name\":{\"O\":\"COL3\",\"L\":\"col3\"},\"offset\":1,\"length\":-1}],\"state\":5,\"backfill_state\":0,\"comment\":\"\",\"index_type\":1,\"is_unique\":true,\"is_primary\":true,\"is_invisible\":false,\"is_global\":false,\"mv_index\":false,\"vector_index\":null}],\"constraint_info\":null,\"fk_info\":null,\"state\":5,\"pk_is_handle\":false,\"is_common_handle\":true,\"common_handle_version\":1,\"comment\":\"\",\"auto_inc_id\":0,\"auto_id_cache\":0,\"auto_rand_id\":0,\"max_col_id\":2,\"max_idx_id\":1,\"max_fk_id\":0,\"max_cst_id\":0,\"update_timestamp\":453921183199395886,\"ShardRowIDBits\":0,\"max_shard_row_id_bits\":0,\"auto_random_bits\":0,\"auto_random_range_bits\":0,\"pre_split_regions\":0,\"partition\":null,\"compression\":\"\",\"view\":null,\"sequence\":null,\"Lock\":null,\"version\":5,\"tiflash_replica\":null,\"is_columnar\":false,\"temp_table_type\":0,\"cache_table_status\":0,\"policy_ref_info\":null,\"stats_options\":null,\"exchange_partition_info\":null,\"ttl_info\":null,\"revision\":0}]"] [error="[CDC:ErrTiDBUnexpectedJobMeta]unexpected `job_meta` from tidb"] [errorVerbose="[CDC:ErrTiDBUnexpectedJobMeta]unexpected `job_meta` from tidb\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/errors.go:178\ngithub.com/pingcap/errors.(*Error).GenWithStackByArgs\n\tgithub.com/pingcap/errors@v0.11.5-0.20240318064555-6bd07397691f/normalize.go:175\ngithub.com/pingcap/tiflow/cdc/puller.(*ddlJobPullerImpl).handleJob\n\tgithub.com/pingcap/tiflow/cdc/puller/ddl_puller.go:401\ngithub.com/pingcap/tiflow/cdc/puller.(*ddlJobPullerImpl).handleRawKVEntry\n\tgithub.com/pingcap/tiflow/cdc/puller/ddl_puller.go:204\ngithub.com/pingcap/tiflow/cdc/puller.(*ddlJobPullerImpl).Run.func3\n\tgithub.com/pingcap/tiflow/cdc/puller/ddl_puller.go:151\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.8.0/errgroup/errgroup.go:78\nruntime.goexit\n\truntime/asm_amd64.s:1700"]
```

### Versions of the cluster

[release-version=v8.5.0-alpha-9-gb2a4f9af2] 
[git-hash=b2a4f9af26d21cff818f291e19f44dfd274240e4] [git-branch=HEAD]

### PR DESCRIPTION
**Pull request by wlwilliamx**
### What problem does this PR solve?

Issue Number: close #11774

### What is changed and how it works?

**Description**

I implemented a new function, SplitQueries, which utilizes TiDB’s parser to parse and split SQL statements correctly. This ensures robust handling of complex SQL strings, including those with special characters in column names.

**Key Changes**

1. Introduced SplitQueries function
  * This function uses TiDB’s parser to split a concatenated SQL string into individual queries.
  * The parser generates an Abstract Syntax Tree (AST) for the SQL string, and each AST node is restored into a complete query with a semicolon appended.
2. Replaced Existing Query Splitting Logic
* Updated all parts of the codebase where query splitting occurs to use the new SplitQueries function.
* This ensures consistency and correctness across the project.

**Notes**

This change depends on TiDB’s parser. Please ensure the parser version is up-to-date in the project dependencies.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

I manually tested this PR using the combined DDL query like:

```sql
CREATE TABLE IF NOT EXISTS coms.PK_MULTI_COL_522 (COL1 VARBINARY(10) NOT NULL,COL3 DECIMAL(55,0) NOT NULL,PRIMARY KEY(COL1(5), COL3) /*T![clustered_index] CLUSTERED */) ENGINE = InnoDB DEFAULT CHARACTER SET = UTF8 DEFAULT COLLATE = UTF8_BIN; CREATE TABLE IF NOT EXISTS coms.PK_MULTI_COL1983STROBJSTROBJ (COL2 ENUM('JSDTB58=RHX=OT80NEI8:9Z_3DE_AX:V^PVKQIS@TA8C4EB7RCXTYDW<:>KD=PUGN_Y1E_YL?JIGL5VV??A7SB6_HZEVYX=GQ1OABH60Z[4^@1]LXJO','IRG','I0G7YKT;J9YWDXXPNYNNF','SRXFIDYUC_2EWMNLESI:ZOHS@R9Y_3SU\u001aKIIZ1NXWKN0M>0B@P_LMB:FL4QQHIEPRSD@YY[21FUFDF5','9O5DE:ATDW04TPZCUCWKOV<HZSBMWN^<V2WXYTEAHDOX','O>W2ET@7ZNT^YOK0Z3D0Z;DZWIAJOCA4GP:OHDL]=KM^8I?P32W','ZWS;ML64UQFBQMX4<QIA9Y@C?X92DI>JU7LOAUNB]T0CBMLF5E<XXNTRNQNXEMV:_PCAV]JMR]TOM]JQ74B]U','BOBI9<QVSCVX>NX^DBEOWXT1CWI6[WHR<^VE7MSE5?C2XX32Q0KZCX2SGYI5:A','71DW8HTIJUD=3;ZQ7;PP=QLNAIZ5TPNZ_FE;HDZ_HKF8VBCHGS?A5U3VFP3','@D;L=NL_5CAWE>3BYA0') COLLATE utf8mb4_general_ci NOT NULL,COL3 TINYINT(50) NOT NULL,PRIMARY KEY(COL2, COL3) /*T![clustered_index] CLUSTERED */) ENGINE = InnoDB DEFAULT CHARACTER SET = UTF8MB4 DEFAULT COLLATE = UTF8MB4_GENERAL_CI;
```

##### Will it cause performance regression or break compatibility?

No.

##### Do you need to update user documentation, design documentation or monitoring documentation?

No.

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by hongyunyan — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Comment by wlwilliamx** [comment]
link https://github.com/pingcap/tiflow/pull/11262

**Pull request merged**
