### PR TITLE
lightning(dm): ignore checkpoint error should using ExtStorage

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: ref #7114

### What is changed and how it works?

in old code, `(l *LightningLoader) ignoreCheckpointError` forget to use engine's injected S3 to cleanup checkpoint

#### Tests 

 - Integration test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
but the progress becomes 0% 😂 

```

    "finished_unit_status": {
        "mysql-01": [
 ...
            {
                "Unit": "DMLoadTask",
                "Task": "mysql-01",
                "Stage": "Finished",
                "CfgModRevision": 0,
                "StageUpdatedTime": "2022-11-24T05:20:55.336177527Z",
                "Result": {},
                "Status": {
                    "totalBytes": 614,
                    "progress": "0.00 %"
                },
                "Duration": 48761762780
            }
        ]
```

**Review by D3Hunter — APPROVED** [review]

**Review by okJiang — APPROVED** [review]

**Pull request merged**
