### PR TITLE
(dm) [bugfix] backward compatibility with show command #5017

### PR DESCRIPTION
**Pull request by duanhuichao**
Problem:
With the version upgrade, on the new version of MySQL Cluster,
the query results of many system commands will display some new
columns. These new columns show new features or information of MySQL.

In general, it is recommended to provide backward compatibility of
system commands (e.g., show xxx) rather than hard-coded return value
format (i.e., limiting the number of returned columns).

For DM, there are some commands that are difficult to backward-compatible:
(1) SHOW MASTER STATUS
(2) SHOW SLAVE HOSTS
(3) SHOW BINARY LOGS

Fix:
Through the reflection mechanism, we only take the value of the required
corresponding column and do not limit the number of returned columns.
This patch removes the limit on the number of columns returned by the
'show slave hosts' command.

ref pingcap/tiflow#5017

### CODE REVIEW

**Comment by lance6716** [comment]
@duanhuichao Hi, please follow the 2nd & 3rd comment of ti-chi-bot to adjust PR description

**Comment by lance6716** [comment]
I found we have provided a helper function to do similar thing in https://github.com/pingcap/tidb/blob/9b9051f113a6f19857f6a8aa1f28159cb1ec40cc/dumpling/export/sql.go#L694

Could you use that function instead of using reflect? It's more easier to understand.

**Comment by lonng** [comment]
@duanhuichao Thanks for you contribution, and can you add some tests for this PR?

**Comment by lance6716** [comment]
Hi @duanhuichao, another user also meet this problem, so we are going to fix this problem in these days. Can you check the comments to finish your PR?

If you don't have time to response, we will fix it on our own in next week. Thanks for your contribution to find the problem!

**Comment by lance6716** [comment]
replaced by https://github.com/pingcap/tiflow/pull/7372

**Pull request closed without merging**
