### PR TITLE
config(ticdc): move region-per-span to changefeed config

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: ref #7720 

### What is changed and how it works?

Move region-per-span config to changefeed.

#### Tests 

 - Unit test
 - Manual test
  1. Create a changefeed using following changefeed.toml
  2. Update an existing changefeed (without scale out) using following changefeed.toml
```toml
[scheduler]
region-per-span = 10000
```

##### Will it cause performance regression or break compatibility?

No

##### Do you need to update user documentation, design documentation or monitoring documentation?

No

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Comment by overvenus** [comment]
/run-kafka-integration-test pd=7ca1b9aa2ca6b6ee6be4696d377e9065b1b09359
/run-integration-tests pd=7ca1b9aa2ca6b6ee6be4696d377e9065b1b09359

**Pull request merged**
