### PR TITLE
pipeline(ticdc): enable table actor by default

### PR DESCRIPTION
**Pull request by sdojjy**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/3881

### What is changed and how it works?
enable table actor by default

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
enable table actor by default
```

### CODE REVIEW

**Review by ben1009 — COMMENTED** [review]
i have a stupid question
https://github.com/pingcap/tiflow/blob/cbc17674f4ab2add8f48a0f9f533aa89cb402343/cdc/processor/pipeline/sorter.go#L88

```
func (n *sorterNode) Init(ctx pipeline.NodeContext) error {
	wg := errgroup.Group{}
	return n.start(ctx, false, &wg, 0, nil)
}

func (n *sorterNode) start(ctx pipeline.NodeContext, isTableActorMode bool, eg *errgroup.Group, tableActorID actor.ID, tableActorRouter *actor.Router) error {
	n.isTableActorMode = isTableActorMode
	n.eg = eg
```

this block is not controlled by the config or dead code

**Comment by sdojjy** [comment]
> tiflow/cdc/processor/pipeline/sorter.go

If table actor is not enable, it will be called by nodeRunner https://github.com/pingcap/tiflow/blob/3a5cbcb0de4cfc5f47194cb03d5903c27403d206/pkg/pipeline/runner.go#L58

```
func (r *nodeRunner) run(ctx context.Context) error {
	nodeCtx := NewNodeContext(ctx, Message{}, r.outputCh)
	defer close(r.outputCh)
	defer func() {
		err := r.node.Destroy(nodeCtx)
		if err != nil && errors.Cause(err) != stdContext.Canceled {
			log.Error("found an error when stopping node",
				zap.String("node", r.name), zap.Error(err))
		}
	}()
	err := r.node.Init(nodeCtx)
	if err != nil {
		return err
	}
```

**Review by overvenus — APPROVED** [review]

**Review by ben1009 — APPROVED** [review]

**Pull request merged**
