### PR TITLE
chaos: fix utf8mb3 and utf8mb4_0900_ai_ci for chaos test

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: ref #4159

### What is changed and how it works?
- create database with charset latin1
- use utf8mb4 instead of utf8, see https://github.com/PingCAP-QE/go-sqlsmith/pull/18 

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by GMHDBJD** [comment]
https://github.com/pingcap/tiflow/actions/runs/2997517629 chaos test passed. cc @lance6716 @D3Hunter @buchuitoudegou

**Review by D3Hunter — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
