### PR TITLE
pkg/actor(ticdc): generic actor message

### LINKED ISSUE #4972: Use generic to simple actor message
Resolve TODO in actor message.

https://github.com/pingcap/tiflow/blob/be5524dd90d5db245a22cc125599b5c81d78c2bb/pkg/actor/message/message.go#L34-L45

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: close #4972 

### What is changed and how it works?

Replace a concrete typed field with a generic typed field in actor message.

Need to merge #4971 first.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by ben1009** [comment]
```
[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-169)[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-170)[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-171)[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-172)[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-173)[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-174)[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-175)[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-176)[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-177)[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-178)[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-179)[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-180)[2022-03-22T06:10:01.970Z] pkg/actor/system.go:162:1: receiver-naming: receiver name rd should be consistent with previous receiver name p for invalid-type (revive)

[2022-03-22T06:10:01.970Z] func (rd *ready[T]) prepareStop() {

[2022-03-22T06:10:01.970Z] 	rd.Lock()

[2022-03-22T06:10:01.970Z] 	rd.state = readyStateStopping

[2022-03-22T06:10:01.970Z] 	rd.Unlock()

[2022-03-22T06:10:01.970Z] }

[2022-03-22T06:10:01.970Z] pkg/actor/system.go:168:1: receiver-naming: receiver name rd should be consistent with previous receiver name p for invalid-type (revive)

[2022-03-22T06:10:01.970Z] func (rd *ready[T]) stop() {

[2022-03-22T06:10:01.970Z] 	rd.Lock()

[2022-03-22T06:10:01.970Z] 	rd.state = readyStateStopped

[2022-03-22T06:10:01.970Z] 	rd.Unlock()

[2022-03-22T06:10:01.970Z] 	rd.cond.Broadcast()

[2022-03-22T06:10:01.970Z] }
```

some of the lint got disabled after upgrade to 1.8, may have some side effects ?
```
[2022-03-22T06:10:01.970Z] level=warning msg="[linters context] gosimple is disabled because of go1.18. If you are not using go1.18, you can set `go: go1.17` in the `run` section. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-163)."

[2022-03-22T06:10:01.970Z] level=warning msg="[linters context] staticcheck is disabled because of go1.18. If you are not using go1.18, you can set `go: go1.17` in the `run` section. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-164)."

[2022-03-22T06:10:01.970Z] level=warning msg="[linters context] structcheck is disabled because of go1.18. If you are not using go1.18, you can set `go: go1.17` in the `run` section. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-165)."

[2022-03-22T06:10:01.970Z] level=warning msg="[linters context] stylecheck is disabled because of go1.18. If you are not using go1.18, you can set `go: go1.17` in the `run` section. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-166)."

[2022-03-22T06:10:01.970Z] level=warning msg="[linters context] unparam is disabled because of go1.18. If you are not using go1.18, you can set `go: go1.17` in the `run` section. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649[](https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/3605/pipeline/#step-55-log-167)."

[2022-03-22T06:10:01.970Z] level=warning msg="[linters context] unused is disabled because of go1.18. If you are not using go1.18, you can set `go: go1.17` in the `run` section. You can track the evolution of the go1.18 support by
```

**Comment by overvenus** [comment]
> some of the lint got disabled after upgrade to 1.8, may have some side effects ?

Due to upstream x/tools/go/ssa does not support generic yet, we have to disable them, otherwise it panics, see more https://github.com/golangci/golangci-lint/issues/2649

**Review by hi-rustin — APPROVED** [review]

**Comment by ben1009** [comment]
> 

I mean some of the lints got disabled may cause some issue supposed to found but not

**Comment by ben1009** [comment]
> > some of the lint got disabled after upgrade to 1.8, may have some side effects ?
> 
> Due to upstream x/tools/go/ssa does not support generic yet, we have to disable them, otherwise it panics, see more [golangci/golangci-lint#2649](https://github.com/golangci/golangci-lint/issues/2649)

I mean some of the lints got disabled may cause some issue supposed to found but not

**Comment by overvenus** [comment]
> [2022-03-22T06:10:01.970Z] pkg/actor/system.go:168:1: receiver-naming: receiver name rd should be consistent with previous receiver name p for invalid-type (revive)

I think it's a false alarm.

**Review by ben1009 — APPROVED** [review]

**Review by zhaoxinyu — APPROVED** [review]

**Review by sdojjy — APPROVED** [review]

**Comment by ben1009** [comment]
fyi https://planetscale.com/blog/generics-can-make-your-go-code-slower

**Pull request merged**
