### PR TITLE
config(ticdc): No longer set open-protocol as default value for kafka sink protocol

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 
close https://github.com/pingcap/tiflow/issues/3879

### What is changed and how it works?
No longer set default values for kafka sink protocol

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported function/method change

Side effects

 None

Related changes

 None

### Release note 

```release-note
 None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/cc @amyangfei @overvenus 

The compatibility issue was solved in my last pr and we can stop setting the default values.

Could you please take a look? Thanks! 💚 💙 💜 💛 ❤️

**Comment by hi-rustin** [comment]
/uncc amyangfei  overvenus 

I seem to have let you guys review too much of my pr! 😆  Let me rebalance a bit.

/cc @ben1009 @sdojjy 

Could you please take a look? Thanks! 💚 💙 💜 💛 ❤️

**Review by ben1009 — APPROVED** [review]

**Comment by ben1009** [comment]
to my understanding, the pr aim to No longer recommend open-protocol as default value for kafka sink protocol

**Review by sdojjy — APPROVED** [review]

**Pull request merged**
