### PR TITLE
scheduler, tests: stabilize balancer tests

### LINKED ISSUE #4307: TestBalancerFindTargetTied is unstable
### Which jobs are flaking?

unit test

### Which test(s) are flaking?

TestBalancerFindTargetTied

### Jenkins logs or GitHub Actions link

```log
=== RUN   TestBalancerFindTargetTied
    balancer_test.go:238: 
        	Error Trace:	balancer_test.go:238
        	Error:      	Should be false
        	Test:       	TestBalancerFindTargetTied
--- FAIL: TestBalancerFindTargetTied (0.00s)
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### PR DESCRIPTION
**Pull request by liuzix**
### What problem does this PR solve?

Issue Number: close #4307 

### What is changed and how it works?
- Used a fixed random seed for all balancer test cases.
- Improved the case for checking that FindTarget is randomized.

### Check List 

Tests 

 - Unit test
 - Manually running unit tests

```
> ./scheduler.test -test.count 1000 | grep PASS
PASS
```

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by asddongmen** [comment]
[2022-01-12T09:59:22.780Z] [2022/01/12 17:57:32.341 +08:00] [WARN] [server.go:633] ["error receiving from peer"] [error="context canceled"]

[2022-01-12T09:59:22.780Z] [2022/01/12 17:57:32.451 +08:00] [INFO] [server_wrapper_test.go:51] ["error received"] [error="rpc error: code = Canceled desc = context canceled"]

[2022-01-12T09:59:22.780Z] [2022/01/12 17:57:32.479 +08:00] [INFO] [server_wrapper_test.go:51] ["error received"] [error="rpc error: code = Canceled desc = context canceled"]

[2022-01-12T09:59:22.780Z] FAIL

[2022-01-12T09:59:22.780Z] FAIL	github.com/pingcap/tiflow/pkg/p2p	16.377s

**Comment by liuzix** [comment]
> [2022-01-12T09:59:22.780Z] [2022/01/12 17:57:32.341 +08:00] [WARN] [server.go:633] ["error receiving from peer"] [error="context canceled"]
> 
> [2022-01-12T09:59:22.780Z] [2022/01/12 17:57:32.451 +08:00] [INFO] [server_wrapper_test.go:51] ["error received"] [error="rpc error: code = Canceled desc = context canceled"]
> 
> [2022-01-12T09:59:22.780Z] [2022/01/12 17:57:32.479 +08:00] [INFO] [server_wrapper_test.go:51] ["error received"] [error="rpc error: code = Canceled desc = context canceled"]
> 
> [2022-01-12T09:59:22.780Z] FAIL
> 
> [2022-01-12T09:59:22.780Z] FAIL github.com/pingcap/tiflow/pkg/p2p 16.377s

Will fix in another PR.

**Review by amyangfei — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Pull request merged**
