### PR TITLE
metrics: remove metrics proxy

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: ref #4287

### What is changed and how it works?
- remove metrics proxy
- upgrade promethus and use `DeletePartialMatch` if we want to delete by partial labels.

#### Tests 
Manaully test

```release-note
None
```

### CODE REVIEW

**Comment by CharlesCheung96** [comment]
The integration test is fixed in this [pr](https://github.com/pingcap/tiflow/pull/6945/files#diff-bffb058b78b9842d5e4fdb46a7fd39537fe4a2ff843e57773db583da3d997392L1), please rebase this branch and trigger engine tests again.

**Review by lance6716 — APPROVED** [review]

**Comment by GMHDBJD** [comment]
cc @D3Hunter @buchuitoudegou

**Review by buchuitoudegou — APPROVED** [review]
Would you mind introduce a bit below this comment about why we used this before and why we abandon it now?

**Comment by GMHDBJD** [comment]
> Would you mind introduce a bit below this comment about why we used this before and why we abandon it now?

see https://github.com/pingcap/dm/pull/575 for more detail. We want to remove metrics when task/source stopped. However, our metrics don't quite fit the specification. e.g. [txnHistogram](https://github.com/pingcap/tiflow/blob/6f9c00d8602a965a7bd763a03081a8661c059d6b/dm/loader/metrics.go#L42) is created with  target_schema/target_table label, but we need to remove when its task/source is deleted, so we need delete the metrics when label is partial match. https://github.com/pingcap/dm/pull/575 wraps metrics and label with a Map, which has perfomance issue. Promethus support `DeletePartialMatch` now. https://github.com/prometheus/client_golang/pull/1013

**Pull request merged**
