### PR TITLE
test(dm): fix using pgrep to check argument pattern

### LINKED ISSUE #5731: [sequence_sharding_optimistic] check diff failed at last
### Which jobs are flaking?

sequence_sharding_optimistic

### Which test(s) are flaking?

DM-IT
release-6.1

### Jenkins logs or GitHub Actions link

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/6421/pipeline/

```
["column num not equal"] ["upstream table"=t1] ["column num"=3] ["downstream table"=t_target] ["column num"=4] 
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### LINKED ISSUE #6526: Err: table id xxx: invalid table id, no corresponding table map event
### What did you do?

start task with relay

### What did you expect to see?

task runs as normal

### What did you see instead?

 Err: table id xxx: invalid table id, no corresponding table map event

https://github.com/pingcap/tiflow/issues/5731#issuecomment-1191226079

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
nightly
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close #6526, close #5731, close https://github.com/pingcap/tiflow/issues/5287

### What is changed and how it works?

- we use `kill_process dm-worker1` in test script, and finally it will become `pgrep dm-worker1`. This is not right because `dm-worker1` is in arguments and `pgrep` only check process name.
- old problems, same root cause but different case as https://github.com/pingcap/tiflow/issues/5807
- after syncer processes RowsEvent, check_sync_diff will pass, but XIDEvent may have not been written to relay log. We retry checking for 5 seconds.

#### Tests 

 - Integration test
 - Manual test (add detailed scripts or steps below)
```
# lance @ lance6716-nuc10i7fnh in ~/go/src/github.com/pingcap/tiflow on git:master o [14:31:49] 
$ pgrep -f dm-worker1     
467807

# lance @ lance6716-nuc10i7fnh in ~/go/src/github.com/pingcap/tiflow on git:master x [14:32:09] 
$ pgrep dm-worker1                                       

```
### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Review by D3Hunter — APPROVED** [review]

**Comment by lance6716** [comment]
pgrep with no flags only reads the first 15 characters of the executable's name.

so `pkill dm-master.test.previous` will fail. WTF

**Comment by lonng** [comment]
We retry `/run-dm-integration-test` so many times. Do you file an issue tracking the unstable case?
@lance6716

**Comment by lonng** [comment]
We retry `/run-dm-integration-test` so many times. Do you file an issue tracking the unstable case?
@lance6716

**Comment by lance6716** [comment]
> We retry `/run-dm-integration-test` so many times. Do you file an issue tracking the unstable case? @lance6716

Yes, most of them are old issues, and I also recorded new failing cases.

**Pull request merged**
