### PR TITLE
dep: update tidb package

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #xxx

#### Tests 

 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Comment by lance6716** [comment]
/hold

blocked by https://github.com/pingcap/tidb/issues/53673

**Comment by lance6716** [comment]
new error is 

```
[2024/06/04 12:08:25.788 +08:00] [WARN] [util.go:201] ["create conflict view failed with no retry"] [task=test] [unit=lightning-load] [query="CREATE OR REPLACE VIEW `lightning_task_info`.conflict_view\n\t\t\tAS SELECT 1 AS is_precheck_conflict, task_id, create_time, table_name, NULL AS index_name, NULL AS key_data,\n\t\t\trow_data, NULL AS raw_key, NULL AS raw_value, NULL AS raw_handle, NULL AS raw_row, NULL AS kv_type, path,\n\t\t\toffset, error, row_id FROM `lightning_task_info`.conflict_records;"] [args=null] [retryCnt=0] [error="Error 1142 (42000): CREATE VIEW command denied to user 'test1'@'%' for table 'conflict_view'"]
[2024/06/04 12:08:25.788 +08:00] [ERROR] [lightning.go:591] ["restore failed"] [task=test] [unit=lightning-load] [error="[Lightning:DB:ErrInitErrManager]init error manager error: create conflict view failed: Error 1142 (42000): CREATE VIEW command denied to user 'test1'@'%' for table 'conflict_view'"]
```

**Review by asddongmen — APPROVED** [review]

**Pull request merged**
