### PR TITLE
test: add create table case for upgrade test

### LINKED ISSUE #4159: refine tests
### Is your feature request related to a problem?

to walkaround link-issue-checker in PR

### Describe the feature you'd like

refine tests

### Describe alternatives you've considered

_No response_

### Teachability, Documentation, Adoption, Migration Strategy

_No response_

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: ref #4159

### What is changed and how it works?
- add create table test
- add drop table test

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by GMHDBJD** [comment]
https://github.com/pingcap/tiflow/actions/runs/2329624234

**Comment by GMHDBJD** [comment]
https://github.com/pingcap/tiflow/actions/runs/2330127371

**Review by lance6716 — APPROVED** [review]
what case does it test?

**Review by Ehco1996 — APPROVED** [review]
LGTM

**Pull request merged**
