### PR TITLE
Support Sequences

### LINKED ISSUE #4559: Sequence support is incomplete
### Is your feature request related to a problem?

Sequence support is incomplete in TiCDC.

The current capability of TiCDC:  

> The [DDL operation CREATE SEQUENCE](https://docs.pingcap.com/tidb/stable/sql-statement-create-sequence) and the [SEQUENCE function](https://docs.pingcap.com/tidb/stable/sql-statement-create-sequence#sequence-function) in TiDB. When the upstream TiDB uses SEQUENCE, TiCDC ignores SEQUENCE DDL operations/functions performed upstream. However, DML operations using SEQUENCE functions can be correctly replicated.
> 
> 2022/02/10, https://docs.pingcap.com/tidb/stable/ticdc-overview#unsupported-scenarios

Besides, there are two flaws we found,
1. TiCDC have no idea about how to deal with DDLs below:
    ```SQL
    CREATE SEQUENCE `SEQ1` start with 1 minvalue 1 maxvalue 999999999999999 increment by 1 nocache cycle;
    CREATE TABLE t(k int not null, a int default next value for SEQ1, PRIMARY KEY (k));
    ```
2. TiCDC filters all SEQUENCE DDL, it means we lost SEQUENCE even if downstream is TiDB. We lose data in TiDB disaster recovery scenario.

### Describe the feature you'd like

Support sequence feature completely when downstream is TiDB, and disable sequence completely when downstream is MySQL.

### Describe alternatives you've considered

_No response_

### Teachability, Documentation, Adoption, Migration Strategy

_No response_

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #4559 

### What is changed and how it works?

As MariaDB [supports Sequences](https://mariadb.com/kb/en/sequences/) it would be good if DM allows MariaDB→DM→TiDB for things like `CREATE SEQUENCE`.

#### Tests 

 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
Support for `CREATE SEQUENCE`, `ALTER SEQUENCE` and `DROP SEQUENCE` was added. 
```

### CODE REVIEW

**Comment by dveeden** [comment]
Things that might need work:
- What would be a good way to add unittests or integration tests for this?
- There is a differences for when calling `DROP TABLE` on a sequence. Should we re-write that in DM?

**Review by asddongmen — APPROVED** [review]

**Review by lyzx2001 — APPROVED** [review]

**Comment by lance6716** [comment]
Strange that I didn't find ALTER SEQUENCE support in TiDB document https://docs.pingcap.com/tidb/stable/sql-statement-create-sequence . So I think at least we should not allow replicating this type of DDL.

And it will cause a behaviour change, so let PM start a review @frank945946

**Comment by dveeden** [comment]
> Strange that I didn't find ALTER SEQUENCE support in TiDB document https://docs.pingcap.com/tidb/stable/sql-statement-create-sequence . So I think at least we should not allow replicating this type of DDL.
> 
> And it will cause a behaviour change, so let PM start a review @Frank945946

This is supported:
```
sql> CREATE SEQUENCE s1 MINVALUE=2;
Query OK, 0 rows affected (0.1489 sec)

sql> ALTER SEQUENCE s1 MINVALUE=3;
ERROR: 4136 (HY000): Sequence 'test.s1' values are conflicting

sql> ALTER SEQUENCE s1 MINVALUE=1;
Query OK, 0 rows affected (0.1619 sec)

sql> SELECT TIDB_VERSION()\G
*************************** 1. row ***************************
TIDB_VERSION(): Release Version: v7.6.0
Edition: Community
Git Commit Hash: 52794d985ba6325d75a714d4eaa0838d59425eb6
Git Branch: heads/refs/tags/v7.6.0
UTC Build Time: 2024-01-22 14:20:42
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv
1 row in set (0.0007 sec)
```

**Review by AilinKid — APPROVED** [review]

**Comment by Frank945946** [comment]
As create, alter, and drop operations on sequences have already been supported in TiDB, LGTM supports migrating the sequence event from MariaDB to TiDB by DM. @dveeden @lance6716

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
