### PR TITLE
kafka(ticdc): ddl sink create admin client check error.

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: ref #8523 

### What is changed and how it works?

* check error after create the admin client.

#### Tests 

 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]
Could you add a test?

**Review by sdojjy — APPROVED** [review]

**Pull request merged**
