### PR TITLE
mounter(ticdc): reuse buf to reduce memory allocation when checksum enabled

### LINKED ISSUE #11529: introduce checksum verifier to manage checksum related functionality
Introduce one new struct, `checksumVerifier`, to manage all temporary slices used for the checksum calculation and verification

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #11529

### What is changed and how it works?

* add one new struct to manage checksum calculation and verification related logic

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by sdojjy — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Comment by 3AceShowHand** [comment]
close this since does not see obvious throughput performance improvement.

**Pull request closed without merging**
