### PR TITLE
sink(ticdc): use pd clock in storage sink

### LINKED ISSUE #10352: remove the local clock dependency from storage sink
Currently, the cloud storage sink uses local clock to generate files. If A table is scheduled from cdc node A to cdc node B, and ntp is not enabled on the cluster, or the time of the two machines is different, the generated file names may be backward or not incremental.

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: close #10352, ref #10374

### What is changed and how it works?
- Use pdClock instead of local clock to generate date seperator.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`Fix the issue that date seperator generated by the storage sink may roll back in table scheduling scenarios`.
```

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
It is ok for me if this is a quick and short term fix. But for long term we eventually will decouple the dependency with PD, we should have a better comprehensive solution later.

**Review by sdojjy — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Pull request merged**
