### PR TITLE
online-ddl: change default value of online-ddl to true

### LINKED ISSUE #4823: change default value of online-ddl to true
### Is your feature request related to a problem?

Some user use online ddl for every source, they need to set online-ddl for every task

### Describe the feature you'd like

change default value of online-ddl to true

### Describe alternatives you've considered

_No response_

### Teachability, Documentation, Adoption, Migration Strategy

_No response_

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: close #4823

### What is changed and how it works?
change default value to true

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
Enable online-ddl by default
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]
@okJiang PTAL

**Review by lichunzhu — APPROVED** [review]
LGTM

**Pull request merged**
