### PR TITLE
lightning(dm): add checksum to task configuation

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: ref #3510

#### Tests 

 - Integration test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
/cc @okJiang @gozssky 

PR contaions changes of generated file, not that big

**Comment by lance6716** [comment]
ptal @okJiang @gozssky

**Comment by lance6716** [comment]
ptal @okJiang @gozssky

**Review by gozssky — APPROVED** [review]

**Comment by lance6716** [comment]
ptal @buchuitoudegou @D3Hunter

**Review by buchuitoudegou — APPROVED** [review]

**Pull request merged**
