### PR TITLE
syncer(dm): discard checkpoint snapshot when syncer reset

### PR DESCRIPTION
**Pull request by gozssky**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/8374

`checkpointFlushWorker` may skip calling `FlushPointsExcept` if `execError` is not nil. This leads to inconsistent snapshot status.

https://github.com/pingcap/tiflow/blob/2f363f653a49fc557ebaab1afa7a47f900fbfc8f/dm/syncer/checkpoint_flush_worker.go#L82

https://github.com/pingcap/tiflow/blob/2f363f653a49fc557ebaab1afa7a47f900fbfc8f/dm/syncer/checkpoint.go#L662

### What is changed and how it works?
Always discard checkpoint snapshots after the syncer is reset.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by lance6716** [comment]
UT is needed to be updated

**Comment by gozssky** [comment]
@lance6716 @GMHDBJD PTAL again, test passed.

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
