### PR TITLE
sink(ticdc): add start ts to mysql log and refine get tso

### LINKED ISSUE #6460: Log start-ts in log when TiCDC MySQL sink fails to execute DML/DDL
Without the log, it is nearly impracticable for using ignore-start-ts feature to filter unwanted DML/DDL.

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: close #6460

### What is changed and how it works?

Add start-ts to mysql sink log and refine get tso.

#### Tests 

 - Integration test

### Release note 

```release-note
Log DML start ts when MySQL sink meets error.
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Comment by asddongmen** [comment]
=== Failed

[2022-07-25T11:41:54.262Z] === FAIL: cdc/sink/mysql TestPrepareDML (0.00s)

[2022-07-25T11:41:54.262Z] UPDATE `test`.`t1` SET `a`=?,`b`=? WHERE `a`=? AND `b`=? LIMIT 1;

[2022-07-25T11:41:54.262Z]     mysql_test.go:122: 

[2022-07-25T11:41:54.262Z]         	Error Trace:	mysql_test.go:122

[2022-07-25T11:41:54.262Z]         	Error:      	Not equal: 

[2022-07-25T11:41:54.262Z]         	            	expected: &mysql.preparedDMLs{startTs:[]uint64(nil), sqls:[]string{}, values:[][]interface {}{}, rowCount:0}

[2022-07-25T11:41:54.263Z]         	            	actual  : &mysql.preparedDMLs{startTs:[]uint64{}, sqls:[]string{}, values:[][]interface {}{}, rowCount:0}

[2022-07-25T11:41:54.263Z]         	            	

[2022-07-25T11:41:54.263Z]         	            	Diff:

[2022-07-25T11:41:54.263Z]         	            	--- Expected

[2022-07-25T11:41:54.263Z]         	            	+++ Actual

[2022-07-25T11:41:54.263Z]         	            	@@ -1,3 +1,4 @@

[2022-07-25T11:41:54.263Z]         	            	 (*mysql.preparedDMLs)({

[2022-07-25T11:41:54.263Z]         	            	- startTs: ([]uint64) <nil>,

[2022-07-25T11:41:54.263Z]         	            	+ startTs: ([]uint64) {

[2022-07-25T11:41:54.263Z]         	            	+ },

[2022-07-25T11:41:54.263Z]         	            	  sqls: ([]string) {

[2022-07-25T11:41:54.263Z]         	Test:       	TestPrepareDML

[2022-07-25T11:41:54.263Z]

**Review by asddongmen — APPROVED** [review]

**Pull request merged**
