### PR TITLE
checker(dm): expose verify privileges api

### LINKED ISSUE #7116: expose verify privileges api of checker

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #7116

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by D3Hunter** [comment]
merge need wait until 6.3 branch is created

**Review by lance6716 — APPROVED** [review]

**Review by buchuitoudegou — APPROVED** [review]

**Pull request merged**
