### PR TITLE
sorter/leveldb(ticdc): fix duplicate events

### LINKED ISSUE #3381: Flaking  integration test unified_sorter
### Which jobs are flaking?

integration_test

### Which test(s) are flaking?

unified_sorter

### Jenkins logs or GitHub Actions link

```log
[2021-11-10T12:56:36.650Z] table unified_sort.check1 not exists at last check

[2021-11-10T12:56:58.674Z] make: *** [integration_test_mysql] Error 1
```

https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/6006/pipeline/136

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: close #3381 ref #4631 

### What is changed and how it works?

Let exhaustedResolvedTs advances correctly, so reader does not
send events that have been sent before.

This issue is introduced by #4712

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]

**Review by sdojjy — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]

**Comment by lance6716** [comment]
some UT failed, like

```
panic: sync: WaitGroup is reused before previous Wait has returned
```

https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/4069/pipeline/

**Pull request merged**
