### PR TITLE
sink(ticdc): adjust lag bucket and add metrics for sink flush lag

### LINKED ISSUE #10675: [Enhancement] Improve observability of TiCDC lag
Need to improve observability of TiCDC lag in the following aspects:
1. Per event histogram metrics calculated by (TS after flushing to downstream - event TSO)

2. More fine grained bucketing for lag metrics. Currently the bucketing after 20 s is very coarse grained (https://github.com/pingcap/tiflow/blob/master/cdc/owner/metrics.go#L162).

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: close #10675

### What is changed and how it works?
Adjust the lag bucket of related metrics like `ticdc_owner_checkpoint_lag_histogram`.

Add a new metric `ticdc_sink_flush_lag_histogram` to monitor the per event flush lag calculated by `ts_after_event_flushed_to_downstream - commit_ts_of_event`
image

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by lidezhu** [comment]
PTAL @sdojjy @asddongmen

**Review by sdojjy — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Pull request merged**
