### PR TITLE
mysql(ticdc): consider collation when build the causality key

### LINKED ISSUE #9533: ticdc causality should be case sensitive
The same as #9489

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #9533 

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Comment by lance6716** [comment]
can we use sqlmodel library? In future we will implement more features

**Comment by 3AceShowHand** [comment]
> can we use sqlmodel library? In future we will implement more features

It's better if TiCDC and DM can share the same library.

**Review by hicqu — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Pull request merged**
