### PR TITLE
github: replace pingcap/ticdc with pingcap/tiflow in workflow

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

Some remaining `pingcap/ticdc`, finished the remaining problem-2 in https://github.com/pingcap/tiflow/issues/3749

**The DM github action tests are verified in #3966.**

These files were introduced from `v5.3.0`, so cherry pick to `release-5.3` is enough.

### What is changed and how it works?

replace `pingcap/ticdc` with `pingcap/tiflow` in files from `.github` dir

### Check List 

Tests 

 - Unit test
 - Integration test
 
```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]
Do this also has a script to make changes so we can replay the script to our PR?

**Review by lonng — APPROVED** [review]

**Pull request merged**
