### PR TITLE
test(engine): update lightning dependency to fix missing finishedBytes

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: ref #4159

### What is changed and how it works?

to include https://github.com/pingcap/tidb/pull/39365

#### Tests 

 - Integration test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
the failed case can pass in my local environment

/cc @D3Hunter @okJiang

**Comment by okJiang** [comment]
is this an unstable test? https://ci2.pingcap.net/blue/organizations/jenkins/engine_ghpr_integration_test/detail/engine_ghpr_integration_test/2227/pipeline

**Review by D3Hunter — APPROVED** [review]

**Comment by lance6716** [comment]
ptal @okJiang

**Review by okJiang — APPROVED** [review]

**Pull request merged**
