### PR TITLE
tests(ticdc): migrate test-infra to testify for several pkg

### LINKED ISSUE #2904: migrate test-infra to testify for `cdc/puller` pkg

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: close #2904, #2905, #2906

### What is changed and how it works?
Migrate all test cases under cdc/puller and cdc/sorter to testify.

### Check List 

Tests 

 - Unit test

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Review by ben1009 — APPROVED** [review]

**Comment by CharlesCheung96** [comment]
/
/run-all-tests

**Pull request merged**
