### PR TITLE
* (ticdc): manually cherry-pick simple protocol to release-7.5

### LINKED ISSUE #10874: cherry-pick simple protocol to release-7.5 branch
Cherry-pick simple protocol to release-7.5 to meet user requirement.

### PR DESCRIPTION
**Pull request by asddongmen**
Signed-off-by: dongmen <414110582@qq.com>

### What problem does this PR solve?

Issue Number: close #10874 

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
Manually cherry-pick simple protocol function to release-7.5
```

### CODE REVIEW

**Comment by asddongmen** [comment]
pull-cdc-integration-kafka-test

**Comment by asddongmen** [comment]
Block by https://github.com/pingcap/tiflow/pull/10646

**Review by 3AceShowHand — APPROVED** [review]

**Review by hongyunyan — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Pull request merged**
