### PR TITLE
sink(ticdc):  improve canal json encoder performance

### LINKED ISSUE #7540: improve canal-json encoder performance

### PR DESCRIPTION
**Pull request by sdojjy**
### What problem does this PR solve?

Issue Number: close #7540

### What is changed and how it works?
 Use easyjson to encode canal json

table with 62 columns,  performance is improved from 6k to 12k +
image

table with 124 columns, performance is improved from 4.3k to 8k +
image

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by nongfushanquan — APPROVED** [review]
good job！

**Review by asddongmen — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]

**Pull request merged**
