### PR TITLE
dep: update tidb version

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref #5493 

### What is changed and how it works?

update tidb version to include some metrics change

#### Tests 

 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by gozssky — APPROVED** [review]

**Comment by lance6716** [comment]
ping @GMHDBJD

**Comment by lance6716** [comment]
PTAL @liuzix @GMHDBJD

**Review by amyangfei — APPROVED** [review]

**Comment by lance6716** [comment]
/hold

metric dumpling_dump_finished_tables has invalid value

**Pull request merged**
