### PR TITLE
dm: fix MariaDB up down test

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: close #4287 

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by GMHDBJD** [comment]
/hold
waiting https://github.com/pingcap/tiflow/pull/11743

**Review by D3Hunter — APPROVED** [review]

**Pull request merged**
