### PR TITLE
sink(ticdc): only enable batch dml for more than one row

### LINKED ISSUE #10972: TiCDC: non batch dml is better than batch dml for sysbench oltp_update_non_index
image
image
Run sysbench oltp_update_non_index with `batch-dml-enable=false` and `batch-dml-enable=true`, when batch-dml-enable is false, it has higher throughput but consumes less cpu for downstream tidb.

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: close #10972 

#### Tests 

 - Manual test (add detailed scripts or steps below)
    run sysbench oltp_update_non_index and compare the performance.

image
Sink throughput increase from 22k to 34k.

image
Downstream tidb cpu usage decrease from 1600% to 1300%.

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

**Comment by asddongmen** [comment]
awesome!

**Review by CharlesCheung96 — APPROVED** [review]

**Comment by lidezhu** [comment]
Try to find a better threshold.

**Pull request merged**
