### PR TITLE
mysql(ticdc): handle the case when @@sql_mode is null

### LINKED ISSUE #7989: Cannot use a MySQL-compatible sink which @@SQL_MODE is NULL
### What did you do?

Use [Alibaba Cloud's AnalyzeDB for MySQL](https://www.alibabacloud.com/help/en/analyticdb-for-mysql) as sink

```
--sink-uri 'mysql://root:password@127.0.0.1:3306/?transaction-atomicity=table&time-zone=%2B08:00'
```

### What did you expect to see?

CDC changefeed created successfully

### What did you see instead?

```
MySQL query error: sql: Scan error on column index 0, name "@@session.sql_mode": converting NULL to string is unsupported
```

### Versions of the cluster

TiCDC  v6.1.2

### PR DESCRIPTION
**Pull request by kennytm**
Signed-off-by: kennytm <kennytm@gmail.com>

### What problem does this PR solve?

Issue Number: close #7989

### What is changed and how it works?

Use `sql.NullString` to receive the result of `select @@sql_mode`. Treat NULL as empty string.

#### Tests 

 - Unit test

##### Will it cause performance regression or break compatibility?

No

##### Do you need to update user documentation, design documentation or monitoring documentation?

No

### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```
Fix compatibility issue when using Alibaba AnalyzeDB for MySQL as TiCDC sink

### CODE REVIEW

**Review by nongfushanquan — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Comment by kennytm** [comment]
/run-check-issue-triage-complete
/run-engine-integration-test

<details>

```
[2022-12-29T02:31:28.736Z] === RUN   TestDMJob

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:28.736Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:28.737Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:28.737Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:28.737Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:28.737Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:28.737Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:28.737Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:28.994Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:29.251Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:29.509Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:29.767Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:30.025Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:30.282Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:30.541Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:30.541Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:31.105Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:31.105Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:32.005Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:32.005Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:32.263Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:32.263Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:32.520Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test2.t1' doesn't exist

[2022-12-29T02:31:32.777Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:33.051Z]     e2e_dm_test.go:171: no rows

[2022-12-29T02:31:33.312Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:33.569Z]     e2e_dm_test.go:171: no rows

[2022-12-29T02:31:33.569Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:34.133Z]     e2e_dm_test.go:167: query error: Error 1146: Table 'test1.t1' doesn't exist

[2022-12-29T02:31:34.697Z]     e2e_dm_test.go:171: no rows

[2022-12-29T02:31:44.666Z]     e2e_dm_test.go:208: 

[2022-12-29T02:31:44.666Z]         	Error Trace:	/home/jenkins/agent/workspace/engine_ghpr_integration_test/go/src/github.com/pingcap/tiflow/engine/test/e2e/e2e_dm_test.go:208

[2022-12-29T02:31:44.666Z]         	            				/home/jenkins/agent/workspace/engine_ghpr_integration_test/go/src/github.com/pingcap/tiflow/engine/test/e2e/e2e_dm_test.go:87

[2022-12-29T02:31:44.666Z]         	            				/home/jenkins/agent/workspace/engine_ghpr_integration_test/go/src/github.com/pingcap/tiflow/engine/test/e2e/asm_amd64.s:1594

[2022-12-29T02:31:44.666Z]         	Error:      	"null" does not contain "totalEvents"

[2022-12-29T02:31:44.666Z]         	Test:       	TestDMJob

[2022-12-29T02:31:44.666Z]     e2e_dm_test.go:208: 

[2022-12-29T02:31:44.666Z]         	Error Trace:	/home/jenkins/agent/workspace/engine_ghpr_integration_test/go/src/github.com/pingcap/tiflow/engine/test/e2e/e2e_dm_test.go:208

[2022-12-29T02:31:44.666Z]         	            				/home/jenkins/agent/workspace/engine_ghpr_integration_test/go/src/github.com/pingcap/tiflow/engine/test/e2e/e2e_dm_test.go:83

[2022-12-29T02:31:44.667Z]         	            				/home/jenkins/agent/workspace/engine_ghpr_integration_test/go/src/github.com/pingcap/tiflow/engine/test/e2e/asm_amd64.s:1594

[2022-12-29T02:31:44.667Z]         	Error:      	"null" does not contain "totalEvents"

[2022-12-29T02:31:44.667Z]         	Test:       	TestDMJob

[2022-12-29T02:31:44.667Z]     e2e_dm_test.go:115: 

[2022-12-29T02:31:44.667Z]         	Error Trace:	/home/jenkins/agent/workspace/engine_ghpr_integration_test/go/src/github.com/pingcap/tiflow/engine/test/e2e/e2e_dm_test.go:115

[2022-12-29T02:31:44.667Z]         	            				/home/jenkins/agent/workspace/engine_ghpr_integration_test/go/src/github.com/pingcap/tiflow/engine/test/e2e/e2e_dm_test.go:120

[2022-12-29T02:31:44.667Z]         	Error:      	Not equal: 

[2022-12-29T02:31:44.667Z]         	            	expected: 2

[2022-12-29T02:31:44.667Z]         	            	actual  : 1

[2022-12-29T02:31:44.667Z]         	Test:       	TestDMJob
```

</details>

**Pull request merged**
