### PR TITLE
tests(ticdc): add avro integration test to cover avro functionality 

### LINKED ISSUE #8934: add avro integration test to cover checksum functionality

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #8934 

### What is changed and how it works?

* add avro integration test, to cover the most basic checksum functionality.

#### Tests 

 - Integration test

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Comment by purelind** [comment]
> link

t looks like the image is not updated due to the pod profile using the cache, clean up the cache and try again

**Review by sdojjy — APPROVED** [review]

**Review by nongfushanquan — APPROVED** [review]

**Pull request merged**
