### PR TITLE
test(ticdc): fix bank failure caused by wrong snapshot in db session

### LINKED ISSUE #8211: CDC integration test bank failed with panic
### Which jobs are flaking?

cdc_ghpr_integration_test

### Which test(s) are flaking?

bank

### Jenkins logs or GitHub Actions link

https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/18245/pipeline/146/

```
[2023-02-09T07:36:05.679Z] [2023/02/09 15:36:05.437 +08:00] [INFO] [case.go:549] ["ddl synced"] [table=finishmark5000]
[2023-02-09T07:36:05.679Z] [2023/02/09 15:36:05.437 +08:00] [INFO] [case.go:555] ["downstream sync success"] [endTs="2023-02-09 15:36:05"]
[2023-02-09T07:36:05.680Z] [2023/02/09 15:36:05.439 +08:00] [INFO] [case.go:172] ["sequence verify pass"] [tag=root@tcp(127.0.0.1:4000)/bank]
[2023-02-09T07:36:05.680Z] [2023/02/09 15:36:05.443 +08:00] [INFO] [case.go:172] ["sequence verify pass"] [tag=root@tcp(127.0.0.1:3306)/bank]
[2023-02-09T07:36:05.680Z] [2023/02/09 15:36:05.450 +08:00] [INFO] [case.go:278] ["bank verify pass"] [tag=root@tcp(127.0.0.1:4000)/bank]
[2023-02-09T07:36:05.680Z] [2023/02/09 15:36:05.457 +08:00] [INFO] [case.go:278] ["bank verify pass"] [tag=root@tcp(127.0.0.1:3306)/bank]
[2023-02-09T07:36:05.680Z] [2023/02/09 15:36:05.542 +08:00] [PANIC] [case.go:571] ["downstream verify failed"] [error="[CDC:ErrReachMaxTry]reach maximum try: 10, error: missing changes sequence account_seq4, current sequence=90, previous sequence=88: missing changes sequence account_seq4, current sequence=90, previous sequence=88"] [stack="main.run.func2\n\t/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/tests/integration_tests/bank/case.go:571\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75"]
[2023-02-09T07:36:05.680Z] panic: downstream verify failed
[2023-02-09T07:36:05.680Z] 
[2023-02-09T07:36:05.680Z] goroutine 181 [running]:
[2023-02-09T07:36:05.680Z] go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc000133420?})
[2023-02-09T07:36:05.680Z] 	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
[2023-02-09T07:36:05.680Z] go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00031c340, {0xc00045a5c0, 0x1, 0x1})
[2023-02-09T07:36:05.680Z] 	/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
[2023-02-09T07:36:05.680Z] go.uber.org/zap.(*Logger).Panic(0xc00045a5c0?, {0x8f5918?, 0xc00012e270?}, {0xc00045a5c0, 0x1, 0x1})
[2023-02-09T07:36:05.680Z] 	/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:258 +0x59
[2023-02-09T07:36:05.680Z] github.com/pingcap/log.Panic({0x8f5918?, 0x13?}, {0xc00045a5c0?, 0x9e8e28?, 0xc000587440?})
[2023-02-09T07:36:05.680Z] 	/go/pkg/mod/github.com/pingcap/log@v1.1.1-0.20221116035753-734d527bc87c/global.go:54 +0x8b
[2023-02-09T07:36:05.680Z] main.run.func2()
[2023-02-09T07:36:05.680Z] 	/home/jenkins/agent/workspace/cdc_ghpr_integration_test/go/src/github.com/pingcap/tiflow/tests/integration_tests/bank/case.go:571 +0xa85
[2023-02-09T07:36:05.680Z] golang.org/x/sync/errgroup.(*Group).Go.func1()
[2023-02-09T07:36:05.680Z] 	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
[2023-02-09T07:36:05.680Z] created by golang.org/x/sync/errgroup.(*Group).Go
[2023-02-09T07:36:05.680Z] 	/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
[2023-02-09T07:36:05.680Z] exit status 2
[2023-02-09T07:36:05.680Z] + stop_tidb_cluster
[2023-02-09T07:36:23.741Z] make: *** [integration_test_mysql] Error 1
[2023-02-09T07:36:38.224Z] Killing processes
[2023-02-09T07:36:38.596Z] kill finished with exit code 1
script returned exit code 2
```

detail logs:

[pipeline.log](https://github.com/pingcap/tiflow/files/10695120/pipeline.log)
[cdc.log](https://github.com/pingcap/tiflow/files/10695122/cdc.log)

### Anything else we need to know

version
master@https://github.com/pingcap/tiflow/commit/302a478cf4103f1a2727a5c3365bd4d9de973914

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: close #8211

### What is changed and how it works?

`*sql.DB` holds a connection pool, it returns a random idle connection, in the bank test we need to ensure the database connection has the same snapshot  during verification.

#### Tests 

 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Comment by asddongmen** [comment]
/hold 
It fails again: https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/18321/pipeline/

**Pull request merged**
