### PR TITLE
dm(engine): fix jobMaster panic

### LINKED ISSUE #7624: dm jobMaster panic in chaos test
### What did you do?

run chaos test

### What did you expect to see?

pass test

### What did you see instead?

```log
./chaos-executor-1.log:[2022/11/15 18:19:58.859 +00:00] [ERROR] [task_runner.go:207] ["Task panicked"] [id=9d86b5a3-1059-4e56-ad6b-3ad0ac864392] [error="panic: runtime error: invalid memory address or nil pointer dereference"] [errorVerbose="panic: runtime error: invalid memory address or nil pointer dereference\ngithub.com/pingcap/tiflow/engine/executor/worker.(*TaskRunner).launchTask.func1.1\n\tgithub.com/pingcap/tiflow/engine/executor/worker/task_runner.go:206\nruntime.gopanic\n\truntime/panic.go:884\nruntime.panicmem\n\truntime/panic.go:260\nruntime.sigpanic\n\truntime/signal_unix.go:835\ngithub.com/pingcap/tiflow/engine/jobmaster/dm.(*JobMaster).CloseImpl\n\tgithub.com/pingcap/tiflow/engine/jobmaster/dm/dm_jobmaster.go:292\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseJobMaster).Close.func1\n\tgithub.com/pingcap/tiflow/engine/framework/base_jobmaster.go:255\nsync.(*Once).doSlow\n\tsync/once.go:74\nsync.(*Once).Do\n\tsync/once.go:65\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseJobMaster).Close\n\tgithub.com/pingcap/tiflow/engine/framework/base_jobmaster.go:254\ngithub.com/pingcap/tiflow/engine/framework/internal/eventloop.(*Runner[...]).Run\n\tgithub.com/pingcap/tiflow/engine/framework/internal/eventloop/runner.go:73\ngithub.com/pingcap/tiflow/engine/executor/worker.(*TaskRunner).launchTask.func1\n\tgithub.com/pingcap/tiflow/engine/executor/worker/task_runner.go:225\nruntime.goexit\n\truntime/asm_amd64.s:1594"]
```

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

```console
(paste Dataflow Engine version here)
```

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: close #7624

### What is changed and how it works?
1. check `jm.messageAgent` before close it

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Comment by lance6716** [comment]
https://github.com/pingcap/tiflow/blob/c33e03594573f96248f84a44468d7d0864a7659e/engine/jobmaster/dm/dm_jobmaster.go#L103

https://github.com/pingcap/tiflow/blob/c33e03594573f96248f84a44468d7d0864a7659e/engine/framework/worker.go#L90

Is this panic caused by CloseImpl called concurrent with InitImpl or other callback functions? if so, we need to update the comments and check data race of jobmaster members

**Comment by amyangfei** [comment]
> https://github.com/pingcap/tiflow/blob/c33e03594573f96248f84a44468d7d0864a7659e/engine/jobmaster/dm/dm_jobmaster.go#L103-L107
> 
> https://github.com/pingcap/tiflow/blob/c33e03594573f96248f84a44468d7d0864a7659e/engine/framework/worker.go#L90-L98
> 
> Is this panic caused by CloseImpl called concurrent with InitImpl or other callback functions? if so, we need to update the comments and check data race of jobmaster members

No, `Init` and `CloseImpl` are guaranteed to be strict serialization, they can't be called concurrently. The `InitImpl` of DM logic was not called, it may caused by the `PreInit` failure in framework jobmaster. The sequence diagram is as follows

- `Init`
   - `doPreInit` -> fails here
   - business logic `InitImpl`
   - `doPostInit`
- `Init` returns error, call `CloseImpl`

**Comment by lance6716** [comment]
> > https://github.com/pingcap/tiflow/blob/c33e03594573f96248f84a44468d7d0864a7659e/engine/jobmaster/dm/dm_jobmaster.go#L103-L107
> > 
> > https://github.com/pingcap/tiflow/blob/c33e03594573f96248f84a44468d7d0864a7659e/engine/framework/worker.go#L90-L98
> > 
> > Is this panic caused by CloseImpl called concurrent with InitImpl or other callback functions? if so, we need to update the comments and check data race of jobmaster members
> 
> No, `Init` and `CloseImpl` are guaranteed to be strictly serializable, they can't be called concurrently. The `InitImpl` of DM logic was not called, it may caused by the `PreInit` failure in framework jobmaster. The sequence diagram is as follows
> 
> * `Init`
>   
>   * `doPreInit` -> fails here
>   * business logic `InitImpl`
>   * `doPostInit`
> * `Init` returns error, call `CloseImpl`

@CharlesCheung96 please help us update the comment of CloseImpl, mention that it can be called before InitImpl

**Comment by lance6716** [comment]
Or maybe add a TODO that the framework has no need to call CloseImpl at doPreInit failing, because InitImpl is not called so business logic has not taken place, no need to clean up the business logic.

**Comment by amyangfei** [comment]
> Or maybe add a TODO that the framework has no need to call CloseImpl at doPreInit failing, because InitImpl is not called so business logic has not taken place, no need to clean up the business logic.

We can add an issue to follow up. It is reasonable that don't call `CloseImpl` if `InitImpl` is not called.

**Review by gozssky — APPROVED** [review]

**Pull request merged**
