### PR TITLE
tests(cdc): migrate pingcap/check to testify, remove unused leaktest

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: ref #6094

### What is changed and how it works?

- Use testify in pkg/txnutil/gc package
- Remove unused leaktest

#### Tests 

 - Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by CharlesCheung96** [comment]
Perhaps we should add a new script to verify that `goleak` is enabled for each `pkg`.

**Comment by amyangfei** [comment]
> Perhaps we should add a new script to verify that `goleak` is enabled for each `pkg`.

Good point @CharlesCheung96

**Comment by CharlesCheung96** [comment]
image
Whether `leak-test` should be removed?

**Comment by amyangfei** [comment]
> image
> 
> Whether `leak-test` should be removed?

Yes, I have communicated with CI colleague

**Review by CharlesCheung96 — APPROVED** [review]

**Comment by amyangfei** [comment]
ptal @maxshuang

**Review by maxshuang — APPROVED** [review]

**Pull request merged**
