### PR TITLE
config(ticdc): deprecate  changefeed level config enable-old-value

### LINKED ISSUE #9667: deprecate the changefeed level `enable-old-value` configuration
`enable-old-value` controls whether to output previous column values for the update events, also adjust the output content of the delete event previously.

Mostly, It's set to true. There is no need to make it configurable, so remove it.

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #9667 

### What is changed and how it works?

* remove the `enable-old-value` from the changefeed configuration.
* remove all reference about this variable

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
deprecate the changefeed level `enable-old-value` configuration, always is true
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

**Comment by asddongmen** [comment]
Finally.

**Review by sdojjy — APPROVED** [review]

**Pull request merged**
