### PR TITLE
metrics, pulsar (ticdc): add pulsar metrics panel

### PR DESCRIPTION
**Pull request by yumchina**
### What problem does this PR solve?

1 add pulsar metrics template

Issue Number: ref https://github.com/pingcap/tiflow/issues/9413

#### Tests 

 - No code

### Release note 
```release-note
None
```

### CODE REVIEW

**Comment by asddongmen** [comment]
Please add a screenshot of the panel you add in the pull request description block.

**Review by asddongmen — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]

**Pull request merged**
