### PR TITLE
sink(ticdc): Optimize the performance when getting the metadata of Kafka topics

### PR DESCRIPTION
**Pull request by hi-rustin**
This is an automated cherry-pick of #9060 and https://github.com/pingcap/tiflow/pull/8893 and #8938

 
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/8959 close https://github.com/pingcap/tiflow/issues/8957
 
### What is changed and how it works?

- Get the metadata by needs instead of getting all topic's metadata.
- Support OAuth.
- Support Kop.

#### Tests 

 - Unit test
 - Manual test 

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
Optimize the performance when TiCDC gets the metadata of Kafka topics
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
Tested locally:
1. create the pulsar and KOP sever with docker
2. start tidb cluster
3. start ticdc server
4. create tenant and namespace
```shell
bin/pulsar-admin --auth-plugin org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2 --auth-params '{"privateKey":"/conf/client_credentials.json", "issuerUrl":"https://dev-x.us.auth0.com", "audience":"pulsar"}' tenants create ticdc
bin/pulsar-admin --auth-plugin org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2 --auth-params '{"privateKey":"/conf/client_credentials.json", "issuerUrl":"https://dev-x.us.auth0.com", "audience":"pulsar"}'  tenants list
bin/pulsar-admin --auth-plugin org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2 --auth-params '{"privateKey":"/conf/client_credentials.json", "issuerUrl":"https://dev-x.us.auth0.com", "audience":"pulsar"}'  namespaces create ticdc/test
bin/pulsar-admin --auth-plugin org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2 --auth-params '{"privateKey":"/conf/client_credentials.json", "issuerUrl":"https://dev-x.us.auth0.com", "audience":"pulsar"}'  namespaces list ticdc
```
5. create a changefeed with config: 
```log
./cdc cli changefeed create --sink-uri="kafka://10.x.27:19092/ticdc/test/a?max-message-bytes=1048576&protoco
l=open-protocol&kafka-version=2.0.0&replication-factor=1" --config=changefeed.toml
[2023/06/08 16:33:29.934 +08:00] [WARN] [kafka.go:580] ["Kafka config item not found"] [configName=min.insync.replicas]
[2023/06/08 16:33:29.948 +08:00] [WARN] [kafka.go:494] ["partition-num is not set, use the default partition count"] [topic=ticdc/test/a] [partitions=3]
[2023/06/08 16:33:30.298 +08:00] [WARN] [mq.go:202] ["resolved ts buffer is closed"] [namespace=] [changefeed=] [role=cdc-client]
[2023/06/08 16:33:30.299 +08:00] [WARN] [mq_flush_worker.go:117] ["MQ sink flush worker channel closed"]
Create changefeed successfully!
ID: 7d1a813f-c0f8-4866-8672-5e20cee471c6
Info: {"upstream-id":0,"sink-uri":"kafka://10.x27:19092/ticdc/test/a?max-message-bytes=1048576\u0026protocol=open-protocol\u0026kafka-version=2.0.0\u0026replication-factor=1","opts":{},"create-time":"2023-06-08T16:33:27.673989417+08:00","start-ts":442030675094667266,"target-ts":0,"admin-job-type":0,"sort-engine":"unified","sort-dir":"","config":{"case-sensitive":true,"enable-old-value":true,"force-replicate":false,"check-gc-safe-point":true,"filter":{"rules":["*.*"],"ignore-txn-start-ts":null},"mounter":{"worker-num":16},"sink":{"transaction-atomicity":"","protocol":"open-protocol","dispatchers":null,"column-selectors":null,"schema-registry":"","encoder-concurrency":16,"kafka-config":{"sasl-mechanism":"OAUTHBEARER","sasl-oauth-client-id":"x","sasl-oauth-client-secret":"x==","sasl-oauth-token-url":"https://dev-x.us.auth0.com/oauth/token","sasl-oauth-grant-type":"client_credentials","sasl-oauth-audience":"pulsar"}},"cyclic-replication":{"enable":false,"replica-id":0,"filter-replica-ids":null,"id-buckets":0,"sync-ddl":false},"consistent":{"level":"none","max-log-size":64,"flush-interval":2000,"storage":""}},"state":"normal","error":null,"sync-point-enabled":false,"sync-point-interval":600000000000,"creator-version":"v6.1.0-master"}
```
6. check the topic created: `bin/pulsar-admin --auth-plugin org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2 --auth-params '{"privateKey":"/conf/client_credentials.json", "issuerUrl":"https://dev-x.us.auth0.com", "audience":"pulsar"}' topics list-partitioned-topics ticdc/test`
7. try to create table and write some data, consume the topic:
```log
bin/pulsar-client --auth-plugin org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2 --auth-params '{"privateKey":"/conf/client_credentials.json", "issuerUrl":"https://dev-x.us.auth0.com", "audience":"pulsar"}'  consume -s sub ticdc/test/a  -n 0

----- got message -----
key:[AAAAAAAAAAEAAAAAAAAAH3sidHMiOjQ0MjAzMDg4NTA1ODkwNDA2NSwidCI6M30=], properties:[], content:
----- got message -----
key:[AAAAAAAAAAEAAAAAAAAAR3sidHMiOjQ0MjAzMDg4NTM3MzQ3Njg2Niwic2NtIjoidGVzdCIsInRibCI6InRwX2ludF9sejQiLCJyaWQiOjMsInQiOjF9], properties:[], content:?{"u":{"c_bigint":{"t":8,"f":65,"v":8},"c_int":{"t":3,"f":65,"v":4},"c_mediumint":{"t":9,"f":65,"v":3},"c_smallint":{"t":2,"f":65,"v":2},"c_tinyint":{"t":1,"f":65,"v":1},"id":{"t":3,"h":true,"f":11,"v":3}}}
```

**Review by nongfushanquan — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Pull request merged**
