### PR TITLE
sinkv2(cdc): fix sinkv2 grafana

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: ref #5928

### What is changed and how it works?
add changefeed and instance filter to sinkv2 panel.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

- before
image

- after
image

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Review by zhaoxinyu — APPROVED** [review]

**Comment by zhaoxinyu** [comment]
Please add the screenshots before and after this fix.

**Pull request merged**
