### PR TITLE
dm(engine): add finished_unit_status in DM QueryJobStatus

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref #7115 

### What is changed and how it works?

when DM jobmaster receives its worker finishing message, save it to metadata

#### Tests 

 - Unit test
 - Integration test
 - manually test

```
{
  "job_id":"74145e07-1bb4-4566-a58b-8610423c5bdf",
  "task_status":{
    "mysql-01":{
      "expected_stage":"Running",
      "worker_id":"",
      "config_outdated":false,
      "status":null
    }
  },
  "finished_unit_status":{
    "mysql-01":[
      {
        "Unit":"DMDumpTask",
        "Task":"mysql-01",
        "Stage":"Finished",
        "CfgModRevision":0,
        "Result":{
          
        },
        "Status":{
          "totalTables":3,
          "completedTables":3,
          "finishedBytes":144,
          "finishedRows":2,
          "estimateTotalRows":3
        }
      },
      {
        "Unit":"DMLoadTask",
        "Task":"mysql-01",
        "Stage":"Finished",
        "CfgModRevision":0,
        "Result":{
          
        },
        "Status":{
          "finishedBytes":144,
          "totalBytes":144,
          "progress":"100.00 %",
          "currentSpeedBytesPerSecond":144
        }
      }
    ]
  }
}
```

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
@D3Hunter I posted an response example in the description of PR, will refine later

**Review by D3Hunter — APPROVED** [review]
rest lgtm

**Review by okJiang — APPROVED** [review]

**Pull request merged**
