### PR TITLE
mock(engine): prepare correct master meta to make master works normally

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: ref #6665

Note this PR is **NOT** a fix of #6665, but fix of some error mock code.

### What is changed and how it works?

Without this fix, mock server master is not created correctly.

```go
[2022/08/09 15:26:24.881 +08:00] [WARN] [master.go:224] ["invalid master meta"] [data=] [error="unexpected end of JSON input"] [errorVerbose="unexpected end of JSON input\ngithub.com/pingcap/errors.AddStack\n\t/home/apple/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/home/apple/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/juju_adaptor.go:15\ngithub.com/pingcap/tiflow/engine/framework.NewBaseMaster\n\t/home/apple/code/tiflow/engine/framework/master.go:222\ngithub.com/pingcap/tiflow/engine/framework.MockBaseMaster\n\t/home/apple/code/tiflow/engine/framework/mock_master_util.go:68\ngithub.com/pingcap
/tiflow/engine/jobmaster/example.newExampleMaster\n\t/home/apple/code/tiflow/engine/jobmaster/example/master_impl_test.go:40\ngithub.com/pingcap/tiflow/engine/jobmaster/example.TestExampleMaster\n\t/home/apple/code/tiflow/engine/jobmaster/example/master_impl_test.go:53\ntesting.tRunner\n\t/home/apple/.g/go/src/testing/testing.go:1439\nruntime.goexit\n\t/home/apple/.g/go/src/runtime/asm_amd64.s:1571"]
[2022/08/09 15:28:43.531 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=601.586µs] [sql="SELECT * FROM `master_meta_kv_data` WHERE id = \"master\" AND `master_meta_kv_data`.`deleted` IS NULL ORDER BY `master_meta_kv_data`.`seq_id` LIMIT 1"] [affected-rows=0] [error="record not found"]
[2022/08/09 15:28:43.532 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=394.972µs] [sql="INSERT INTO `logic_epoches` (`created_at`,`updated_at`,`job_id`,`epoch`) VALUES (\"2022-08-09 15:28:43.532\",\"2022-08-09 15:28:43.532\",\"\",1) ON CONFLICT DO NOTHING"] [affected-rows=1]
[2022/08/09 15:28:43.532 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=220.699µs] [sql="UPDATE `logic_epoches` SET `epoch`=epoch + 1,`updated_at`=\"2022-08-09 15:28:43.532\" WHERE job_id = \"\""] [affected-rows=1]
[2022/08/09 15:28:43.533 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=295.68µs] [sql="SELECT * FROM `logic_epoches` WHERE job_id = \"\" ORDER BY `logic_epoches`.`seq_id` LIMIT 1"] [affected-rows=1]
[2022/08/09 15:28:43.533 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=182.343µs] [sql="UPDATE `master_meta_kv_data` SET `address`=\"\",`config`=\"\",`epoch`=2,`id`=\"master\",`node_id`=\"\",`project_id`=\"\",`status`=\"1\",`type`=\"0\",`updated_at`=\"2022-08-09 15:28:43.533\" WHERE id = \"master\" AND `master_meta_kv_data`.`deleted` IS NULL"] [affected-rows=0]
[2022/08/09 15:28:43.533 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=137.804µs] [sql="SELECT * FROM `master_meta_kv_data` WHERE id = \"master\" AND `master_meta_kv_data`.`deleted` IS NULL ORDER BY `master_meta_kv_data`.`seq_id` LIMIT 1"] [affected-rows=0] [error="record not found"]
[2022/08/09 15:28:43.534 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=156.444µs] [sql="UPDATE `master_meta_kv_data` SET `address`=\"\",`config`=\"\",`epoch`=0,`id`=\"master\",`node_id`=\"\",`project_id`=\"\",`status`=\"2\",`type`=\"0\",`updated_at`=\"2022-08-09 15:28:43.533\" WHERE id = \"master\" AND `master_meta_kv_data`.`deleted` IS NULL"] [affected-rows=0]
[2022/08/09 15:28:43.535 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=424.587µs] [sql="UPDATE `logic_epoches` SET `epoch`=epoch + 1,`updated_at`=\"2022-08-09 15:28:43.534\" WHERE job_id = \"\""] [affected-rows=1]
[2022/08/09 15:28:43.535 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=310.265µs] [sql="SELECT * FROM `logic_epoches` WHERE job_id = \"\" ORDER BY `logic_epoches`.`seq_id` LIMIT 1"] [affected-rows=1]
[2022/08/09 15:28:43.736 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=1.018961ms] [sql="INSERT INTO `worker_statuses` (`created_at`,`updated_at`,`project_id`,`job_id`,`id`,`type`,`status`,`epoch`,`errmsg`,`ext_bytes`) VALUES (\"2022-08-09 15:28:43.736\",\"2022-08-09 15:28:43.736\",\"\",\"\",\"\",\"0\",\"3\",0,\"\",\"\") ON CONFLICT (`id`,`job_id`) DO UPDATE SET `updated_at`=`excluded`.`updated_at`,`project_id`=`excluded`.`project_id`,`job_id`=`excluded`.`job_id`,`id`=`excluded`.`id`,`type`=`excluded`.`type`,`status`=`excluded`.`status`,`epoch`=`excluded`.`epoch`,`errmsg`=`excluded`.`errmsg`,`ext_bytes`=`excluded`.`ext_bytes`"] [affected-rows=1]
```

- incorrect meta data

```go
[2022/08/09 15:28:43.531 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=601.586µs] [sql="SELECT * FROM `master_meta_kv_data` WHERE id = \"master\" AND `master_meta_kv_data`.`deleted` IS NULL ORDER BY `master_meta_kv_data`.`seq_id` LIMIT 1"] [affected-rows=0] [error="record not found"]
[2022/08/09 15:28:43.532 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=394.972µs] [sql="INSERT INTO `logic_epoches` (`created_at`,`updated_at`,`job_id`,`epoch`) VALUES (\"2022-08-09 15:28:43.532\",\"2022-08-09 15:28:43.532\",\"\",1) ON CONFLICT DO NOTHING"] [affected-rows=1]
[2022/08/09 15:28:43.532 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=220.699µs] [sql="UPDATE `logic_epoches` SET `epoch`=epoch + 1,`updated_at`=\"2022-08-09 15:28:43.532\" WHERE job_id = \"\""] [affected-rows=1]
[2022/08/09 15:28:43.533 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=295.68µs] [sql="SELECT * FROM `logic_epoches` WHERE job_id = \"\" ORDER BY `logic_epoches`.`seq_id` LIMIT 1"] [affected-rows=1]
[2022/08/09 15:28:43.533 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=182.343µs] [sql="UPDATE `master_meta_kv_data` SET `address`=\"\",`config`=\"\",`epoch`=2,`id`=\"master\",`node_id`=\"\",`project_id`=\"\",`status`=\"1\",`type`=\"0\",`updated_at`=\"2022-08-09 15:28:43.533\" WHERE id = \"master\" AND `master_meta_kv_data`.`deleted` IS NULL"] [affected-rows=0]
[2022/08/09 15:28:43.533 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=137.804µs] [sql="SELECT * FROM `master_meta_kv_data` WHERE id = \"master\" AND `master_meta_kv_data`.`deleted` IS NULL ORDER BY `master_meta_kv_data`.`seq_id` LIMIT 1"] [affected-rows=0] [error="record not found"]
[2022/08/09 15:28:43.534 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=156.444µs] [sql="UPDATE `master_meta_kv_data` SET `address`=\"\",`config`=\"\",`epoch`=0,`id`=\"master\",`node_id`=\"\",`project_id`=\"\",`status`=\"2\",`type`=\"0\",`updated_at`=\"2022-08-09 15:28:43.533\" WHERE id = \"master\" AND `master_meta_kv_data`.`deleted` IS NULL"] [affected-rows=0]
[2022/08/09 15:28:43.535 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=424.587µs] [sql="UPDATE `logic_epoches` SET `epoch`=epoch + 1,`updated_at`=\"2022-08-09 15:28:43.534\" WHERE job_id = \"\""] [affected-rows=1]
[2022/08/09 15:28:43.535 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=310.265µs] [sql="SELECT * FROM `logic_epoches` WHERE job_id = \"\" ORDER BY `logic_epoches`.`seq_id` LIMIT 1"] [affected-rows=1]
[2022/08/09 15:28:43.736 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=1.018961ms] [sql="INSERT INTO `worker_statuses` (`created_at`,`updated_at`,`project_id`,`job_id`,`id`,`type`,`status`,`epoch`,`errmsg`,`ext_bytes`) VALUES (\"2022-08-09 15:28:43.736\",\"2022-08-09 15:28:43.736\",\"\",\"\",\"\",\"0\",\"3\",0,\"\",\"\") ON CONFLICT (`id`,`job_id`) DO UPDATE SET `updated_at`=`excluded`.`updated_at`,`project_id`=`excluded`.`project_id`,`job_id`=`excluded`.`job_id`,`id`=`excluded`.`id`,`type`=`excluded`.`type`,`status`=`excluded`.`status`,`epoch`=`excluded`.`epoch`,`errmsg`=`excluded`.`errmsg`,`ext_bytes`=`excluded`.`ext_bytes`"] [affected-rows=1]
```

- metadata is not persisted

```go
[2022/08/09 15:28:43.531 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=601.586µs] [sql="SELECT * FROM `master_meta_kv_data` WHERE id = \"master\" AND `master_meta_kv_data`.`deleted` IS NULL ORDER BY `master_meta_kv_data`.`seq_id` LIMIT 1"] [affected-rows=0] [error="record not found"]
[2022/08/09 15:28:43.533 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=182.343µs] [sql="UPDATE `master_meta_kv_data` SET `address`=\"\",`config`=\"\",`epoch`=2,`id`=\"master\",`node_id`=\"\",`project_id`=\"\",`status`=\"1\",`type`=\"0\",`updated_at`=\"2022-08-09 15:28:43.533\" WHERE id = \"master\" AND `master_meta_kv_data`.`deleted` IS NULL"] [affected-rows=0]
[2022/08/09 15:28:43.533 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=137.804µs] [sql="SELECT * FROM `master_meta_kv_data` WHERE id = \"master\" AND `master_meta_kv_data`.`deleted` IS NULL ORDER BY `master_meta_kv_data`.`seq_id` LIMIT 1"] [affected-rows=0] [error="record not found"]
[2022/08/09 15:28:43.534 +08:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=156.444µs] [sql="UPDATE `master_meta_kv_data` SET `address`=\"\",`config`=\"\",`epoch`=0,`id`=\"master\",`node_id`=\"\",`project_id`=\"\",`status`=\"2\",`type`=\"0\",`updated_at`=\"2022-08-09 15:28:43.533\" WHERE id = \"master\" AND `master_meta_kv_data`.`deleted` IS NULL"] [affected-rows=0]
```

#### Tests 

 - Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by maxshuang — APPROVED** [review]

**Comment by amyangfei** [comment]
PTAL @liuzix @CharlesCheung96

**Review by liuzix — APPROVED** [review]

**Pull request merged**
