### PR TITLE
owner,docs,pkg(ticdc): fix typo and remove dead code

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/5039

### What is changed and how it works?

- fix typo
- remove dead code

### Check List 

Tests 

 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change

Side effects

None

Related changes

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]
LGTM

**Review by asddongmen — APPROVED** [review]

**Comment by hi-rustin** [comment]
@asddongmen @overvenus Removed some useless config. Could you please take a look again?

**Comment by asddongmen** [comment]
lgtm

**Pull request merged**
