### PR TITLE
[WIP] cdc: verification tidb as downstream, integration test only

### PR DESCRIPTION
**Pull request by ben1009**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/4519
fix https://github.com/pingcap/tiflow/issues/5019
### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by ben1009** [comment]
> /run-all-tests

1

**Comment by ben1009** [comment]
> > /run-all-tests
> 
> 1

1

**Comment by ben1009** [comment]
> /run-all-tests

1

**Comment by ben1009** [comment]
> > /run-all-tests
> 
> 1

**Comment by ben1009** [comment]
> > > /run-all-tests
> > 
> > 
> > 1

**Comment by ben1009** [comment]
> > > > /run-all-tests
> > > 
> > > 
> > > 1

**Comment by ben1009** [comment]
> > > > > /run-all-tests
> > > > 
> > > > 
> > > > 1

**Comment by ben1009** [comment]
> > > > > > /run-all-tests
> > > > > 
> > > > > 
> > > > > 1

**Comment by ben1009** [comment]
> > > > > > > /run-all-tests
> > > > > > 
> > > > > > 
> > > > > > 1

**Comment by ben1009** [comment]
> > > > > > > > /run-all-tests
> > > > > > > 
> > > > > > > 
> > > > > > > 1

**Comment by ben1009** [comment]
> > > > > > > > > /run-all-tests
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 1

**Comment by ben1009** [comment]
> > > > > > > > > > /run-all-tests
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 1

**Comment by hi-rustin** [comment]
I am going to close this PR because there are a lot of conflicts here. Thanks!

**Pull request closed without merging**
