### PR TITLE
test(ticdc): Correct SHA256 checksum for downloaded golang version

### LINKED ISSUE #7272: ticdc: sha256sum of golang download needs update
@dveeden I think we need to change this sha value.

_Originally posted by @hi-rustin in https://github.com/pingcap/tiflow/pull/7240#discussion_r984186774_

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #7272

### What is changed and how it works?

As you can see the checksum was still the one for Go 1.18:

```
$ sha256sum go1.*
e85278e98f57cdb150fe8409e6e5df5343ecb13cebf03a5d5ff12bd55a80264f  go1.18.linux-amd64.tar.gz
464b6b66591f6cf055bc5df90a9750bf5fbc9d038722bb84a9d56a2bea974be6  go1.19.linux-amd64.tar.gz
```

#### Tests 

 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by dveeden** [comment]
And this can be confirmed with the data from https://go.dev/dl/ (under "Archived versions")

image

**Review by amyangfei — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
