### PR TITLE
* : upgrade go to 1.23

### LINKED ISSUE #11606: Upgrade go to 1.23
### Is your feature request related to a problem?

No

### Describe the feature you'd like

Upgrade golang to version 1.23

### Describe alternatives you've considered

_No response_

### Teachability, Documentation, Adoption, Migration Strategy

_No response_

### PR DESCRIPTION
**Pull request by Benjamin2037**
### What problem does this PR solve?

Issue Number: close #11606

```release-note
Upgrade golang to version 1.23 
```

### CODE REVIEW

**Review by yudongusa — APPROVED** [review]
LGTM

**Comment by Benjamin2037** [comment]
For golangci-lint, it is not work well with go 1.23, I found `errcheck` will cause panic of golangci-lint. Also in go 1.23, there are more strict for lint rules, I skip some check because of fix them need more workload and time. left them to later. @hicqu @GMHDBJD 
`  # temp disable errcheck because of panic of lint check.
  # temp disable some check for upgrade to go 1.23, later need to enable them according situation. include:
  # depguard, revive，govet，nakedret， predeclared
  enable:
    - asciicheck
    - bodyclose
    #- depguard
    - dogsled
    - dupl
    #- errcheck
    - exportloopref
    - gocritic
    - godot
    - goprintffuncname
    - gosimple
    #- govet
    - ineffassign
    - misspell
    #- nakedret
    - noctx
    - prealloc
    #- revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - durationcheck
    - gofumpt
    - goheader
    - gomodguard
    - importas
    - makezero
    - nilerr
    #- predeclared
    - sqlclosecheck
    - thelper
    - tparallel
    - wastedassign`

**Review by hicqu — APPROVED** [review]

**Pull request merged**
