### PR TITLE
chaos(engine): fix missing checkout PR in manually workflow

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: ref #5640

### What is changed and how it works?

- Should checkout to PR head when running workflow manually.

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by amyangfei** [comment]
verified in: https://github.com/pingcap/tiflow/actions/runs/2703486507

```go
[2022/07/20 09:44:59.051 +00:00] [INFO] [version.go:35] ["Welcome to Dataflow Engine"] [release-version=v6.2.0-master] [git-hash=108fd919cc4cb2c0f3952f6a386ab25d06d4cd34] [git-branch=HEAD] [utc-build-time="2022-07-20 09:38:49"] [go-version="go version go1.18.4 linux/amd64"]
```

**Comment by maxshuang** [comment]
Does this pr solve the problem that  workflow miss to checkout pr when we  manually trigger github action?

**Comment by amyangfei** [comment]
> Does this pr solve the problem that workflow miss to checkout pr when we manually trigger github action?

Yes

**Comment by amyangfei** [comment]
ptal @maxshuang @CharlesCheung96

**Review by maxshuang — APPROVED** [review]

**Pull request merged**
