### PR TITLE
mounter(ticdc): timezone fill default value should also consider tz.

### LINKED ISSUE #10931: timestamp fill default value should also consider timezone
#10803, we fix the default value that does not consider the data type.

Since TiDB stores the timestamp value in the UTC timezone, when filling the default value for the timezone type value, we should also convert the default value to the TiCDC specified timezone.

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #10931 

### What is changed and how it works?

* Ensure to correctly set the default value for the timestamp. It's in UTC and needs to be changed to the timezone set by TiCDC.

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

**Review by hongyunyan — APPROVED** [review]
LGTM

**Comment by CharlesCheung96** [comment]
Is there any change in compatibility?

**Pull request merged**
