### PR TITLE
makefile: remove unused library

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: ref #3583

### What is changed and how it works?

- `github.com/rakyll/statik` was introduced in dm portal, since #4247 has removed all portal related code, we can clean up `github.com/rakyll/statik` libs.
- Add a `tools.go` file to make it easy to update library version in tools module.

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by amyangfei** [comment]
PTAL, thanks. @Ehco1996

**Review by Ehco1996 — APPROVED** [review]
LGTM

**Pull request merged**
