### PR TITLE
processor(cdc): extract getTableName method

### LINKED ISSUE #5259: cdc simplify the get table name logic.
as title.

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #5259 

### What is changed and how it works?

* extract `processor.getTableName` method
* `processor.tick` return `nextState`, which is not used, so remove it.

### Check List 

Tests 
 - No code

Code changes

Side effects

Related changes

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by liuzix** [comment]
Content LGTM, but maybe we can split the PR into two or three parts? I think two parts are enough, one for processor-related changes, another for the scheduler.

**Comment by 3AceShowHand** [comment]
> Content LGTM, but maybe we can split the PR into two or three parts? I think two parts are enough, one for processor-related changes, another for the scheduler.

Thanks for your review, I will revert changes in the `scheduler` part, and do it in other scheduler related PR.

**Review by asddongmen — APPROVED** [review]

**Review by overvenus — APPROVED** [review]

**Pull request merged**
