### PR TITLE
redo(cdc): merge 0822 redo hotfix

### LINKED ISSUE #6663: cdc hotfix 0822
as title

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #6663 

### What is changed and how it works?

This is a manaul cherry-pick of the #6518 

#### Tests 

 - No code

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by zhaoxinyu — APPROVED** [review]

**Review by hicqu — APPROVED** [review]

**Comment by asddongmen** [comment]
it seems a make error, please fix it.

**Pull request merged**
