### PR TITLE
kafka(ticdc): Revert "kafka(ticdc): claim check support large message raw value for…

### LINKED ISSUE #11493: release-8.3 revert claim check raw value format
This is planned to be released since v8.4.0, so the related code should not be on the release-8.3 branch.

### PR DESCRIPTION
**Pull request by 3AceShowHand**
…mat (#11395)"

This reverts commit 4b825c598520cd60107c368ce0a6b5a42cd61958.

### What problem does this PR solve?

Issue Number: close #11493 

### What is changed and how it works?

* revert the commit 4b825c598

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by CharlesCheung96 — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Review by sdojjy — APPROVED** [review]

**Review by yudongusa — APPROVED** [review]
LGTM: only revert  and impact for this new feature in current version

**Pull request merged**
