### PR TITLE
integration(ticdc): temporary ignore `Error 1105` for default_value integration test

### LINKED ISSUE #4600: integration-kafka-tests/default_value fails
### Which jobs are flaking?

integration-kafka-tests

### Which test(s) are flaking?

default_value

### Jenkins logs or GitHub Actions link

```log
[2022-02-16T04:19:42.183Z] [2022/02/16 12:19:42.075 +08:00] [FATAL] [main.go:190] ["unexpected error when executing sql"] [error="Error 1105: invalid data type: Unsupported datum flag 9 for Bit vector"] [stack="main.dml\n\t/home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/tests/integration_tests/default_value/main.go:190\nmain.testGetDefaultValue.func2\n\t/home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/tests/integration_tests/default_value/main.go:94"]
```

https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_kafka_integration_test/detail/cdc_ghpr_kafka_integration_test/8851/pipeline/#step-1048-log-1018

### Anything else we need to know

_No response_

### PR DESCRIPTION
**Pull request by maxshuang**
close  #4600

### What problem does this PR solve?

Issue Number: close #4600 

### What is changed and how it works?
temporary ignore `Error 1105` for default_value integration test

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]

**Comment by hi-rustin** [comment]
> /run-integration-test /run-kafka-integration-test

@maxshuang @overvenus I can confirm that nothing has changed in our sync diff, and I think the failed case may have received the effects of the upstream changes. I'll probably try locally tonight to see what's going on.

**Pull request merged**
