### PR TITLE
syntax(DM): fix syntax error

### LINKED ISSUE #8127: DM: `bounded` should be replaced by `bound` in comments
### What did you do?

`bounded` should be replaced by `bound` in comments

### What did you expect to see?

_No response_

### What did you see instead?

_No response_

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
master
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve?

Issue Number: close #8127 

### What is changed and how it works?
replace `bounded` with `bound` in comments and unit tests

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]
😄

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
