### PR TITLE
syncer(dm): remove placement rule table option for tracker

### LINKED ISSUE #7493: track table structure from downstream failed to handle missing placement rule
### What did you do?

https://asktug.com/t/topic/994856

if the table structure is not contained in checkpoints, DM will fetch it from downstream, but placement rule information is missing

### What did you expect to see?

no error

### What did you see instead?

_No response_

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
at least v6.1.1, v6.1.2
```

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close #7493

### What is changed and how it works?

as title

#### Tests 

 - Unit test

### Release note 

```release-note
Fix sometime DM task is stopped with error "Unknown placement policy"
```

### CODE REVIEW

**Comment by lance6716** [comment]
this is the fix PR for release-6.1 like https://github.com/pingcap/tiflow/pull/7495 , PTAL

@okJiang @GMHDBJD

**Review by okJiang — APPROVED** [review]
lgtm

**Review by lichunzhu — APPROVED** [review]
LGTM

**Pull request merged**
