### PR TITLE
dmctl: fix error and add test for `binlog-schema delete` 

### LINKED ISSUE #7373: binlog-schema delete is always failed
### What did you do?

from https://asktug.com/t/topic/963049, and test locally

```
» binlog-schema delete test start_task t -s mysql-replica-01
{
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": false,
            "msg": "[code=44009:class=schema-tracker:scope=internal:level=medium], Message:  is not a valid `CREATE TABLE` statement, RawCause: [parser:1149]You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use",
            "source": "mysql-replica-01",
            "worker": ""
        }
    ]
}
```

### What did you expect to see?

I didn't see any positive test case about `binlog-schema delete`, we should add it.

### What did you see instead?

_No response_

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
(paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
nightly
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

DM is paused

```console
» query-status test
{
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": true,
            "msg": "",
            "sourceStatus": {
                "source": "mysql-replica-01",
                "worker": "worker2",
                "result": null,
                "relayStatus": null
            },
            "subTaskStatus": [
                {
                    "name": "test",
                    "stage": "Paused",
                    "unit": "Sync",
                    "result": {
                        "isCanceled": false,
                        "errors": [
                            {
                                "ErrCode": 20057,
                                "ErrClass": "config",
                                "ErrScope": "internal",
                                "ErrLevel": "high",
                                "Message": "start-time 2037-12-12 01:02:03 is too late, no binlog location matches it",
                                "RawCause": "",
                                "Workaround": "Please check the `--start-time` is expected or try again later."
                            }
                        ],
                        "detail": null
                    },
                    "unresolvedDDLLockID": "",
                    "sync": {
                        "totalEvents": "0",
                        "totalTps": "0",
                        "recentTps": "0",
                        "masterBinlog": "(mysql-bin.000001, 1410)",
                        "masterBinlogGtid": "0add8fb9-0201-11ed-9e0a-de5ffb51d67e:1-6",
                        "syncerBinlog": "(mysql-bin.000001, 1410)",
                        "syncerBinlogGtid": "0add8fb9-0201-11ed-9e0a-de5ffb51d67e:1-6",
                        "blockingDDLs": [
                        ],
                        "unresolvedGroups": [
                        ],
                        "synced": true,
                        "binlogType": "remote",
                        "secondsBehindMaster": "0",
                        "blockDDLOwner": "",
                        "conflictMsg": ""
                    },
                    "validation": null
                }
            ]
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by liumengya94**
### What problem does this PR solve?

Issue Number: close #7373

### What is changed and how it works?
Use `SchemaOp_RemoveSchema` in `newSourceTableSchemaDeleteCmd`.

#### Tests 

 - Integration test

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
cc @GMHDBJD

**Review by D3Hunter — APPROVED** [review]

**Pull request merged**
