### PR TITLE
version(ticdc): bump max compatiable TiDB/TiKV/PD

### LINKED ISSUE #4214: Bump v5.4.0 TiCDC max compatible TiDB/TiKV/PD
As title.

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: close #4214

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by amyangfei — COMMENTED** [review]
`release-5.3` branch also misses similar change

**Review by amyangfei — APPROVED** [review]

**Review by hi-rustin — APPROVED** [review]

**Pull request merged**
