### PR TITLE
sink(cdc): improve metrics about conflict detector and sink queue

### PR DESCRIPTION
**Pull request by hicqu**
### What problem does this PR solve?

Issue Number: ref #8255 

### What is changed and how it works?

Improve metrics about conflict detector and sink queue.

#### Tests 

 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]

**Comment by amyangfei** [comment]
This PR also closes #8281. /cc @asddongmen

**Pull request merged**
