### PR TITLE
integration(cdc): add tidb schrddl integration test

### LINKED ISSUE #6130: Migrate schrddl to cdc integration test for checking DDL logic
### Is your feature request related to a problem?

For normal DDL test and concurrent DDL tests

### Describe the feature you'd like

Migrate schrddl to cdc integration test for checking DDL logic

### Describe alternatives you've considered

_No response_

### Teachability, Documentation, Adoption, Migration Strategy

_No response_

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve?

Issue Number: close #6130 

### What is changed and how it works?
migrate schrddl to cdc integration test for normal and concurrent DDL test

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
@maxshuang Do we need to move forward with it?

**Comment by maxshuang** [comment]
Sure.The related issue has been resolved.

**Comment by hi-rustin** [comment]
@maxshuang The CI failed.

**Comment by CharlesCheung96** [comment]
@maxshuang The CI failed.

**Pull request closed without merging**
