### PR TITLE
syncer: also skip after reset upstream connection when position-based

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/3711

### What is changed and how it works?

see https://github.com/pingcap/tiflow/issues/3711#issuecomment-1002422437

When upstream error is caused by primary-secondary switch, this PR doesn't make it worse because task auto-resume will also try to replicate from checkpoint

### Check List 

Tests 

 - Integration test

Code changes

Side effects

Related changes

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by glorv — APPROVED** [review]

**Review by Ehco1996 — APPROVED** [review]
LGTM

**Comment by glorv** [comment]
/hold
@GMHDBJD  PTAL

**Review by GMHDBJD — APPROVED** [review]
LGTM
manually trigger below test
https://github.com/pingcap/tiflow/actions/runs/1639568781
https://github.com/pingcap/tiflow/actions/runs/1639568910
https://github.com/pingcap/tiflow/actions/runs/1639568364
https://github.com/pingcap/tiflow/actions/runs/1639567875

**Pull request merged**
