### PR TITLE
codec(ticdc): use handlekey instead of primary key for avro

### LINKED ISSUE #5597: avro codec should use unique key as message key when there is no primary key
### What did you do?

N/A

### What did you expect to see?

as title

### What did you see instead?

currently avro would only use primary key as message key

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by zhangyangyu**
### What problem does this PR solve?

Issue Number: close #5597 

### What is changed and how it works?

Avro shall use Handle Key as message key in case when there is no primary key, we could still try to use a not null unique key , makes downstream easy to use these events.

When there is no handle key, such as force replica situations, Avro message keys would be null. Downstream consumers need to accomodate for this. (This is already the current behavriour)

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Comment by lance6716** [comment]
> we could still try to use a not null unique key

I remember handle key is not a "not null unique key", please check it @3AceShowHand

**Comment by zhangyangyu** [comment]
> > avro codec should use unique key as message key when there is no primary key
> 
> > we could still try to use a not null unique key
> 
> I remember handle key is not a "not null unique key", please check it @3AceShowHand

how do you think @leoppro

**Review by zhaoxinyu — APPROVED** [review]

**Comment by liuzix** [comment]
There should be an end-to-end test for this issue. Holding for now.

**Comment by lance6716** [comment]
> > > avro codec should use unique key as message key when there is no primary key
> > 
> > 
> > > we could still try to use a not null unique key
> > 
> > 
> > I remember handle key is not a "not null unique key", please check it @3AceShowHand
> 
> how do you think @leoppro

I have checked the code, the HandleKey flag is fine.

**Review by maxshuang — APPROVED** [review]

**Pull request merged**
