### PR TITLE
dm: fix typo

### PR DESCRIPTION
**Pull request by buchuitoudegou**
### What problem does this PR solve?

Issue Number: ref #5143 

### What is changed and how it works?
fix some typo

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
seems CHANGELOG.md is removed in TiDB repo. we can also delete it now.

**Comment by buchuitoudegou** [comment]
> seems CHANGELOG.md is removed in TiDB repo. we can also delete it now.

Will remove it.

**Pull request merged**
