### PR TITLE
fakejob(engine): refactor fake job based on master/worker framework

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: ref #7225

### What is changed and how it works?

Refactor fake job based on master/worker framework

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by amyangfei** [comment]
chaos test passed: https://github.com/pingcap/tiflow/actions/runs/3619330555/jobs/6100245336

**Review by maxshuang — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Pull request merged**
