### PR TITLE
Updated tidb dependency

### PR DESCRIPTION
**Pull request by mjonss**
### What problem does this PR solve?

Issue Number: ref #9641

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
Hi @mjonss I noticed some changed must be made at DM side. Would you accept that I directly commit into your branch?

**Comment by lance6716** [comment]
For the error in dm integration tests "[Lightning:Config:ErrInvalidConfig]tikv-importer.on-duplicate cannot be used with tikv-importer.parallel-import", I think it can be resolved by "only setting IncrementalImport = true when `cfg.TikvImporter.Backend == lcfg.BackendLocal`"

https://github.com/pingcap/tiflow/blob/6dd155946afdaf3de7d18687f37c739d829953c0/dm/loader/lightning.go#L367

**Comment by lance6716** [comment]
seems now the DM integration tests are failing on flaky tests

**Comment by mjonss** [comment]
@lance6716 Hi, who would you suggest to review this? I have updated the last failing test now.

**Review by lance6716 — APPROVED** [review]
lgtm for DM and engine part

**Review by nongfushanquan — APPROVED** [review]

**Pull request merged**
