### PR TITLE
Makefile,scripts: speed up make fmt and fix check-diff-line-width

### LINKED ISSUE #7809: Speed up make fmt and fix check-diff-line-width
As title.

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: close #7809

### What is changed and how it works?

Speed up make fmt and fix check-diff-line-width

#### Tests 

 - Unit test

##### Will it cause performance regression or break compatibility?

No

##### Do you need to update user documentation, design documentation or monitoring documentation?

No

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Comment by overvenus** [comment]
/run-integration-test tidb=f5487e3f2596cdd63ae9840606c7fff3fb539e03

**Pull request merged**
