### PR TITLE
feature branch: merge release-multi-source with newest master branch

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/4687

### What is changed and how it works?
Update feature branch release-multi-source and resolve some conflicts.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

- None

Side effects

- None

Related changes

- None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by lichunzhu** [comment]
@lance6716 @WizardXiao PTAL
just merge master into release branch

**Review by lance6716 — APPROVED** [review]
I think you can directly push to the branch and check CI. We can't review a PR at such scale.

**Comment by lichunzhu** [comment]
> I think you can directly push to the branch and check CI. We can't review a PR at such scale.

You're right. I'll do this in next PR.

**Review by WizardXiao — APPROVED** [review]

**Pull request closed without merging**
