### PR TITLE
ddl(ticdc): Add error handling for mismatched `Job.Query` and `Job.BinlogInfo.MultipleTableInfos` in TiCDC

### LINKED ISSUE #11507: ticdc: version 8.3.0 of TiCDC is not compatible with version 8.1.0 of TiKV
### What did you do?

**Description**:  
While performing integration testing with TiCDC's master branch (version 8.3.0), I encountered an issue where the `batch_add_table` test fails. The TiCDC node crashes because the puller module panics during DDL execution.

**Steps to Reproduce**:
1. Run `make prepare_test_binaries community=true` to download TiDB, TiKV, PD, and other components. This pulls version 8.1.0 of the components (I'll explain why below).
2. Execute `make integration_test_build`.
3. Execute `make integration_test` to start the integration test.

**Observed Behavior**:  
During the `batch_add_table` integration test, TiCDC's puller module panics when processing DDL, causing the TiCDC node to crash.

**Cause Analysis**:  
The reason TiCDC 8.3.0 pulled version 8.1.0 of TiDB, TiKV, PD, etc., is that when running `make prepare_test_binaries` with the `community=true` option, if the version is not manually specified, it defaults to downloading version 8.1.0 of all TiDB components. (related to #11508)

After manually replacing the TiDB, TiKV, PD components with the latest versions, the `batch_add_table` integration test passed successfully. This indicates that TiCDC 8.3.0 currently does not maintain backward compatibility with TiKV 8.1.0.

### What did you expect to see?

I expected the batch_add_table integration test to pass without any issues when using TiCDC 8.3.0 with TiDB, TiKV, and PD components (even if they are from version 8.1.0). The system should handle version differences gracefully, or at the very least, the prepare_test_binaries step should automatically pull compatible versions of all components.

### What did you see instead?

img_v3_02e0_1c59243e-9039-4edf-bbf7-7592e91e009g

```
panic: runtime error: index out of range [1] with length 1

goroutine 809 [running]:
[github.com/pingcap/tiflow/cdc/puller.(*ddlJobPullerImpl).handleJob](http://github.com/pingcap/tiflow/cdc/puller.(*ddlJobPullerImpl).handleJob)(0xc0040b7980, 0xc001756820)
        /root/tiflow/cdc/puller/ddl_puller.go:410 +0x4c92
[github.com/pingcap/tiflow/cdc/puller.(*ddlJobPullerImpl).handleRawKVEntry](http://github.com/pingcap/tiflow/cdc/puller.(*ddlJobPullerImpl).handleRawKVEntry)(0xc0040b7980, {0xbde3480, 0xc0031b5db0}, 0xc00123b1f0)
        /root/tiflow/cdc/puller/ddl_puller.go:206 +0x35c
[github.com/pingcap/tiflow/cdc/puller.(*ddlJobPullerImpl).Run.func3()](http://github.com/pingcap/tiflow/cdc/puller.(*ddlJobPullerImpl).Run.func3())
        /root/tiflow/cdc/puller/ddl_puller.go:153 +0x218
[golang.org/x/sync/errgroup.(*Group).Go.func1()](http://golang.org/x/sync/errgroup.(*Group).Go.func1())
        /root/go/pkg/mod/[golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78](http://golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78) +0x92
created by [golang.org/x/sync/errgroup.(*Group).Go](http://golang.org/x/sync/errgroup.(*Group).Go) in goroutine 805
        /root/go/pkg/mod/[golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75](http://golang.org/x/sync@v0.7.0/errgroup/errgroup.go:75) +0x125
~
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
8.1.0
```

Upstream TiKV version (execute `tikv-server --version`):

```console
8.1.0
```

TiCDC version (execute `cdc version`):

```console
8.3.0
```

### PR DESCRIPTION
**Pull request by wlwilliamx**
### What problem does this PR solve?

Issue Number: close #11507

### What is changed and how it works?

**Description:**

This PR addresses an issue in TiCDC where a mismatch between the number of queries in `Job.Query` and the number of `TableInfo` entries in `Job.BinlogInfo.MultipleTableInfos` leads to an `index out of range` panic. This issue originates from TiDB's fast create table functionality, which previously merged multiple DDL jobs into a single batch but failed to correctly merge their corresponding queries. As a result, the length of `Job.Query` did not match the number of tables in `Job.BinlogInfo.MultipleTableInfos`, causing TiCDC to panic during DDL job processing.

This issue has been fixed in TiDB (see issue [tidb#53076](https://github.com/pingcap/tidb/issues/53076) and PR [tidb#53515](https://github.com/pingcap/tidb/pull/53515)). However, since TiCDC relies on external systems to provide consistent metadata, it is essential to add error handling to ensure these fields match before processing DDL jobs.

**Changes:**
1. Added error handling in TiCDC's puller to validate that the number of queries in `Job.Query` matches the number of `TableInfo` entries in `Job.BinlogInfo.MultipleTableInfos`.
2. If a mismatch is detected, TiCDC will log an error and panic to prevent further processing with inconsistent metadata. This allows easier identification of the root cause and ensures stability during job handling.

```go
if strings.Count(job.Query, ";") != len(job.BinlogInfo.MultipleTableInfos) {
    log.Panic("the number of queries in `Job.Query` is not equal to "+
        "the number of `TableInfo` in `Job.BinlogInfo.MultipleTableInfos`, ",
        zap.String("Job.Query", job.Query),
        zap.Any("Job.BinlogInfo.MultipleTableInfos", job.BinlogInfo.MultipleTableInfos),
        zap.Error(cerror.ErrTiDBUnexpectedJobMeta.GenWithStackByArgs()))
}
```

**Context:**
This bug surfaced due to TiDB's optimization in fast create table, which performs DDL batching by merging multiple jobs. The issue arose because TiDB did not correctly merge the associated queries for each job in this scenario. Since TiCDC directly consumes the metadata from TiDB, any inconsistency in the data structure leads to downstream errors.

By adding this validation, we ensure that TiCDC processes jobs only when the metadata is consistent and structured as expected. This is critical because TiCDC depends on external systems like TiDB to provide correct metadata for reliable replication. Adding error handling ensures that we detect anomalies earlier and prevent unexpected behavior that could potentially affect data replication.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

```shell
make prepare_test_binaries community=true ver=v8.1.0
make integration_test_build
make integration_test CASE=batch_add_table
```

##### Will it cause performance regression or break compatibility?

No.

##### Do you need to update user documentation, design documentation or monitoring documentation?

No.

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by hongyunyan — APPROVED** [review]
LGTM

**Review by CharlesCheung96 — APPROVED** [review]

**Comment by wlwilliamx** [comment]
TiDB accelerates create tables: [PR](https://github.com/pingcap/tidb/pull/49687)

**Comment by wlwilliamx** [comment]
related implementation: #11262

**Pull request merged**
