### PR TITLE
tests(ticdc): fix canal_json_basic charset issue

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/4555

### What is changed and how it works?
sync diff will concat_ws all fields when calculating checksum. This causes some string conversions. Then an error occurs during the conversion.

```log
[2022/02/11 08:00:17.680 +00:00] [WARN] [utils.go:741] ["execute checksum query fail"] [query="SELECT COUNT(*) as CNT, BIT_XOR(CAST(CRC32(CONCAT_WS(',', `id`, `t_tinyint`, `t_tinyint_unsigned`, `t_smallint`, `t_smallint_unsigned`, `t_mediumint`, `t_mediumint_unsigned`, `t_int`, `t_int_unsigned`, `t_bigint`, `t_bigint_unsigned`, `t_boolean`, round(`t_float`, 5-floor(log10(abs(`t_float`)))), round(`t_double`, 14-floor(log10(abs(`t_double`)))), `t_decimal`, `t_char`, `t_varchar`, `c_binary`, `c_varbinary`, `t_tinytext`, `t_text`, `t_mediumtext`, `t_longtext`, `t_tinyblob`, `t_blob`, `t_mediumblob`, `t_longblob`, `t_date`, `t_datetime`, `t_timestamp`, `t_time`, `t_enum`, `t_set`, `t_json`, CONCAT(ISNULL(`id`), ISNULL(`t_tinyint`), ISNULL(`t_tinyint_unsigned`), ISNULL(`t_smallint`), ISNULL(`t_smallint_unsigned`), ISNULL(`t_mediumint`), ISNULL(`t_mediumint_unsigned`), ISNULL(`t_int`), ISNULL(`t_int_unsigned`), ISNULL(`t_bigint`), ISNULL(`t_bigint_unsigned`), ISNULL(`t_boolean`), ISNULL(round(`t_float`, 5-floor(log10(abs(`t_float`))))), ISNULL(round(`t_double`, 14-floor(log10(abs(`t_double`))))), ISNULL(`t_decimal`), ISNULL(`t_char`), ISNULL(`t_varchar`), ISNULL(`c_binary`), ISNULL(`c_varbinary`), ISNULL(`t_tinytext`), ISNULL(`t_text`), ISNULL(`t_mediumtext`), ISNULL(`t_longtext`), ISNULL(`t_tinyblob`), ISNULL(`t_blob`), ISNULL(`t_mediumblob`), ISNULL(`t_longblob`), ISNULL(`t_date`), ISNULL(`t_datetime`), ISNULL(`t_timestamp`), ISNULL(`t_time`), ISNULL(`t_enum`), ISNULL(`t_set`), ISNULL(`t_json`))))AS UNSIGNED)) as CHECKSUM FROM `test`.`multi_data_type` WHERE ((TRUE) AND (TRUE));"] [args=null] [error="Error 3854: Cannot convert string '\\x89PNG\r\n...' from binary to utf8mb4"]

```

This value is not a valid utf8 value.
image

 So I modified it for now. The exact reason why it worked before the default charset change is still under investigation.

### Check List 

Tests 

 - Integration test

Code changes

None

Side effects

None

Related changes

None

### Release note 

```release-note

None
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Comment by amyangfei** [comment]
> sync diff will concat_ws all fields when calculating checksum. This causes some string conversions. Then an error occurs during the conversion.

Is this a bug of `sync-diff`?

**Comment by hi-rustin** [comment]
> > sync diff will concat_ws all fields when calculating checksum. This causes some string conversions. Then an error occurs during the conversion.
> 
> Is this a bug of `sync-diff`?

I think this is a bug in tidb, because the sql is executed in tidb.

**Comment by amyangfei** [comment]
> > > sync diff will concat_ws all fields when calculating checksum. This causes some string conversions. Then an error occurs during the conversion.
> > 
> > 
> > Is this a bug of `sync-diff`?
> 
> I think this is a bug in tidb, because the sql is executed in tidb.

Do we have a linked issue in TiDB

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
