### PR TITLE
codec(ticdc): simple decoder set column flag incorrectly since miss index id 

### LINKED ISSUE #11236: simple protocol decoder set index column incorrectly
### What did you do?

```
`CREATE TABLE test.sbtest3 (
	  id int(11) NOT NULL,
	  k int(11) NOT NULL DEFAULT '0',
	  PRIMARY KEY (id),
	  KEY k_3 (k)
	)`
```

### What did you expect to see?

the column `k` is not handle key column

### What did you see instead?

the column `k` is set as handle key column, since the key `k_3` id is 0, identical to the handle key column id

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #11236 

### What is changed and how it works?
* set index id to distinguish each index

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

**Review by lidezhu — APPROVED** [review]

**Comment by 3AceShowHand** [comment]
This is cherry-pick back to release-7.5 by the #11228

**Pull request merged**
