### PR TITLE
scheduler(ticdc): split more evenly

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: ref #7720 

### What is changed and how it works?

* ~Enable split span by default.~
* Split span evenly.

#### Tests 

 - Unit test
 - Integration test

##### Will it cause performance regression or break compatibility?

No.

##### Do you need to update user documentation, design documentation or monitoring documentation?

No.

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by nongfushanquan — COMMENTED** [review]
I recommend not enabling split span by default .the user can enable this feature in the  changefeed configure  if necessary

**Comment by 3AceShowHand** [comment]
> I recommend not enabling split span by default .the user can enable this feature in the changefeed configure if necessary

I agreed. In the most use case, there are multiple tables in the changefeed so that split span is not necessary.

We can update the documents to tell users this feature, and let them to decide whether to enable it or not.

**Review by 3AceShowHand — APPROVED** [review]

**Comment by overvenus** [comment]
> I recommend not enabling split span by default .the user can enable this feature in the changefeed configure if necessary

How about setting a larger default value? E.g., 100K regions. It's will disable the feature for most cases (smaller than 100k regions).

**Review by asddongmen — APPROVED** [review]

**Pull request merged**
