### PR TITLE
test(dm): try fix upstream switch CI

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref #4159

### Check List 

Tests 

 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
https://github.com/pingcap/tiflow/actions/runs/2279221315

**Review by lichunzhu — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
https://github.com/pingcap/tiflow/actions/runs/2279361716

**Pull request merged**
