### PR TITLE
Fix file sink file format bug about version par

### PR DESCRIPTION
**Pull request by yuqi1129**
### What problem does this PR solve? 

see https://github.com/pingcap/ticdc/issues/1514

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### CODE REVIEW

**Comment by yuqi1129** [comment]
@3pointer, Hi could you take time to review this PR, no comments on this PR for a long time, if this is outdated i will close this issue, thanks

**Comment by ben1009** [comment]
is this pr still active?

**Comment by yuqi1129** [comment]
> is this pr still active?

Yes, this is a similar PR with https://github.com/pingcap/ticdc/pull/1423

**Comment by hi-rustin** [comment]
/run-all-tests

/cc

I will take a look.

**Comment by tisonkun** [comment]
@3pointer @hi-rustin any update on this PR?

**Comment by hi-rustin** [comment]
Thank you very much for your contribution. Due to a product feature change, the experimental feature cdclog has been removed. If you have any questions, please feel free to @ me. 💚 💙 💜 💛 ❤️

**Pull request closed without merging**
