### PR TITLE
test(dm): fix upstream switch CI and reduce versions in upgrading CI

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref #4159

### What is changed and how it works?

- during the upstream switch CI down because docker image change for 23 days, we somehow break this CI. 
- reduce versions in upgrading test

#### Tests 

 - Integration test
    https://github.com/pingcap/tiflow/runs/7554381577?check_suite_focus=true

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
ping @buchuitoudegou @GMHDBJD

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Review by buchuitoudegou — APPROVED** [review]

**Pull request merged**
