### PR TITLE
kv (ticdc): Improve the codebase of kvClient.

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve?

Issue Number: ref #10584 

### What is changed and how it works?
- Move stream related filed into `eventFeedStream` struct to make the code more clear. 
- Reduce a lock usage by make sure the `storeStreamsCache` can only be accessed in one goroutine. 

#### Tests 

 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by asddongmen** [comment]
It is no need to merge this PR into master branch.

**Review by sdojjy — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Pull request merged**
