### PR TITLE
loader(dm): remove loader and ColumnMapping and dump TLS certs

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref #3510

### What is changed and how it works?

loader is replaced by embedded lightning, column mapping is replaced by extract-table/database/source, and lightning can use cert bytes so no need to dump the content.

#### Tests 

 - pass old tests

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
waiting https://github.com/pingcap/tidb-tools/issues/690

**Review by lichunzhu — APPROVED** [review]
LGTM

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
