### PR TITLE
config(dm): fix can't downgrade

### LINKED ISSUE #4974: faild to downgrade to previous version
### What did you do?

ci faild
https://github.com/pingcap/tiflow/runs/5635985219?check_suite_focus=true

### What did you expect to see?

ci pass

### What did you see instead?

start creating sources
{
    "result": false,
    "msg": "[code=20003:class=config:scope=internal:level=medium], Message: decode source config, RawCause: yaml: unmarshal errors:\n  
line 1: field enable not found in type config.SourceConfig, Workaround: Please check the configuration file has correct YAML format.",
    "sources": [
    ]

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
(paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve?

Issue Number: close #4974

### What is changed and how it works?

add `omitDefaultVals` for sourceCfg

### Check List 

Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)
 -  trigger ci in https://github.com/pingcap/tiflow/runs/5640253027?check_suite_focus=true

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by GMHDBJD** [comment]
You should add omitempty for json here. https://github.com/pingcap/tiflow/blob/0d44968787e8403e1051e250233a409f84bb5aca/dm/dm/config/source_config.go#L406

**Comment by lance6716** [comment]
please fix bot check-issue-triage-complete

 Found may-affects label on bug issue pingcap/tiflow#4974.

**Comment by Ehco1996** [comment]
ci passed in https://github.com/pingcap/tiflow/runs/5640253027?check_suite_focus=true
PTAL @GMHDBJD

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
