### PR TITLE
go.mod: replace seahash with a valid github repo

### LINKED ISSUE #10673: Dependency `blainsmith.com/go/seahash` is invalid
The dependency `blainsmith.com/go/seahash` is invalid if you set `GOPROXY='direct'`. The vanity import path is not configured in proper way:

```
❯ curl https://blainsmith.com/go/seahash/
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="go-import" content="https:&#x2F;&#x2F;blainsmith.com&#x2F;go&#x2F;seahash&#x2F; git https:&#x2F;&#x2F;github.com&#x2F;blainsmith&#x2F;seahash">
        <meta name="go-source" content="https:&#x2F;&#x2F;blainsmith.com&#x2F;go&#x2F;seahash&#x2F; https:&#x2F;&#x2F;github.com&#x2F;blainsmith&#x2F;seahash https:&#x2F;&#x2F;github.com&#x2F;blainsmith&#x2F;seahash/tree/master{/dir} https:&#x2F;&#x2F;github.com&#x2F;blainsmith&#x2F;seahash/blob/master{/dir}/{file}#L{line}">
        <meta http-equiv="refresh" content="0; url=https://pkg.go.dev/blainsmith.com&#x2F;go&#x2F;seahash">
    </head>
    <body>
        <img src="https://blainsmith.goatcounter.com/count?p=https:&#x2F;&#x2F;blainsmith.com&#x2F;go&#x2F;seahash&#x2F;" />
    </body>
</html>
```

The `content` of `go-import` meta tag should start with `blainsmith.com/go/seahash` but not `https://blainsmith.com/go/seahash`, which will cause `go: blainsmith.com/go/seahash@v1.2.1: unrecognized import path "blainsmith.com/go/seahash": parse https://blainsmith.com/go/seahash?go-get=1: no go-import meta tags (meta tag https://blainsmith.com/go/seahash/ did not match import path blainsmith.com/go/seahash)` error.

What's more, the github path referenced by this import tag has been deleted: `https://github.com/blainsmith/seahash` is 404 now.

We should try to remove this dependency ASAP.

### PR DESCRIPTION
**Pull request by YangKeao**
### What problem does this PR solve?

Issue Number: close #10673

### What is changed and how it works?

Use a cloned repo to replace the official seahash, because the original seahash repo has been removed.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - [x] No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]

**Comment by lance6716** [comment]
@YangKeao please sign CLA

**Comment by YangKeao** [comment]
> @YangKeao please sign CLA

Done

**Pull request merged**
