### PR TITLE
retry(dm): align with tidb latest error message

### LINKED ISSUE #4159: refine tests
### Is your feature request related to a problem?

to walkaround link-issue-checker in PR

### Describe the feature you'd like

refine tests

### Describe alternatives you've considered

_No response_

### Teachability, Documentation, Adoption, Migration Strategy

_No response_

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #4159 , close https://github.com/pingcap/tiflow/issues/4246

### What is changed and how it works?

since tidb has changed the error message, we should also update the matching pattern

### Check List 

Tests 

 - Integration test

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
/hold

need turn on CASE=drop_column_with_index

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Review by okJiang — APPROVED** [review]

**Pull request merged**
