### PR TITLE
sink/mq/producer(ticdc): fix test typo

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/5039

### What is changed and how it works?
fix test typo.
It should be sasl-user instead of sasl-username.

### Check List 

Tests 

 - Unit test

Code changes

None

Side effects

None

Related changes

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Comment by hi-rustin** [comment]
/hold

I think we can do better.

**Pull request merged**
