### PR TITLE
test(dm): add async checkpoint flush integration test

### PR DESCRIPTION
**Pull request by db-will**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/4159

### What is changed and how it works?
Add integration test for async checkpoint flush to simulate failure of async flush

### Check List 

Tests 

 - Integration test

Code changes
None

Side effects
None

Related changes

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by GMHDBJD** [comment]
Do you have time to look at this issue #3928? I think it may be introduced by async checkpoint

**Review by lance6716 — COMMENTED** [review]
The newly added integration tests should put its name in `dm/tests/others_integration_1.txt` or others_integration_2.txt

BTW, what's the detailed scenario this test want to imitate? Failed to async flush checkpoint will not block data replication?

**Comment by lance6716** [comment]
ping @db-will

**Comment by db-will** [comment]
> 

yes, cause we don't want to background async flush failure could impact on DM process.

**Review by lance6716 — APPROVED** [review]

**Review by Ehco1996 — COMMENTED** [review]
LGTM

**Review by Ehco1996 — APPROVED** [review]

**Pull request merged**
