### PR TITLE
test(engine): remove promutil/test/go.mod to avoid gosetup error

### LINKED ISSUE #5700: test(engine):Remove promutil/test/go.mod to remove error of gosetup
### What did you do?

run gosetup for tiflow

### What did you expect to see?

successful

### What did you see instead?

middle_img_v2_4492783c-f5f5-401d-9c24-bfd0c401382g

### Versions of the cluster

Dataflow Engine version (run `df-master -V` or `df-executor -V`):

```console
master@269ba32404a5846f8dbba1a6f6bd3c6ffba6be2e
```

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve?

Issue Number: close #5700 

### What is changed and how it works?
1. remove go.mod/sum in promutil/test
2. fix build error for promutil/test

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Comment by amyangfei** [comment]
`make check` failed.

**Comment by amyangfei** [comment]
Please fix `make check` @maxshuang

**Comment by gozssky** [comment]
Please update title to "test(engine): xxxx". See https://github.com/pingcap/tiflow/blob/master/CONTRIBUTING.md#format-of-the-commit-message.

**Comment by maxshuang** [comment]
> Please fix `make check` @maxshuang

Done.

**Pull request merged**
