### PR TITLE
util: mask sasl-password in sink-uri

### LINKED ISSUE #7182: Masking of `sink-uri` doesn't mask `sasl-password` for Kafka URIs
### What did you do?

Use a `sink-uri` like `kafka://...?sasl-mechanism=SCRAM-SHA-256&sasl-password=xxxxx&sasl-user=ticdc`

tiup cdc cli changefeed query --pd=http://127.0.0.1:2379 --changefeed-id=test-changefeed 

### What did you expect to see?

The `sasl-password` to be masked, just like the MySQL password in `mysql://` uris

### What did you see instead?

Unmasked `sasl-password`

### Versions of the cluster

v6.1.1

### PR DESCRIPTION
**Pull request by dveeden**
### What problem does this PR solve?

Issue Number: close #7182

#### Tests 

 - Unit test

##### Will it cause performance regression or break compatibility?

No

##### Do you need to update user documentation, design documentation or monitoring documentation?

No

### Release note 

```release-note
The `sasl-password` in the `sink-uri` is masked in the `changefeed query` output
```

### CODE REVIEW

**Comment by asddongmen** [comment]
Thanks for your contribution. Please link an issue and fix the failed unit test case.

rest LGTM

**Review by asddongmen — APPROVED** [review]

**Review by hi-rustin — APPROVED** [review]
Thanks!

**Pull request merged**
