### PR TITLE
mock(engine): use pure-go sqlite to suppress build warning

### PR DESCRIPTION
**Pull request by gozssky**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/6590

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by amyangfei** [comment]
There is data race in unit test: https://ci.pingcap.net/blue/organizations/jenkins/ut-check/detail/ut-check/27513/pipeline/

**Review by lance6716 — APPROVED** [review]

**Review by maxshuang — APPROVED** [review]

**Review by maxshuang — APPROVED** [review]

**Comment by maxshuang** [comment]
LGTM

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
