### PR TITLE
test(cdc): fix date-formats test fail

### LINKED ISSUE #7825: test(cdc): tidb-mysql-test date-formats fail
### What did you do?

run tidb-mysql-test test locally

### What did you expect to see?

run well

### What did you see instead?

fail.
https://ci.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test/detail/cdc_ghpr_integration_test/6051/pipeline/

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
fd2904a7ac9ff395ff7f908a3c2a961a95551484
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
[c4b5999](https://github.com/pingcap/tiflow/commit/c4b5999b97bf3ae2f67f9c654e0857ed3fa8eccd)
```

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve?

Issue Number: close #7825 

#### Tests 
 - Integration test

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Review by nongfushanquan — APPROVED** [review]

**Comment by nongfushanquan** [comment]
/run-integration-test  tidb=f5487e3f2596cdd63ae9840606c7fff3fb539e03

**Pull request merged**
