### PR TITLE
sink/mq,sink/mysql(ticdc): remove useless opts for MQ and MySQL sink

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/5849

### What is changed and how it works?
remove useless opts for MQ sink.

This PR simply removes the dead code.
Before.
You pass opts it won't do anything, but it won't report an error.

After the change.
You pass opts again cli will report an error.

Upgrade
The original parameters won't work after the upgrade, and it won't panic.

#### Tests 

 - Unit test

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No, I didn't find any docs about this arg.
### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
I tested:
v6.1.0 -> this pr
v5.0.6 -> this pr
v4.0.14 -> this pr

```shell
./cdc cli changefeed create --sink-uri="blackhole://" --changefeed-id="test1" --opts "registry=http://schema-registry:8081"
```

**Comment by hi-rustin** [comment]
This PR simply removes the dead code.
Before.
You pass opts it won't do anything, but it won't report an error.

After the change.
You pass opts again cli will report an error.

Upgrade
The original parameters won't work after the upgrade, and it won't panic.

**Review by leoppro — APPROVED** [review]

**Review by nongfushanquan — APPROVED** [review]
LGTM

**Pull request merged**
