### PR TITLE
chaos(engine): fix business metastore name in chaos test

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: ref #6218

### What is changed and how it works?

- metastore name was changed from `metastore-user-etcd` to `metastore-business-etcd` in #6202

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by maxshuang — APPROVED** [review]

**Comment by amyangfei** [comment]
verified in: https://github.com/pingcap/tiflow/actions/runs/2653667623

**Review by CharlesCheung96 — APPROVED** [review]

**Pull request merged**
