### PR TITLE
[WIP] changefeed(ticdc): abort changefeed creation if there are running import task

### LINKED ISSUE #8385: Abort the creation of changefeed if there are running data import task
### Is your feature request related to a problem?

When running data import tasks (lightning/PiTR) against a TiDB cluster, creating changefeeds may cause the downstream to receive incorrect events, as lightning importing data through SST files while changefeed relies on the TiKV change log, and PiTR does not obey the transaction constraint. 

### Describe the feature you'd like

When creating changefeed, check if there are running data import tasks. 

### Describe alternatives you've considered

_No response_

### Teachability, Documentation, Adoption, Migration Strategy

When data importing tasks are running, the sst switch mode will be set as `SwitchMode_Import`. Therefore, when creating changefeeds, we can check if the sst switch mode is `SwitchMode_Import`. If yes, then abort the creation of the changefeed and return an error.

### PR DESCRIPTION
**Pull request by charleszheng44**
### What problem does this PR solve?
Issue Number: close #8385 

### What is changed and how it works?
When creating a new changefeed, we will check if the upstream has import tasks running, i.e. lightning/pitr, if yes, the creation of the changefeed will be aborted. 

To check if there is import tasks, we check if the sst service's `SwitchMode` is `SwitchMode_Import`.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 
```release-note
 `None`
```

### CODE REVIEW

**Comment by lance6716** [comment]
Is it still WIP? you can ping me after finish this PR @charleszheng44

**Comment by charleszheng44** [comment]
> Is it still WIP? you can ping me after finish this PR @charleszheng44

Yes, still under testing. Will ping you once it is done

**Comment by charleszheng44** [comment]
@nongfushanquan @lance6716 This feature depends on how lightning and PiTR store the indicator in TiKV PD, which will be delivered by 7.0.

**Comment by lance6716** [comment]
@BusyJay This PR seems require the TiKV side to implement SwitchMode (ImportMode), but I remember we don't plan to support it in https://github.com/tikv/tikv/pull/14305 . Not sure which of you two should be changed.

**Comment by BusyJay** [comment]
Import mode is not always used when loading data, right? How can this PR depends on a inconsistent behavior?

**Comment by joccau** [comment]
After the last meeting about discussing the compatibility for tools(PITR/lightning/cdc)，the new design is that:
- lightning will set a tag on pd(etcd) when import, and the pitr can check the tag when creating log-backup task.
- pitr will set a tag on pd(etcd) when `br restore`, and the cdc can to check the tag if want to create changefeed.
And tools can make the common interface to `set the tag`, and others can check it.

**Comment by charleszheng44** [comment]
depend on https://github.com/pingcap/tidb/pull/41956

**Comment by charleszheng44** [comment]
ref to #8544

**Pull request closed without merging**
