### PR TITLE
pkg/chann(ticdc): remove close method of DrainableChann

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: ref #8255

### What is changed and how it works?
remove close method of DrainableChann

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]
t

**Comment by hi-rustin** [comment]
/merge

Label it only requires one LGTM. Because it is a quite simple change.

**Review by zhaoxinyu — APPROVED** [review]

**Pull request merged**
