### PR TITLE
engine: rename the enginepb package name to pb

### PR DESCRIPTION
**Pull request by lonng**
Signed-off-by: Henry Lonng <henry@lonng.org>

### What problem does this PR solve?

Issue Number: ref #6356 

### What is changed and how it works?

The package `github.com/pingcap/tiflow/engine/enginepb` has a duplicated word `engine`, and it's better to keep the same package naming style with `github.com/pingcap/tiflow/dm/pb` because all imports use `pb` as its alias (see below picture).

3vqs59YDFr

This PR refactors the package name of `github.com/pingcap/tiflow/engine/enginepb` and eliminate the duplicated word `engine`.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Comment by lonng** [comment]
I will address the conflicts after two reviewers LGTM.

**Comment by maxshuang** [comment]
@lonng @amyangfei 
The reason why engine change pkg name from 'pb' to 'enginepb' is :
https://github.com/pingcap/tiflow/issues/5555
https://github.com/pingcap/tiflow/pull/5627

I think we need to do more work.

**Comment by amyangfei** [comment]
> @lonng @amyangfei The reason why engine change pkg name from 'pb' to 'enginepb' is : #5555 #5627
> 
> I think we need to do more work.

Yes, I forget this issue. What about using the structure in pingcap/kvproto

https://github.com/pingcap/kvproto/tree/master/pkg

**Comment by lonng** [comment]
> > @lonng @amyangfei The reason why engine change pkg name from 'pb' to 'enginepb' is : #5555 #5627
> > I think we need to do more work.
> 
> Yes, I forget this issue. What about using the structure in pingcap/kvproto, https://github.com/pingcap/kvproto/tree/master/pkg, such as
> 
> ```shell
> pb
> ├── cdc
> ├── dm
> └── engine
> ```
> 
> But we need package alias when using them.

Make sense, I will reorg the structure.

**Comment by lonng** [comment]
@amyangfei Why not change the `enginepb.WorkerInfo` to `pb.ExecutorInfo`,

```
message WorkerInfo {
    string id = 1;
    string executor_id = 2;
    bytes  status = 3;
    bytes  config = 4;
    bool  is_tombstone = 5;
    int64  last_hb_time = 6;
    int64  workload = 7;
}
```

What the difference between `id` and `executor_id`?

**Comment by amyangfei** [comment]
> @amyangfei Why not change the `enginepb.WorkerInfo` to `pb.ExecutorInfo`,
> 
> ```
> message WorkerInfo {
>     string id = 1;
>     string executor_id = 2;
>     bytes  status = 3;
>     bytes  config = 4;
>     bool  is_tombstone = 5;
>     int64  last_hb_time = 6;
>     int64  workload = 7;
> }
> ```
> 
> What the difference between `id` and `executor_id`?

`enginepb.WorkerInfo` here is the information of a worker in master-worker framework, where `worker` can be treated as a runtime task and runs real job such as DM task. So `id` is the worker id, `executor_id` means on which executor is the worker running.

**Comment by lonng** [comment]
@amyangfei Got it.

**Comment by gozssky** [comment]
https://github.com/pingcap/tiflow/pull/6669 has changed the proto inlcude directory from engine/proto to project directory. So I guess there will be no pb type collision like `pb.WorkerInfo`.

Now engine is using the official [golang protobuf](https://github.com/protocolbuffers/protobuf-go). Golang protobuf doesn't allow duplicate filename globally, see https://github.com/golang/protobuf/issues/1122. That's why I changed the include directory. Otherwise, it will conflict with https://github.com/pingcap/tipb.

To avoid such problems, I think we can refer to https://github.com/googleapis/googleapis structure. Not only the generated codes but also the proto files, need to have a unique import path. So that we don't need to change our message name, file name or package name, which looks weird. There is a simple example in https://github.com/juanfont/headscale/tree/main/proto/headscale/v1.

**Review by gozssky — APPROVED** [review]

**Comment by lonng** [comment]
This PR needs further work to merge and I will close it.

**Pull request closed without merging**
