### PR TITLE
debug(ticdc): add more logs to the kafka sink and enable sarama log

### LINKED ISSUE #11823: kafka consumer meet message for the same row with large offset but smaller commit-ts
The kafka consumer receive message for the same row, which at larger offset but the commit-ts is smaller than the previous messages, this may caused by the Kafka sink send message out of order.

At the moment, we think this may caused by the issue:
* https://github.com/IBM/sarama/issues/2619

This cannot be reproduced by the internal tests now, we are adding more test cases.

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #11823 

### What is changed and how it works?

* add logs to the kafka sink before send out the message
* replace sarama by a custom sarama branch, add more log if retry happens
* add logs to the kafka sink when receive response and detect if commit-ts regressed

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by flowbehappy — APPROVED** [review]

**Review by wk989898 — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Comment by purelind** [comment]
The failure of the dm-compatibility-test is due to Qiniu Cloud's block, which prevents downloads; it has been temporarily bypassed through a PR https://github.com/PingCAP-QE/ci/pull/3269

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
