### PR TITLE
pkg/orchestrator(ticdc): add timeout before remove capture

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: ref #9344

### What is changed and how it works?
1.  add timeout before remove capture
2. do not resign owner when ErrNotOwner is encountered 
3. close processor as soon as possible

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

**Comment by asddongmen** [comment]
Please add a return below:https://github.com/pingcap/tiflow/blob/09bb766104ad1fffb64b09a94c069e1337da37da/pkg/p2p/server.go#L380C14-L381C3  
It causes panic in the integration test.

**Review by nongfushanquan — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Pull request merged**
