### PR TITLE
syncer(dm): fix corrupt latin1 data when replicating

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/7028

### What is changed and how it works?

decode latin1 data to unicode at DM's scope

#### Tests 

 - Integration test

### Release note 

```release-note
Fix a bug that latin1 data may be corrupt when replicating
```

### CODE REVIEW

**Review by D3Hunter — APPROVED** [review]

**Review by buchuitoudegou — APPROVED** [review]

**Comment by GMHDBJD** [comment]
@lance6716 `text` type does not work

**Comment by lance6716** [comment]
ptal @GMHDBJD

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
