### PR TITLE
sink(ticdc): rename sinkv2 to sink in metrics

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/8132

### What is changed and how it works?
- rename sinkv2 to sink in metrics 
- remove useless sinkv1 panels

#### Tests 

 - Manual test (add detailed scripts or steps below)

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
Tested it locally:
image

**Review by amyangfei — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Review by nongfushanquan — APPROVED** [review]

**Pull request merged**
