### PR TITLE
tests (ticdc): remove ticdc github action ci

### LINKED ISSUE #9460: remove unstable and unnecessary ticdc github action ci
### Which jobs are flaking?

All PRs.

### Which test(s) are flaking?

img_v2_d8dab8d8-c4f8-4646-a172-3ce64b2f071g

### Jenkins logs or GitHub Actions link

```log
(paste logs here)
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve?

Issue Number: close #9460 

### What is changed and how it works?

The test cases in Github Action Ci of TiCDC are already covered in `tests/integration_tests`, so these unstable CI pipelines can just be removed.
#### Tests 

 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by nongfushanquan — APPROVED** [review]

**Comment by CharlesCheung96** [comment]
Please state the reasons for removing such tests in the pr body.

**Review by CharlesCheung96 — APPROVED** [review]

**Comment by CharlesCheung96** [comment]
Perhaps the relevant test files should be deleted? Ref: https://github.com/pingcap/tiflow/tree/master/tests/mq_protocol_tests

**Review by 3AceShowHand — APPROVED** [review]

**Pull request merged**
