### PR TITLE
loader: fix wrong progress in query-status for loader

### LINKED ISSUE #3252: load progress in query-status sometimes become smaller
### What did you do?

query-status when in load stage

### What did you expect to see?

load progress become larger

### What did you see instead?

sometimes become smaller
```
tiup dmctl:v2.0.7 --master-addr=172.16.6.1:8161 query-status test -s mysql-replica-01
Starting component `dmctl`: /home/gmhdbjd/.tiup/components/dmctl/v2.0.7/dmctl/dmctl --master-addr=172.16.6.1:8161 query-status test -s mysql-replica-01
{
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": true,
            "msg": "",
            "sourceStatus": {
                "source": "mysql-replica-01",
                "worker": "dm-172.16.6.7-8363",
                "result": null,
                "relayStatus": null
            },
            "subTaskStatus": [
                {
                    "name": "test",
                    "stage": "Running",
                    "unit": "Load",
                    "result": null,
                    "unresolvedDDLLockID": "",
                    "load": {
                        "finishedBytes": "65011251",
                        "totalBytes": "3854328608",
                        "progress": "1.69 %",
                        "metaBinlog": "(mysql-bin.000005, 918368254)",
                        "metaBinlogGTID": "1e62060e-3c65-11ec-a30b-0242ac110002:1-5633"
                    }
                }
            ]
        }
    ]
}
tiup dmctl:v2.0.7 --master-addr=172.16.6.1:8161 query-status test -s mysql-replica-01
Starting component `dmctl`: /home/gmhdbjd/.tiup/components/dmctl/v2.0.7/dmctl/dmctl --master-addr=172.16.6.1:8161 query-status test -s mysql-replica-01
{
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": true,
            "msg": "",
            "sourceStatus": {
                "source": "mysql-replica-01",
                "worker": "dm-172.16.6.7-8363",
                "result": null,
                "relayStatus": null
            },
            "subTaskStatus": [
                {
                    "name": "test",
                    "stage": "Running",
                    "unit": "Load",
                    "result": null,
                    "unresolvedDDLLockID": "",
                    "load": {
                        "finishedBytes": "67108866",
                        "totalBytes": "3854328608",
                        "progress": "1.74 %",
                        "metaBinlog": "(mysql-bin.000005, 918368254)",
                        "metaBinlogGTID": "1e62060e-3c65-11ec-a30b-0242ac110002:1-5633"
                    }
                }
            ]
        }
    ]
}
tiup dmctl:v2.0.7 --master-addr=172.16.6.1:8161 query-status test -s mysql-replica-01
Starting component `dmctl`: /home/gmhdbjd/.tiup/components/dmctl/v2.0.7/dmctl/dmctl --master-addr=172.16.6.1:8161 query-status test -s mysql-replica-01
{
    "result": true,
    "msg": "",
    "sources": [
        {
            "result": true,
            "msg": "",
            "sourceStatus": {
                "source": "mysql-replica-01",
                "worker": "dm-172.16.6.7-8363",
                "result": null,
                "relayStatus": null
            },
            "subTaskStatus": [
                {
                    "name": "test",
                    "stage": "Running",
                    "unit": "Load",
                    "result": null,
                    "unresolvedDDLLockID": "",
                    "load": {
                        "finishedBytes": "64011683",
                        "totalBytes": "3854328608",
                        "progress": "1.66 %",
                        "metaBinlog": "(mysql-bin.000005, 918368254)",
                        "metaBinlogGTID": "1e62060e-3c65-11ec-a30b-0242ac110002:1-5633"
                    }
                }
            ]
        }
    ]
}
```

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
```

DM version (execute `dmctl -V`):
```console
nightly
```

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve?

Issue Number: close #3252

### What is changed and how it works?

fix metrrics load logic

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)
   revert [old logic](https://github.com/pingcap/dm/pull/1778/files#r775709296)

Code changes

Side effects

Related changes

### Release note 

```release-note
`fix a bug that wrong progress in query-status for loader`.
```

### CODE REVIEW

**Comment by Ehco1996** [comment]
this is just revert old [logic](https://github.com/pingcap/dm/pull/1778/files#r775709296) please do a quick review, 

/cc @GMHDBJD  @lance6716

**Review by lance6716 — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
