### PR TITLE
Makefile,tests(ticdc): adjust version and print version in tests

### LINKED ISSUE #4979: Adjust version in Makefile and print version in tests
As title.

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: close #4979

### Check List 

Tests 

 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by overvenus** [comment]
[](https://github.com/overvenus)/run-integration-tests

**Review by zhaoxinyu — APPROVED** [review]

**Review by hi-rustin — APPROVED** [review]
I seem to remember that we have other startup scripts that also start the cluster (with tls?). Could you please check if they should all print versions?

**Pull request merged**
