### PR TITLE
script(cdc): don't check line width for test files

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: ref #4287 

### What is changed and how it works?

When I write tests, I think a long string literal (like generated SQL) is good to read. But it can't pass CI.

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note 
 `None`.
```

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
I personally feel that the test needs to be kept at normal width as well. It is no different from the core code. Both need to ensure good readability. But if you have a strong opinion about it, I'm ok with that.

**Comment by lance6716** [comment]
> I personally feel that the test needs to be kept at normal width as well. It is no different from the core code. Both need to ensure good readability. But if you have a strong opinion about it, I'm ok with that.

I made some test file changes like this 
https://github.com/pingcap/tiflow/pull/4587/files#diff-7a385c2f760ae6ee8284c0ec6a649a8953602ae51fca4dd19f7ee28c806e2a4eR87

```diff
			expected: &preparedDMLs{
-				sqls:     []string{"DELETE FROM `common_1`.`uk_without_pk` WHERE `a1` = ? AND `a3` = ? LIMIT 1;"},
+				sqls:     []string{"DELETE FROM `common_1`.`uk_without_pk` WHERE `a1` = ? AND `a3` = ? LIMIT 1"},
				values:   [][]interface{}{{1, 1}},
				rowCount: 1,
			},
```

That's not very easy to find a good layout to pass the CI

**Review by overvenus — CHANGES_REQUESTED** [review]
> I personally feel that the test needs to be kept at normal width as well. It is no different from the core code. Both need to ensure good readability. But if you have a strong opinion about it, I'm ok with that.

Agree, without width limit, we may write tests like crazy long, see

https://github.com/pingcap/tiflow/blob/1e8f99f5e4b80a63266204abcb4bb605ef673d3c/dm/loader/convert_data_test.go#L64-L69

https://github.com/pingcap/tiflow/blob/1e8f99f5e4b80a63266204abcb4bb605ef673d3c/pkg/orchestrator/reactor_state_test.go#L61-L68

**Comment by lance6716** [comment]
ok, I will use str+str to split the long string literal in my original pr.

**Comment by overvenus** [comment]
> ok, I will use str+str to split the long string literal in my original pr.

try SQL formatter https://www.dpriver.com/pp/sqlformat.htm

```go
	longLongLongSQL := `
DELETE FROM `common_1`.`uk_without_pk`
WHERE  `a1` = ?
       AND `a3` = ?
LIMIT 1`
```

**Pull request closed without merging**
