### PR TITLE
sink(ticdc): support TTL table for cdc sink

### LINKED ISSUE #7997: CDC support TTL table
### Is your feature request related to a problem?

CDC should support TTL table

### Describe the feature you'd like

When a table is a TTL table in upstream, the downstream should turn off its `TTL_ENABLE` option to `OFF`

### Describe alternatives you've considered

_No response_

### Teachability, Documentation, Adoption, Migration Strategy

_No response_

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve?

Issue Number: close #7997

### What is changed and how it works?

The DDL statements with TTL options will be changed when syncing to donwstream

- `CREATE TABLE ... TTL=t + INTERVAL 1 DAY` => `CREATE TABLE ... TTL=`t` + INTERVAL 1 DAY TTL_ENABLE='OFF'`
- `ALTER TABLE t TTL=t +  INTERVAL 1 DAY` => `ALTER TABLE t TTL=t +  INTERVAL 1 DAY TTL_ENABLE='OFF'`
- `ALTER TABLE t TTL_ENABLE='ON'` => `ALTER TABLE t`

TTL is a new experimental feature since v6.5.0, see: https://docs.pingcap.com/tidb/stable/time-to-live

We can add `TTL` option to a table to identify the rows in the table will be deleted when they are expired. 

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
When syncing DDL with TTL options to downstream, the `TTL_ENABLE` will force be set to `OFF`
```

### CODE REVIEW

**Review by nongfushanquan — COMMENTED** [review]
could you add more background information about the ttl table feature?

**Review by asddongmen — APPROVED** [review]

**Review by nongfushanquan — APPROVED** [review]

**Pull request merged**
