### PR TITLE
engine(dm): adjust the subtask config

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close #4287

### What is changed and how it works?

the OP logic is expected that all subtasks are called adjust. So for engine task we also do it

#### Tests 

 - Manual test (add detailed scripts or steps below)
    service should be able to adjust the value to LoadModelLogical

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by okJiang** [comment]
test still failed @lance6716

**Comment by lance6716** [comment]
> Details

it should be a flaky test

**Review by D3Hunter — APPROVED** [review]

**Review by okJiang — APPROVED** [review]

**Pull request merged**
