### PR TITLE
dep: update TiDB to introduce SchemaTracker

### LINKED ISSUE #3400: `pause-relay` fail to get expected result
### Which jobs are flaking?

DM-IT

### Which test(s) are flaking?

dmctl_basic

### Jenkins logs or GitHub Actions link

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/449/pipeline/133/

### REASON:

we call `start-relay` when `pause-relay` in around 18:07:00, that's too adjacent so when DM-worker enable relay, it will directly see a "paused" relay stage in etcd. 

https://github.com/pingcap/ticdc/blob/2569abaa3e64bc930b5cab18a0d6edaae2a41ef0/dm/dm/worker/source_worker.go#L340-L345

It's not a "running" relay stage in etcd, DM-worker will not start relay and keep relay in a "New" stage. As we are expecting DM-worker start-then-pause relay which should be a "paused" relay stage, so the declarative check of `pause-relay` is failed.

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### LINKED ISSUE #6607: unstable validator_basic `"processedRowsStatus": "insert\/update\/delete: 1\/0\/0" count: 0 != expected: 1`
### Which jobs are flaking?

validator_basic

### Which test(s) are flaking?

DM-IT

### Jenkins logs or GitHub Actions link

```log
[2022-08-04T04:41:26.432Z] command: query-status test "processedRowsStatus": "insert\/update\/delete: 1\/0\/0" count: 0 != expected: 1, failed the 9-th time, will retry again

[2022-08-04T04:41:28.321Z] {

[2022-08-04T04:41:28.321Z]     "result": true,

[2022-08-04T04:41:28.321Z]     "msg": "",

[2022-08-04T04:41:28.321Z]     "sources": [

[2022-08-04T04:41:28.321Z]         {

[2022-08-04T04:41:28.321Z]             "result": true,

[2022-08-04T04:41:28.321Z]             "msg": "",

[2022-08-04T04:41:28.321Z]             "sourceStatus": {

[2022-08-04T04:41:28.321Z]                 "source": "mysql-replica-01",

[2022-08-04T04:41:28.321Z]                 "worker": "worker1",

[2022-08-04T04:41:28.321Z]                 "result": null,

[2022-08-04T04:41:28.321Z]                 "relayStatus": null

[2022-08-04T04:41:28.321Z]             },

[2022-08-04T04:41:28.321Z]             "subTaskStatus": [

[2022-08-04T04:41:28.321Z]                 {

[2022-08-04T04:41:28.321Z]                     "name": "test",

[2022-08-04T04:41:28.321Z]                     "stage": "Running",

[2022-08-04T04:41:28.321Z]                     "unit": "Sync",

[2022-08-04T04:41:28.321Z]                     "result": null,

[2022-08-04T04:41:28.321Z]                     "unresolvedDDLLockID": "",

[2022-08-04T04:41:28.321Z]                     "sync": {

[2022-08-04T04:41:28.321Z]                         "totalEvents": "9",

[2022-08-04T04:41:28.321Z]                         "totalTps": "0",

[2022-08-04T04:41:28.321Z]                         "recentTps": "0",

[2022-08-04T04:41:28.321Z]                         "masterBinlog": "(dm-integration-test-go1180-8595-nfnn8-hzl1f-bin.000001, 11377)",

[2022-08-04T04:41:28.321Z]                         "masterBinlogGtid": "21886096-13ae-11ed-8dcd-9e8c32ceba30:1-48",

[2022-08-04T04:41:28.322Z]                         "syncerBinlog": "(dm-integration-test-go1180-8595-nfnn8-hzl1f-bin.000001, 11377)",

[2022-08-04T04:41:28.322Z]                         "syncerBinlogGtid": "",

[2022-08-04T04:41:28.322Z]                         "blockingDDLs": [

[2022-08-04T04:41:28.322Z]                         ],

[2022-08-04T04:41:28.322Z]                         "unresolvedGroups": [

[2022-08-04T04:41:28.322Z]                         ],

[2022-08-04T04:41:28.322Z]                         "synced": true,

[2022-08-04T04:41:28.322Z]                         "binlogType": "remote",

[2022-08-04T04:41:28.322Z]                         "secondsBehindMaster": "0",

[2022-08-04T04:41:28.322Z]                         "blockDDLOwner": "",

[2022-08-04T04:41:28.322Z]                         "conflictMsg": ""

[2022-08-04T04:41:28.322Z]                     },

[2022-08-04T04:41:28.322Z]                     "validation": {

[2022-08-04T04:41:28.322Z]                         "task": "test",

[2022-08-04T04:41:28.322Z]                         "source": "mysql-replica-01",

[2022-08-04T04:41:28.322Z]                         "mode": "full",

[2022-08-04T04:41:28.322Z]                         "stage": "Running",

[2022-08-04T04:41:28.322Z]                         "validatorBinlog": "(dm-integration-test-go1180-8595-nfnn8-hzl1f-bin.000001, 10922)",

[2022-08-04T04:41:28.322Z]                         "validatorBinlogGtid": "",

[2022-08-04T04:41:28.322Z]                         "result": null,

[2022-08-04T04:41:28.322Z]                         "processedRowsStatus": "insert/update/delete: 0/0/0",

[2022-08-04T04:41:28.322Z]                         "pendingRowsStatus": "insert/update/delete: 0/0/0",

[2022-08-04T04:41:28.322Z]                         "errorRowsStatus": "new/ignored/resolved: 0/0/0"

[2022-08-04T04:41:28.322Z]                     }

[2022-08-04T04:41:28.322Z]                 }

[2022-08-04T04:41:28.322Z]             ]

[2022-08-04T04:41:28.322Z]         }

[2022-08-04T04:41:28.322Z]     ]

[2022-08-04T04:41:28.322Z] }
```

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/8595/pipeline

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: ref #5334 close #3400 close #6607

### What is changed and how it works?

update dependency to see if current TiDB API has changed. Plan to switch to that implementation in next PR

#### Tests 

 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
go.mod may be updated by other PR, in order to reduce conflicts I want to merge this PR soon.
/cc @GMHDBJD @buchuitoudegou

**Review by lonng — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
https://github.com/pingcap/tiflow/issues/3400

/run-dm-integration-test

**Comment by lance6716** [comment]
/hold

unit test 10m time out

```

[2022-08-05T05:01:42.024Z] goroutine 630971 [select]:
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/ddl.(*ddl).DoDDLJob(0xc064f90d80, {0x8120060, 0xc0336f0240}, 0xc036c92120)
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/ddl/ddl.go:984 +0xbd1
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/ddl.(*ddl).CreateSchemaWithInfo(0xc0365093b0?, {0x8120060, 0xc0336f0240}, 0xc036c83ea0, 0x1)
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/ddl/ddl_api.go:201 +0x5d5
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/ddl.(*ddl).CreateSchema(0xc0336f0240?, {0x8120060, 0xc0336f0240}, 0xc061622800)
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/ddl/ddl_api.go:152 +0x83b
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/executor.(*DDLExec).executeCreateDatabase(0xc036b2a8c0, 0xc069a25200?)
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/executor/ddl.go:236 +0xc2
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/executor.(*DDLExec).Next(0xc036b2a8c0, {0x80bda50, 0xc069a251d0}, 0x0?)
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/executor/ddl.go:150 +0x471
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/executor.Next({0x80bda50, 0xc069a251d0}, {0x80c1220, 0xc036b2a8c0}, 0xc036c9c000)
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/executor/executor.go:319 +0x5bc
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/executor.(*ExecStmt).next(0xc032d86690, {0x80bda50, 0xc069a251d0}, {0x80c1220, 0xc036b2a8c0}, 0xc036cd4fe8?)
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/executor/adapter.go:898 +0x8a
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor(0xc032d86690, {0x80bda50, 0xc069a251d0}, {0x80c1220?, 0xc036b2a8c0})
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/executor/adapter.go:698 +0x6b8
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay(0xc032d86690, {0x80bda50, 0xc069a251d0}, {0x80c1220, 0xc036b2a8c0?}, 0x0)
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/executor/adapter.go:548 +0x29d
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/executor.(*ExecStmt).Exec(0xc032d86690, {0x80bda50, 0xc069a251d0})
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/executor/adapter.go:497 +0xb85
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/session.runStmt({0x80bda50, 0xc069a24ea0}, 0xc0336f0240, {0x80cf0f0, 0xc032d86690?})
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/session/session.go:2136 +0x619
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc0336f0240, {0x80bda50, 0xc069a24ea0}, {0x80d5360, 0xc061622800})
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/session/session.go:2002 +0xddb
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/session.(*session).ExecuteInternal(0xc0336f0240, {0x80bda50, 0xc069a24ea0}, {0x6a31cae, 0x22}, {0x0, 0x0, 0x0})
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/session/session.go:1506 +0x465
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/session.mustExecute({0x8126798, 0xc0336f0240}, {0x6a31cae, 0x22}, {0x0, 0x0, 0x0})
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/session/bootstrap.go:2144 +0x107
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/session.doDDLWorks({0x8126798, 0xc0336f0240})
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/session/bootstrap.go:1966 +0x4f
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/session.bootstrap({0x8126798?, 0xc0336f0240})
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/session/bootstrap.go:447 +0x2c5
[2022-08-05T05:01:42.024Z] github.com/pingcap/tidb/session.runInBootstrapSession({0x80e4308, 0xc033698d40}, 0x6b43060)
[2022-08-05T05:01:42.024Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/session/session.go:2803 +0x215
[2022-08-05T05:01:42.025Z] github.com/pingcap/tidb/session.BootstrapSession({0x80e4308?, 0xc033698d40})
[2022-08-05T05:01:42.025Z] 	/go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220802094005-8fdd64ea9eaf/session/session.go:2682 +0x285
[2022-08-05T05:01:42.025Z] github.com/pingcap/tiflow/dm/pkg/schema.(*Tracker).Init(0xc0366c75c0, {0x80bd9e0?, 0xc0001b8008}, {0x69cec29, 0xc}, 0xc001065e60, 0xc018512bd0, {0xc018512bd0?})
[2022-08-05T05:01:42.025Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/dm/pkg/schema/tracker.go:208 +0x83a
[2022-08-05T05:01:42.025Z] github.com/pingcap/tiflow/dm/pkg/schema.NewTestTracker({0x80bd9e0, 0xc0001b8008}, {0x69cec29, 0xc}, 0x0?, 0x0?, {0x0?})
[2022-08-05T05:01:42.025Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/dm/pkg/schema/tracker.go:282 +0xdf
[2022-08-05T05:01:42.025Z] github.com/pingcap/tiflow/dm/syncer.TestValidatorCheckpointPersist(0xc01b87bba0)
[2022-08-05T05:01:42.025Z] 	/home/jenkins/agent/workspace/ut-check/tiflow/dm/syncer/validator_checkpoint_test.go:95 +0x25c8
[2022-08-05T05:01:42.025Z] testing.tRunner(0xc01b87bba0, 0x6b44728)
[2022-08-05T05:01:42.025Z] 	/usr/local/go/src/testing/testing.go:1439 +0x214
[2022-08-05T05:01:42.025Z] created by testing.(*T).Run
[2022-08-05T05:01:42.025Z] 	/usr/local/go/src/testing/testing.go:1486 +0x725
```

**Comment by lance6716** [comment]
CI workload seems gone, it's stable again 😂 

/unhold
/merge

**Pull request merged**
