### PR TITLE
sinkv2(cdc): add more sinkv2 txn sink metrics

### PR DESCRIPTION
**Pull request by hicqu**
Signed-off-by: qupeng <qupeng@pingcap.com>

### What problem does this PR solve?

Issue Number: ref #5928

### What is changed and how it works?

Add more metric panels for transaction sink.

#### Tests 

 - No code

An example can be found [here](http://10.2.5.12:3000/d/YiGL8hBZ1fsdfsfs/test-cluster-ticdc?orgId=1&from=1664267090861&to=1664267323632).

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]
Thanks!

**Comment by 3AceShowHand** [comment]
It looks the `Output Row Count (per second)` is identical to the `MySQL sink write rows count/s` and `Kafka sink write rows count/s`, how about renaming it to `sink write rows count/s`.

**Comment by 3AceShowHand** [comment]
For each panel, please also enable `legend/values` options, at least `current`.

**Comment by hicqu** [comment]
> 

I prefer to keep `Output Row Count (per second)`. Seems it's clear enough.

**Review by 3AceShowHand — APPROVED** [review]

**Pull request merged**
