### PR TITLE
redo(ticdc): read redo log by commitTs_startTs order

### LINKED ISSUE #5285: Redo log: [PANIC] [txn_cache.go:50] [\"Row changed event received by the sink module should be ordered\"]
### What did you do?

- http://rms.pingcap.net:31714/artifacts/testground/plan-exec-752162-xbwg7/plan-exec-752162-xbwg7-3594272324/main-logs
- Execute: /cdc  redo  apply  --sink-uri=mysql://xxx --storage=s3://nfs/xxx --tmp-dir=/tmp/nfs
[PANIC] [txn_cache.go:50] [\"Row changed event received by the sink module should be ordered\"] [previousTxn=\"{\\\"Table\\\":{\\\"db-name\\\":\\\"workload\\\",\\\"tbl-name\\\":\\\"sbtest8\\\",\\\"tbl-id\\\":74,\\\"is-partition\\\":false},\\\"StartTs\\\":432793371743355055,\\\"CommitTs\\\":432793371743355056,\\\"Rows\\\":[{\\\"start-ts\\\":432793371743355055,\\\"commit-ts\\\":432793371743355056,\\\"row-id\\\":0,\\\
...
 [currentRow=\"{\\\"start-ts\\\":432793371743355053,\\\"commit-ts\\\":432793371743355056,\\\"row-id\\\":0,\\\"table\\\":{\\\"db-name\\\":\\\"workload\\\",\\\"tbl-name\\\":\\\"sbtest8

### What did you expect to see?

_No response_

### What did you see instead?

redo log apply panic.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
(paste TiCDC version here)
[release-version=v6.1.0-nightly]
[git-hash=967060a8a8f63388e47540fe175902c99798892c]
[git-branch=heads/refs/tags/v6.1.0-nightly]
[utc-build-time="2022-04-26 10:55:22"] 
[go-version="go version go1.18 linux/amd64"] 
```

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: close #5285

### What is changed and how it works?
1. sorter redo log by commitTs_startTs order

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Comment by ben1009** [comment]
@CharlesCheung96 this should be ready for you 
 > Sent from <a href='https://neat.run?ref=gh_footer'>Neat</a>

**Comment by ben1009** [comment]
@CharlesCheung96 have you had a chance to update this? 
 > Sent from <a href='https://neat.run?ref=gh_footer'>Neat</a>

**Pull request merged**
