### PR TITLE
owner(ticdc): return barrierTs immediately

### LINKED ISSUE #7357: not skip etcd worker tick if nothing is changed
https://github.com/pingcap/tiflow/blob/c5b1dd0edcf2d1b03838619fdb27acab908b1f27/pkg/orchestrator/reactor_state.go#L262-L282

always add a pending patch, but nothing is changed,  that will make etcd worker skip one tick

### LINKED ISSUE #7361: return barrierTs immediately
return barrierTs immediately to save one tick interval

### PR DESCRIPTION
**Pull request by sdojjy**
### What problem does this PR solve?

Issue Number: close #7361

### What is changed and how it works?
return barrierTs immediately to save on tick interval

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Review by hi-rustin — APPROVED** [review]

**Comment by hi-rustin** [comment]
/hold

Waiting for more review.

**Review by hicqu — APPROVED** [review]

**Pull request merged**
