### PR TITLE
lightning: adjust lightning additional routes

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/3340

### What is changed and how it works?
After lightning supports additional routes in https://github.com/pingcap/tidb/issues/37797, dm should adjust this field for inline lightning.

#### Tests 

 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by lichunzhu** [comment]
@GMHDBJD PTAL

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
