### PR TITLE
cdc/test: integration test add default null for unsigned type

### LINKED ISSUE #4787: add `unsigned` to integration test

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #4787 

### What is changed and how it works?

add some `unsigned` type with `null` to integration test

### Check List 

Tests 

 - Integration test

Code changes

Side effects

Related changes

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Review by liuzix — APPROVED** [review]
Can you briefly document the potential problem in the test files? Rest LGTM.

**Pull request merged**
