### PR TITLE
syncer(dm): fix corrupt latin1 data when replicating (#7027) (#7055)

### PR DESCRIPTION
**Pull request by lance6716**
cherry-pick from https://github.com/pingcap/tiflow/pull/7055

---
This is an automated cherry-pick of #7027

Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/7028

### What is changed and how it works?

decode latin1 data to unicode at DM's scope

#### Tests 

 - Integration test

### Release note 

```release-note
Fix a bug that latin1 data may be corrupt when replicating
```

### CODE REVIEW

**Review by buchuitoudegou — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]

**Comment by lance6716** [comment]
/run-integration-test tidb=v6.1.1 tikv=v6.1.1 pd=v6.1.1
/run-kafka-integration-test tidb=v6.1.1 tikv=v6.1.1 pd=v6.1.1

**Comment by lance6716** [comment]
/run-integration-test tidb=release-6.1 tikv=release-6.1 pd=release-6.1
/run-kafka-integration-test tidb=release-6.1 tikv=release-6.1 pd=release-6.1

**Comment by wuhuizuo** [comment]
/run-integration-test tidb=release-6.1 tikv=release-6.1 pd=release-6.1 tiflash=release-6.1
/run-kafka-integration-test tidb=release-6.1 tikv=release-6.1 pd=release-6.1 tiflash=release-6.1

**Pull request merged**
