### PR TITLE
fix(cdc): failed to start when connects to pd with multiple endpoints and the 1st endpoint is not available

### LINKED ISSUE #4777: TiCDC failed to start when the 1st endpoint of pd that specified in --pd is unvailable
### What did you do?

The original cause are the e2e case of tidb-operator fails https://github.com/pingcap/tidb-operator/issues/4412, so basically, what this case do is
1. create tls certificates for components that are declared in `TidbCluster` (CustomResource in k8s, tidb-operator will create corresponding tidb, tikv, pd, ticdc pods)
2. create three `TidbCluster` under different namespaces so they will have different dns names, every namespace will have 1 replica of each components, and they are interconnected to provider service. To be more specific, ticdc's arguments will looks like `--pd=https://cluster-1-pd:2379,https://cluster-2-pd-0.cluster-2-pd-peer.pingcap-1.svc.cluster.local:2379,https://cluster-3-pd-0.cluster-3-pd-peer.pingcap-2.svc.cluster.local:2379`.
3. fail one pd replica under a namespaces and restart all component pods under the same namespace.

Then the problem happens that ticdc pod fails to restart while other components works fine. the error logs looks like below:

```
Error: run server: new etcd client: [CDC:ErrNewCaptureFailed]context deadline exceeded: context deadline exceeded
[2022/03/04 18:00:34.772 +08:00] [ERROR] [server.go:130] ["run server"] [error="[CDC:ErrNewCaptureFailed]context deadline exceeded: context deadline exceeded\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20210513014640-40f9a1999b3b/errors.go:174\ngithub.com/pingcap/errors.(*Error).GenWithStackByCause\n\tgithub.com/pingcap/errors@v0.11.5-0.20210513014640-40f9a1999b3b/normalize.go:302\ngithub.com/pingcap/ticdc/pkg/errors.WrapError\n\tgithub.com/pingcap/ticdc/pkg/errors/helper.go:30\ngithub.com/pingcap/ticdc/cdc.(*Server).Run\n\tgithub.com/pingcap/ticdc/cdc/server.go:136\ngithub.com/pingcap/ticdc/pkg/cmd/server.(*options).run\n\tgithub.com/pingcap/ticdc/pkg/cmd/server/server.go:128\ngithub.com/pingcap/ticdc/pkg/cmd/server.NewCmdServer.func1\n\tgithub.com/pingcap/ticdc/pkg/cmd/server/server.go:275\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.0.0/command.go:842\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.0.0/command.go:950\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.0.0/command.go:887\ngithub.com/pingcap/ticdc/pkg/cmd.Run\n\tgithub.com/pingcap/ticdc/pkg/cmd/cmd.go:47\nmain.main\n\tcommand-line-arguments/main.go:22\nruntime.main\n\truntime/proc.go:225\nruntime.goexit\n\truntime/asm_amd64.s:1371\nnew etcd client"]
[2022/03/04 18:00:34.772 +08:00] [ERROR] [client.go:750] ["[pd] fetch pending tso requests error"] [dc-location=global] [error="[PD:client:ErrClientGetTSO]context canceled: context canceled"]
[2022/03/04 18:00:34.772 +08:00] [INFO] [client.go:669] ["[pd] exit tso dispatcher"] [dc-location=global]
Usage:
  cdc server [flags]
...
```

The reproduce steps, sorry for the complicated scripts, not so sure how to reproduce it under non-k8s environment:
1. install `kind`, `helm`, `kubectl` first if you donot have one
2. install all the components and reproduce the problem via the script below.

```sh
function install_kind(){
    cat > ${REPRO_DIR}/kind-cluster.yaml << EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: reproduce-ticdc
networking:
  podSubnet: 10.10.0.0/16
  serviceSubnet: 10.40.0.0/16
nodes:
  - role: control-plane
  - role: worker
  - role: worker
EOF

    kind create cluster --config ${REPRO_DIR}/kind-cluster.yaml
}

function install_dependencies(){
    curl -L "https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.yaml" -o "${REPRO_DIR}/cert-manager.yaml"
    kubectl apply -f ${REPRO_DIR}/cert-manager.yaml

    version=v1.3.1
    helm repo add pingcap https://charts.pingcap.org/
    helm install to -n operator pingcap/tidb-operator --version=$version --create-namespace

    kubectl create -f https://raw.githubusercontent.com/pingcap/tidb-operator/$version/manifests/crd.yaml
    echo "wait for dependencies to be ready"
    kubectl wait --for=condition=Available=true deploy --all -n cert-manager --timeout=60s
    kubectl wait --for=condition=Available=true deploy --all -n operator --timeout=60s
}

function install_issuer(){
    cat > ${REPRO_DIR}/issuer.yaml <<EOF
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-selfsigned-ca-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ca
  namespace: cert-manager
spec:
  commonName: TiDB CA
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: cluster-selfsigned-ca-issuer
  secretName: cluster-ca-secret
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  generation: 1
  name: cluster-tidb-issuer
spec:
  ca:
    secretName: cluster-ca-secret
EOF
    kubectl apply -f ${REPRO_DIR}/issuer.yaml
}

function install_tls_certs(){
    CLUSTER=$1
    NS=$2
    cat > ${REPRO_DIR}/certs-${CLUSTER}-${NS}.yaml << EOF
apiVersion: v1
kind: Namespace
metadata:
  name: ${NS}
---
apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ${CLUSTER}-cluster-client-secret
    namespace: ${NS}
  spec:
    commonName: TiDB
    duration: 8760h0m0s
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: cluster-tidb-issuer
    renewBefore: 360h0m0s
    secretName: ${CLUSTER}-cluster-client-secret
    subject:
      organizations:
      - PingCAP
    usages:
    - client auth
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ${CLUSTER}-pd-cluster-secret
    namespace: ${NS}
  spec:
    commonName: TiDB
    dnsNames:
    - ${CLUSTER}-pd
    - ${CLUSTER}-pd.${NS}
    - ${CLUSTER}-pd.${NS}.svc.cluster.local
    - ${CLUSTER}-pd-peer
    - ${CLUSTER}-pd-peer.${NS}
    - ${CLUSTER}-pd-peer.${NS}.svc.cluster.local
    - '*.${CLUSTER}-pd-peer'
    - '*.${CLUSTER}-pd-peer.${NS}'
    - '*.${CLUSTER}-pd-peer.${NS}.svc.cluster.local'
    duration: 8760h0m0s
    ipAddresses:
    - 127.0.0.1
    - ::1
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: cluster-tidb-issuer
    renewBefore: 360h0m0s
    secretName: ${CLUSTER}-pd-cluster-secret
    subject:
      organizations:
      - PingCAP
    usages:
    - server auth
    - client auth
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ${CLUSTER}-ticdc-cluster-secret
    namespace: ${NS}
  spec:
    commonName: TiDB
    dnsNames:
    - ${CLUSTER}-ticdc
    - ${CLUSTER}-ticdc.${NS}
    - ${CLUSTER}-ticdc.${NS}.svc.cluster.local
    - ${CLUSTER}-ticdc-peer
    - ${CLUSTER}-ticdc-peer.${NS}
    - ${CLUSTER}-ticdc-peer.${NS}.svc.cluster.local
    - '*.${CLUSTER}-ticdc-peer'
    - '*.${CLUSTER}-ticdc-peer.${NS}'
    - '*.${CLUSTER}-ticdc-peer.${NS}.svc.cluster.local'
    duration: 8760h0m0s
    ipAddresses:
    - 127.0.0.1
    - ::1
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: cluster-tidb-issuer
    renewBefore: 360h0m0s
    secretName: ${CLUSTER}-ticdc-cluster-secret
    subject:
      organizations:
      - PingCAP
    usages:
    - server auth
    - client auth
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ${CLUSTER}-tidb-client-secret
    namespace: ${NS}
  spec:
    commonName: TiDB Client
    duration: 8760h0m0s
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: cluster-tidb-issuer
    renewBefore: 360h0m0s
    secretName: ${CLUSTER}-tidb-client-secret
    subject:
      organizations:
      - PingCAP
    usages:
    - client auth
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ${CLUSTER}-tidb-cluster-secret
    namespace: ${NS}
  spec:
    commonName: TiDB
    dnsNames:
    - ${CLUSTER}-tidb
    - ${CLUSTER}-tidb.${NS}
    - ${CLUSTER}-tidb.${NS}.svc.cluster.local
    - ${CLUSTER}-tidb-peer
    - ${CLUSTER}-tidb-peer.${NS}
    - ${CLUSTER}-tidb-peer.${NS}.svc.cluster.local
    - '*.${CLUSTER}-tidb-peer'
    - '*.${CLUSTER}-tidb-peer.${NS}'
    - '*.${CLUSTER}-tidb-peer.${NS}.svc.cluster.local'
    duration: 8760h0m0s
    ipAddresses:
    - 127.0.0.1
    - ::1
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: cluster-tidb-issuer
    renewBefore: 360h0m0s
    secretName: ${CLUSTER}-tidb-cluster-secret
    subject:
      organizations:
      - PingCAP
    usages:
    - server auth
    - client auth
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ${CLUSTER}-tidb-server-secret
    namespace: ${NS}
  spec:
    commonName: TiDB Server
    dnsNames:
    - ${CLUSTER}-tidb
    - ${CLUSTER}-tidb.${NS}
    - '*.${CLUSTER}-tidb'
    - ${CLUSTER}-tidb.${NS}.svc.cluster.local
    - '*.${CLUSTER}-tidb.${NS}'
    - '*.${CLUSTER}-tidb.${NS}.svc.cluster.local'
    duration: 8760h0m0s
    ipAddresses:
    - 127.0.0.1
    - ::1
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: cluster-tidb-issuer
    renewBefore: 360h0m0s
    secretName: ${CLUSTER}-tidb-server-secret
    subject:
      organizations:
      - PingCAP
    usages:
    - server auth
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    name: ${CLUSTER}-tikv-cluster-secret
    namespace: ${NS}
  spec:
    commonName: TiDB
    dnsNames:
    - ${CLUSTER}-tikv
    - ${CLUSTER}-tikv.${NS}
    - ${CLUSTER}-tikv.${NS}.svc.cluster.local
    - ${CLUSTER}-tikv-peer
    - ${CLUSTER}-tikv-peer.${NS}
    - ${CLUSTER}-tikv-peer.${NS}.svc.cluster.local
    - '*.${CLUSTER}-tikv-peer'
    - '*.${CLUSTER}-tikv-peer.${NS}'
    - '*.${CLUSTER}-tikv-peer.${NS}.svc.cluster.local'
    duration: 8760h0m0s
    ipAddresses:
    - 127.0.0.1
    - ::1
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: cluster-tidb-issuer
    renewBefore: 360h0m0s
    secretName: ${CLUSTER}-tikv-cluster-secret
    subject:
      organizations:
      - PingCAP
    usages:
    - server auth
    - client auth
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
EOF
    kubectl apply -f ${REPRO_DIR}/certs-${CLUSTER}-${NS}.yaml
}

function install_tidbclusters(){
    cat > ${REPRO_DIR}/tidb-clusters.yaml << EOF
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: cluster-1
  namespace: pingcap
spec:
  acrossK8s: true
  annotations:
    cluster-test-key: value
  clusterDomain: cluster.local
  configUpdateStrategy: RollingUpdate
  discovery: {}
  enablePVReclaim: false
  imagePullPolicy: IfNotPresent
  labels:
    cluster-test-key: value
  pd:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: pd
                app.kubernetes.io/instance: cluster-1
            namespaces:
            - pingcap
            topologyKey: rack
          weight: 50
    annotations:
      component-test-key: value
    baseImage: pingcap/pd
    config: |
      [log]
        level = "info"

      [schedule]
        max-store-down-time = "5m"
    labels:
      component-test-key: value
    limits:
      cpu: "1"
      memory: 2Gi
    maxFailoverCount: 3
    replicas: 1
    requests:
      cpu: 100m
      memory: 100Mi
      storage: 1Gi
  pvReclaimPolicy: Delete
  schedulerName: tidb-scheduler
  ticdc:
    baseImage: pingcap/ticdc
    config: ""
    replicas: 1
  tidb:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: tidb
                app.kubernetes.io/instance: cluster-1
            namespaces:
            - pingcap
            topologyKey: rack
          weight: 50
    annotations:
      component-test-key: value
    baseImage: pingcap/tidb
    config: |
      [log]
        level = "info"
        [log.file]
          max-backups = 3
    labels:
      component-test-key: value
    limits:
      cpu: "2"
      memory: 4Gi
    maxFailoverCount: 3
    replicas: 1
    requests:
      cpu: 100m
      memory: 100Mi
      storage: 10Gi
    separateSlowLog: true
    service:
      annotations:
        component-test-key: value
      exposeStatus: true
      labels:
        component-test-key: value
      type: ClusterIP
    tlsClient:
      enabled: true
  tikv:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: tikv
                app.kubernetes.io/instance: cluster-1
            namespaces:
            - pingcap
            topologyKey: rack
          weight: 50
    annotations:
      component-test-key: value
    baseImage: pingcap/tikv
    config: |
      log-level = "info"

      [storage]
        reserve-space = "0MB"
    evictLeaderTimeout: 1m
    labels:
      component-test-key: value
    limits:
      cpu: "2"
      memory: 4Gi
    maxFailoverCount: 3
    replicas: 1
    requests:
      cpu: 100m
      memory: 100Mi
      storage: 10Gi
  timezone: Asia/Shanghai
  tlsCluster:
    enabled: true
  version: v5.3.0
---
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: cluster-2
  namespace: pingcap-1
spec:
  acrossK8s: true
  annotations:
    cluster-test-key: value
  cluster:
    clusterDomain: cluster.local
    name: cluster-1
    namespace: pingcap
  clusterDomain: cluster.local
  configUpdateStrategy: RollingUpdate
  discovery: {}
  enablePVReclaim: false
  imagePullPolicy: IfNotPresent
  labels:
    cluster-test-key: value
  pd:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: pd
                app.kubernetes.io/instance: cluster-2
            namespaces:
            - pingcap-1
            topologyKey: rack
          weight: 50
    annotations:
      component-test-key: value
    baseImage: pingcap/pd
    config: |
      [log]
        level = "info"

      [schedule]
        max-store-down-time = "5m"
    labels:
      component-test-key: value
    limits:
      cpu: "1"
      memory: 2Gi
    maxFailoverCount: 3
    replicas: 1
    requests:
      cpu: 100m
      memory: 100Mi
      storage: 1Gi
  pvReclaimPolicy: Delete
  schedulerName: tidb-scheduler
  ticdc:
    baseImage: pingcap/ticdc
    config: ""
    replicas: 1
  tidb:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: tidb
                app.kubernetes.io/instance: cluster-2
            namespaces:
            - pingcap-1
            topologyKey: rack
          weight: 50
    annotations:
      component-test-key: value
    baseImage: pingcap/tidb
    config: |
      [log]
        level = "info"
        [log.file]
          max-backups = 3
    labels:
      component-test-key: value
    limits:
      cpu: "2"
      memory: 4Gi
    maxFailoverCount: 3
    replicas: 1
    requests:
      cpu: 100m
      memory: 100Mi
      storage: 10Gi
    separateSlowLog: true
    service:
      annotations:
        component-test-key: value
      exposeStatus: true
      labels:
        component-test-key: value
      type: ClusterIP
    tlsClient:
      enabled: true
  tikv:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: tikv
                app.kubernetes.io/instance: cluster-2
            namespaces:
            - pingcap-1
            topologyKey: rack
          weight: 50
    annotations:
      component-test-key: value
    baseImage: pingcap/tikv
    config: |
      log-level = "info"

      [storage]
        reserve-space = "0MB"
    evictLeaderTimeout: 1m
    labels:
      component-test-key: value
    limits:
      cpu: "2"
      memory: 4Gi
    maxFailoverCount: 3
    replicas: 1
    requests:
      cpu: 100m
      memory: 100Mi
      storage: 10Gi
  timezone: Asia/Shanghai
  tlsCluster:
    enabled: true
  version: v5.3.0
---
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: cluster-3
  namespace: pingcap-2
spec:
  acrossK8s: true
  annotations:
    cluster-test-key: value
  cluster:
    clusterDomain: cluster.local
    name: cluster-1
    namespace: pingcap
  clusterDomain: cluster.local
  configUpdateStrategy: RollingUpdate
  discovery: {}
  enablePVReclaim: false
  imagePullPolicy: IfNotPresent
  labels:
    cluster-test-key: value
  pd:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: pd
                app.kubernetes.io/instance: cluster-3
            namespaces:
            - pingcap-2
            topologyKey: rack
          weight: 50
    annotations:
      component-test-key: value
    baseImage: pingcap/pd
    config: |
      [log]
        level = "info"

      [schedule]
        max-store-down-time = "5m"
    labels:
      component-test-key: value
    limits:
      cpu: "1"
      memory: 2Gi
    maxFailoverCount: 3
    replicas: 1
    requests:
      cpu: 100m
      memory: 100Mi
      storage: 1Gi
  pvReclaimPolicy: Delete
  schedulerName: tidb-scheduler
  ticdc:
    baseImage: pingcap/ticdc
    config: ""
    replicas: 1
  tidb:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: tidb
                app.kubernetes.io/instance: cluster-3
            namespaces:
            - pingcap-2
            topologyKey: rack
          weight: 50
    annotations:
      component-test-key: value
    baseImage: pingcap/tidb
    config: |
      [log]
        level = "info"
        [log.file]
          max-backups = 3
    labels:
      component-test-key: value
    limits:
      cpu: "2"
      memory: 4Gi
    maxFailoverCount: 3
    replicas: 1
    requests:
      cpu: 100m
      memory: 100Mi
      storage: 10Gi
    separateSlowLog: true
    service:
      annotations:
        component-test-key: value
      exposeStatus: true
      labels:
        component-test-key: value
      type: ClusterIP
    tlsClient:
      enabled: true
  tikv:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: tikv
                app.kubernetes.io/instance: cluster-3
            namespaces:
            - pingcap-2
            topologyKey: rack
          weight: 50
    annotations:
      component-test-key: value
    baseImage: pingcap/tikv
    config: |
      log-level = "info"

      [storage]
        reserve-space = "0MB"
    evictLeaderTimeout: 1m
    labels:
      component-test-key: value
    limits:
      cpu: "2"
      memory: 4Gi
    maxFailoverCount: 3
    replicas: 1
    requests:
      cpu: 100m
      memory: 100Mi
      storage: 10Gi
  timezone: Asia/Shanghai
  tlsCluster:
    enabled: true
  version: v5.3.0
EOF

    kubectl apply -f ${REPRO_DIR}/tidb-clusters.yaml
}

function Main(){
    REPRO_DIR=${PWD}/repro
    mkdir -p ${REPRO_DIR}

    install_kind
    install_dependencies
    install_issuer

    clusters=(cluster-1 cluster-2 cluster-3)
    namespaces=(pingcap pingcap-1 pingcap-2)
    idx=(0 1 2)
    for i in ${idx[@]}
    do install_tls_certs ${clusters[i]} ${namespaces[i]}
    done

    install_tidbclusters
    echo "waiting for tidbclusters to be ready"
    kubectl wait --for=condition=Ready=true --all-namespaces --all tidbclusters.pingcap.com --timeout=600s

    echo "fail pd in namespace: pingcap by setting an inexist image"
    kubectl patch tc cluster-1 -p '{"spec":{"pd":{"baseImage":"pingcap/inexist"}}}' -n pingcap --type=merge
    kubectl wait --for=condition=Ready=false -n pingcap pod/cluster-1-pd-0 --timeout=120s

    echo "restart ticdc pod"
    kubectl delete po -n pingcap cluster-1-ticdc-0
}

Main

function Cleanup(){
    kind delete clusters reproduce-ticdc
    rm -rf ${PWD}/repro
}
# Cleanup
```
3. check the status and logs of ticdc pod via `kubectl  logs cluster-1-ticdc-0 -npingcap`

### What did you expect to see?

ticdc restart successfully.

### What did you see instead?

ticdc failed to start, pod is in crashloopbackoff.

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
v5.3.0
```

Upstream TiKV version (execute `tikv-server --version`):

```console
v5.3.0
```

TiCDC version (execute `cdc version`):

IMO, other versions including master will have this problem too.

```console
v5.3.0
```

### PR DESCRIPTION
**Pull request by just1900**
### What problem does this PR solve?

Issue Number: close #4777

#### Changed:

remove the `grpcTLSOption` in etcd client config, 

#### how it works:

https://github.com/etcd-io/etcd/pull/11184 have provide an workaround to set authority to deal with the problem indicated in https://github.com/etcd-io/etcd/issues/11180, what it does it to create an [TransportCredentialsWithDialer interface](https://github.com/etcd-io/etcd/blob/d19fbe541bf9c81e2d69d71d1068bd40c04de200/clientv3/client.go#L661) which wraps the original `grpccredentials.TransportCredentials`. and its implementation [here](https://github.com/etcd-io/etcd/blob/d19fbe541bf9c81e2d69d71d1068bd40c04de200/clientv3/credentials/credentials.go#L77), this `TransportCredentialsWithDialer` will set authority to the corresponding enpoint at `ClientHandshake` [period](https://github.com/etcd-io/etcd/blob/d19fbe541bf9c81e2d69d71d1068bd40c04de200/clientv3/credentials/credentials.go#L92) first, and then delegate other logic to original `TransportCredentials`, so as to ensure the authority is correct.
But if we set `grpcTLSOption` in dialOptions, this will overwrite the existing `TransportCredentialsWithDialer` with original grpc `TransportCredentials`.
https://github.com/pingcap/tiflow/blob/20626babf21fc381d4364646c40dd84598533d66/pkg/security/credential.go#L52-L57

This PR will remove the the `grpcTLSOption` in etcd client config, thus won't overwrite the existing `TransportCredentialsWithDialer`.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
fix the issue that ticdc failed to start when connects to  multiple pd endpoints with tls-enabled and the 1st endpoint is not available
```

### CODE REVIEW

**Comment by sdojjy** [comment]
@just1900 check-issue-triage-complete task is failed, can you fix it?

**Comment by just1900** [comment]
How should I fix this?

**Comment by sdojjy** [comment]
@just1900 seems that workaround is remove by https://github.com/etcd-io/etcd/pull/11574,  do we still need this PR?

**Comment by just1900** [comment]
> @just1900 seems that workaround is removed by [etcd-io/etcd#11574](https://github.com/etcd-io/etcd/pull/11574), do we still need this PR?

I notice that too, I'm not sure whether upgrading etcd will help fix current problem, it's worth a try. But IMHO, as long as we set the `grpcTLSOption`, we will overwrite that transport, thus the problem exists.
BTW, I'm afraid upgrading etcd to v3.5 is not an easy work :P

**Comment by sdojjy** [comment]
> How could I fix this?
you can ref this doc
https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/cherrypick-a-pr.html#pass-triage-complete-check

**Comment by sdojjy** [comment]
> > @just1900 seems that workaround is removed by [etcd-io/etcd#11574](https://github.com/etcd-io/etcd/pull/11574), do we still need this PR?
> 
> I notice that too, I'm not sure whether upgrading etcd will help fix current problem, it's worth a try. But IMHO, as long as we set the `grpcTLSOption`, we will overwrite that transport, thus the problem exists. BTW, I'm afraid upgrading etcd to v3.5 is not an easy work :P

release-6.0 already upgraded to v3.5, so merge this pr to 5.4

**Review by sdojjy — APPROVED** [review]
LGTM

**Review by overvenus — APPROVED** [review]

**Comment by VelocityLight** [comment]
close #4777

**Pull request merged**
