### PR TITLE
kafka(ticdc): fix kafka dml sink report error to sink manager (#9879)

### PR DESCRIPTION
**Pull request by hicqu**
### What problem does this PR solve?

Issue Number: ref #9855

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Comment by hicqu** [comment]
It has already been merged into release-7.1: https://github.com/pingcap/tiflow/pull/9879.
And here is the cherry picking to release-6.5: https://github.com/pingcap/tiflow/pull/9880.

**Review by 3AceShowHand — APPROVED** [review]

**Review by sdojjy — APPROVED** [review]

**Comment by hicqu** [comment]
It has been picked into release-6.5 in #9880 . Seems #11942 is duplicated.

**Pull request merged**
