### PR TITLE
lint(dm):fix all lint errors in dm module

### PR DESCRIPTION
**Pull request by liumengya94**
### What problem does this PR solve?

Issue Number: ref #7271 

### What is changed and how it works?

Fix all errors under dm module, with `golangci-lint v1.50.0`

#### Tests 

Bump the golang-lint-ci to 1.50.0 and make check for dm.

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Comment by okJiang** [comment]
just a question. How will you pass the verify test?

**Review by D3Hunter — APPROVED** [review]

**Pull request merged**
