### PR TITLE
pulsar/logger: ensure the .With*() fields are logged

### LINKED ISSUE #10604: TiCDC Pulsar Logger dropped all fields
### What did you do?

The [Pulsar Logger](https://github.com/pingcap/tiflow/blob/4903628a2d575448c3d3fad4bf973edfc1cf9537/pkg/sink/pulsar/logger.go) implemented in #9674 simply recorded all fields in `.With{Field,Fields,Error}`, but they are never emitted from `.{Debug,Info,Warn,Error}{,f}`, causing them to lose contextual info in the final log.

### What did you expect to see?

-

### What did you see instead?

-

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
v7.5.0
```

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve?

Issue Number: close #10604

### What is changed and how it works?

Just make `Logger` and `Entry` use the same structure.

#### Tests 

 - Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]

**Comment by kennytm** [comment]
needs a severity label for #10604 :sweat_smile:

**Pull request merged**
