### PR TITLE
dm(validator): hide source flags

### LINKED ISSUE #4426: dm: continuous validation
### Is your feature request related to a problem?

no

### Describe the feature you'd like

support continuous data validation during sync.

subtasks
- [ ] add pre-check for validation
- [ ] fast validation mode
  - [ ] validation stage observation
  - [ ] checkpoint
  - [ ] save pending/error data into dm_meta
- [ ] full validation mode
- [ ] dmctl commands for validation
- [ ] prometheus monitoring metric for validation, grafana dashboard and alerting

### Describe alternatives you've considered

_No response_

### Teachability, Documentation, Adoption, Migration Strategy

_No response_

### PR DESCRIPTION
**Pull request by buchuitoudegou**
### What problem does this PR solve?

Issue Number: ref #4426 

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by lance6716 — COMMENTED** [review]
--source is added as a flag in `NewRootCmd`, and other commands like `query-status` write `[-s source ...]` in the help message. We can keep in for validator

**Comment by buchuitoudegou** [comment]
> --source is added as a flag in `NewRootCmd`, and other commands like `query-status` write `[-s source ...]` in the help message. We can keep in for validator

we don't want users to use this flags when trying to enabling the validator. 

FYI: https://github.com/pingcap/docs-cn/pull/10465#discussion_r919963410

**Review by lance6716 — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]

**Pull request merged**
