### PR TITLE
dm-worker: use run ctx instead global ctx to fix double write

### LINKED ISSUE #7658: DM data inconsistency after dm worker down
### What did you do?

1. Deploy DM cluster with 3 dm worker
2. Create dm tasks
3. Run sysbench workload for 5 min
4. Kill the dm-worker
5. Wait dm task synced to downstream
6. Compare data consistency between upstream/downstream

### What did you expect to see?

Data should be consistent

### What did you see instead?

Data inconsistency seen

```
Comparing the table structure of ``dm_tolerance_worker_down`.`sbtest2`` ... equivalent
Comparing the table structure of ``dm_tolerance_worker_down`.`sbtest3`` ... equivalent
Comparing the table structure of ``dm_tolerance_worker_down`.`sbtest4`` ... equivalent
Comparing the table structure of ``dm_tolerance_worker_down`.`sbtest1`` ... equivalent
Comparing the table data of ``dm_tolerance_worker_down`.`sbtest2`` ... failure
Comparing the table data of ``dm_tolerance_worker_down`.`sbtest3`` ... failure
Comparing the table data of ``dm_tolerance_worker_down`.`sbtest1`` ... failure
Comparing the table data of ``dm_tolerance_worker_down`.`sbtest4`` ... failure
_____________________________________________________________________________
Progress [============================================================>] 100% 0/0
The data of `dm_tolerance_worker_down`.`sbtest4` is not equal
The data of `dm_tolerance_worker_down`.`sbtest3` is not equal
The data of `dm_tolerance_worker_down`.`sbtest2` is not equal
The data of `dm_tolerance_worker_down`.`sbtest1` is not equal

```

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
/ # /dm-master -V                                                      
Release Version: v6.5.0-alpha                                          
Git Commit Hash: 9d60d064ef5e681867a60c95cdb2b99c10c0c67c              
Git Branch: heads/refs/tags/v6.5.0-alpha                               
UTC Build Time: 2022-11-18 11:06:46                                    
Go Version: go version go1.19.2 linux/amd64                            
Failpoint Build: false                                                 
                                                                       
/ # /dm-worker -V                                                      
Release Version: v6.5.0-alpha                                          
Git Commit Hash: 9d60d064ef5e681867a60c95cdb2b99c10c0c67c              
Git Branch: heads/refs/tags/v6.5.0-alpha                               
UTC Build Time: 2022-11-18 11:06:46                                    
Go Version: go version go1.19.2 linux/amd64                            
Failpoint Build: false                                                 
/ # ./dmctl -V                                             
Release Version: v6.5.0-alpha                              
Git Commit Hash: 9d60d064ef5e681867a60c95cdb2b99c10c0c67c  
Git Branch: heads/refs/tags/v6.5.0-alpha                   
UTC Build Time: 2022-11-18 11:06:46                        
Go Version: go version go1.19.2 linux/amd64                
Failpoint Build: false                                     
```

Upstream MySQL/MariaDB server version:
```console
mysql> select version();
+------------+
| version()  |
+------------+
| 5.7.36-log |
+------------+
1 row in set (0.00 sec)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
mysql> select tidb_version();
| tidb_version()
                                                    
| Release Version: v6.5.0-alpha
Edition: Community
Git Commit Hash: 3bcd5a889bded9ab23e7d077ea5c69df7982a495
Git Branch: heads/refs/tags/v6.5.0-alpha
UTC Build Time: 2022-11-19 11:13:51
GoVersion: go1.19.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |
```
How did you deploy DM: tiup or manually?
```console
ti-operator
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
/ # ./dmctl --master-addr=127.0.0.1:8261 query-status -s source-0                            
{                                                                                            
    "result": true,                                                                          
    "msg": "",                                                                               
    "sources": [                                                                             
        {                                                                                    
            "result": true,                                                                  
            "msg": "",                                                                       
            "sourceStatus": {                                                                
                "source": "source-0",                                                        
                "worker": "dm-dm-worker-1",                                                  
                "result": null,                                                              
                "relayStatus": null                                                          
            },                                                                               
            "subTaskStatus": [                                                               
                {                                                                            
                    "name": "test",                                                          
                    "stage": "Running",                                                      
                    "unit": "Sync",                                                          
                    "result": null,                                                          
                    "unresolvedDDLLockID": "",                                               
                    "sync": {                                                                
                        "totalEvents": "3080479",                                            
                        "totalTps": "221",                                                   
                        "recentTps": "0",                                                    
                        "masterBinlog": "(mysql-bin.000002, 407120738)",                     
                        "masterBinlogGtid": "adade2e6-693e-11ed-a584-e65bc66ff355:1-835280", 
                        "syncerBinlog": "(mysql-bin.000002, 407120738)",                     
                        "syncerBinlogGtid": "adade2e6-693e-11ed-a584-e65bc66ff355:1-835280", 
                        "blockingDDLs": [                                                    
                        ],                                                                   
                        "unresolvedGroups": [                                                
                        ],                                                                   
                        "synced": true,                                                      
                        "binlogType": "remote",                                              
                        "secondsBehindMaster": "0",                                          
                        "blockDDLOwner": "",                                                 
                        "conflictMsg": "",                                                   
                        "totalRows": "3080479",                                              
                        "totalRps": "221",                                                   
                        "recentRps": "0"                                                     
                    },                                                                       
                    "validation": null                                                       
                }                                                                            
            ]                                                                                
        }                                                                                    
    ]                                                                                        
}                                                                                            
```

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: close #7658 
### What is changed and how it works?
- use runCtx running job
- use kaCtx for keepalive

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by buchuitoudegou — APPROVED** [review]

**Comment by fubinzh** [comment]
label needs-cherry-pick-release-6.1

**Pull request merged**
