### PR TITLE
tracker(dm): use TiDB's mock session context to avoid panic

### LINKED ISSUE #6774: new schema tracker panic
### What did you do?

```
2022-08-16T19:15:51.245580291Z stderr F panic: time: missing Location in call to Date
2022-08-16T19:15:51.245635394Z stderr F 
2022-08-16T19:15:51.245640994Z stderr F goroutine 2138 [running]:
2022-08-16T19:15:51.245644194Z stderr F time.Date(0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
2022-08-16T19:15:51.245647195Z stderr F 	time/time.go:1404 +0x4e5
2022-08-16T19:15:51.245650595Z stderr F github.com/pingcap/tidb/types.CoreTime.GoTime(0x1f418d6b8f000001, 0x0?)
2022-08-16T19:15:51.245661395Z stderr F 	github.com/pingcap/tidb@v1.1.0-beta.0.20220809031647-1436ab9e7b4d/types/core_time.go:174 +0xe9
2022-08-16T19:15:51.245664695Z stderr F github.com/pingcap/tidb/types.(*Time).ConvertTimeZone(0xc001f915c0, 0x0?, 0x5ad60a0)
2022-08-16T19:15:51.245667596Z stderr F 	github.com/pingcap/tidb@v1.1.0-beta.0.20220809031647-1436ab9e7b4d/types/time.go:364 +0x5b
2022-08-16T19:15:51.245670496Z stderr F github.com/pingcap/tidb/types.checkTimestampType(0xc001459200, 0x1f418d6b8f000001)
2022-08-16T19:15:51.245673396Z stderr F 	github.com/pingcap/tidb@v1.1.0-beta.0.20220809031647-1436ab9e7b4d/types/time.go:2150 +0xa5
2022-08-16T19:15:51.245676396Z stderr F github.com/pingcap/tidb/types.Time.check({0xc001459200?}, 0xc0017146a8?)
2022-08-16T19:15:51.245679196Z stderr F 	github.com/pingcap/tidb@v1.1.0-beta.0.20220809031647-1436ab9e7b4d/types/time.go:679 +0x7b
2022-08-16T19:15:51.245688497Z stderr F github.com/pingcap/tidb/types.parseTime(0x0?, {0xc0017146a8, 0x13}, 0x7, 0x2f?, 0x2f?)
2022-08-16T19:15:51.245691697Z stderr F 	github.com/pingcap/tidb@v1.1.0-beta.0.20220809031647-1436ab9e7b4d/types/time.go:1986 +0x1cc
2022-08-16T19:15:51.245694797Z stderr F github.com/pingcap/tidb/types.ParseTime(...)
2022-08-16T19:15:51.245697697Z stderr F 	github.com/pingcap/tidb@v1.1.0-beta.0.20220809031647-1436ab9e7b4d/types/time.go:1962
2022-08-16T19:15:51.245701097Z stderr F github.com/pingcap/tidb/expression.GetTimeValue({0x3a4f4d8, 0xc001602200}, {0x3252580?, 0xc0015a0ea0?}, 0x0?, 0xc001f91938?)
2022-08-16T19:15:51.245704298Z stderr F 	github.com/pingcap/tidb@v1.1.0-beta.0.20220809031647-1436ab9e7b4d/expression/helper.go:109 +0x650
2022-08-16T19:15:51.245707498Z stderr F github.com/pingcap/tidb/ddl.getDefaultValue({0x3a4f4d8, 0xc001602200}, 0xc001f81740, 0xc001f91af8?)
2022-08-16T19:15:51.245710398Z stderr F 	github.com/pingcap/tidb@v1.1.0-beta.0.20220809031647-1436ab9e7b4d/ddl/ddl_api.go:1186 +0x151
2022-08-16T19:15:51.245713298Z stderr F github.com/pingcap/tidb/ddl.SetDefaultValue({0x3a4f4d8, 0xc001602200}, 0xc001f81740, 0xc0001d61b0?)
2022-08-16T19:15:51.245716198Z stderr F 	github.com/pingcap/tidb@v1.1.0-beta.0.20220809031647-1436ab9e7b4d/ddl/ddl_api.go:4120 +0x2c
2022-08-16T19:15:51.245719098Z stderr F github.com/pingcap/tidb/ddl.columnDefToCol({0x3a4f4d8, 0xc001602200}, 0xb, 0xc000bff3b0, 0x4?)
2022-08-16T19:15:51.245721999Z stderr F 	github.com/pingcap/tidb@v1.1.0-beta.0.20220809031647-1436ab9e7b4d/ddl/ddl_api.go:1080 +0x72e
2022-08-16T19:15:51.245725299Z stderr F github.com/pingcap/tidb/ddl.buildColumnAndConstraint({0x3a4f4d8, 0xc001602200}, 0xc0018f8740?, 0xc000bff3b0, 0x0?, {0x3263949, 0x4}, {0x32731c1, 0x8})
2022-08-16T19:15:51.245728999Z stderr F 	github.com/pingcap/tidb@v1.1.0-beta.0.20220809031647-1436ab9e7b4d/ddl/ddl_api.go:877 +0x271
2022-08-16T19:15:51.245731999Z stderr F github.com/pingcap/tidb/ddl.buildColumnsAndConstraints({0x3a4f4d8, 0xc001602200}, {0xc0018fd500, 0x12, 0x3a00a01?}, {0xc0015b4ed8, 0x1, 0x1}, {0x3263949, 0x4}, ...)
2022-08-16T19:15:51.245734899Z stderr F 	github.com/pingcap/tidb@v1.1.0-beta.0.20220809031647-1436ab9e7b4d/ddl/ddl_api.go:721 +0x20e
2022-08-16T19:15:51.245738699Z stderr F github.com/pingcap/tidb/ddl.BuildTableInfoWithStmt({0x3a4f4d8, 0xc001602200}, 0xc001635ee0, {0x32703b5, 0x7}, {0x327d2ea, 0xb}, 0x0)
2022-08-16T19:15:51.245752Z stderr F 	github.com/pingcap/tidb@v1.1.0-beta.0.20220809031647-1436ab9e7b4d/ddl/ddl_api.go:2165 +0x1da
2022-08-16T19:15:51.2457558Z stderr F github.com/pingcap/tidb/ddl/schematracker.SchemaTracker.CreateTable({0xc001635ee0?}, {0x3a4f4d8, 0xc001602200}, 0xc001635ee0)
2022-08-16T19:15:51.245758901Z stderr F 	github.com/pingcap/tidb@v1.1.0-beta.0.20220809031647-1436ab9e7b4d/ddl/schematracker/dm_tracker.go:198 +0x22b
2022-08-16T19:15:51.245762101Z stderr F github.com/pingcap/tiflow/dm/pkg/schema.(*Tracker).Exec(0xc0014ebef0, {0x39ef748, 0xc001462800}, {0xc001efe7de, 0xe}, {0x3a05ad8, 0xc001635ee0?})
2022-08-16T19:15:51.245765001Z stderr F 	github.com/pingcap/tiflow/dm/pkg/schema/tracker.go:165 +0x1d8
2022-08-16T19:15:51.245772301Z stderr F github.com/pingcap/tiflow/dm/syncer.(*Syncer).loadTableStructureFromDump(0xc0014bed80, {0x39ef748, 0xc001462800})
2022-08-16T19:15:51.245775601Z stderr F 	github.com/pingcap/tiflow/dm/syncer/syncer.go:3018 +0x16bb
2022-08-16T19:15:51.245778502Z stderr F github.com/pingcap/tiflow/dm/syncer.(*Syncer).Run(0xc0014bed80, {0x39ef748?, 0xc001462800?})
2022-08-16T19:15:51.245781402Z stderr F 	github.com/pingcap/tiflow/dm/syncer/syncer.go:1736 +0xcd7
2022-08-16T19:15:51.245784302Z stderr F github.com/pingcap/tiflow/dm/syncer.(*Syncer).Process(0xc0014bed80, {0x39ef748, 0xc001462700}, 0xc000b657b8?)
2022-08-16T19:15:51.245787302Z stderr F 	github.com/pingcap/tiflow/dm/syncer/syncer.go:723 +0x32a
2022-08-16T19:15:51.245790302Z stderr F created by github.com/pingcap/tiflow/dm/worker.(*SubTask).run
2022-08-16T19:15:51.245811103Z stderr F 	github.com/pingcap/tiflow/dm/worker/subtask.go:260 +0x56c
```

in any Chaos CI of GitHub actions, like https://github.com/pingcap/tiflow/actions/runs/2870425940

### What did you expect to see?

_No response_

### What did you see instead?

_No response_

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
(paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close #6774 

### What is changed and how it works?

as title

#### Tests 

 - Unit test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
checking chaos CI

https://github.com/pingcap/tiflow/actions/runs/2872469144

**Comment by lance6716** [comment]
https://github.com/pingcap/tiflow/actions/runs/2872469144 CI becomes normal

/cc @GMHDBJD

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
/hold

will add a `recover`

**Comment by lance6716** [comment]
ping @D3Hunter @buchuitoudegou

**Review by D3Hunter — APPROVED** [review]

**Pull request merged**
