### PR TITLE
chaos(engine): fix chaos test fail

### LINKED ISSUE #6567: Chaos test in github action fail after replacing the business metastore with mysql
### What did you do?

1. replace the business metastore with mysql
2. check if github action of tiflow chaos tests work well

### What did you expect to see?

chaos tests run ok

### What did you see instead?

chaos tests are failed

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

```console
master
```

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve?

Issue Number: close #6567 

### What is changed and how it works?
Use mysql as business metastore 

```release-note
`None`.
```

### CODE REVIEW

**Comment by maxshuang** [comment]
https://github.com/maxshuang/ticdc/runs/7625931795?check_suite_focus=true
Chaos tests have passed in my own repo.

**Review by amyangfei — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Pull request merged**
