### PR TITLE
sinkv2(ticdc): make sure do not update checkpoint ts when sink is stopping

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/7274

### What is changed and how it works?
Make sure we do not update checkpoints ts when the sink is stopping. Make sure to freeze the tracker before closing.

#### Tests 

 - Unit test

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
Fix an issue where the Sink component may advance checkpoint ts incorrectly
```

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
Self check

**Review by hicqu — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]

**Review by nongfushanquan — APPROVED** [review]

**Pull request merged**
