### PR TITLE
config(ticdc): use 1 minute kv retry time

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Use 1 minute for kv retry time to ensure ScanRegion successfully
even if there are some region has no leader for a long time.

Issue Number: close #5230 

### What is changed and how it works?

Use a large default timeout.

#### Tests 

 - Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by CharlesCheung96 — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]

**Comment by overvenus** [comment]
@ti-chi-bot

**Pull request merged**
