### PR TITLE
test(dm): fix syncer runs slowly so using not latest relay log

### LINKED ISSUE #3400: `pause-relay` fail to get expected result
### Which jobs are flaking?

DM-IT

### Which test(s) are flaking?

dmctl_basic

### Jenkins logs or GitHub Actions link

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/449/pipeline/133/

### REASON:

we call `start-relay` when `pause-relay` in around 18:07:00, that's too adjacent so when DM-worker enable relay, it will directly see a "paused" relay stage in etcd. 

https://github.com/pingcap/ticdc/blob/2569abaa3e64bc930b5cab18a0d6edaae2a41ef0/dm/dm/worker/source_worker.go#L340-L345

It's not a "running" relay stage in etcd, DM-worker will not start relay and keep relay in a "New" stage. As we are expecting DM-worker start-then-pause relay which should be a "paused" relay stage, so the declarative check of `pause-relay` is failed.

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close #3400

### What is changed and how it works?

wait syncer switched to latest relay log

#### Tests 

 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
PTAL @GMHDBJD @buchuitoudegou

**Review by buchuitoudegou — APPROVED** [review]

**Review by lichunzhu — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
included in https://github.com/pingcap/tiflow/pull/6578

**Pull request closed without merging**
