### PR TITLE
fake(engine): add cached checkpoint in job master

### LINKED ISSUE #6598: node failure test is not stable
### What did you do?

find unstable test in: https://github.com/pingcap/tiflow/runs/7648725349?check_suite_focus=true

detail logs:
[node-failure-workflow-logs.zip](https://github.com/pingcap/tiflow/files/9250535/node-failure-workflow-logs.zip)
 

### What did you expect to see?

_No response_

### What did you see instead?

Observe worker with business-id = 0

```go
➜  ag "createworker called"|grep -i "businessid=0"
3m3e-server-executor-0.log:896:[2022/08/03 09:38:43.852 +00:00] [INFO] [fake_master.go:209] ["CreateWorker called"] [BusinessID=0] [worker-id=55fff198-df10-4274-b2fc-e2849f3fe462]
3m3e-server-executor-0.log:1883:[2022/08/03 09:39:31.256 +00:00] [INFO] [fake_master.go:209] ["CreateWorker called"] [BusinessID=0] [worker-id=123995fc-290b-46dd-a420-74218af5a9e7]
3m3e-server-executor-0.log:3285:[2022/08/03 09:39:55.202 +00:00] [INFO] [fake_master.go:209] ["CreateWorker called"] [BusinessID=0] [worker-id=92e7c89f-2a59-47a1-aacf-b8f1dfb6de41]
3m3e-server-executor-2.log:133:[2022/08/03 09:37:41.414 +00:00] [INFO] [fake_master.go:209] ["CreateWorker called"] [BusinessID=0] [worker-id=dca7ef32-bf90-4b87-b86a-ef5933fa45fb]
3m3e-server-executor-2.log:13556:[2022/08/03 09:40:29.056 +00:00] [INFO] [fake_master.go:209] ["CreateWorker called"] [BusinessID=0] [worker-id=06066c7e-233a-470b-ad0f-55e7b3335b21]

➜  ag 92e7c89f-2a59-47a1-aacf-b8f1dfb6de41|grep -i dispatch

➜  ag 123995fc-290b-46dd-a420-74218af5a9e7|grep -i dispatch
3m3e-server-executor-0.log:1899:[2022/08/03 09:39:31.281 +00:00] [INFO] [master.go:651] ["Dispatch Worker succeeded"] [job_id=969aa230-65f4-4e1b-b855-f7484d28050e] [args="{\"ProjectInfo\":{},\"WorkerID\":\"123995fc-290b-46dd-a420-74218af5a9e7\",\"MasterID\":\"969aa230-65f4-4e1b-b855-f7484d28050e\",\"WorkerType\":7,\"WorkerConfig\":\"eyJpZCI6MCwidGFyZ2V0LXRpY2siOjEwMDAwMDAwLCJldGNkLXdhdGNoLWVuYWJsZSI6dHJ1ZSwiZXRjZC1lbmRwb2ludHMiOlsiZXRjZC1zdGFuZGFsb25lOjIzNzkiXSwiZXRjZC13YXRjaC1wcmVmaXgiOiIvZmFrZS1qb2IvdGVzdC8iLCJpbmplY3QtZXJyb3ItaW50ZXJ2YWwiOjAsImNoZWNrcG9pbnQiOnsidGljayI6NTY1LCJyZXZpc2lvbiI6MzgsIm12Y2MtY291bnQiOjQsInZhbHVlIjoicmVzdGFydC1zZXJ2ZXItbWFzdGVyLXZhbHVlLTIifX0=\"}"]

➜  ag 06066c7e-233a-470b-ad0f-55e7b3335b21|grep -i dispatch
3m3e-server-executor-2.log:13594:[2022/08/03 09:40:29.069 +00:00] [INFO] [master.go:651] ["Dispatch Worker succeeded"] [job_id=969aa230-65f4-4e1b-b855-f7484d28050e] [args="{\"ProjectInfo\":{},\"WorkerID\":\"06066c7e-233a-470b-ad0f-55e7b3335b21\",\"MasterID\":\"969aa230-65f4-4e1b-b855-f7484d28050e\",\"WorkerType\":7,\"WorkerConfig\":\"eyJpZCI6MCwidGFyZ2V0LXRpY2siOjEwMDAwMDAwLCJldGNkLXdhdGNoLWVuYWJsZSI6dHJ1ZSwiZXRjZC1lbmRwb2ludHMiOlsiZXRjZC1zdGFuZGFsb25lOjIzNzkiXSwiZXRjZC13YXRjaC1wcmVmaXgiOiIvZmFrZS1qb2IvdGVzdC8iLCJpbmplY3QtZXJyb3ItaW50ZXJ2YWwiOjAsImNoZWNrcG9pbnQiOnsidGljayI6MCwicmV2aXNpb24iOjAsIm12Y2MtY291bnQiOjAsInZhbHVlIjoiIn19\"}"]
```

Correct checkpoint:

```go
3m3e-server-executor-0.log:1899:[2022/08/03 09:39:31.281 +00:00] [INFO] [master.go:651] ["Dispatch Worker succeeded"] [job_id=969aa230-65f4-4e1b-b855-f7484d28050e] [args="{\"ProjectInfo\":{},\"WorkerID\":\"123995fc-290b-46dd-a420-74218af5a9e7\",\"MasterID\":\"969aa230-65f4-4e1b-b855-f7484d28050e\",\"WorkerType\":7,\"WorkerConfig\":\"eyJpZCI6MCwidGFyZ2V0LXRpY2siOjEwMDAwMDAwLCJldGNkLXdhdGNoLWVuYWJsZSI6dHJ1ZSwiZXRjZC1lbmRwb2ludHMiOlsiZXRjZC1zdGFuZGFsb25lOjIzNzkiXSwiZXRjZC13YXRjaC1wcmVmaXgiOiIvZmFrZS1qb2IvdGVzdC8iLCJpbmplY3QtZXJyb3ItaW50ZXJ2YWwiOjAsImNoZWNrcG9pbnQiOnsidGljayI6NTY1LCJyZXZpc2lvbiI6MzgsIm12Y2MtY291bnQiOjQsInZhbHVlIjoicmVzdGFydC1zZXJ2ZXItbWFzdGVyLXZhbHVlLTIifX0=\"}"]

>>> base64.b64decode('eyJpZCI6MCwidGFyZ2V0LXRpY2siOjEwMDAwMDAwLCJldGNkLXdhdGNoLWVuYWJsZSI6dHJ1ZSwiZXRjZC1lbmRwb2ludHMiOlsiZXRjZC1zdGFuZGFsb25lOjIzNzkiXSwiZXRjZC13YXRjaC1wcmVmaXgiOiIvZmFrZS1qb2IvdGVzdC8iLCJpbmplY3QtZXJyb3ItaW50ZXJ2YWwiOjAsImNoZWNrcG9pbnQiOnsidGljayI6NTY1LCJyZXZpc2lvbiI6MzgsIm12Y2MtY291bnQiOjQsInZhbHVlIjoicmVzdGFydC1zZXJ2ZXItbWFzdGVyLXZhbHVlLTIifX0=')
b'{"id":0,"target-tick":10000000,"etcd-watch-enable":true,"etcd-endpoints":["etcd-standalone:2379"],"etcd-watch-prefix":"/fake-job/test/","inject-error-interval":0,"checkpoint":{"tick":565,"revision":38,"mvcc-count":4,"value":"restart-server-master-value-2"}}'
```

- error checkpoint:

```go
3m3e-server-executor-2.log:13594:[2022/08/03 09:40:29.069 +00:00] [INFO] [master.go:651] ["Dispatch Worker succeeded"] [job_id=969aa230-65f4-4e1b-b855-f7484d28050e] [args="{\"ProjectInfo\":{},\"WorkerID\":\"06066c7e-233a-470b-ad0f-55e7b3335b21\",\"MasterID\":\"969aa230-65f4-4e1b-b855-f7484d28050e\",\"WorkerType\":7,\"WorkerConfig\":\"eyJpZCI6MCwidGFyZ2V0LXRpY2siOjEwMDAwMDAwLCJldGNkLXdhdGNoLWVuYWJsZSI6dHJ1ZSwiZXRjZC1lbmRwb2ludHMiOlsiZXRjZC1zdGFuZGFsb25lOjIzNzkiXSwiZXRjZC13YXRjaC1wcmVmaXgiOiIvZmFrZS1qb2IvdGVzdC8iLCJpbmplY3QtZXJyb3ItaW50ZXJ2YWwiOjAsImNoZWNrcG9pbnQiOnsidGljayI6MCwicmV2aXNpb24iOjAsIm12Y2MtY291bnQiOjAsInZhbHVlIjoiIn19\"}"]

>>> base64.b64decode('eyJpZCI6MCwidGFyZ2V0LXRpY2siOjEwMDAwMDAwLCJldGNkLXdhdGNoLWVuYWJsZSI6dHJ1ZSwiZXRjZC1lbmRwb2ludHMiOlsiZXRjZC1zdGFuZGFsb25lOjIzNzkiXSwiZXRjZC13YXRjaC1wcmVmaXgiOiIvZmFrZS1qb2IvdGVzdC8iLCJpbmplY3QtZXJyb3ItaW50ZXJ2YWwiOjAsImNoZWNrcG9pbnQiOnsidGljayI6MCwicmV2aXNpb24iOjAsIm12Y2MtY291bnQiOjAsInZhbHVlIjoiIn19')
b'{"id":0,"target-tick":10000000,"etcd-watch-enable":true,"etcd-endpoints":["etcd-standalone:2379"],"etcd-watch-prefix":"/fake-job/test/","inject-error-interval":0,"checkpoint":{"tick":0,"revision":0,"mvcc-count":0,"value":""}}'
```

That was caused by incorrect persistent

```go
3272:[2022/08/03 09:39:55.054 +00:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=1.945139ms] [sql="INSERT INTO `dfe_proj_default_meta_kvs` (`created_at`,`updated_at`,`meta_key`,`meta_value`,`job_id`) VALUES ('2022-
08-03 09:39:55.053','2022-08-03 09:39:55.053','fake-master/checkpoint/969aa230-65f4-4e1b-b855-f7484d28050e','{\"ticks\":{\"0\":659,\"1\":1040,\"2\":659,\"3\":1038},\"checkpoints\":{\"0\":{\"tick\":0,\"revision\":44,\"mvcc-count\":5,\"valu
e\":\"restart-executor-value-0\"},\"1\":{\"tick\":0,\"revision\":52,\"mvcc-count\":6,\"value\":\"restart-executor-value-1\"},\"2\":{\"tick\":0,\"revision\":46,\"mvcc-count\":5,\"value\":\"restart-executor-value-0\"},\"3\":{\"tick\":0,\"re
vision\":54,\"mvcc-count\":6,\"value\":\"restart-executor-value-1\"}}}','969aa230-65f4-4e1b-b855-f7484d28050e') ON DUPLICATE KEY UPDATE `updated_at`='2022-08-03 09:39:55.053',`meta_key`=VALUES(`meta_key`),`meta_value`=VALUES(`meta_value`)
,`job_id`=VALUES(`job_id`)"] [affected-rows=2]
3292:[2022/08/03 09:39:55.205 +00:00] [DEBUG] [callbacks.go:134] ["trace log"] [component=gorm] [elapsed=1.54191ms] [sql="INSERT INTO `dfe_proj_default_meta_kvs` (`created_at`,`updated_at`,`meta_key`,`meta_value`,`job_id`) VALUES ('2022-0
8-03 09:39:55.204','2022-08-03 09:39:55.204','fake-master/checkpoint/969aa230-65f4-4e1b-b855-f7484d28050e','{\"ticks\":{\"1\":1044,\"3\":1044},\"checkpoints\":{\"1\":{\"tick\":0,\"revision\":52,\"mvcc-count\":6,\"value\":\"restart-executo
r-value-1\"},\"3\":{\"tick\":0,\"revision\":54,\"mvcc-count\":6,\"value\":\"restart-executor-value-1\"}}}','969aa230-65f4-4e1b-b855-f7484d28050e') ON DUPLICATE KEY UPDATE `updated_at`='2022-08-03 09:39:55.204',`meta_key`=VALUES(`meta_key`
),`meta_value`=VALUES(`meta_value`),`job_id`=VALUES(`job_id`)"] [affected-rows=2]
```

```go
[2022/08/03 09:39:55.202 +00:00] [INFO] [fake_master.go:433] ["FakeMaster: OnWorkerOffline"] [worker-id=123995fc-290b-46dd-a420-74218af5a9e7] [error="[DFLOW:ErrWorkerOffline]worker is offline: workerID: 123995fc-290b-46dd-a420-74218af5a9e7, error message: %!s(MISSING)"]
[2022/08/03 09:39:55.202 +00:00] [INFO] [master.go:577] [CreateWorker] [job_id=969aa230-65f4-4e1b-b855-f7484d28050e] [worker-type=7] [worker-config="{\"id\":0,\"target-tick\":10000000,\"etcd-watch-enable\":true,\"etcd-endpoints\":[\"etcd-standalone:2379\"],\"etcd-watch-prefix\":\"/fake-job/test/\",\"inject-error-interval\":0,\"checkpoint\":{\"tick\":659,\"revision\":44,\"mvcc-count\":5,\"value\":\"restart-executor-value-0\"}}"] [cost=1] [resources="[]"] [master-id=969aa230-65f4-4e1b-b855-f7484d28050e]
[2022/08/03 09:39:55.202 +00:00] [INFO] [fake_master.go:209] ["CreateWorker called"] [BusinessID=0] [worker-id=92e7c89f-2a59-47a1-aacf-b8f1dfb6de41]
[2022/08/03 09:39:55.202 +00:00] [INFO] [fake_master.go:433] ["FakeMaster: OnWorkerOffline"] [worker-id=5093dfa3-075a-4824-a389-60a4f5e3653c] [error="[DFLOW:ErrWorkerOffline]worker is offline: workerID: 5093dfa3-075a-4824-a389-60a4f5e3653c, error message: %!s(MISSING)"]
```

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

'56eda9ebb1dd53a67add9f133e13603a3949efce'

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: close #6598

### What is changed and how it works?

Cache checkpoint in job master, if part of workers are offline, keep the old value of them.

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by amyangfei** [comment]
passed chaos test in: https://github.com/pingcap/tiflow/actions/runs/2789584041

**Comment by maxshuang** [comment]
@amyangfei  Could you explain more about this unstable test? I think I don't real get the point.

**Comment by amyangfei** [comment]
> @amyangfei Could you explain more about this unstable test? I think I don't real get the point.

The issue was explained in the original issue.

**Comment by maxshuang** [comment]
https://github.com/pingcap/tiflow/runs/7666668553?check_suite_focus=true
Another case for this issue. 
Seems this case becomes unstable after pr https://github.com/pingcap/tiflow/pull/6436

**Review by maxshuang — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Comment by maxshuang** [comment]
After offline discussion with amyangfei and CharlesCheung96, 
we need to investigate whether the new merged pr causes the behavior that `job is dispatched to an offline executor`.

**Pull request merged**
