### PR TITLE
openapi(dm): change url path from config to templates

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve? 

part of https://github.com/pingcap/ticdc/issues/3583

### What is changed and how it works?

as title , only path and var name changed, no new logic

### Check List 

Tests 

 - Unit test
 - Integration test
 - No code

Code changes

 - Has exported function/method change
 - Has persistent data change

Side effects

Related changes

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by Ehco1996** [comment]
could you please take another look for this pr ? thanks 🧡🧡🧡

**Comment by Ehco1996** [comment]
could you please take another look for this pr ? thanks 🧡🧡🧡

this PR just change the url path / variable from `task configs` to `task templates` , **no new logic**

/cc @GMHDBJD  @lance6716

**Review by lance6716 — APPROVED** [review]

**Comment by Ehco1996** [comment]
ping @GMHDBJD @okJiang  😬😬😬

this PR just change the url path / variable from `task configs` to `task templates` , no new logic

**Review by okJiang — APPROVED** [review]

**Pull request merged**
