### PR TITLE
tests(ticdc): add ddl test for redo

### LINKED ISSUE #8533: Data race `model.(*RedoDDLEvent).MarshalMsg()` with `owner.(*ddlSinkImpl).emitDDLEvent()`
### What did you do?

Run CI.

### What did you expect to see?

No data race

### What did you see instead?

Data race

```
WARNING: DATA RACE
Write at 0x00c004265510 by goroutine 561:
  github.com/pingcap/tiflow/cdc/owner.(*ddlSinkImpl).emitDDLEvent()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/owner/ddl_sink.go:301 +0xf44
  github.com/pingcap/tiflow/cdc/owner.(*changefeed).asyncExecDDLEvent()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/owner/changefeed.go:976 +0x7a8
  github.com/pingcap/tiflow/cdc/owner.(*changefeed).asyncExecDDLJob()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/owner/changefeed.go:941 +0xd09
  github.com/pingcap/tiflow/cdc/owner.(*changefeed).handleBarrier()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/owner/changefeed.go:857 +0xd51
  github.com/pingcap/tiflow/cdc/owner.(*changefeed).tick()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/owner/changefeed.go:317 +0x976
  github.com/pingcap/tiflow/cdc/owner.(*changefeed).Tick()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/owner/changefeed.go:218 +0x392
  github.com/pingcap/tiflow/cdc/owner.(*ownerImpl).Tick()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/owner/owner.go:201 +0xc66
  github.com/pingcap/tiflow/pkg/orchestrator.(*EtcdWorker).Run()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/pkg/orchestrator/etcd_worker.go:290 +0x1b46
  github.com/pingcap/tiflow/cdc/capture.(*captureImpl).runEtcdWorker()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/capture/capture.go:500 +0x309
  github.com/pingcap/tiflow/cdc/capture.(*captureImpl).campaignOwner()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/capture/capture.go:451 +0x146a
  github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run.func3()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/capture/capture.go:317 +0x78
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x82

Previous read at 0x00c004265510 by goroutine 906:
  github.com/pingcap/tiflow/cdc/model.(*RedoDDLEvent).MarshalMsg()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/model/sink_gen.go:730 +0x904
  github.com/pingcap/tiflow/cdc/model.(*RedoLog).MarshalMsg()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/model/sink_gen.go:951 +0x359
  github.com/pingcap/tiflow/cdc/model/codec.MarshalRedoLog()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/model/codec/codec.go:160 +0x1cb
  github.com/pingcap/tiflow/cdc/redo/writer/memory.(*polymorphicRedoEvent).encode()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/redo/writer/memory/encoding_worker.go:73 +0xed
  github.com/pingcap/tiflow/cdc/redo/writer/memory.(*encodingWorkerGroup).runWorker()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/redo/writer/memory/encoding_worker.go:156 +0x216
  github.com/pingcap/tiflow/cdc/redo/writer/memory.(*encodingWorkerGroup).Run.func2()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/redo/writer/memory/encoding_worker.go:135 +0x6f
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x82

Goroutine 561 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0x12e
  github.com/pingcap/tiflow/cdc/capture.(*captureImpl).run()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/capture/capture.go:313 +0x7f1
  github.com/pingcap/tiflow/cdc/capture.(*captureImpl).Run()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/capture/capture.go:270 +0x336
  github.com/pingcap/tiflow/cdc/server.(*server).run.func1()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/server/server.go:313 +0x78
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x82

Goroutine 906 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0x12e
  github.com/pingcap/tiflow/cdc/redo/writer/memory.(*encodingWorkerGroup).Run()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/redo/writer/memory/encoding_worker.go:134 +0x224
  github.com/pingcap/tiflow/cdc/redo/writer/memory.NewLogWriter.func1()
      /home/jenkins/agent/workspace/cdc_ghpr_kafka_integration_test/go/src/github.com/pingcap/tiflow/cdc/redo/writer/memory/mem_log_writer.go:76 +0x7c
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x82
```

### Versions of the cluster

TiCDC version (execute `cdc version`):

https://github.com/pingcap/tiflow/commit/66ffedd6d052498d987eee73562885cb6e94fe0b

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: ref #8056, close #8533

### What is changed and how it works?
1. add ddl integration test for redo
2. remove unused mock_fileReader
3. [fix data race](https://github.com/pingcap/tiflow/pull/8411/commits/de800544944f8b09f96706dba60f96cb35431762)

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Comment by asddongmen** [comment]
/run-integration-test /tiflash=release-6.6 /tikv=release-6.6 
/run-kafka-integration-test /tiflash=release-6.6 /tikv=release-6.6 
/run-dm-integration-test /tiflash=release-6.6 /tikv=release-6.6

**Comment by CharlesCheung96** [comment]
/run-integration-test /tiflash=release-6.6 /tikv=release-6.6
/run-kafka-integration-test /tiflash=release-6.6 /tikv=release-6.6
/run-dm-integration-test /tiflash=release-6.6 /tikv=release-6.6

**Comment by CharlesCheung96** [comment]
/run-engine-integration-test
/run-integration-test /tiflash=release-6.6 /tikv=release-6.6
/run-kafka-integration-test /tiflash=release-6.6 /tikv=release-6.6
/run-dm-integration-test /tiflash=release-6.6 /tikv=release-6.6

**Comment by CharlesCheung96** [comment]
/run-kafka-integration-test /tiflash=release-6.6 /tikv=release-6.6

**Comment by CharlesCheung96** [comment]
/run-kafka-integration-test /tiflash=release-6.6 /tikv=release-6.6
/run-dm-integration-test /tiflash=release-6.6 /tikv=release-6.6

**Comment by CharlesCheung96** [comment]
/run-integration-test /tiflash=release-6.6 /tikv=release-6.6
/run-kafka-integration-test /tiflash=release-6.6 /tikv=release-6.6
/run-dm-integration-test /tiflash=release-6.6 /tikv=release-6.6

**Comment by CharlesCheung96** [comment]
/run-integration-test /tiflash=release-6.6 /tikv=release-6.6
/run-kafka-integration-test /tiflash=release-6.6 /tikv=release-6.6
/run-dm-integration-test /tiflash=release-6.6 /tikv=release-6.6

**Comment by CharlesCheung96** [comment]
/run-dm-integration-test /tiflash=release-6.6 /tikv=release-6.6

**Comment by CharlesCheung96** [comment]
/run-dm-integration-test /tiflash=release-6.6 /tikv=release-6.6
/run-engine-integration-test

**Comment by CharlesCheung96** [comment]
/run-dm-integration-test /tiflash=release-6.6 /tikv=release-6.6

**Comment by CharlesCheung96** [comment]
/run-dm-integration-test /tiflash=release-6.6 /tikv=release-6.6

**Pull request merged**
