### PR TITLE
actions(dm): revert to Ubuntu 18 for dm-ansible

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: ref #6680 

### What is changed and how it works?

don't know why Ubuntu 20 can't run dm-ansible. just revert it

#### Tests 

 - Integration test
   https://github.com/pingcap/tiflow/runs/7851099567?check_suite_focus=true

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
https://github.com/pingcap/tiflow/actions/runs/2865016941

**Comment by lance6716** [comment]
https://github.com/pingcap/tiflow/actions/runs/2865088038

**Comment by lance6716** [comment]
https://github.com/pingcap/tiflow/runs/7851099567?check_suite_focus=true

**Review by buchuitoudegou — APPROVED** [review]

**Pull request merged**
