### PR TITLE
sink(ticdc): fix create storage sink

### LINKED ISSUE #9316: changefeed can be successfully created using an illegal config
Create changefeed with the following config:
```bash
 cdc cli changefeed --server=127.0.0.1:8300 create "--sink-uri=s3://bucket/local-test/?access-key=*****&secret-access-key=123456force-path-style=true&transaction-atomicity=none&protocol=csv" -c test
```

We expect that using an illegal secret access key will cause the creation operation to fail. But we succeeded in creating the changefeed:
```bash
# cdc cli changefeed --server=127.0.0.1:8300 query -c test
{
  "upstream_id": 7238864490429791901,
  "namespace": "default",
  "id": "test",
  "sink_uri": "s3://bucket/local-test/?access-key=******\u0026secret-access-key=123456force-path-style=true\u0026transaction-atomicity=none\u0026protocol=csv",
  "config": {
    "memory_quota": 1073741824,
    "case_sensitive": true,
    "enable_old_value": false,
    "force_replicate": false,
    "ignore_ineligible_table": false,
    "check_gc_safe_point": true,
...
```

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: ref #8772, close #9316

### What is changed and how it works?
1. check connection when create storage

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

**Review by nongfushanquan — COMMENTED** [review]
please use the accurate description for the issue

**Review by asddongmen — APPROVED** [review]

**Review by nongfushanquan — APPROVED** [review]

**Pull request merged**
