### PR TITLE
tests(ticdc): Adding tests to the default dispatcher when old value is enabled

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/4379

### What is changed and how it works?

Adding tests to the default dispatcher when old value is enabled.

### Check List 

Tests 

 - Unit test

Code changes

None

Side effects

None

Related changes

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/cc @asddongmen @zhaoxinyu 

Could you please take a look? Thanks! 💚 💙 💜 💛 ❤️

**Review by 3AceShowHand — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Pull request merged**
