### PR TITLE
dm: handle the query in metadata from binlog

### PR DESCRIPTION
**Pull request by joccau**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/11735

### What is changed and how it works?
Handle the new format of binlog metadata from mariadb to read the binlog position.

#### Tests 

 - [x] Unit test
 - [ ] Integration test
 - [ ] Manual test (add detailed scripts or steps below)
 - [ ] No code

##### Will it cause performance regression or break compatibility?
Not.

##### Do you need to update user documentation, design documentation or monitoring documentation?
Not.

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Comment by lance6716** [comment]
@joccau please sign CLA

**Comment by joccau** [comment]
> @joccau please sign CLA

Done

**Pull request merged**
