### PR TITLE
ddl_puller (ticdc): only create a schemStorage in a changefeed or processor

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve?

Issue Number: ref #8106 

### What is changed and how it works?

Before this PR, `ddlPuller` held an exclusive `schemaSnapshot` that contained the metadata of all tables in the upstream TiDB. `ddlPuller` needed to use the information in this `schemaSnapshot` to process the received DDL events. At the same time, the `owner` or `processor` also held a struct named `schemaStorage`, which contained the same information as `ddlPuller`'s `schemaSnapshot`.

Therefore, by simply allowing `ddlPuller` and `owner` or `processor` to share a `schemaStorage`, the memory consumption of the original `schemaSnapshot` can be reduced.

This pull request removes the exclusive `schemaSnapshot` from `ddlPuller`, which should decrease the amount of memory required to store tableInfo. The hope is that this change will reduce memory consumption for storing table Infos by up to 50%.
Below are the memory usage statistics for TiCDC, both with and without this PR, in a scenario with 100,000 tables.

**Without this PR:**
image

**With this PR:**
image

#### Tests 

 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by asddongmen** [comment]
@purelind  要用这个命令 `/run-kafka-integration-test`

**Review by nongfushanquan — COMMENTED** [review]
could you add some comments  to describe the main idea about how  to reduce the memory consumed

**Comment by asddongmen** [comment]
> could you add some comments to describe the main idea about how to reduce the memory consumed
@nongfushanquan 
Done, it's added in this PR's description. PTAL. Thank you!

**Review by hicqu — APPROVED** [review]

**Review by sdojjy — APPROVED** [review]

**Pull request merged**
