### PR TITLE
cdc: ignore redo log meta regress for restarting

### PR DESCRIPTION
**Pull request by hicqu**
### What problem does this PR solve?

Issue Number: ref #6277 

### What is changed and how it works?

After #6313 is merged, cdc instance can panic if redo meta regresses. It can really happend when a cdc instance restarts.

This PR ignored redo meta regress. 

#### Tests 

 - Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by zhaoxinyu — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Comment by hicqu** [comment]
It's closed as it doesn't fix the problem at root exactly. It's replaced by #6321 .

**Pull request merged**
