### PR TITLE
sinkManager (ticdc): Fix a sorter panic issue caused by uint64 overflow.

### LINKED ISSUE #8664: A panic occurred when a table just started.
### What did you do?

Create a changefeed that replicates 100k tables.

### What did you expect to see?

no panic.

### What did you see instead?

[2023/03/23 14:03:31.697 +08:00] [INFO] [table.go:251] ["schedulerv3: table found new task"] [namespace=default] [changefeed=test] [tableID=119726] [task="{\"Span\":\"{table_id:119726,start_key:74800000000001d3ffae5f720000000000fa,end_key:74800000000001d3ffae5f730000000000fa}\",\"StartTs\":440284295189233707,\"IsRemove\":false,\"IsPrepare\":true,\"Epoch\":{}}"]

[2023/03/23 14:03:32.405 +08:00] [INFO] [processor.go:264] ["Add Table finished"] [captureID=202a3a1f-8cf5-43f4-9515-8e14adf00a55] [namespace=default] [changefeed=test] [span={table_id:119726,start_key:74800000000001d3ffae5f720000000000fa,end_key:74800000000001d3ffae5f730000000000fa}] [tableResolvedTs=440284325296209924] [globalResolvedTs=440284097322680321] [tableCheckpointTs=440284295189233707] [globalCheckpointTs=440284096903249958] [state=Unknown] [isPrepare=false]

[2023/03/23 14:03:32.417 +08:00] [PANIC] [event_sorter.go:223] ["fetch unresolved events"] [namespace=default] [changefeed=test] [span={table_id:119726,start_key:74800000000001d3ffae5f720000000000fa,end_key:74800000000001d3ffae5f730000000000fa}] [upperBound=440284325296209925] [resolved=440284325296209924] [stack="github.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble.(*EventSorter).FetchByTable\n\tgithub.com/pingcap/tiflow/cdc/processor/sourcemanager/engine/pebble/event_sorter.go:223\ngithub.com/pingcap/tiflow/cdc/processor/sourcemanager.(*SourceManager).FetchByTable\n\tgithub.com/pingcap/tiflow/cdc/processor/sourcemanager/manager.go:134\ngithub.com/pingcap/tiflow/cdc/processor/sinkmanager.(*sinkWorker).handleTask\n\tgithub.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_worker.go:141\ngithub.com/pingcap/tiflow/cdc/processor/sinkmanager.(*sinkWorker).handleTasks\n\tgithub.com/pingcap/tiflow/cdc/processor/sinkmanager/table_sink_worker.go:105\ngithub.com/pingcap/tiflow/cdc/processor/sinkmanager.(*SinkManager).startWorkers.func1\n\tgithub.com/pingcap/tiflow/cdc/processor/sinkmanager/manager.go:195"]

### Versions of the cluster

Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

```console
(paste TiDB cluster version here)
```

Upstream TiKV version (execute `tikv-server --version`):

```console
(paste TiKV version here)
```

TiCDC version (execute `cdc version`):

```console
https://github.com/pingcap/tiflow/pull/8633
```

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve?

Issue Number: close #8664 

#### Tests 

 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
Fix a sorter panic issue caused by uint64 overflow.
```

### CODE REVIEW

**Review by sdojjy — APPROVED** [review]

**Comment by CharlesCheung96** [comment]
Please add the description in pr body.

**Review by CharlesCheung96 — APPROVED** [review]

**Pull request merged**
