### PR TITLE
checker(dm): prepare to check on both upstream and downstream table structures

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref #4287

### What is changed and how it works?

the struct `{Schema string, Name string}` is passed to TablesChecker, so it can use downstream table of that struct to fetch table structure

#### Tests 

 - Pass old tests

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
ptal

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Review by lichunzhu — APPROVED** [review]
LGTM

**Pull request merged**
