### PR TITLE
lightning(dm): update dependency for lightning

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: ref #4287 

### What is changed and how it works?

to use https://github.com/pingcap/tidb/pull/39318

#### Tests 

 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
ping @okJiang

**Review by okJiang — APPROVED** [review]

**Pull request merged**
