### PR TITLE
sorter(ticdc): handle resolved ts directly to reduce allocate memory for polymorphic event

### LINKED ISSUE #7234: sorter handle resolved ts event directly.

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #7234

### What is changed and how it works?

* puller send resolved ts to the sorter directly, avoid new the `PolymorphicEvent`, this should reduce memory allocation overhead 

image

As shown the profiling above, the left is master branch, `gcBgMarkWorker` cost around `14.5%`, the PR branch is on the right, `gcBgMarkWorker` cost around `13%`, reduced a little bit.

#### Tests 

 - Unit test
 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by nongfushanquan — COMMENTED** [review]
Please add some comments  to tell the benefits and reason of this pr expected

**Comment by asddongmen** [comment]
Can you add some description onto **What is changed and how it works?**

**Review by asddongmen — APPROVED** [review]

**Pull request closed without merging**
