### PR TITLE
dm(metrics): move dashboard from dm-ansible

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve?

Issue Number: ref #4654

### What is changed and how it works?

move dashboard.json out of dm-ansible dir,  i will adapted the CI after this PR merged

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
where did you delete the old files?

**Comment by Ehco1996** [comment]
> where did you delete the old files?

can not delete now, if so nighly CI will failed

**Review by lance6716 — APPROVED** [review]

**Comment by Ehco1996** [comment]
could you please take another look for this pr ? thanks 🧡🧡🧡 

@hi-rustin

**Pull request merged**
