### PR TITLE
kafka-consumer(ticdc): cherry-pick all changes

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Fix flaking tests.

### What is changed and how it works?
cherry-pick all changes to kafka-consumer to fix  the flaking tests.

### Check List 

Tests 

 - Integration test

Code changes

None

Side effects

None

Related changes

None
### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
> /run-kafka-integration-test

passed +1

**Comment by hi-rustin** [comment]
> /run-kafka-integration-test

passed +1

**Comment by hi-rustin** [comment]
> /run-kafka-integration-test

passed +1

**Comment by hi-rustin** [comment]
> /run-kafka-integration-test

passed +1

**Comment by hi-rustin** [comment]
> /run-kafka-integration-test

passed +1

**Review by liuzix — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]

**Pull request merged**
