### PR TITLE
ticdc/token-region: don't set metric to 0 since multiple tables share it

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve? 

Metrics in token region are shared by multiple tables, so we should not use `set` to a set specific value

### What is changed and how it works?

Use accurate inc or dec instead

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
Fix kv client cached region metric could be negative.
```

### CODE REVIEW

**Comment by maxshuang** [comment]
I test this pr, look good.

**Review by asddongmen — APPROVED** [review]

**Review by ben1009 — APPROVED** [review]

**Comment by overvenus** [comment]
Cc https://github.com/pingcap/tiflow/issues/4300

**Pull request merged**
