### PR TITLE
sink/mysql(ticdc): make mysql sink to handle ipv6 address correctly

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/6135

### What is changed and how it works?
correctly handle the  ipv6 address. Add `[]` for it.

The Hostname() API removes it, but `[]` must be added for it to be the correct dsn.

#### Tests 

 - Unit test
 - Manual test (https://github.com/pingcap/tiflow/pull/6141#issuecomment-1172168960)

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
Fix the problem that TiCDC cannot correctly recognize the ipv6 address in SinkURI
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
Manual test procedure.
1. Make sure my system has ipv6 support
```log
➜  ~ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
	nd6 options=201<PERFORMNUD,DAD>
```
2. Start local mysql and set bind_address=::1
3. Start tidb and ticdc cluster
4. create changefeed with `./cdc cli changefeed create --pd="http://127.0.0.1:2379" --sink-uri="mysql://root@[::1]:3306/" --changefeed-id="simple-replication-task1" --sort-engine="unifaied"  --log-level debug `
```log
Create changefeed successfully!
ID: simple-replication-task1
Info: {"upstream-id":0,"sink-uri":"mysql://root@[::1]:3306/","create-time":"2022-07-01T17:58:50.425004+08:00","start-ts":434285977343885313,"target-ts":0,"admin-job-type":0,"sort-engine":"unified","sort-dir":"","config":{"case-sensitive":true,"enable-old-value":true,"force-replicate":false,"check-gc-safe-point":true,"filter":{"rules":["*.*"],"ignore-txn-start-ts":null},"mounter":{"worker-num":16},"sink":{"dispatchers":null,"protocol":"","column-selectors":null,"schema-registry":""},"consistent":{"level":"none","max-log-size":64,"flush-interval":1000,"storage":""}},"state":"normal","error":null,"sync-point-enabled":false,"sync-point-interval":600000000000,"creator-version":"v6.2.0-master-dirty"}

```

**Review by overvenus — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Comment by hi-rustin** [comment]
More work need.
1. verify that the ipv6 address is passed correctly in sinkuri (with the [] wrapper), giving useful hints
2. add documentation for users to guide them to the correct format

**Comment by hi-rustin** [comment]
> More work need.
> 
>     1. verify that the ipv6 address is passed correctly in sinkuri (with the [] wrapper), giving useful hints
> 
>     2. add documentation for users to guide them to the correct format

I will send another PR for these todos.

Also, I'll try to simplify the mysql sink test code(too much duplicate code)

So let me merge this PR. If you still have some questions, please feel free to `/merge cancel` or `/unhold`.

/MERGE

**Comment by hi-rustin** [comment]
Also , we may need to find a way to reduce the duplication between the `mysql.go` and `mysql_syncpoint_store.go`

**Pull request merged**
