### PR TITLE
sorter(ticdc): fix the issue of using wrong values for writeCount and dataSize

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/3206

### Check List 

Tests 

 - [x] Unit test

Code changes

None

Side effects

None

Related changes

None

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by sdojjy — APPROVED** [review]
LTGM

**Comment by asddongmen** [comment]
please fix the failed test cases.

**Comment by asddongmen** [comment]
LTGM

**Review by asddongmen — APPROVED** [review]

**Pull request merged**
