### PR TITLE
engine: refine the address command line argument name

### LINKED ISSUE #6453: Refine the tiflow master/executor address arguments name
### Is your feature request related to a problem?

```
                        - "/tiflow"
                        - "master"
                        - "--config=/config.toml"
                        - "--log-level=debug"
                        - "--master-addr=0.0.0.0:10240"
                        - "--advertise-addr=server-master:10240"
                        - "--etcd-endpoints=etcd-standalone:2379"
                        - "--frame-meta-endpoints=mysql-standalone:3306"
                        - "--business-meta-endpoints=etcd-standalone:2379"
```

It's weird to use command line: `tiflow master --master-addr` because the meaning of address is obviously so it's better to use `tiflow master --addr xxx`

### Describe the feature you'd like

Remove the duplicated part in the argument name.

### Describe alternatives you've considered

_No response_

### Teachability, Documentation, Adoption, Migration Strategy

_No response_

### PR DESCRIPTION
**Pull request by lonng**
### What problem does this PR solve?

Issue Number: close #6453

### What is changed and how it works?

As issue #6453 described, the address command line argument name is duplicated with the sub-command name. This PR fixes this issue.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
Refine the tiflow command line argument name
```

### CODE REVIEW

**Comment by lonng** [comment]
The `tiflow-operator` should adopt these changes.
cc @lichunzhu

**Comment by lichunzhu** [comment]
> The `tiflow-operator` should adopt these changes. cc @lichunzhu

gotcha

**Comment by amyangfei** [comment]
`MasterAddr` and `WorkerAddr` in test files should be replaced too.

```go
[2022-07-25T05:17:49.016Z] engine/test/heartbeat_test.go:61:3: unknown field 'MasterAddr' in struct literal of type servermaster.Config
[2022-07-25T05:17:49.016Z] engine/test/heartbeat_test.go:69:3: unknown field 'WorkerAddr' in struct literal of type executor.Config
[2022-07-25T05:17:49.016Z] engine/test/util_test.go:99:3: unknown field 'MasterAddr' in struct literal of type servermaster.Config
[2022-07-25T05:17:49.016Z] engine/test/util_test.go:108:3: unknown field 'WorkerAddr' in struct literal of type executor.Config
[2022-07-25T05:17:49.016Z] WARN invalid TestEvent: FAIL	github.com/pingcap/tiflow/engine/test [build failed]
[2022-07-25T05:17:49.016Z] bad output from test2json: FAIL	github.com/pingcap/tiflow/engine/test [build failed]
[2022-07-25T05:17:49.016Z] ∅  engine/test/mock
[2022-07-25T05:17:49.581Z] 
[2022-07-25T05:17:49.581Z] === Errors
[2022-07-25T05:17:49.581Z] engine/client/client_test.go:49:3: unknown field 'MasterAddr' in struct literal of type servermaster.Config
[2022-07-25T05:17:49.581Z] engine/client/client_test.go:69:3: unknown field 'WorkerAddr' in struct literal of type executor.Config
[2022-07-25T05:17:49.581Z] engine/executor/server_test.go:55:6: cfg.WorkerAddr undefined (type *Config has no field or method WorkerAddr)
[2022-07-25T05:17:49.581Z] engine/executor/server_test.go:114:6: cfg.WorkerAddr undefined (type *Config has no field or method WorkerAddr)
[2022-07-25T05:17:49.581Z] engine/test/heartbeat_test.go:61:3: unknown field 'MasterAddr' in struct literal of type servermaster.Config
[2022-07-25T05:17:49.582Z] engine/test/heartbeat_test.go:69:3: unknown field 'WorkerAddr' in struct literal of type executor.Config
[2022-07-25T05:17:49.582Z] engine/test/util_test.go:99:3: unknown field 'MasterAddr' in struct literal of type servermaster.Config
[2022-07-25T05:17:49.582Z] engine/test/util_test.go:108:3: unknown field 'WorkerAddr' in struct literal of type executor.Config
```

**Review by gozssky — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
