### PR TITLE
syncer(dm): fix unstable multi-schema change tests

### LINKED ISSUE #7513: unstable multi-schema change test
### Which jobs are flaking?

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/10581/pipeline

copied the log to prevent log is cleaned

```
[2022-11-02T05:16:33.158Z] Running test /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/run.sh...
[2022-11-02T05:16:33.158Z] Verbose mode = false
[2022-11-02T05:16:33.417Z] 0 dm-master alive
[2022-11-02T05:16:33.417Z] 0 dm-worker alive
[2022-11-02T05:16:33.417Z] 0 dm-syncer alive
[2022-11-02T05:16:33.417Z] process dm-master.test already exit
[2022-11-02T05:16:33.417Z] process dm-worker.test already exit
[2022-11-02T05:16:33.417Z] process dm-syncer.test already exit
[2022-11-02T05:16:33.417Z] [Wed Nov  2 13:16:33 CST 2022] <<<<<< START DM-MASTER on port 8261, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-master.toml >>>>>>
[2022-11-02T05:16:33.417Z] wait for rpc addr 127.0.0.1:8261 alive the 1-th time
[2022-11-02T05:16:34.796Z] wait for rpc addr 127.0.0.1:8261 alive the 2-th time
[2022-11-02T05:16:35.732Z] rpc addr 127.0.0.1:8261 is alive
[2022-11-02T05:16:35.733Z] [Wed Nov  2 13:16:35 CST 2022] <<<<<< START DM-WORKER on port 8262, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker1.toml >>>>>>
[2022-11-02T05:16:35.733Z] wait for rpc addr 127.0.0.1:8262 alive the 1-th time
[2022-11-02T05:16:36.670Z] rpc addr 127.0.0.1:8262 is alive
[2022-11-02T05:16:36.670Z] [Wed Nov  2 13:16:36 CST 2022] <<<<<< START DM-WORKER on port 8263, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker2.toml >>>>>>
[2022-11-02T05:16:36.670Z] wait for rpc addr 127.0.0.1:8263 alive the 1-th time
[2022-11-02T05:16:37.605Z] rpc addr 127.0.0.1:8263 is alive
[2022-11-02T05:16:37.605Z] dmctl test cmd: "operate-source create /tmp/dm_test/gbk/source1.yaml"
[2022-11-02T05:16:37.864Z] dmctl test cmd: "operate-source create /tmp/dm_test/gbk/source2.yaml"
[2022-11-02T05:16:39.244Z] prepare data
[2022-11-02T05:16:39.244Z] start task
[2022-11-02T05:16:39.244Z] dmctl test cmd: "start-task /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-task.yaml --remove-meta"
[2022-11-02T05:16:40.621Z] check diff successfully
[2022-11-02T05:16:40.621Z] prepare incremental data
[2022-11-02T05:16:40.879Z] check incremental phase
[2022-11-02T05:16:41.137Z] check diff successfully
[2022-11-02T05:16:41.137Z] ERROR 1146 (42S02) at line 1: Table 'gbk.ddl1' doesn't exist
[2022-11-02T05:16:41.137Z] run tidb sql failed 1-th time, retry later
[2022-11-02T05:16:43.672Z] ERROR 1146 (42S02) at line 1: Table 'gbk.ddl2_copy' doesn't exist
[2022-11-02T05:16:43.672Z] run tidb sql failed 1-th time, retry later
[2022-11-02T05:16:45.581Z] ERROR 1146 (42S02) at line 1: Table 'gbk.ddl3' doesn't exist
[2022-11-02T05:16:45.581Z] run tidb sql failed 1-th time, retry later
[2022-11-02T05:16:47.485Z] ERROR 1049 (42000) at line 1: Unknown database 'gbk3'
[2022-11-02T05:16:47.485Z] run tidb sql failed 1-th time, retry later
[2022-11-02T05:16:49.416Z] ERROR 1146 (42S02) at line 1: Table 'gbk.ddl4' doesn't exist
[2022-11-02T05:16:49.416Z] run tidb sql failed 1-th time, retry later
[2022-11-02T05:16:51.345Z] prepare data for invalid connection test
[2022-11-02T05:16:51.345Z] check log contain failed 1-th time, retry later
[2022-11-02T05:16:54.661Z] wait process dm-worker.test exit...
[2022-11-02T05:16:54.661Z] process dm-worker.test already exit
[2022-11-02T05:16:54.661Z] [Wed Nov  2 13:16:54 CST 2022] <<<<<< START DM-WORKER on port 8262, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker1.toml >>>>>>
[2022-11-02T05:16:54.661Z] wait for rpc addr 127.0.0.1:8262 alive the 1-th time
[2022-11-02T05:16:55.614Z] rpc addr 127.0.0.1:8262 is alive
[2022-11-02T05:16:55.614Z] [Wed Nov  2 13:16:55 CST 2022] <<<<<< START DM-WORKER on port 8263, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker2.toml >>>>>>
[2022-11-02T05:16:55.614Z] wait for rpc addr 127.0.0.1:8263 alive the 1-th time
[2022-11-02T05:16:56.585Z] rpc addr 127.0.0.1:8263 is alive
[2022-11-02T05:16:56.585Z] start test invalid connection with status running
[2022-11-02T05:16:56.585Z] check count
[2022-11-02T05:16:56.858Z] check diff successfully
[2022-11-02T05:16:56.858Z] check test invalid connection with status running successfully
[2022-11-02T05:16:57.823Z] wait process dm-worker.test exit...
[2022-11-02T05:16:58.805Z] wait process dm-worker.test exit...
[2022-11-02T05:17:00.205Z] wait process dm-worker.test exit...
[2022-11-02T05:17:01.198Z] wait process dm-worker.test exit...
[2022-11-02T05:17:01.198Z] process dm-worker.test already exit
[2022-11-02T05:17:01.198Z] [Wed Nov  2 13:17:00 CST 2022] <<<<<< START DM-WORKER on port 8262, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker1.toml >>>>>>
[2022-11-02T05:17:01.198Z] wait for rpc addr 127.0.0.1:8262 alive the 1-th time
[2022-11-02T05:17:02.211Z] rpc addr 127.0.0.1:8262 is alive
[2022-11-02T05:17:02.212Z] [Wed Nov  2 13:17:01 CST 2022] <<<<<< START DM-WORKER on port 8263, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker2.toml >>>>>>
[2022-11-02T05:17:02.212Z] wait for rpc addr 127.0.0.1:8263 alive the 1-th time
[2022-11-02T05:17:03.238Z] rpc addr 127.0.0.1:8263 is alive
[2022-11-02T05:17:03.238Z] start test invalid connection with status queueing
[2022-11-02T05:17:03.238Z] run tidb sql failed 1-th time, retry later
[2022-11-02T05:17:05.155Z] check count
[2022-11-02T05:17:05.415Z] check diff successfully
[2022-11-02T05:17:05.415Z] check test invalid connection with status queueing successfully
[2022-11-02T05:17:06.355Z] wait process dm-worker.test exit...
[2022-11-02T05:17:07.733Z] wait process dm-worker.test exit...
[2022-11-02T05:17:08.673Z] wait process dm-worker.test exit...
[2022-11-02T05:17:08.673Z] process dm-worker.test already exit
[2022-11-02T05:17:08.673Z] [Wed Nov  2 13:17:08 CST 2022] <<<<<< START DM-WORKER on port 8262, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker1.toml >>>>>>
[2022-11-02T05:17:08.673Z] wait for rpc addr 127.0.0.1:8262 alive the 1-th time
[2022-11-02T05:17:09.614Z] rpc addr 127.0.0.1:8262 is alive
[2022-11-02T05:17:09.614Z] [Wed Nov  2 13:17:09 CST 2022] <<<<<< START DM-WORKER on port 8263, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker2.toml >>>>>>
[2022-11-02T05:17:09.614Z] wait for rpc addr 127.0.0.1:8263 alive the 1-th time
[2022-11-02T05:17:10.553Z] rpc addr 127.0.0.1:8263 is alive
[2022-11-02T05:17:10.554Z] start test invalid connection with status none
[2022-11-02T05:17:10.554Z] run tidb sql failed 1-th time, retry later
[2022-11-02T05:17:13.092Z] check count
[2022-11-02T05:17:13.092Z] check diff successfully
[2022-11-02T05:17:13.092Z] check test invalid connection with status none successfully
[2022-11-02T05:17:14.031Z] wait process dm-worker.test exit...
[2022-11-02T05:17:14.967Z] wait process dm-worker.test exit...
[2022-11-02T05:17:15.905Z] wait process dm-worker.test exit...
[2022-11-02T05:17:15.905Z] process dm-worker.test already exit
[2022-11-02T05:17:15.905Z] [Wed Nov  2 13:17:15 CST 2022] <<<<<< START DM-WORKER on port 8262, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker1.toml >>>>>>
[2022-11-02T05:17:15.905Z] wait for rpc addr 127.0.0.1:8262 alive the 1-th time
[2022-11-02T05:17:17.286Z] rpc addr 127.0.0.1:8262 is alive
[2022-11-02T05:17:17.286Z] [Wed Nov  2 13:17:16 CST 2022] <<<<<< START DM-WORKER on port 8263, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker2.toml >>>>>>
[2022-11-02T05:17:17.286Z] wait for rpc addr 127.0.0.1:8263 alive the 1-th time
[2022-11-02T05:17:18.224Z] rpc addr 127.0.0.1:8263 is alive
[2022-11-02T05:17:18.224Z] start test inserting data after invalid connection
[2022-11-02T05:17:18.224Z] run tidb sql failed 1-th time, retry later
[2022-11-02T05:17:20.134Z] check count
[2022-11-02T05:17:20.394Z] check diff successfully
[2022-11-02T05:17:20.394Z] check test inserting data after invalid connection successfully
[2022-11-02T05:17:21.331Z] wait process dm-worker.test exit...
[2022-11-02T05:17:22.712Z] wait process dm-worker.test exit...
[2022-11-02T05:17:22.712Z] process dm-worker.test already exit
[2022-11-02T05:17:22.712Z] [Wed Nov  2 13:17:22 CST 2022] <<<<<< START DM-WORKER on port 8262, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker1.toml >>>>>>
[2022-11-02T05:17:22.712Z] wait for rpc addr 127.0.0.1:8262 alive the 1-th time
[2022-11-02T05:17:23.651Z] rpc addr 127.0.0.1:8262 is alive
[2022-11-02T05:17:23.651Z] [Wed Nov  2 13:17:23 CST 2022] <<<<<< START DM-WORKER on port 8263, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker2.toml >>>>>>
[2022-11-02T05:17:23.651Z] wait for rpc addr 127.0.0.1:8263 alive the 1-th time
[2022-11-02T05:17:24.590Z] rpc addr 127.0.0.1:8263 is alive
[2022-11-02T05:17:24.590Z] start test adding UNIQUE on column with duplicate data
[2022-11-02T05:17:24.590Z] check cancelled error
[2022-11-02T05:17:24.590Z] dmctl test cmd: "query-status gbk"
[2022-11-02T05:17:24.850Z] got=0 expected=1
[2022-11-02T05:17:24.850Z] command: query-status gbk origin SQL: \[ALTER TABLE gbk.invalid_conn_test1 ADD UNIQUE(i)\]: DDL ALTER TABLE `gbk`.`invalid_conn_test1` ADD UNIQUE(`i`) executed in background and met error count: 0 != expected: 1, failed the 0-th time, will retry again
[2022-11-02T05:17:27.388Z] got=0 expected=1
[2022-11-02T05:17:27.388Z] command: query-status gbk origin SQL: \[ALTER TABLE gbk.invalid_conn_test1 ADD UNIQUE(i)\]: DDL ALTER TABLE `gbk`.`invalid_conn_test1` ADD UNIQUE(`i`) executed in background and met error count: 0 != expected: 1, failed the 1-th time, will retry again
[2022-11-02T05:17:29.296Z] got=1 expected=1
[2022-11-02T05:17:29.296Z] dmctl test cmd: "resume-task gbk"
[2022-11-02T05:17:29.296Z] got=3 expected=3
[2022-11-02T05:17:29.296Z] check test adding UNIQUE on column with duplicate data successfully
[2022-11-02T05:17:30.676Z] wait process dm-worker.test exit...
[2022-11-02T05:17:31.614Z] wait process dm-worker.test exit...
[2022-11-02T05:17:32.552Z] wait process dm-worker.test exit...
[2022-11-02T05:17:32.552Z] process dm-worker.test already exit
[2022-11-02T05:17:32.552Z] [Wed Nov  2 13:17:32 CST 2022] <<<<<< START DM-WORKER on port 8262, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker1.toml >>>>>>
[2022-11-02T05:17:32.552Z] wait for rpc addr 127.0.0.1:8262 alive the 1-th time
[2022-11-02T05:17:33.487Z] rpc addr 127.0.0.1:8262 is alive
[2022-11-02T05:17:33.487Z] [Wed Nov  2 13:17:33 CST 2022] <<<<<< START DM-WORKER on port 8263, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker2.toml >>>>>>
[2022-11-02T05:17:33.487Z] wait for rpc addr 127.0.0.1:8263 alive the 1-th time
[2022-11-02T05:17:34.426Z] rpc addr 127.0.0.1:8263 is alive
[2022-11-02T05:17:34.426Z] start test invalid connection with status running (multi-schema change)
[2022-11-02T05:17:34.687Z] check count 1
[2022-11-02T05:17:34.687Z] run tidb sql failed 1-th time, retry later
[2022-11-02T05:17:36.596Z] run tidb sql failed 2-th time, retry later
[2022-11-02T05:17:39.131Z] check count 2
[2022-11-02T05:17:39.131Z] check diff successfully
[2022-11-02T05:17:39.131Z] check test invalid connection with status running (multi-schema change) successfully
[2022-11-02T05:17:40.069Z] wait process dm-worker.test exit...
[2022-11-02T05:17:41.008Z] wait process dm-worker.test exit...
[2022-11-02T05:17:41.946Z] wait process dm-worker.test exit...
[2022-11-02T05:17:41.946Z] process dm-worker.test already exit
[2022-11-02T05:17:41.946Z] [Wed Nov  2 13:17:41 CST 2022] <<<<<< START DM-WORKER on port 8262, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker1.toml >>>>>>
[2022-11-02T05:17:41.946Z] wait for rpc addr 127.0.0.1:8262 alive the 1-th time
[2022-11-02T05:17:42.884Z] rpc addr 127.0.0.1:8262 is alive
[2022-11-02T05:17:42.884Z] [Wed Nov  2 13:17:42 CST 2022] <<<<<< START DM-WORKER on port 8263, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker2.toml >>>>>>
[2022-11-02T05:17:43.143Z] wait for rpc addr 127.0.0.1:8263 alive the 1-th time
[2022-11-02T05:17:44.078Z] rpc addr 127.0.0.1:8263 is alive
[2022-11-02T05:17:44.078Z] start test invalid connection with status queueing (multi-schema change)
[2022-11-02T05:17:44.078Z] check count 1
[2022-11-02T05:17:44.078Z] run tidb sql failed 1-th time, retry later
[2022-11-02T05:17:46.612Z] run tidb sql failed 2-th time, retry later
[2022-11-02T05:17:48.517Z] check count 2
[2022-11-02T05:17:48.517Z] check diff successfully
[2022-11-02T05:17:48.517Z] check test invalid connection with status queueing (multi-schema change) successfully
[2022-11-02T05:17:49.453Z] wait process dm-worker.test exit...
[2022-11-02T05:17:50.393Z] wait process dm-worker.test exit...
[2022-11-02T05:17:51.334Z] wait process dm-worker.test exit...
[2022-11-02T05:17:51.334Z] process dm-worker.test already exit
[2022-11-02T05:17:51.593Z] [Wed Nov  2 13:17:51 CST 2022] <<<<<< START DM-WORKER on port 8262, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker1.toml >>>>>>
[2022-11-02T05:17:51.593Z] wait for rpc addr 127.0.0.1:8262 alive the 1-th time
[2022-11-02T05:17:52.531Z] rpc addr 127.0.0.1:8262 is alive
[2022-11-02T05:17:52.531Z] [Wed Nov  2 13:17:52 CST 2022] <<<<<< START DM-WORKER on port 8263, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/gbk/conf/dm-worker2.toml >>>>>>
[2022-11-02T05:17:52.531Z] wait for rpc addr 127.0.0.1:8263 alive the 1-th time
[2022-11-02T05:17:53.469Z] rpc addr 127.0.0.1:8263 is alive
[2022-11-02T05:17:53.469Z] start test invalid connection with status none (multi-schema change)
[2022-11-02T05:17:53.729Z] check count 1
[2022-11-02T05:17:53.729Z] TEST FAILED: OUTPUT CONTAINS 'ALTER TABLE `gbk`.`invalid_conn_test1` MODIFY COLUMN `n` INT(4) NOT NULL DEFAULT '0'' for 2 times, which supposed to be 1 times
[2022-11-02T05:17:53.729Z] ____________________________________
[2022-11-02T05:17:53.729Z] [Wed Nov  2 13:17:53 CST 2022] Executing SQL: ADMIN SHOW DDL JOB QUERIES LIMIT 10 OFFSET 0
[2022-11-02T05:17:53.729Z] *************************** 1. row ***************************
[2022-11-02T05:17:53.729Z] JOB_ID: 615
[2022-11-02T05:17:53.729Z]  QUERY: ALTER TABLE `gbk`.`invalid_conn_test1` MODIFY COLUMN `n` INT(4) NOT NULL DEFAULT '0'
[2022-11-02T05:17:53.729Z] *************************** 2. row ***************************
[2022-11-02T05:17:53.729Z] JOB_ID: 615
[2022-11-02T05:17:53.729Z]  QUERY: ALTER TABLE `gbk`.`invalid_conn_test1` MODIFY COLUMN `n` INT(4) NOT NULL DEFAULT '0'
[2022-11-02T05:17:53.729Z] *************************** 3. row ***************************
[2022-11-02T05:17:53.729Z] JOB_ID: 614
[2022-11-02T05:17:53.729Z]  QUERY: ALTER TABLE `gbk`.`invalid_conn_test2` MODIFY COLUMN `m` INT(4) NOT NULL DEFAULT '0'
[2022-11-02T05:17:53.729Z] *************************** 4. row ***************************
[2022-11-02T05:17:53.729Z] JOB_ID: 613
[2022-11-02T05:17:53.729Z]  QUERY: ALTER TABLE `gbk`.`invalid_conn_test2` MODIFY COLUMN `k` INT(4) NOT NULL DEFAULT '0'
[2022-11-02T05:17:53.729Z] *************************** 5. row ***************************
[2022-11-02T05:17:53.729Z] JOB_ID: 612
[2022-11-02T05:17:53.729Z]  QUERY: ALTER TABLE `gbk`.`invalid_conn_test1` MODIFY COLUMN `m` INT(4) NOT NULL DEFAULT '0'
[2022-11-02T05:17:53.729Z] *************************** 6. row ***************************
[2022-11-02T05:17:53.729Z] JOB_ID: 611
[2022-11-02T05:17:53.729Z]  QUERY: ALTER TABLE `gbk`.`invalid_conn_test1` MODIFY COLUMN `k` INT(4) NOT NULL DEFAULT '0'
[2022-11-02T05:17:53.729Z] *************************** 7. row ***************************
[2022-11-02T05:17:53.729Z] JOB_ID: 610
[2022-11-02T05:17:53.729Z]  QUERY: ALTER TABLE `gbk`.`invalid_conn_test2` MODIFY COLUMN `j` INT(4) NOT NULL DEFAULT '0'
[2022-11-02T05:17:53.729Z] *************************** 8. row ***************************
[2022-11-02T05:17:53.729Z] JOB_ID: 609
[2022-11-02T05:17:53.729Z]  QUERY: ALTER TABLE `gbk`.`invalid_conn_test2` MODIFY COLUMN `i` INT(4) NOT NULL DEFAULT '0'
[2022-11-02T05:17:53.729Z] *************************** 9. row ***************************
[2022-11-02T05:17:53.729Z] JOB_ID: 608
[2022-11-02T05:17:53.729Z]  QUERY: ALTER TABLE `gbk`.`invalid_conn_test1` MODIFY COLUMN `j` INT(4) NOT NULL DEFAULT '0'
[2022-11-02T05:17:53.730Z] *************************** 10. row ***************************
[2022-11-02T05:17:53.730Z] JOB_ID: 607
[2022-11-02T05:17:53.730Z]  QUERY: ALTER TABLE `gbk`.`invalid_conn_test1` MODIFY COLUMN `i` INT(4) NOT NULL DEFAULT '0'
[2022-11-02T05:17:53.730Z] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2022-11-02T05:17:53.730Z] curl: (7) Failed connect to 127.0.0.1:8361; Connection refused
[2022-11-02T05:17:53.730Z] curl: (7) Failed connect to 127.0.0.1:8461; Connection refused
[2022-11-02T05:17:53.730Z] curl: (7) Failed connect to 127.0.0.1:8561; Connection refused
[2022-11-02T05:17:53.730Z] curl: (7) Failed connect to 127.0.0.1:8661; Connection refused
[2022-11-02T05:17:53.730Z] curl: (7) Failed connect to 127.0.0.1:8761; Connection refused
[2022-11-02T05:17:53.730Z] curl: (7) Failed connect to 127.0.0.1:8264; Connection refused
[2022-11-02T05:17:53.730Z] curl: (7) Failed connect to 127.0.0.1:18262; Connection refused
[2022-11-02T05:17:53.730Z] curl: (7) Failed connect to 127.0.0.1:18263; Connection refused
[2022-11-02T05:17:53.730Z] make: *** [dm_integration_test] Error 1
```

### Which test(s) are flaking?

DM-IT gbk

### Jenkins logs or GitHub Actions link

[dm-log.txt](https://github.com/pingcap/tiflow/files/9916596/dm-log.txt)

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### PR DESCRIPTION
**Pull request by lyzx2001**
### What problem does this PR solve?

Issue Number: close #7513 

### What is changed and how it works?
After https://github.com/pingcap/tidb/pull/39248 is merged into TiDB, these multi-schema change tests should work as expected.

#### Tests 

 - Integration test

##### Will it cause performance regression or break compatibility?
No.
##### Do you need to update user documentation, design documentation or monitoring documentation?
No.
### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by lyzx2001** [comment]
https://github.com/pingcap/tidb/pull/39248 has been merged into TiDB, these multi-schema change tests should work as expected.

**Review by lance6716 — APPROVED** [review]

**Review by lichunzhu — APPROVED** [review]
LGTM

**Pull request merged**
