### PR TITLE
*: add gci to format imports

### PR DESCRIPTION
**Pull request by gozssky**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/7347

### What is changed and how it works?
Add gci to format imports.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]
no need to review if CI pass 😄

**Review by asddongmen — APPROVED** [review]

**Review by buchuitoudegou — APPROVED** [review]

**Pull request merged**
