### PR TITLE
protocol(ticdc): force enable old value for canal json protocol

### PR DESCRIPTION
**Pull request by hi-rustin**
This is an automated cherry-pick of #3747 and #3983

### What problem does this PR solve? 
close https://github.com/pingcap/ticdc/issues/3676

### What is changed and how it works?

* add validate funcs
* complete protocol when create changefeed
* add tests

### Check List 

Tests 

 - Unit test
 - Manual test(https://github.com/pingcap/ticdc/pull/3747#issuecomment-986629511)
Code changes

 - Has exported function/method change
 - Has exported variable/fields change

Side effects

None

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
Fix the problem that old value is not forced on automatically in `canal-json` and `maxwell` protocols
```

### CODE REVIEW

**Comment by lance6716** [comment]
can we merge it @hi-rustin

**Comment by hi-rustin** [comment]
> can we merge it @hi-rustin

Yes. But review required.

**Review by asddongmen — APPROVED** [review]

**Comment by hi-rustin** [comment]
I marked it as require-LGT1 because it's actually part of https://github.com/pingcap/tiflow/pull/3780 because it didn't hold and merged part of the code.

**Pull request merged**
