### PR TITLE
owner,scheduler(ticdc): fix some typos and add log

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/5039

### What is changed and how it works?

fix some typos and add log.

### Check List 

Tests 

 - No code

Code changes

None

Side effects
None

Related changes
None

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
/label require-LGT1

Since it just fixes typos and adds logs, marking it only takes one 👍.

**Review by ben1009 — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
