### PR TITLE
DM(syncer): fix syncer may be dead cycle when access match inject ddl repeatedly by special ddls

### LINKED ISSUE #5009: DM(syncer): syncer may be dead cycle when access match inject ddl repeatedly by special ddls
### What did you do?

1. one source has two sub table
2. pessimistic shard mode
3. sql like this:
    tb1 --> ddl (need inject ddl1,ddl2)
    tb2 --> ddl (need inject ddl1,ddl2)

### What did you expect to see?

sync normally.

### What did you see instead?

dead cycle.

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
6.0/master
```
Upstream MySQL/MariaDB server version:
```console
5.7.22-log
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
5.7.25-TiDB-v5.3.0
```
How did you deploy DM: tiup or manually?
```console
manually
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by WizardXiao**
### What problem does this PR solve?

Issue Number: close #5009 

### What is changed and how it works?
add check for repeatedly access match inject.

### Check List 

Tests 

 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Review by lance6716 — APPROVED** [review]

**Comment by Ehco1996** [comment]
start DM-101 optimistic
/run-dm-integration-test

**Pull request merged**
