### PR TITLE
sinkv2(ticdc): add black hole sink

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/5928

### What is changed and how it works?
- add black hole sink
- extract the sink type

#### Tests 

 - Unit test

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
None
```

### CODE REVIEW

**Review by hi-rustin — COMMENTED** [review]
Self check

**Review by zhaoxinyu — APPROVED** [review]

**Review by lonng — APPROVED** [review]

**Review by sdojjy — APPROVED** [review]

**Pull request merged**
