### PR TITLE
processor(ticdc): add min resolved/checkpoint table ID metrics

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Replace a high cardinality metric with a low one.

Issue Number: ref #2183

### What is changed and how it works?

Add min resolved/checkpoint table ID metrics.

### Check List 

 - Manual test (add detailed scripts or steps below)

image
Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Comment by 3AceShowHand** [comment]
It looks good.

We should find a better way to represent the graph.

**Comment by ben1009** [comment]
when/how to use the metric ?

**Comment by overvenus** [comment]
> when/how to use the metric ?

It is useful when there are some locks left in a table which blocks resolved ts, we can get the table ID from the metrics, and resolve lock manually.

**Review by ben1009 — APPROVED** [review]

**Pull request merged**
