### PR TITLE
syncer(dm): merge location recorder from feature branch

### LINKED ISSUE #6319: use binlog location recorder

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #6319

### What is changed and how it works?

as title

#### Tests 

 - pass old tests

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
related tests passed

/cc @D3Hunter @buchuitoudegou @GMHDBJD

**Review by D3Hunter — APPROVED** [review]

**Review by buchuitoudegou — APPROVED** [review]

**Pull request merged**
