### PR TITLE
checker(dm): considering extended column when precheck 

### LINKED ISSUE #7574: unstable DM test adjust_gtid
### Which jobs are flaking?

DM-IT

### Which test(s) are flaking?

adjust_gtid

### Jenkins logs or GitHub Actions link

```
2022-11-10T04:18:44.730Z] start running case: [adjust_gtid] script: [/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/adjust_gtid/run.sh]
[2022-11-10T04:18:44.730Z] Running test /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/adjust_gtid/run.sh...
[2022-11-10T04:18:44.730Z] Verbose mode = false
[2022-11-10T04:18:44.730Z] 0 dm-master alive
[2022-11-10T04:18:44.730Z] 0 dm-worker alive
[2022-11-10T04:18:44.730Z] 0 dm-syncer alive
[2022-11-10T04:18:44.730Z] process dm-master.test already exit
[2022-11-10T04:18:44.730Z] process dm-worker.test already exit
[2022-11-10T04:18:44.730Z] process dm-syncer.test already exit
[2022-11-10T04:18:44.988Z] [Thu Nov 10 12:18:44 CST 2022] <<<<<< START DM-MASTER on port 8261, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/adjust_gtid/conf/dm-master.toml >>>>>>
[2022-11-10T04:18:44.988Z] wait for rpc addr 127.0.0.1:8261 alive the 1-th time
[2022-11-10T04:18:45.923Z] wait for rpc addr 127.0.0.1:8261 alive the 2-th time
[2022-11-10T04:18:46.859Z] rpc addr 127.0.0.1:8261 is alive
[2022-11-10T04:18:47.117Z] [Thu Nov 10 12:18:46 CST 2022] <<<<<< START DM-WORKER on port 8262, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/adjust_gtid/conf/dm-worker1.toml >>>>>>
[2022-11-10T04:18:47.117Z] wait for rpc addr 127.0.0.1:8262 alive the 1-th time
[2022-11-10T04:18:48.053Z] rpc addr 127.0.0.1:8262 is alive
[2022-11-10T04:18:48.053Z] dmctl test cmd: "operate-source create /tmp/dm_test/adjust_gtid/source1.yaml"
[2022-11-10T04:18:48.312Z] [Thu Nov 10 12:18:48 CST 2022] <<<<<< START DM-WORKER on port 8263, config: /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/tests/adjust_gtid/conf/dm-worker2.toml >>>>>>
[2022-11-10T04:18:48.312Z] wait for rpc addr 127.0.0.1:8263 alive the 1-th time
[2022-11-10T04:18:49.691Z] rpc addr 127.0.0.1:8263 is alive
[2022-11-10T04:18:49.691Z] dmctl test cmd: "operate-source create /tmp/dm_test/adjust_gtid/source2.yaml"
[2022-11-10T04:18:50.628Z] dmctl test cmd: "start-task /tmp/dm_test/adjust_gtid/dm-task.yaml --remove-meta"
[2022-11-10T04:18:52.534Z] check diff successfully
[2022-11-10T04:18:52.534Z] TEST FAILED: OUTPUT DOES NOT CONTAIN 'dm-integration-test-go1190-10735-1j1m0-29xqd-bin.000001'
[2022-11-10T04:18:52.534Z] ____________________________________
[2022-11-10T04:18:52.537Z] [Thu Nov 10 12:18:52 CST 2022] Executing SQL: select binlog_name,binlog_pos,binlog_gtid from dm_meta.test_syncer_checkpoint where id="mysql-replica-01" and is_global=1
[2022-11-10T04:18:52.537Z] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

[dm-ci.log](https://github.com/pingcap/tiflow/files/9977461/dm-ci.log)

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref #3340 close #7574

### What is changed and how it works?

add precheck about extended columns

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
@lichunzhu please help check if the behaviour is acceptable, for example, which case is warning and which case is error

**Comment by lichunzhu** [comment]
> @lichunzhu please help check if the behaviour is acceptable, for example, which case is warning and which case is error

Current solution LGTM now. Both upstream contains extend column and downstrean doesn't contains extend column should return errors.

**Comment by lance6716** [comment]
ptal @GMHDBJD @buchuitoudegou

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
