### PR TITLE
syncer(dm): update dep to remove clone for TableInfo

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: ref #4287

### What is changed and how it works?

~in the old PR, I'm afraid that TableInfo is changing by SchemaTracker when DMLWorker is accesing, so I clone it before assign it to DMLWorker. But seems DML and DDL job will not be processed simutaneously, this clone is not needed.~

#### Tests 

 - pass original test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by okJiang — COMMENTED** [review]
I don't find where changes the tableInfo😂, can you give an example? BTW, related problem about version updating is fixed in https://github.com/pingcap/tiflow/pull/7584.

**Comment by lance6716** [comment]
TableInfo is changed in SchemaTracker when handling DDL, https://github.com/pingcap/tidb/pull/39103

An example: TableInfo is read by checkpoint component as a "flushed TableInfo", and when task has error, checkpoint will use flushed TableInfo to rollback some changes. If the TableInfo is mutable, flushed TableInfo may be modified after a DDL
 is applied in SchemaTracker, rolling back logic is wrong.

**Comment by lance6716** [comment]
ptal @CharlesCheung96 @GMHDBJD @okJiang

**Review by okJiang — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]

**Pull request merged**
