### PR TITLE
config, scheduler(ticdc): add MaxTableCount and AddTableBatchSize to ChangefeedSchedulerConfig

### LINKED ISSUE #11216: the scheduling time is too long when synchronize 150k tables in single changefeed
1. Create a changefeed which synchronize 150k tables.
2. The schedule has not been completed in 40 minutes.
image

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: close #11216

### What is changed and how it works?
1. Move [AddTableBatchSize](https://github.com/pingcap/tiflow/pull/11197/files#diff-5efe37006daf176ecbb4df807539f64719314947957f5b78bb4bd3453c2ab881R47) from server to changefeed config.
2. Add [MaxTableCount](https://github.com/pingcap/tiflow/pull/11197/files#diff-46d391757d5e8384d6854c28080c8eb981dd84f96bdb317da51ad9c6bf7c1c5fR115-R122) to limit the max tables for each capture to avoid unbalance.
3. Auto adjust batchSize in [scheduler_basic](https://github.com/pingcap/tiflow/pull/11197/files#diff-46d391757d5e8384d6854c28080c8eb981dd84f96bdb317da51ad9c6bf7c1c5fR59-R74) if `AddTableBatchSize=0`. And the adjustment range is [50 to 1000](https://github.com/pingcap/tiflow/pull/11197/files#diff-5efe37006daf176ecbb4df807539f64719314947957f5b78bb4bd3453c2ab881R29-R32). 

#### Tests 

 - Manual test (add detailed scripts or steps below)
 - Before this PR: 
 The schedule has not been completed in 40 minutes.
image

- This PR: The scheduling was completed in 10min
image

### Release note 

```release-note
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release note.

If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

**Review by hongyunyan — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Comment by CharlesCheung96** [comment]
Currently, users can manually adjust parameters to support a large number of table scenarios.

**Pull request closed without merging**
