### PR TITLE
table partiiton: exchange partition with table 6.3 GA

### LINKED ISSUE #6990: table partition: exchange partition with table Feature Request
### Is your feature request related to a problem?

exchange partition with table Feature Request

### Describe the feature you'd like

TiCDC can execute exchange partition with table ddl.

### Describe alternatives you've considered

_No response_

### Teachability, Documentation, Adoption, Migration Strategy

_No response_

### PR DESCRIPTION
**Pull request by ymkzpx**
### What problem does this PR solve?

Issue Number: close #6990

#### Tests 

 - Integration test
 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
table partiiton: exchange partition with table 6.3 GA.
```

### CODE REVIEW

**Comment by 3AceShowHand** [comment]
It looks like we can add an integration test for the `exchange partition` feature

**Review by asddongmen — APPROVED** [review]

**Review by 3AceShowHand — APPROVED** [review]

**Pull request merged**
