### PR TITLE
owner(ticdc): fix the nil panic

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/5266

### What is changed and how it works?
fix the nil panic.
Follow up https://github.com/pingcap/tiflow/pull/4183 

### Check List 

Tests 

 - [Manual test](https://github.com/pingcap/tiflow/pull/5304#issuecomment-1111764196) 

Code changes

None

Side effects

None

Related changes

None

### Release note 

```release-note
Fix an issue where TiCDC clusters may panic after an upgrade
```

### CODE REVIEW

**Comment by hi-rustin** [comment]
1. Start the ticdc cluster
2. Create multiple changefeeds
3. delete a changfeed
4. upgrade ticdc
4. no Panic

**Review by overvenus — APPROVED** [review]

**Pull request merged**
