### PR TITLE
dm: update to latest tidb to fix lightning loader

### LINKED ISSUE #4486: data race for DM lightning loader
### What did you do?

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/3205/pipeline

### What did you expect to see?

_No response_

### What did you see instead?

```
[2022-01-27T02:38:35.212Z] [2022/01/27 10:35:26.336 +08:00] [INFO] [info.go:49] ["Welcome to TiDB-Lightning"] [component="ddl tracker"] [release-version=v5.0.0-master] [git-hash=None] [git-branch=None] [go-version=go1.16.4] [utc-build-time=None] [race-enabled=true]

[2022-01-27T02:38:35.212Z] +---+----------------------------------------------+-------------+--------+

[2022-01-27T02:38:35.212Z] | # | CHECK ITEM                                   | TYPE        | PASSED |

[2022-01-27T02:38:35.212Z] +---+----------------------------------------------+-------------+--------+

[2022-01-27T02:38:35.212Z] | 1 | Source csv files size is proper              | performance | true   |

[2022-01-27T02:38:35.212Z] +---+----------------------------------------------+-------------+--------+

[2022-01-27T02:38:35.212Z] | 2 | checkpoints are valid                        | critical    | true   |

[2022-01-27T02:38:35.212Z] +---+----------------------------------------------+-------------+--------+

[2022-01-27T02:38:35.212Z] | 3 | table schemas are valid                      | critical    | true   |

[2022-01-27T02:38:35.212Z] +---+----------------------------------------------+-------------+--------+

[2022-01-27T02:38:35.212Z] | 4 | Cluster is available                         | critical    | true   |

[2022-01-27T02:38:35.212Z] +---+----------------------------------------------+-------------+--------+

[2022-01-27T02:38:35.212Z] | 5 | Lightning has the correct storage permission | critical    | true   |

[2022-01-27T02:38:35.212Z] +---+----------------------------------------------+-------------+--------+

[2022-01-27T02:38:35.212Z] 

[2022-01-27T02:38:35.212Z] ==================

[2022-01-27T02:38:35.212Z] WARNING: DATA RACE

[2022-01-27T02:38:35.212Z] Write at 0x00c0065790e0 by goroutine 89:

[2022-01-27T02:38:35.212Z]   github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).restoreTables.func7.1()

[2022-01-27T02:38:35.212Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:1511 +0x1e4

[2022-01-27T02:38:35.212Z] 

[2022-01-27T02:38:35.212Z] Previous write at 0x00c0065790e0 by goroutine 83:

[2022-01-27T02:38:35.212Z]   github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).restoreTables.func7.1()

[2022-01-27T02:38:35.212Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:1511 +0x1e4

[2022-01-27T02:38:35.212Z] 

[2022-01-27T02:38:35.212Z] Goroutine 89 (running) created at:

[2022-01-27T02:38:35.212Z]   github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).restoreTables.func7()

[2022-01-27T02:38:35.212Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:1506 +0x12c

[2022-01-27T02:38:35.212Z]   github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).restoreTables.func5()

[2022-01-27T02:38:35.212Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:1416 +0xa2

[2022-01-27T02:38:35.212Z]   github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).restoreTables()

[2022-01-27T02:38:35.212Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:1520 +0x1276

[2022-01-27T02:38:35.212Z]   github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).restoreTables-fm()

[2022-01-27T02:38:35.212Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:1323 +0x6a

[2022-01-27T02:38:35.212Z]   github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).Run()

[2022-01-27T02:38:35.212Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:450 +0x281

[2022-01-27T02:38:35.212Z]   github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).run()

[2022-01-27T02:38:35.212Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/lightning.go:343 +0x14e4

[2022-01-27T02:38:35.212Z]   github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).RunOnce()

[2022-01-27T02:38:35.212Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/lightning.go:201 +0x184

[2022-01-27T02:38:35.213Z]   github.com/pingcap/tiflow/dm/loader.(*LightningLoader).runLightning()

[2022-01-27T02:38:35.213Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/loader/lightning.go:200 +0x245

[2022-01-27T02:38:35.213Z]   github.com/pingcap/tiflow/dm/loader.(*LightningLoader).restore()

[2022-01-27T02:38:35.213Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/loader/lightning.go:252 +0xb59

[2022-01-27T02:38:35.213Z]   github.com/pingcap/tiflow/dm/loader.(*LightningLoader).Process()

[2022-01-27T02:38:35.213Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/loader/lightning.go:301 +0x62f

[2022-01-27T02:38:35.213Z] 

[2022-01-27T02:38:35.213Z] Goroutine 83 (finished) created at:

[2022-01-27T02:38:35.213Z]   github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).restoreTables.func7()

[2022-01-27T02:38:35.213Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:1506 +0x12c

[2022-01-27T02:38:35.213Z]   github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).restoreTables.func5()

[2022-01-27T02:38:35.213Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:1416 +0xa2

[2022-01-27T02:38:35.213Z]   github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).restoreTables()

[2022-01-27T02:38:35.213Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:1520 +0x1276

[2022-01-27T02:38:35.213Z]   github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).restoreTables-fm()

[2022-01-27T02:38:35.213Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:1323 +0x6a

[2022-01-27T02:38:35.213Z]   github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).Run()

[2022-01-27T02:38:35.213Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:450 +0x281

[2022-01-27T02:38:35.213Z]   github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).run()

[2022-01-27T02:38:35.213Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/lightning.go:343 +0x14e4

[2022-01-27T02:38:35.213Z]   github.com/pingcap/tidb/br/pkg/lightning.(*Lightning).RunOnce()

[2022-01-27T02:38:35.213Z]       /go/pkg/mod/github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/lightning.go:201 +0x184

[2022-01-27T02:38:35.213Z]   github.com/pingcap/tiflow/dm/loader.(*LightningLoader).runLightning()

[2022-01-27T02:38:35.213Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/loader/lightning.go:200 +0x245

[2022-01-27T02:38:35.213Z]   github.com/pingcap/tiflow/dm/loader.(*LightningLoader).restore()

[2022-01-27T02:38:35.213Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/loader/lightning.go:252 +0xb59

[2022-01-27T02:38:35.213Z]   github.com/pingcap/tiflow/dm/loader.(*LightningLoader).Process()

[2022-01-27T02:38:35.213Z]       /home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/loader/lightning.go:301 +0x62f
```

### Versions of the cluster

master

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### LINKED ISSUE #4489: DM worker panic in chaos test
### What did you do?

run chaos test https://github.com/pingcap/tiflow/actions/runs/1751777535

### What did you expect to see?

test succeed

### What did you see instead?

test failed
worker panic with log
```
[2022/01/26 16:16:02.563 +00:00] [INFO] [subtask.go:253] ["start to run"] [subtask=task_optimistic] [unit=Load]
[2022/01/26 16:16:02.563 +00:00] [INFO] [lightning.go:277] ["lightning load start"] [task=task_optimistic] [unit=lightning-load]
[2022/01/26 16:16:02.577 +00:00] [INFO] [util.go:179] ["put load worker in etcd"] [task=task_optimistic] [source=replica-01] [worker=dm-worker-0]
[2022/01/26 16:16:02.659 +00:00] [INFO] [checkpoint.go:570] ["initial checkpoint record"] [component="lightning checkpoint database list"] [task=task_optimistic] [source=replica-01]
[2022/01/26 16:16:02.773 +00:00] [INFO] [checkpoint.go:590] ["update lightning loader status"] [component="lightning checkpoint database list"] [task=task_optimistic] [source=replica-01] [status=running]
[2022/01/26 16:16:03.902 +00:00] [INFO] [printer.go:54] ["Welcome to dm-worker"] ["Release Version"=v5.4.0-master] ["Git Commit Hash"=910bcd86364701233347e0d183bc201feda74cd0] ["Git Branch"=HEAD] ["UTC Build Time"="2022-01-26 16:09:55"] ["Go Version"="go version go1.16.13 linux/amd64"]
[dm-worker-1_default_dm-worker-f57db5c5baeeb6a1e4fad376d3723b81eaa1b954ea33e86f5dfbd67b548a8bbe.log](https://github.com/pingcap/tiflow/files/7947443/dm-worker-1_default_dm-worker-f57db5c5baeeb6a1e4fad376d3723b81eaa1b954ea33e86f5dfbd67b548a8bbe.log)

```
```
{"log":"panic: runtime error: invalid memory address or nil pointer dereference\n","stream":"stderr","time":"2022-01-26T16:16:02.915207495Z"}
{"log":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2bcc8f2]\n","stream":"stderr","time":"2022-01-26T16:16:02.915222595Z"}
{"log":"\n","stream":"stderr","time":"2022-01-26T16:16:02.915226296Z"}
{"log":"goroutine 1596 [running]:\n","stream":"stderr","time":"2022-01-26T16:16:02.915229596Z"}
{"log":"github.com/pingcap/tidb/br/pkg/lightning/checkpoints.(*TableCheckpoint).Apply(0x0, 0xc00a520930)\n","stream":"stderr","time":"2022-01-26T16:16:02.915285898Z"}
{"log":"\u0009github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/checkpoints/checkpoints.go:362 +0x52\n","stream":"stderr","time":"2022-01-26T16:16:02.9153269Z"}
{"log":"github.com/pingcap/tidb/br/pkg/lightning/web.(*checkpointsMap).update(0x5e04c98, 0xc00a3d96e0, 0x0, 0x0, 0x0)\n","stream":"stderr","time":"2022-01-26T16:16:02.9153323Z"}
{"log":"\u0009github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/web/progress.go:60 +0x2b2\n","stream":"stderr","time":"2022-01-26T16:16:02.915336Z"}
{"log":"github.com/pingcap/tidb/br/pkg/lightning/web.BroadcastCheckpointDiff(0xc00a3d96e0)\n","stream":"stderr","time":"2022-01-26T16:16:02.9153396Z"}
{"log":"\u0009github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/web/progress.go:157 +0x3b\n","stream":"stderr","time":"2022-01-26T16:16:02.915360601Z"}
{"log":"github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).listenCheckpointUpdates.func1(0xc000739920, 0xc00914b358, 0xc00915c290, 0xc005661ed8, 0xc005812140)\n","stream":"stderr","time":"2022-01-26T16:16:02.915364301Z"}
{"log":"\u0009github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:1004 +0x1bf\n","stream":"stderr","time":"2022-01-26T16:16:02.915367802Z"}
{"log":"created by github.com/pingcap/tidb/br/pkg/lightning/restore.(*Controller).listenCheckpointUpdates\n","stream":"stderr","time":"2022-01-26T16:16:02.915538809Z"}
{"log":"\u0009github.com/pingcap/tidb@v1.1.0-beta.0.20220124083611-18fc286fbf0d/br/pkg/lightning/restore/restore.go:987 +0x17f\n","stream":"stderr","time":"2022-01-26T16:16:02.915545909Z"}
```

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
master
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by glorv**
### What problem does this PR solve?

Issue Number: close #4486, close #4489

### What is changed and how it works?
Update tidb dep to the newest version. pingcap/tidb#32011 will fix these two bugs. 

### Check List 

Tests 

 - chaos test
  - manually trigger chaos test result can be seen in https://github.com/glorv/ticdc/pull/1

Code changes

Side effects

Related changes

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by glorv** [comment]
/hold
Waiting for the test result of https://github.com/glorv/ticdc/pull/1

**Comment by glorv** [comment]
/unhold
chaos test result can be seen at https://github.com/glorv/ticdc/runs/5137105665. Load phase doesn't trigger failure anymore. One of the case (base(network emulation base)) failed, but this is caused by sharding ddl. So I think the bug in the load phase is fixed.

**Review by Ehco1996 — APPROVED** [review]
LGTM

**Comment by glorv** [comment]
/hold
Need to fix the tests first

**Comment by glorv** [comment]
blocked by #4582

**Comment by glorv** [comment]
@lance6716  Explicitly disabled new collation in https://github.com/pingcap/tiflow/pull/4557/commits/caa5050d7b6043723bb6be72faec740c04b81bd2 for schema tracker, PTAL again.

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
