### PR TITLE
kv(ticdc): fix state.lastResolvedTs fallback issue

### LINKED ISSUE #7309: fix state.lastResolvedTs fallback issue

### PR DESCRIPTION
**Pull request by sdojjy**
### What problem does this PR solve?

Issue Number: close #7309

### What is changed and how it works?
the previous logic is:  if the newly resolved ts sent by tikv is smaller than state.lastResolvedTs , not advance the state.lastResolvedTs value
but in #7079 we changed this behavior by mistake

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Review by overvenus — COMMENTED** [review]
Could you add a test?

**Review by asddongmen — APPROVED** [review]

**Pull request merged**
