### PR TITLE
test(engine): add DM sync_collation integration test

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref #6776

### What is changed and how it works?

as title

#### Tests 

 - Integration test

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
blocked by https://github.com/pingcap/tidb/issues/37241

**Review by gozssky — APPROVED** [review]

**Review by maxshuang — APPROVED** [review]

**Comment by lance6716** [comment]
@CharlesCheung96 engine integration test is not working at this time, because the other two tests rely on a unfinished feature "task left finish message while exit"

**Comment by CharlesCheung96** [comment]
> @CharlesCheung96 engine integration test is not working at this time, because the other two tests rely on an unfinished feature "task left finish message while exit"

Please add a TODO comment in corresponding cases.

**Comment by lance6716** [comment]
> > @CharlesCheung96 engine integration test is not working at this time, because the other two tests rely on an unfinished feature "task left finish message while exit"
> 
> Please add a TODO comment in corresponding cases.

OK, I'll do it in next PR, very soon.

**Review by CharlesCheung96 — APPROVED** [review]

**Pull request merged**
