### PR TITLE
test(engine): fix fake job integration test fail when the worker is finished

### LINKED ISSUE #6978: fake(engine): parseExtBytes returns error
### What did you do?

Run a Fake job to completion.

### What did you expect to see?

The job's status should go to `Finished`.

### What did you see instead?

The job master keeps failing over.

`
[2022/09/06 03:46:50.132 +00:00] [INFO] [base_jobmaster.go:279] ["worker start exiting"] [job_id=d7a319a9-6e40-4d28-ae85-7a3891f33df2] [cause="invalid character 'w' looking for beginning of value"] [causeVerbose="invalid character 'w' looking for beginning of value\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.Trace\n\tgithub.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/juju_adaptor.go:15\ngithub.com/pingcap/tiflow/engine/framework/fake.parseExtBytes\n\tgithub.com/pingcap/tiflow/engine/framework/fake/fake_master.go:548\ngithub.com/pingcap/tiflow/engine/framework/fake.(*Master).tickedCheckWorkers\n\tgithub.com/pingcap/tiflow/engine/framework/fake/fake_master.go:333\ngithub.com/pingcap/tiflow/engine/framework/fake.(*Master).Tick\n\tgithub.com/pingcap/tiflow/engine/framework/fake/fake_master.go:388\ngithub.com/pingcap/tiflow/engine/framework.(*DefaultBaseJobMaster).Poll\n\tgithub.com/pingcap/tiflow/engine/framework/base_jobmaster.go:236\ngithub.com/pingcap/tiflow/engine/framework/internal/eventloop.(*Runner[...]).doRun\n\tgithub.com/pingcap/tiflow/engine/framework/internal/eventloop/runner.go:90\ngithub.com/pingcap/tiflow/engine/framework/internal/eventloop.(*Runner[...]).Run\n\tgithub.com/pingcap/tiflow/engine/framework/internal/eventloop/runner.go:60\ngithub.com/pingcap/tiflow/engine/executor/worker.(*TaskRunner).launchTask.func1\n\tgithub.com/pingcap/tiflow/engine/executor/worker/task_runner.go:223\nruntime.goexit\n\truntime/asm_arm64.s:1263"]
`

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

```console
ca31feec87f59d77a46e97879c1fccb2e000d754
```

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve?

Issue Number: close #6978 

### What is changed and how it works?
Set fake worker inner status to extMsg even the case when worker is finished or canceled

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by gozssky — APPROVED** [review]

**Comment by amyangfei** [comment]
Integration test failed, seems caused by incorrect handled curl output. What about trying `curl -s`

```
[2022-09-06T07:32:23.125Z]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

[2022-09-06T07:32:23.125Z]                                  Dload  Upload   Total   Spent    Left  Speed

[2022-09-06T07:32:23.125Z] 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   479  100   479    0     0   150k      0 --:--:-- --:--:-- --:--:--  233k

[2022-09-06T07:32:23.382Z] {"id":"d0baa6f3-0e47-4a83-9413-bfc8efd3de0b", "type":"FakeJob", "state":"Finished", "config":"ewogICJqb2ItbmFtZSI6ICJ0ZXN0X2pvYl9maW5pc2hlZCIsCiAgIndvcmtlci1jb3VudCI6IDIsCiAgInRhcmdldC10aWNrIjogMTAwLAogICJldGNkLXdhdGNoLWVuYWJsZSI6IHRydWUsCiAgImV0Y2QtZW5kcG9pbnRzIjogWyJldGNkLXN0YW5kYWxvbmU6MjM3OSJdLAogICJldGNkLXdhdGNoLXByZWZpeCI6ICIvdGVzdF9qb2JfZmluaXNoZWQvIgp9Cg==", "detail":"YWxsIHdvcmtlcnMgaGF2ZSBiZWVuIGZpbmlzaGVk", "error":{"code":"None", "message":"", "not_leader":null}}false

[2022-09-06T07:32:23.382Z] failed to execute cmd:  curl "http://127.0.0.1:10245/api/v1/jobs/d0baa6f3-0e47-4a83-9413-bfc8efd3de0b" | tee /dev/stderr | jq -e '.status == "Finished"'
```

@maxshuang

**Comment by gozssky** [comment]
> [2022-09-06T07:32:23.382Z] failed to execute cmd:  curl "http://127.0.0.1:10245/api/v1/jobs/d0baa6f3-0e47-4a83-9413-bfc8efd3de0b" | tee /dev/stderr | jq -e '.status == "Finished"'

It seems we should check `state` instead of `status`.

**Comment by maxshuang** [comment]
> > [2022-09-06T07:32:23.382Z] failed to execute cmd:  curl "http://127.0.0.1:10245/api/v1/jobs/d0baa6f3-0e47-4a83-9413-bfc8efd3de0b" | tee /dev/stderr | jq -e '.status == "Finished"'
> 
> It seems we should check `state` instead of `status`.

I am fixing it.

**Pull request merged**
