### PR TITLE
syncer(dm): split big transaction when flush checkpoint

### LINKED ISSUE #5010: DM may meet `Error 8004: Transaction is too large, size: xxx` when update checkpoint
### What did you do?

https://asktug.com/t/topic/603512

seems when there're many tables and big TableInfo, DM will meet this problem. And don't know why v5.4 is more error-prone then earlier versions.

This problem may auto-resume but in some very bad cases I guess auto-resume will not help. In that case, user can split task to many smaller tasks that contain part of tables to be replicated.

### What did you expect to see?

_No response_

### What did you see instead?

_No response_

### Versions of the cluster

v5.4.0

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### LINKED ISSUE #7159: dm loss upstream table structure when enter sync stage and failed immediately
### What did you do?

start an all mode task, and failed when enter sync stage immediately

### What did you expect to see?

`operate-schema get` return upstream table info

### What did you see instead?

`operate-schema get` return downstream table info

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
(paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #5010 close #7159 ref #6784 

### What is changed and how it works?
as title

#### Tests 

 - Integration test

### Release note 

```release-note
DM will try to persist upstream table structure from dump files when firstly switch to sync unit
```

### CODE REVIEW

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Review by buchuitoudegou — APPROVED** [review]

**Comment by lance6716** [comment]
/hold

need to fix CI

**Comment by lance6716** [comment]
/hold
fixing CI

**Pull request merged**
