### PR TITLE
test(ticdc): Fix kv ut meet `panic: close of closed channel in cdc/kv`

### LINKED ISSUE #4135: panic: close of closed channel in cdc/kv
### Which jobs are flaking?

CDC-UT

### Which test(s) are flaking?

unit test github.com/pingcap/tiflow/cdc/kv

### Jenkins logs or GitHub Actions link

```log
panic: close of closed channel
goroutine 3486 [running]:
github.com/pingcap/tiflow/cdc/kv.(*clientSuite).TestRegionWorkerExitWhenIsIdle.func1.1(0xc001684240, 0xc0007641a0, 0xc002326120)
	/home/jenkins/agent/workspace/atom-ut/tiflow/cdc/kv/client_test.go:3348 +0x39
github.com/pingcap/tiflow/cdc/kv.(*clientSuite).TestRegionWorkerExitWhenIsIdle.func1(0x6b20130, 0xc00089aa50)
	/home/jenkins/agent/workspace/atom-ut/tiflow/cdc/kv/client_test.go:3359 +0x26e
github.com/pingcap/tiflow/cdc/kv.(*mockChangeDataService).EventFeed.func1(0xc001e14370, 0x6b20130, 0xc00089aa50)
	/home/jenkins/agent/workspace/atom-ut/tiflow/cdc/kv/client_test.go:255 +0x62
created by github.com/pingcap/tiflow/cdc/kv.(*mockChangeDataService).EventFeed
	/home/jenkins/agent/workspace/atom-ut/tiflow/cdc/kv/client_test.go:254 +0x38f
```

https://ci.pingcap.net/blue/organizations/jenkins/atom-ut/detail/atom-ut/7559/tests/

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### PR DESCRIPTION
**Pull request by maxshuang**
### What problem does this PR solve?

Issue Number: close #4135 

### What is changed and how it works?
(1) use atomic int to avoid close channel many times
(2) use a smaller connectionAge and heartbeat interval to shorten closed connection detcetion 

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]
Bravo!

**Comment by maxshuang** [comment]
I will hold this pr for one day and continuous running the verify to check if we can affectively avoid timeout.

**Pull request merged**
