### PR TITLE
test: add test for list partition table

### PR DESCRIPTION
**Pull request by crazycs520**
### What problem does this PR solve? 

This PR add test for https://github.com/pingcap/tidb/issues/20678.

### What is changed and how it works?

N/A

### Check List 

Tests 

 - Integration test

Code changes

 - N/A

Side effects

 - N/A

Related changes

 - N/A

### Release note
- N/A

### CODE REVIEW

**Comment by amyangfei** [comment]
Will this feature be picked to TiDB 4.0, or it is 5.0 only?

**Comment by crazycs520** [comment]
> Will this feature be picked to TiDB 4.0, or it is 5.0 only?

This feature is 5.0 only.

**Comment by hi-rustin** [comment]
/assign 
I will continue to move it forward.

**Comment by hi-rustin** [comment]
I have no time to work on this. So I am going to close this PR. Thanks!

**Pull request closed without merging**
