### PR TITLE
entry (ticdc):remove useless code in entry package

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve?

Issue Number: ref #10457

### What is changed and how it works?

- Removing unnecessary old code in `cdc/entry` package. 
- Move `schema_test.go` from `cdc/owner` to `cdc/entry`, where it should belongs.

#### Tests 

 - Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Review by asddongmen — COMMENTED** [review]
/retest

**Review by asddongmen — COMMENTED** [review]
/retest

**Pull request merged**
