### PR TITLE
dmctl(dm): add more warnings and update help message

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/5220

### What is changed and how it works?

add more warnings.

also update help message

### Check List 

Tests 

 - Integration test

Related changes

 - Need to update the documentation

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by GMHDBJD — APPROVED** [review]
LGTM, need update docs

**Review by Ehco1996 — APPROVED** [review]
LGTM

**Pull request merged**
