### PR TITLE
api(ticdc): extract forwardToOwnerMiddleware

### LINKED ISSUE #5830: Simplify forwardToOwner in TiCDC API/v1
### Is your feature request related to a problem?

`forwardToOwner()` logic occurs in several handlers in TiCDC API v1, and it can be extracted as a Gin Middleware.

### Describe the feature you'd like

Extracting forwardToOwner() as a Gin Middleware.

### Describe alternatives you've considered

_No response_

### Teachability, Documentation, Adoption, Migration Strategy

_No response_

### PR DESCRIPTION
**Pull request by eastfisher**
### What problem does this PR solve?

Issue Number: close #5830

### What is changed and how it works?

Extract a function called forwardToOwnerMiddleware() which is used as a Gin Middleware.

#### Tests 

 - No code

##### Will it cause performance regression or break compatibility?

No.

##### Do you need to update user documentation, design documentation or monitoring documentation?

No.

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Comment by sdojjy** [comment]
why make this change? some ready-only requests can be handled by the non-owner nodes.

**Comment by eastfisher** [comment]
> why make this change? some ready-only requests can be handled by the non-owner nodes.

Hi! I found that these handlers all check current server is owner or not. If it is not owner, then forward request to owner, or handle it locally.

Other handlers which does not need to check owner role are not changed in this PR.

**Comment by asddongmen** [comment]
Thank you for your contribution!

**Review by asddongmen — APPROVED** [review]

**Review by sdojjy — APPROVED** [review]

**Pull request merged**
