### PR TITLE
dm(engine): fetch source status when API call

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref #5504 

### What is changed and how it works?

as title.

#### Tests 

 - pass existing test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by D3Hunter — APPROVED** [review]

**Comment by lance6716** [comment]
PTAL @GMHDBJD

**Review by buchuitoudegou — APPROVED** [review]
Not familiar with `engine`. rest lgtm. Please hold until @GMHDBJD approves

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
