### PR TITLE
metrics(cdc): fix mq sink write row count metrics.

### LINKED ISSUE #3431: Sink write rows doesn't represent the real rows when sink is MQ
### What did you do?

image

When sink is MQ,  `txn_batch_size` represents the count of messages instead of the count of rows.

### What did you expect to see?

The metric is accurate when sink is MQ.

### What did you see instead?

The metric is incorrect when sink is MQ.

### Versions of the cluster

master

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #3431 

### What is changed and how it works?
image

image

For Canal-JSON, `sink-write-rows-count` is not correctly recorded, this PR only fixes Canal-JSON at the moment.

Maybe we should take further investigation into sink related metrics, and tries to unify them together.

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Review by overvenus — APPROVED** [review]
LGTM

**Review by zhaoxinyu — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Comment by 3AceShowHand** [comment]
/cherry-pick-release-5.3

**Pull request merged**
