### PR TITLE
metrics(engine): add e2e test for syncer metrics

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/5493 

### What is changed and how it works?

check metrics has framework label in e2e test.

#### Tests 

 - Integration test

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Comment by lance6716** [comment]
ping @GMHDBJD

**Comment by lance6716** [comment]
ping @maxshuang

**Comment by lance6716** [comment]
PTAL @GMHDBJD @maxshuang

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
