### PR TITLE
ci(engine): upgrade ci env from ubuntu 18.04 to 20.04

### PR DESCRIPTION
**Pull request by amyangfei**
### What problem does this PR solve?

Issue Number: ref #6680

### What is changed and how it works?

- Upgrade ubuntu to 20.04 in dataflow engine chaos ci

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
None
```

### CODE REVIEW

**Comment by amyangfei** [comment]
chaos-mesh@v1.0.0 is not compatible with ubuntu 22.04. https://github.com/pingcap/tiflow/runs/7759195737?check_suite_focus=true

**Comment by amyangfei** [comment]
Ubuntu 20.04 works fine
https://github.com/pingcap/tiflow/runs/7760648791?check_suite_focus=true

**Comment by amyangfei** [comment]
What about upgrading DM env in another PR @lance6716

**Review by lance6716 — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Pull request merged**
