### PR TITLE
config(ticdc): increase the default table memory quota to 64MiB

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/7030

### What is changed and how it works?
Increase the default table memory quota to 64MiB.

#### Tests 

 - Unit test

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
Increase the default table memory quota to 64MiB
```

### CODE REVIEW

**Review by nongfushanquan — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]
any rationale to choose this value?

**Comment by hi-rustin** [comment]
> any rationale to choose this value?

Please see the issue.

**Pull request merged**
