### PR TITLE
owner(cdc): backport stale metrics fix to 5.4

### PR DESCRIPTION
**Pull request by liuzix**
### What problem does this PR solve?
Issue Number: ref #4774

### What is changed and how it works?
- This PR is the combined cherry-pick of both #4775 and #4998

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test

### Release note 

```release-note
Fix TiCDC incorrectly display stale metrics data on dashboard.
```

### CODE REVIEW

**Review by nongfushanquan — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Comment by asddongmen** [comment]
```
[2022-04-24T13:31:53.519Z]         	Test:       	TestNoFinishOperationBeforeSyncIsReceived 
```
This test is failed. 
Should this https://github.com/pingcap/tiflow/pull/5011 be cherr-picked to 5.4 release branch too?

**Review by hi-rustin — APPROVED** [review]

**Pull request merged**
