### PR TITLE
metrics(dm): move alert rules from dm-ansible

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve?

Issue Number: ref #4654 

### What is changed and how it works?

move dashboard.json and alert rules out of dm-ansible dir, i will adapted the CI after this PR merged

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by Ehco1996** [comment]
@lance6716  i found forget the alert manager rules when i change the CI scripts 😭😭  ptal

**Review by lance6716 — APPROVED** [review]
why some files are kept old version, but grafana JSON get moved

**Comment by Ehco1996** [comment]
> why some files are kept old version, but grafana JSON get moved


As we are introducing alert rules, it was not appropriate to put the rule and dashboard in the same folder, so I moved them around a bit to match the cdc directory structure

https://github.com/pingcap/tiflow/tree/master/metrics

**Comment by lance6716** [comment]
why some files are kept old version?

**Comment by Ehco1996** [comment]
> why some files are kept old version?

i have replied [here](https://github.com/pingcap/tiflow/pull/4726#issuecomment-1055047678) before, i will delete this file after ci pr is merged

**Comment by lance6716** [comment]
> > why some files are kept old version?
> 
> i have replied [here](https://github.com/pingcap/tiflow/pull/4726#issuecomment-1055047678) before, i will delete this file after ci PR is merged

So my question is, why old version of some files will be deleted in future, but others will be deleted now?

**Comment by Ehco1996** [comment]
> > > why some files are kept old version?
> > 
> > 
> > i have replied [here](https://github.com/pingcap/tiflow/pull/4726#issuecomment-1055047678) before, i will delete this file after ci PR is merged
> 
> So my question is, why old version of some files will be deleted in future, but others will be deleted now?

no files are deleted now? you mean grafana jsons in metrcis ? they are not used in CI now (CI still use dm-ansible dir)

**Comment by Ehco1996** [comment]
```
-03-07T07:54:53.795Z] [2022/03/07 15:54:08.753 +08:00] [ERROR] [source_worker.go:777] ["fail to operate subtask stage"] [stage="{\"expect\":2,\"source\":\"mysql-replica-02\",\"task\":\"test\"}"] ["is deleted"=false] [error="[code=40051:class=dm-worker:scope=internal:level=high], Message: current stage is Running but not paused, invalid"] [errorVerbose="[code=40051:class=dm-worker:scope=internal:level=high], Message: current stage is Running but not paused, invalid\ngithub.com/pingcap/tiflow/dm/pkg/terror.(*Error).Generate\n\t/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/pkg/terror/terror.go:267\ngithub.com/pingcap/tiflow/dm/dm/worker.(*SubTask).Resume\n\t/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/subtask.go:606\ngithub.com/pingcap/tiflow/dm/dm/worker.(*SourceWorker).OperateSubTask\n\t/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/source_worker.go:638\ngithub.com/pingcap/tiflow/dm/dm/worker.(*SourceWorker).operateSubTaskStage\n\t/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/source_worker.go:834\ngithub.com/pingcap/tiflow/dm/dm/worker.(*SourceWorker).operateSubTaskStageWithoutConfig\n\t/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/source_worker.go:853\ngithub.com/pingcap/tiflow/dm/dm/worker.(*SourceWorker).handleSubTaskStage\n\t/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/source_worker.go:774\ngithub.com/pingcap/tiflow/dm/dm/worker.(*SourceWorker).observeSubtaskStage\n\t/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/source_worker.go:732\ngithub.com/pingcap/tiflow/dm/dm/worker.(*SourceWorker).EnableHandleSubtasks.func1\n\t/home/jenkins/agent/workspace/dm_ghpr_integration_test/go/src/github.com/pingcap/tiflow/dm/dm/worker/source_worker.go:492\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"]
```

/run-dm-integration-tests

**Pull request merged**
