### PR TITLE
syncer, sqlmodel: support source TableInfo contains hidden column

### LINKED ISSUE #8603: multi-valued index in mysql 8.x can't be synced to downstream tidb cluster by DM
### What did you do?

1. in upstream mysql 8.0
    create table include jason cloumn
    add multi-valued index on jason key-value
```sql
mysql> show create table mvindex.user_data1;
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table      | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| user_data1 | CREATE TABLE `user_data1` (
  `uid` bigint NOT NULL AUTO_INCREMENT,
  `j` json DEFAULT NULL,
  `j2` json DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE KEY `j2` ((cast(json_extract(`j2`,_utf8mb4'$[*]') as signed array)),`uid`),
  KEY `k_1` (`update_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1000001 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

```
2. in downstream tidb
    check data and schema can be synced 
```sql
mysql> show create table user_data1;
+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table      | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| user_data1 | CREATE TABLE `user_data1` (
  `uid` bigint(20) NOT NULL AUTO_INCREMENT,
  `j` json DEFAULT NULL,
  `j2` json DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`uid`) /*T![clustered_index] CLUSTERED */,
  KEY `k_1` (`update_time`),
  UNIQUE KEY `j2` ((cast(json_extract(`j2`, _utf8mb4'$[*]') as signed array)),`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci AUTO_INCREMENT=1030001 |
+------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

```

### What did you expect to see?

Dm work normal for multi-valued index

### What did you see instead?

            "subTaskStatus": [
                {
                    "name": "dm_with_mvindex",
                    "stage": "Paused",
                    "unit": "Sync",
                    "result": {
                        "isCanceled": false,
                        "errors": [
                            {
                                "ErrCode": 36027,
                                "ErrClass": "sync-unit",
                                "ErrScope": "internal",
                                "ErrLevel": "high",
                                "Message": "startLocation: [position: (binlog.000001, 355713380), gtid-set: 5e5c71f8-c71d-11ed-aca1-4ae925081efd:1-659], endLocation: [position: (binlog.000001, 355713876), gtid-set: 5e5c71f8-c71d-11ed-aca1-4ae925081efd:1-659]: gen update sqls failed, sourceTable: `mvindex`.`user_data1`, targetTable: `mvindex`.`user_data1`: Column count doesn't match value count: 6 (columns) vs 5 (values)",
                                "RawCause": "",
                                "Workaround": "Please check the log files to see if a related DDL has been skipped, and you could use `operate-schema` to get and set the table structure."
                            }
                        ],


### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
sh-5.1# ./dm-master -V
Release Version: v7.1.0-alpha
Git Commit Hash: 2b1b5ca84768a4e7ab7bc9b12571bbc2944080b9
Git Branch: heads/refs/tags/v7.1.0-alpha
UTC Build Time: 2023-03-20 11:32:46
Go Version: go version go1.20.2 linux/amd64
Failpoint Build: false


```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #8603

#### Tests 

 - Unit test
 - Integration test

### Release note 

```release-note
DM support replicate MySQL 8.0 multi-value index
```

### CODE REVIEW

**Comment by lance6716** [comment]
blocked by https://github.com/pingcap/tidb-tools/pull/712

**Review by asddongmen — APPROVED** [review]

**Pull request merged**
