### PR TITLE
test(dm): add foreign key test

### PR DESCRIPTION
**Pull request by liumengya94**
### What problem does this PR solve?

Issue Number: ref #7598

### What is changed and how it works?
- append `foreign_key_checks=0` in `dsn` if user didn't configure
- add a test to check the inconsistency of upstream and downstream data when tidb set `foreign_key_checks=0` 

#### Tests 

 - Integration test

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
use foreign_key_checks=0 for incremental replication phase, which may cause data inconsistency
```

### CODE REVIEW

**Review by lance6716 — COMMENTED** [review]
rest lgtm. please update the release note part of PR description

**Review by lance6716 — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]

**Pull request merged**
