### PR TITLE
promutil(engine): avoid embedding Mutex and prometheus.Registry in Registry

### PR DESCRIPTION
**Pull request by gozssky**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/5673

Problem Summary:

Avoid embedding `Mutex` and `prometheus.Registry` in `Registry`. 

Refer to uber go style:
* https://github.com/uber-go/guide/blob/master/style.md#avoid-embedding-types-in-public-structs
* https://github.com/uber-go/guide/blob/master/style.md#zero-value-mutexes-are-valid

### What is changed and how it works?

Make `Mutex` and `prometheus.Registry` become private normal members.

#### Tests 

 - Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]
/cc @maxshuang

**Review by maxshuang — APPROVED** [review]

**Pull request merged**
