### PR TITLE
config(dm): fix can't downgrade config

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: ref #4287

### What is changed and how it works?

fix failed CI https://github.com/pingcap/tiflow/actions/workflows/upgrade_dm_via_tiup.yaml

### Check List 

Tests 

 - Integration test

Code changes

 - Has exported function/method change

Related changes

 - Need to cherry-pick to the release branch

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
https://github.com/pingcap/tiflow/actions/runs/1997947623

ci passed

**Review by WizardXiao — APPROVED** [review]

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
