### PR TITLE
sink/codc(ticdc): fix schema-registry options in cli & config file

### PR DESCRIPTION
**Pull request by zhangyangyu**
Issue Number: ref #5338 

### What problem does this PR solve?

1. `schema-registry` option should accompany  the `protocol` option under `sink` section. Otherwise, it's really unnatural.
2. support update `schema-registry` from cli and file.

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by zhaoxinyu — APPROVED** [review]

**Review by hi-rustin — COMMENTED** [review]
Could you please add a test for applyChanges?

**Review by hi-rustin — APPROVED** [review]

**Pull request merged**
