### PR TITLE
engine: register loader metric

### LINKED ISSUE #9359: loader related metric is not registered in dataflow engine
### What did you do?

loader metric, such as `dm_loader_exit_with_error_count` is not registered in df-engine, so no metric about it

### What did you expect to see?

registered, and we can see metric about it

### What did you see instead?

metric is empty

### Versions of the cluster

Dataflow Engine version (run `tiflow version`):

```console
current master
```

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #9359

### What is changed and how it works?
- register loader metric on engine, and remove useless metrics

#### Tests 

 - [x] Unit test
 - Integration test
 - [x] Manual test (add detailed scripts or steps below)
start a job, see we can see metric of loader error
```
# TYPE dm_loader_exit_with_error_count counter
dm_loader_exit_with_error_count{job_id="1110282",project_id="73876",resumable_err="false",source_id="source-1290068",task="1110282",tenant="30073",worker_id="xxxx"} 6
# HELP dm_worker_task_state task state of dm worker in this job
# TYPE dm_worker_task_state gauge
dm_worker_task_state{job_id="1110282",project_id="73876",source_id="source-1290068",task="1110282",tenant="30073"} 15
```
 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]
e2e_dm_test.go has some examples of metrics testing. Manually test is also OK to me.

**Review by lichunzhu — APPROVED** [review]

**Pull request merged**
