### PR TITLE
sink: fix comment.

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve? 
This PR is a fix of #3002, add a comment about exported methods.

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by 3AceShowHand** [comment]
This PR is a fix of #3002, add a comment about exported methods.

@hi-rustin , Do you know why the linter didn't find the problem.

**Comment by hi-rustin** [comment]
> Please add a release note.
> If you don't think this PR needs a release note then fill it with `None`.

@3AceShowHand Could you please refine the release note?

Some testing may be needed about why it is not detected(It may be related to the confidence.) , so hold it for now.

/hold

**Pull request merged**
