### PR TITLE
*: upgrade tidb version

### PR DESCRIPTION
**Pull request by okJiang**
### What problem does this PR solve?

Issue Number: ref  https://github.com/pingcap/tiflow/issues/4287

#### Tests 

 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by Ehco1996 — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]

**Review by amyangfei — COMMENTED** [review]
CI failed because of leak check.
Please add ignore case of `goleak.IgnoreTopFunction("github.com/lestrrat-go/httprc.runFetchWorker")`
ref: https://github.com/pingcap/tidb/pull/38773/files#diff-1e239c61e1a11484c01fefcc04b1af897fce9cfccfb0e7250f9484a47de8b07fR28

**Comment by okJiang** [comment]
> CI failed because of leak check. Please add ignore case of `goleak.IgnoreTopFunction("github.com/lestrrat-go/httprc.runFetchWorker")` ref: [pingcap/tidb#38773 (files)](https://github.com/pingcap/tidb/pull/38773/files#diff-1e239c61e1a11484c01fefcc04b1af897fce9cfccfb0e7250f9484a47de8b07fR28)

It seems exists lots of error, not only goroutine leaks, https://ci2.pingcap.net/job/dm_ghpr_integration_test/10759/display/redirect

**Comment by okJiang** [comment]
should close https://github.com/pingcap/tidb/pull/39108 to pass dm-it

**Pull request merged**
