### PR TITLE
pipeline(ticdc): remove replConfig in pipeline

### LINKED ISSUE #6138: remove replConfig in table pipeline
```go
type pullerNode struct {
    tableName string // quoted schema and table, used in metircs only

    tableID     model.TableID
    replicaInfo *model.TableReplicaInfo
...
```
`ReplicaInfo` should be managed by table_actor.

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: close #6138

### What is changed and how it works?
remove replConfig in pipeline

#### Tests 

 - Unit test

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by asddongmen — APPROVED** [review]

**Review by hi-rustin — APPROVED** [review]
Make sense to me.

**Pull request merged**
