### PR TITLE
controller(ticdc):  add CreateChangefeed func for controller

### LINKED ISSUE #9866: controller(ticdc): add CreateChangefeed func for controller
controller(ticdc): add CreateChangefeed func for controller

### PR DESCRIPTION
**Pull request by sdojjy**
### What problem does this PR solve?

Issue Number: close #9866

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
None`.
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Review by CharlesCheung96 — APPROVED** [review]

**Comment by wuhuizuo** [comment]
> /hold

sorry, wrong ops.

**Pull request merged**
