### PR TITLE
metrics(dm, engine): add support for engine in dm grafana

### PR DESCRIPTION
**Pull request by CharlesCheung96**
### What problem does this PR solve?

Issue Number: ref #6985 

### What is changed and how it works?
1. Add job_id variable to dm grafana.
2. Change some variable variable definition (such as `task, source and instance`) so that engine and dm can share the same grafana.

Note: Currently only `dump` and `syncer` monitors are available to the engine. In the future, load's monitoring will be replaced with lightning's, and monitors for other modules will gradually be added to the grafana panel. Within this week, we will delete [the original dm‘s monitoring files](https://github.com/pingcap/tiflow/tree/master/dm/metrics/grafana) on the premise of maintaining compatibility

#### Tests 

 Verify that the panel can support both engine and dm:
1. engine 
    - [DM-professional](https://snapshots.raintank.io/dashboard/snapshot/EbElU3R2xNH8SlpoVmfnNCscJII5FIPw?orgId=2)
    - [DM-standard](https://snapshots.raintank.io/dashboard/snapshot/Pq3WYKBWBCpL3Y9z42ySn46MqKJcnYue?orgId=2)
 2. dm
     - [DM-professional](https://snapshots.raintank.io/dashboard/snapshot/CyEDi6cff3tE69YhX82Oold67gHX8hwU)
     - [DM-standard](https://snapshots.raintank.io/dashboard/snapshot/7sdskkQTkTwWSjl9QovunOZJM4v5cIrj)

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by maxshuang — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Comment by lance6716** [comment]
> Please confirm whether other repo uses these two files
dm/metrics/grafana/DM-Monitor-Professional.json
dm/metrics/alertmanager/dm_worker.rules.yml
such as tiup repo, ti monitor repo, etc.

I'll help check this

**Comment by CharlesCheung96** [comment]
/run-integration-test tidb=f5487e3f2596cdd63ae9840606c7fff3fb539e03

**Comment by lance6716** [comment]
/hold

wait to revert some changes

**Review by maxshuang — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]

**Pull request merged**
