### PR TITLE
test(dm): fix two unstable tests

### LINKED ISSUE #6702: DM 031 "mysql-replica-02-`shardddl1`.`tb1`" count: 0 != expected: 1
### Which jobs are flaking?

DM-031

### Which test(s) are flaking?

DM-IT shardddl1_1

### Jenkins logs or GitHub Actions link

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/8785/pipeline

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### LINKED ISSUE #6738: DM-DIFFERENT_SCHEMA_INCREMENTAL `"result": true count: 2 != expected: 3`
### Which jobs are flaking?

DM-DIFFERENT_SCHEMA_INCREMENTAL

### Which test(s) are flaking?

DM-IT shardddl_optimistic

### Jenkins logs or GitHub Actions link

https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/8863/pipeline

```


[2022-08-12T09:09:39.146Z] dmctl test cmd: "resume-task test"

[2022-08-12T09:09:39.402Z] command: resume-task test "result": true count: 2 != expected: 3

[2022-08-12T09:09:39.403Z] {

[2022-08-12T09:09:39.403Z]     "op": "Resume",

[2022-08-12T09:09:39.403Z]     "result": true,

[2022-08-12T09:09:39.403Z]     "msg": "",

[2022-08-12T09:09:39.403Z]     "sources": [

[2022-08-12T09:09:39.403Z]         {

[2022-08-12T09:09:39.403Z]             "result": true,

[2022-08-12T09:09:39.403Z]             "msg": "",

[2022-08-12T09:09:39.403Z]             "source": "mysql-replica-01",

[2022-08-12T09:09:39.403Z]             "worker": "worker1"

[2022-08-12T09:09:39.403Z]         },

[2022-08-12T09:09:39.403Z]         {

[2022-08-12T09:09:39.403Z]             "result": false,

[2022-08-12T09:09:39.403Z]             "msg": "[code=38032:class=dm-master:scope=internal:level=high], Message: some error occurs in dm-worker: ErrCode:36027 ErrClass:\"sync-unit\" ErrScope:\"internal\" ErrLevel:\"high\" Message:\"startLocation: [position: (dm-integration-test-go1180-8863-0pw6v-f7rdt-bin|000001.000001, 8547), gtid-set: 457ca6f6-1a1d-11ed-a841-aeaae3c93fd8:1-34], endLocation: [position: (dm-integration-test-go1180-8863-0pw6v-f7rdt-bin|000001.000001, 8591), gtid-set: 457ca6f6-1a1d-11ed-a841-aeaae3c93fd8:1-34]: gen insert sqls failed, sourceTable: `shardddl1`.`tb1`, targetTable: `shardddl`.`tb`: Column count doesn't match value count: 3 (columns) vs 2 (values)\" Workaround:\"Please check the log files to see if a related DDL has been skipped, and you could use `operate-schema` to get and set the table structure.\" , Workaround: Please execute `query-status` to check status.",

[2022-08-12T09:09:39.403Z]             "source": "mysql-replica-02",

[2022-08-12T09:09:39.403Z]             "worker": "worker2"

[2022-08-12T09:09:39.403Z]         }

[2022-08-12T09:09:39.403Z]     ]

[2022-08-12T09:09:39.403Z] }
```

### Anything else we need to know

- Does this test exist for other branches as well?

- Has there been a high frequency of failure lately?

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close #6702 close #6738

### What is changed and how it works?

- `resume` gRPC has internal `query-status` and they are concurrent, so `query-status` may see the old error which is happened before `resume`
- two MySQL sources are concurrent

#### Tests 

 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by buchuitoudegou — APPROVED** [review]

**Comment by lance6716** [comment]
PTAL @D3Hunter @lichunzhu

**Comment by lance6716** [comment]
PTAL @GMHDBJD  @lichunzhu

**Review by D3Hunter — APPROVED** [review]

**Pull request merged**
