### PR TITLE
github(dm): add release-note-none for robot pull request

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/4478

### What is changed and how it works?
add release-note-none for robot pull request. That way tichi won't bully it.

Regarding the linked issue check, we will soon be able to configure the whitelist. https://github.com/ti-community-infra/tichi/pull/882

### Check List 

Tests 

 - No code

Code changes

None

Side effects

None

Related changes

None
### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by amyangfei — APPROVED** [review]

**Comment by hi-rustin** [comment]
block by https://github.com/ti-community-infra/configs/pull/515

**Pull request merged**
