### PR TITLE
mq(ticdc): fix unstable unit test batch encode

### LINKED ISSUE #7790: TestBatchEncode_Batch fails
### What did you do?

Run tests in CI.

### What did you expect to see?

No test fail.

### What did you see instead?

```console
[2022-12-02T08:27:11.494Z] === Failed

[2022-12-02T08:27:11.494Z] === FAIL: cdc/sinkv2/eventsink/mq TestBatchEncode_Batch (0.17s)

[2022-12-02T08:27:11.494Z]     worker_test.go:158: 

[2022-12-02T08:27:11.494Z]         	Error Trace:	/home/jenkins/agent/workspace/ut-check/tiflow/cdc/sinkv2/eventsink/mq/worker_test.go:158

[2022-12-02T08:27:11.494Z]         	            				/home/jenkins/agent/workspace/ut-check/tiflow/cdc/sinkv2/eventsink/mq/asm_amd64.s:1594

[2022-12-02T08:27:11.494Z]         	Error:      	Not equal: 

[2022-12-02T08:27:11.494Z]         	            	expected: 512

[2022-12-02T08:27:11.494Z]         	            	actual  : 2

[2022-12-02T08:27:11.494Z]         	Test:       	TestBatchEncode_Batch

[2022-12-02T08:27:11.494Z] [2022/12/02 16:22:05.653 +08:00] [INFO] [worker.go:134] ["MQ sink non batch worker started"] [namespace=default] [changefeed=test] [protocol=canal-json]

[2022-12-02T08:27:11.494Z] [2022/12/02 16:22:05.655 +08:00] [INFO] [sink.go:318] ["succeed to parse parameter from sink uri"] [protocol=avro] [txnAtomicity=none]

[2022-12-02T08:27:11.494Z] [2022/12/02 16:22:05.655 +08:00] [INFO] [config.go:413] ["Kafka producer uses gzip compression algorithm"]

[2022-12-02T08:27:11.494Z] [2022/12/02 16:22:05.655 +08:00] [WARN] [config.go:86] ["number of partition specified in sink-uri is less than that of the actual topic. Some partitions will not have messages dispatched to"] [sinkUriPartitions=1] [topicPartitions=3]

[2022-12-02T08:27:11.494Z] [2022/12/02 16:22:05.662 +08:00] [INFO] [sink.go:318] ["succeed to parse parameter from sink uri"] [protocol=open-protocol] [txnAtomicity=none]

[2022-12-02T08:27:11.494Z] [2022/12/02 16:22:05.663 +08:00] [INFO] [config.go:413] ["Kafka producer uses gzip compression algorithm"]

[2022-12-02T08:27:11.494Z] [2022/12/02 16:22:05.663 +08:00] [WARN] [config.go:86] ["number of partition specified in sink-uri is less than that of the actual topic. Some partitions will not have messages dispatched to"] [sinkUriPartitions=1] [topicPartitions=3]

[2022-12-02T08:27:11.494Z] [2022/12/02 16:22:05.664 +08:00] [INFO] [kafka_dml_sink.go:85] ["Try to create a DML sink producer"] [baseConfig="{\"BrokerEndpoints\":[\"127.0.0.1:44483\"],\"PartitionNum\":1,\"ReplicationFactor\":1,\"Version\":\"0.9.0.0\",\"MaxMessageBytes\":1048576,\"Compression\":\"gzip\",\"ClientID\":\"unit-test\",\"EnableTLS\":false,\"Credential\":{\"ca-path\":\"\",\"cert-path\":\"\",\"key-path\":\"\",\"cert-allowed-cn\":null},\"SASL\":{\"sasl-user\":\"\",\"sasl-password\":\"\",\"sasl-mechanism\":\"\",\"sasl-gssapi\":{\"sasl-gssapi-auth-type\":0,\"sasl-gssapi-keytab-path\":\"\",\"sasl-gssapi-kerberos-config-path\":\"\",\"sasl-gssapi-service-name\":\"\",\"sasl-gssapi-user\":\"\",\"sasl-gssapi-password\":\"\",\"sasl-gssapi-realm\":\"\",\"sasl-gssapi-disable-pafxfast\":false}},\"AutoCreate\":false,\"DialTimeout\":10000000000,\"WriteTimeout\":10000000000,\"ReadTimeout\":10000000000}"]

[2022-12-02T08:27:11.494Z] [2022/12/02 16:22:05.665 +08:00] [INFO] [kafka_manager.go:219] ["Kafka admin client list topics success"] [duration=13.33µs]

[2022-12-02T08:27:11.494Z] [2022/12/02 16:22:05.665 +08:00] [INFO] [kafka_dml_sink.go:85] ["Try to create a DML sink producer"] [baseConfig="{\"BrokerEndpoints\":[\"127.0.0.1:34080\"],\"PartitionNum\":1,\"ReplicationFactor\":1,\"Version\":\"0.9.0.0\",\"MaxMessageBytes\":1048576,\"Compression\":\"gzip\",\"ClientID\":\"unit-test\",\"EnableTLS\":false,\"Credential\":{\"ca-path\":\"\",\"cert-path\":\"\",\"key-path\":\"\",\"cert-allowed-cn\":null},\"SASL\":{\"sasl-user\":\"\",\"sasl-password\":\"\",\"sasl-mechanism\":\"\",\"sasl-gssapi\":{\"sasl-gssapi-auth-type\":0,\"sasl-gssapi-keytab-path\":\"\",\"sasl-gssapi-kerberos-config-path\":\"\",\"sasl-gssapi-service-name\":\"\",\"sasl-gssapi-user\":\"\",\"sasl-gssapi-password\":\"\",\"sasl-gssapi-realm\":\"\",\"sasl-gssapi-disable-pafxfast\":false}},\"AutoCreate\":false,\"DialTimeout\":10000000000,\"WriteTimeout\":10000000000,\"ReadTimeout\":10000000000}"]

[2022-12-02T08:27:11.495Z] [2022/12/02 16:22:05.665 +08:00] [INFO] [kafka_manager.go:123] ["store topic partition number"] [topic=mock_topic] [partitionNumber=3]

[2022-12-02T08:27:11.495Z] [2022/12/02 16:22:05.665 +08:00] [INFO] [kafka_manager.go:219] ["Kafka admin client list topics success"] [duration=2.81µs]

[2022-12-02T08:27:11.495Z] [2022/12/02 16:22:05.665 +08:00] [INFO] [kafka_manager.go:152] ["Kafka admin client describe topics success"] [duration=9.493µs]

[2022-12-02T08:27:11.495Z] [2022/12/02 16:22:05.665 +08:00] [INFO] [kafka_manager.go:123] ["store topic partition number"] [topic=mock_topic] [partitionNumber=3]

[2022-12-02T08:27:11.495Z] [2022/12/02 16:22:05.665 +08:00] [INFO] [kafka_manager.go:264] ["topic already exists and the cached information has expired"] [topic=mock_topic]

[2022-12-02T08:27:11.495Z] [2022/12/02 16:22:05.665 +08:00] [INFO] [kafka_manager.go:152] ["Kafka admin client describe topics success"] [duration=4.421µs]

[2022-12-02T08:27:11.495Z] [2022/12/02 16:22:05.665 +08:00] [INFO] [kafka_manager.go:193] ["Kafka admin client describe topic success"] [topic=mock_topic] [partitionNumber=3] [duration=5.933µs]

[2022-12-02T08:27:11.495Z] [2022/12/02 16:22:05.665 +08:00] [INFO] [kafka_manager.go:264] ["topic already exists and the cached information has expired"] [topic=mock_topic]

[2022-12-02T08:27:11.495Z] [2022/12/02 16:22:05.666 +08:00] [INFO] [kafka_manager.go:193] ["Kafka admin client describe topic success"] [topic=mock_topic] [partitionNumber=3] [duration=5.013µs]

```

### Versions of the cluster

master branch

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #7790 

### What is changed and how it works?

send events first, and then batch messages immediately.

#### Tests 

 - Unit test

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by hi-rustin — APPROVED** [review]

**Review by zhaoxinyu — APPROVED** [review]

**Comment by 3AceShowHand** [comment]
/run-integration-test tidb=f5487e3f2596cdd63ae9840606c7fff3fb539e03

**Pull request merged**
