### PR TITLE
Makefile(ticdc): support build cdc in fips mode

### LINKED ISSUE #9962: add support to build FIPS-ready cdc binary
### Is your feature request related to a problem?

From [wiki pedia](https://en.wikipedia.org/wiki/Federal_Information_Processing_Standards):

> The Federal Information Processing Standards (FIPS) of the United States are a set of publicly announced standards that the National Institute of Standards and Technology(NIST) has developed for use in computer systems of non-military United States government agencies and contractors.

### Describe the feature you'd like

add support to build FIPS-ready cdc binary

### Describe alternatives you've considered

_No response_

### Teachability, Documentation, Adoption, Migration Strategy

_No response_

### PR DESCRIPTION
**Pull request by lidezhu**
### What problem does this PR solve?

Issue Number: close #9962 

### What is changed and how it works?
1. add support to build FIPS-ready cdc binary following the info shown in https://github.com/pingcap/tidb/pull/47949
2. add `-fips` in the release version of FIPS-ready binary
image
3. support sanitize version with `-fips` suffix when do version check

#### Tests 

 - Unit test
    Make sure the version sanitize process works with `-fips` suffix;
 - Manual test (add detailed scripts or steps below)
```
ENABLE_FIPS=1 make cdc
go tool nm bin/cdc | grep boring
```
Check the boringcrypto linked via cgo, some function names like:
```
 6d3aa60 t local.crypto/internal/boring._Cfunc__goboringcrypto_AES_cbc_encrypt.abi0
 6d3abc0 t local.crypto/internal/boring._Cfunc__goboringcrypto_AES_ctr128_encrypt.abi0
 6d3ad20 t local.crypto/internal/boring._Cfunc__goboringcrypto_AES_decrypt.abi0
 6d3ade0 t local.crypto/internal/boring._Cfunc__goboringcrypto_AES_encrypt.abi0
 6d3aea0 t local.crypto/internal/boring._Cfunc__goboringcrypto_AES_set_decrypt_key.abi0
 6d3af80 t local.crypto/internal/boring._Cfunc__goboringcrypto_AES_set_encrypt_key.abi0
 6d3b060 t local.crypto/internal/boring._Cfunc__goboringcrypto_BN_bin2bn.abi0
 6d3b140 t local.crypto/internal/boring._Cfunc__goboringcrypto_BN_bn2bin_padded.abi0
 6d3b220 t local.crypto/internal/boring._Cfunc__goboringcrypto_BN_bn2le_padded.abi0
 6d4cec0 t local.crypto/internal/boring._Cfunc__goboringcrypto_BN_free
 6d3b300 t local.crypto/internal/boring._Cfunc__goboringcrypto_BN_free.abi0
 6d3b380 t local.crypto/internal/boring._Cfunc__goboringcrypto_BN_le2bn.abi0
 6d3b460 t local.crypto/internal/boring._Cfunc__goboringcrypto_BN_new.abi0
 6d3b4c0 t local.crypto/internal/boring._Cfunc__goboringcrypto_BN_num_bytes.abi0
 6d3b540 t local.crypto/internal/boring._Cfunc__goboringcrypto_BORINGSSL_bcm_power_on_self_test.abi0
 6d3b5a0 t local.crypto/internal/boring._Cfunc__goboringcrypto_ECDSA_sign.abi0
 6d3b700 t local.crypto/internal/boring._Cfunc__goboringcrypto_ECDSA_size.abi0
 6d3b780 t local.crypto/internal/boring._Cfunc__goboringcrypto_ECDSA_verify.abi0
 6d4cf00 t local.crypto/internal/boring._Cfunc__goboringcrypto_EC_GROUP_free
 6d3b8e0 t local.crypto/internal/boring._Cfunc__goboringcrypto_EC_GROUP_free.abi0
 6d3b960 t local.crypto/internal/boring._Cfunc__goboringcrypto_EC_GROUP_new_by_curve_name.abi0
 6d4cf40 t local.crypto/internal/boring._Cfunc__goboringcrypto_EC_KEY_free
 6d3ba00 t local.crypto/internal/boring._Cfunc__goboringcrypto_EC_KEY_free.abi0
 6d3ba80 t local.crypto/internal/boring._Cfunc__goboringcrypto_EC_KEY_generate_key_fips.abi0
 6d3bb00 t local.crypto/internal/boring._Cfunc__goboringcrypto_EC_KEY_get0_group.abi0
 6d3bb80 t local.crypto/internal/boring._Cfunc__goboringcrypto_EC_KEY_get0_private_key.abi0
 6d3bc00 t local.crypto/internal/boring._Cfunc__goboringcrypto_EC_KEY_get0_public_key.abi0
 6d3bc80 t local.crypto/internal/boring._Cfunc__goboringcrypto_EC_KEY_new_by_curve_name.abi0
 6d3bd20 t local.crypto/internal/boring._Cfunc__goboringcrypto_EC_KEY_set_private_key.abi0
 6d3bde0 t local.crypto/internal/boring._Cfunc__goboringcrypto_EC_KEY_set_public_key.abi0
 6d4cf80 t local.crypto/internal/boring._Cfunc__goboringcrypto_EC_POINT_free
 6d3bea0 t local.crypto/internal/boring._Cfunc__goboringcrypto_EC_POINT_free.abi0
```

##### Will it cause performance regression or break compatibility?
The original binary should not be affected. But the binary build with FIPS support is expected to be slower.

##### Do you need to update user documentation, design documentation or monitoring documentation?
Need to add contents about the support for FIPS-ready binary and how to download it later;

### Release note 

```release-note
Support build fips-ready cdc binary
```

### CODE REVIEW

**Comment by CabinfeverB** [comment]
I found `1000825e0 T crypto/internal/boring/sig.StandardCrypto.abi0` in the go tool nm output? It seems unexpected.

**Comment by lidezhu** [comment]
> I found `1000825e0 T crypto/internal/boring/sig.StandardCrypto.abi0` in the go tool nm output? It seems unexpected.

Updated. The original output is on mac env(tidb binary build with fips mode have similar outupt on mac env). The current output is taken from linux. And it doesn't contain any output like `StandardCrypto.abi0`.

**Review by overvenus — APPROVED** [review]
LGTM, thank you!

**Review by sdojjy — APPROVED** [review]

**Pull request merged**
