### PR TITLE
syncer(dm): skip non-interested ddl before we start use ba list and filter to filter ddls

### LINKED ISSUE #5917: skip non-interested ddl before we start use `ba list` and filter to filter ddls

### PR DESCRIPTION
**Pull request by D3Hunter**
### What problem does this PR solve?

Issue Number: close #5917

### What is changed and how it works?
as title

#### Tests 

 - [x] Unit test
 - Integration test(reuse existing i t)
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by lance6716** [comment]
maybe we can change the target branch to master. The feature branch is to avoid not-finished feature merging into master, but this PR is self-completed. (Not reviewed yet, just guess the content)

**Review by lance6716 — APPROVED** [review]

**Comment by D3Hunter** [comment]
/hold

tidb parser cannot parse some ddls, it'll be taken as uninterested. not sure whether there're ddls which is interested but cannot be parsed. will refine it later.

**Pull request closed without merging**
