### PR TITLE
sink/mq(ticdc): split json.go and add callback

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/5928

### What is changed and how it works?
- split json.go (rename some funcs)
- add callback to encoder
- support the callback for open-protocol

#### Tests 

 - Unit test

##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
None
```

### CODE REVIEW

**Review by 3AceShowHand — APPROVED** [review]

**Review by hi-rustin — COMMENTED** [review]
self check

**Review by zhaoxinyu — APPROVED** [review]

**Pull request merged**
