### PR TITLE
[DNM] cdc/sink: bump sarama to v1.30.0

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with `None`.
```

### CODE REVIEW

**Comment by amyangfei** [comment]
leak test failed
```
[2021-11-18T03:11:20.345Z] goleak: Errors on successful test run: found unexpected goroutines:
[2021-11-18T03:11:20.345Z] [Goroutine 307 in state chan receive, with github.com/klauspost/compress/zstd.(*blockDec).startDecoder on top of the stack:
[2021-11-18T03:11:20.345Z] goroutine 307 [chan receive]:
[2021-11-18T03:11:20.345Z] github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc0010a1040)
[2021-11-18T03:11:20.345Z] 	/nfs/cache/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xd6
[2021-11-18T03:11:20.345Z] created by github.com/klauspost/compress/zstd.newBlockDec
[2021-11-18T03:11:20.345Z] 	/nfs/cache/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b3
[2021-11-18T03:11:20.345Z] 
[2021-11-18T03:11:20.345Z]  Goroutine 308 in state chan receive, with github.com/klauspost/compress/zstd.(*blockDec).startDecoder on top of the stack:
[2021-11-18T03:11:20.345Z] goroutine 308 [chan receive]:
```

**Comment by 3AceShowHand** [comment]
one pr filed for the sarama to fix this issue. delay bump sarama version 

https://github.com/Shopify/sarama/pull/2067

**Pull request closed without merging**
