### PR TITLE
log(all): replace deprecated log.With

### PR DESCRIPTION
**Pull request by gozssky**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/7573

### What is changed and how it works?

Replace deprecated `log.With` with `log.L().With`. See https://github.com/pingcap/log/issues/32.

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]

**Comment by amyangfei** [comment]
lint check failed. https://ci.pingcap.net/blue/organizations/jenkins/lint-check/detail/lint-check/18395/pipeline

**Review by CharlesCheung96 — APPROVED** [review]

**Pull request merged**
