### PR TITLE
metrics (ticdc): add changefeed status alert rules

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve?

Issue Number: ref #9266 

### What is changed and how it works?
image

#### Tests 

 - Manual test (add detailed scripts or steps below)

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by nongfushanquan — APPROVED** [review]

**Review by hi-rustin — APPROVED** [review]

**Comment by asddongmen** [comment]
/hole I need to test one more time.

**Pull request merged**
