### PR TITLE
codec(ticdc): canal-json reused preallocated memory to hold temporal objects, enlarge throughput by 30%

### LINKED ISSUE #7417: canal-json reuse kafka common message field to reduce frequent memory allocation
image

As we can see from the profiling above, `common.NewMsg` allocate 6.42% memory

### PR DESCRIPTION
**Pull request by 3AceShowHand**
### What problem does this PR solve?

Issue Number: close #7417

### What is changed and how it works?

* use preallocated bytes slices to format values, to reduce frequent memory allocation.
* always use the same `common.Msg` struct to hold built mesasge to reduce frequent memory allocation.

```
./workload --database-host 10.2.6.69 --database-db-name wide-column --table-count 1 --row-count 20000000 --thread 32 --tps 20000 --workload-type wide-cloumns
```

On the first 30 minutes, throughput increased from around 3.3 ~ 3.8k to 4.3k ~ 4.8k, around 33%.
image

* On the master branch, 7.18% memory used by `common.NewMsg`
image

* On this PR, `common.NewMsg` does not allocate memory anymore.
image

#### Tests 

 - Unit test

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Comment by 3AceShowHand** [comment]
This PR does not compatible with `sinkV1`, so postpone until the sink v1 deprecated.

**Review by zhaoxinyu — APPROVED** [review]

**Review by asddongmen — APPROVED** [review]

**Comment by hi-rustin** [comment]
> This PR does not compatible with `sinkV1`, so postpone until the sink v1 is deprecated.

/hold

**Pull request closed without merging**
