### PR TITLE
actions(dm): upgrade Ubuntu image version

### LINKED ISSUE #6680: Upgrade deprecated ubuntu in CI environment
### Is your feature request related to a problem?

[Dataflow Engine Chaos: .github#L1](https://github.com/pingcap/tiflow/commit/6e2cd4c308fd4a3f082710c49e08e1234dde216b#annotation_4255926146)
The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002

### Describe the feature you'd like

All ubuntu-18.04 environments include
```bash
upgrade_dm_via_tiup.yaml
27:    runs-on: ubuntu-18.04
73:    runs-on: ubuntu-18.04
185:    runs-on: ubuntu-18.04

dm_upstream_switch.yaml
16:    runs-on: ubuntu-18.04

dm_chaos.yaml
23:    runs-on: ubuntu-18.04

dataflow_engine_chaos.yaml
23:    runs-on: ubuntu-18.04

dm_binlog_999999.yaml
16:    runs-on: ubuntu-18.04
```

### Describe alternatives you've considered

_No response_

### Teachability, Documentation, Adoption, Migration Strategy

_No response_

### PR DESCRIPTION
**Pull request by lance6716**
Signed-off-by: lance6716 <lance6716@gmail.com>

### What problem does this PR solve?

Issue Number: close #6680

#### Tests 

 - No code

### Release note 

```release-note
 `None`.
```

### CODE REVIEW

**Review by amyangfei — APPROVED** [review]
Better to trigger these tests manually and verify it works normally.

**Review by D3Hunter — APPROVED** [review]

**Comment by lance6716** [comment]
waiting https://github.com/pingcap/tiflow/actions/runs/2858096819

**Pull request merged**
