### PR TITLE
openprotocol(ticdc):  fix open protocol java example

### LINKED ISSUE #8842: run open protocol unit test TicdcEventDecoderTest failed
run open protocol unit test TicdcEventDecoderTest failed 
```
Caused by: java.io.EOFException
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:202)
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:170)
        at com.pingcap.ticdc.cdc.TicdcEventDecoder.next(TicdcEventDecoder.java:203)

```

### PR DESCRIPTION
**Pull request by sdojjy**
### What problem does this PR solve?

Issue Number: close #8842

### What is changed and how it works?
sort the example data files

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Review by CharlesCheung96 — APPROVED** [review]

**Comment by CharlesCheung96** [comment]
Please update the pr body to explain why data files should be sorted.

**Review by nongfushanquan — APPROVED** [review]

**Pull request merged**
