### PR TITLE
metrics (ticdc): add ticdc summary dashboard

### LINKED ISSUE #7967: Add a user friendly Grafana dashboard that contains important metrics of TiCDC.
### Is your feature request related to a problem?

The TiCDC dashboard is too complicated to understand, we've received a bounch of complaints about it. 

### Describe the feature you'd like

A user oriented dashboard that contains only key metrics of TiCDC is needed.

### Describe alternatives you've considered

_No response_

### Teachability, Documentation, Adoption, Migration Strategy

_No response_

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve?

Issue Number: close #7967 

### What is changed and how it works?
Add a ticdc summary dashboard for users to take a quick look at TiCDC replicating status.

1. Only keep 25 easy to understand panels:
image

image

image

image

image

image

image

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by nongfushanquan — APPROVED** [review]

**Review by hi-rustin — APPROVED** [review]

**Comment by IANTHEREAL** [comment]
First of all, well done!

Here are some suggestions for changes

Server
* Whether to change the name `Server` to a `TiCDC node/instance monitor`

Changefeed - user-oriented changefeed dashboard
* What does the 2.5 in the status of changefeed mean?
* Users also care about the throughput of changefeed, such as rows/s and MB/s
* I understand that `resolved TS` requires some background knowledge,  maybe it‘s better to move it to dataflow

Dataflow - a full-flow processing panel to troubleshoot basic problems
* whether to change the name `dataflow` to `changefeed internal runtime`

Transaction sink 
* Not quite sure what transaction sink is

cloud storage sink
* add the upload file duration

Redo
* Maybe it is better to move it to dataflow, as a part of the whole process

**Comment by asddongmen** [comment]
> First of all, well done!
> 
> Here are some suggestions for changes
> 
> Server
> 
> * Whether to change the panel name `Server` to a `TiCDC node/instance monitor`
> 
> Changefeed - user-oriented changefeed dashboard
> 
> * What does the 2.5 in the status of changefeed mean?
> * Users also care about the throughput of changefeed, such as rows/s and MB/s
> * I understand that `resolved TS` requires some background knowledge,  maybe it‘s better to move it to `dataflow` panel
> 
> Dataflow - a full-flow processing panel to troubleshoot basic problems
> 
> * whether to change the panel name `dataflow` to `changefeed internal runtime`
> 
> Transaction sink
> 
> * Not quite sure what transaction sink is
> 
> cloud storage sink
> 
> * add the upload file duration
> 
> Redo
> 
> * Maybe it is better to move it to `dataflow` panel, as a part of the whole process

1. 2.5 means nothing, 0 is mapping to normal, 1 is mapping to Error, 2 is mapping to failed, 3 is mapping to stopped, but Grafana will show 2.5 even there is nothing mapping to it, it is inevitable.
2. I will give a brief explaination of `resolved TS` in the description documentation. If there is a gap between `checkpointTs` and `resolvedTs`, we can instantly learn that may be something wrong in the redo / sink component. It is helpful to keep it there.
3. Not all changefeeds will use `redo` function, and it has 4 panel -- not like other conponent that has only 2 panel, so may be it is better to keep it in a seperated row.

**Comment by IANTHEREAL** [comment]
> 3. Not all changefeeds will use `redo` function, and it has 4 panel -- not like other conponent that has only 2 panel, so may be it is better to keep it in a seperated row.

How about putting redo in DR sink (Probably transaction sink)

**Comment by CharlesCheung96** [comment]
> /hold for add redo RPO panel

we wiil add this panel in anthor pr.

**Pull request merged**
