### PR TITLE
discovery,election(engine): remove unused code

### PR DESCRIPTION
**Pull request by gozssky**
### What problem does this PR solve?

Issue Number: ref https://github.com/pingcap/tiflow/issues/6849

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by lonng — APPROVED** [review]

**Review by lance6716 — APPROVED** [review]
So happy

**Pull request merged**
