### PR TITLE
redo(ticdc): replace tableID with Span

### PR DESCRIPTION
**Pull request by overvenus**
### What problem does this PR solve?

Issue Number: ref #7720 

### What is changed and how it works?

Replace TableID with Span in redo.

#### Tests 

 - Unit test
 - Integration test

##### Will it cause performance regression or break compatibility?

No.

##### Do you need to update user documentation, design documentation or monitoring documentation?

No.

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by zhaoxinyu — APPROVED** [review]

**Comment by zhaoxinyu** [comment]
Please fix the compiling issue. Rest LGTM.
```
# github.com/pingcap/tiflow/pkg/spanz
pkg/spanz/convert.go:67:11: undefined: model
make: *** [cdc] Error 2
```

**Review by amyangfei — APPROVED** [review]

**Pull request merged**
