### PR TITLE
test: enable tls test for DM

### LINKED ISSUE #10413: DM tls test is failed
### What did you do?

as title

### What did you expect to see?

_No response_

### What did you see instead?

_No response_

### Versions of the cluster

master

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by lance6716**
### What problem does this PR solve?

Issue Number: close #10413

### What is changed and how it works?

after etcd upgrading, the default value of `EnableGRPCGateway` becomes true, so we need to manually turn it off. see https://github.com/pingcap/dm/issues/1458

#### Tests 

 - Integration test

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by D3Hunter — APPROVED** [review]

**Comment by lance6716** [comment]
/hold

the log shows there's still connections keeps retrying and fails the TLS handshake. Will locate where it comes

**Review by Benjamin2037 — APPROVED** [review]
LGTM

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
