### PR TITLE
syncer(dm): fix wrong ts array init size

### LINKED ISSUE #5267: Wrong workerJobTSArrayInitSize for lag
### What did you do?

vcDahLsB0M

### What did you expect to see?

workerJobTSArrayInitSize should be 2

### What did you see instead?

4. Although there is no effect on the calculation of lag

### Versions of the cluster

DM version (run `dmctl -V` or `dm-worker -V` or `dm-master -V`):
```console
(paste DM version here, and you must ensure versions of dmctl, DM-worker and DM-master are same)
```
Upstream MySQL/MariaDB server version:
```console
(paste upstream MySQL/MariaDB server version here)
```
Downstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):
```console
(paste TiDB cluster version here)
```
How did you deploy DM: tiup or manually?
```console
(leave TiUP or manually here)
```
Other interesting information (system version, hardware config, etc):
```console
>
>
```

### current status of DM cluster (execute `query-status <task-name>` in dmctl)

```console
(paste current status of DM cluster here)
```

### PR DESCRIPTION
**Pull request by Ehco1996**
### What problem does this PR solve?

Issue Number: close #5267

### Check List 

Tests 

 - No code

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to update key monitor metrics in both TiCDC document and official document

### Release note 

```release-note
`None`.
```

### CODE REVIEW

**Comment by GMHDBJD** [comment]
lint failed

**Review by D3Hunter — APPROVED** [review]
lgtm

**Review by GMHDBJD — APPROVED** [review]
LGTM

**Pull request merged**
