### PR TITLE
dmctl: remove update from operate-source

### LINKED ISSUE #7246: DM: unimplemented command but shown in dmctl
The `dmctl operate-source update` command has never been implemented and should not be shown in `help`.

### PR DESCRIPTION
**Pull request by buchuitoudegou**
### What problem does this PR solve?

Issue Number: close #7246

### What is changed and how it works?
- remove `operate-source update` from `dmctl` hint

#### Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

### Release note 

```release-note
`None`
```

### CODE REVIEW

**Review by lichunzhu — APPROVED** [review]

**Comment by buchuitoudegou** [comment]
https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/9972/pipeline

unstable test for shardddl2?

```
"errors": [

[2022-09-28T08:16:18.920Z]                             {

[2022-09-28T08:16:18.920Z]                                 "ErrCode": 42501,

[2022-09-28T08:16:18.920Z]                                 "ErrClass": "ha",

[2022-09-28T08:16:18.920Z]                                 "ErrScope": "internal",

[2022-09-28T08:16:18.920Z]                                 "ErrLevel": "high",

[2022-09-28T08:16:18.920Z]                                 "Message": "startLocation: [position: (dm-integration-test-go1190-9972-nzgzz-w9dk6-bin.000001, 42228), gtid-set: 36a9b28f-3f05-11ed-8c4d-9a5f4fd22f79:1-194], endLocation: [position: (dm-integration-test-go1190-9972-nzgzz-w9dk6-bin.000001, 42353), gtid-set: 36a9b28f-3f05-11ed-8c4d-9a5f4fd22f79:1-195], origin SQL: [alter table shardddl1.tb1 add column b int after a]: fail to do etcd txn operation: txn commit failed",

[2022-09-28T08:16:18.920Z]                                 "RawCause": "rpc error: code = Unavailable desc = error reading from server: EOF",

[2022-09-28T08:16:18.920Z]                                 "Workaround": "Please check dm-master's node status and the network between this node and dm-master"

[2022-09-28T08:16:18.920Z]                             }

[2022-09-28T08:16:18.920Z]                         ],

[2022-09-28T08:16:18.920Z]                         "detail": null

[2022-09-28T08:16:18.920Z]                     },
```
Seems a network error?

**Comment by buchuitoudegou** [comment]
another unstable test: load task

```
[2022-09-28T08:38:29.598Z] dmctl test cmd: "query-status load_task1"

[2022-09-28T08:38:29.857Z] got=0 expected=1

[2022-09-28T08:38:29.857Z] command: query-status load_task1 different worker in load stage, previous worker: worker1, current worker: worker2 count: 0 != expected: 1, failed the 0-th time, will retry again

[2022-09-28T08:38:32.388Z] got=0 expected=1

[2022-09-28T08:38:32.388Z] command: query-status load_task1 different worker in load stage, previous worker: worker1, current worker: worker2 count: 0 != expected: 1, failed the 1-th time, will retry again

[2022-09-28T08:38:34.291Z] got=0 expected=1

[2022-09-28T08:38:34.291Z] command: query-status load_task1 different worker in load stage, previous worker: worker1, current worker: worker2 count: 0 != expected: 1, failed the 2-th time, will retry again

[2022-09-28T08:38:36.187Z] got=0 expected=1

[2022-09-28T08:38:36.187Z] command: query-status load_task1 different worker in load stage, previous worker: worker1, current worker: worker2 count: 0 != expected: 1, failed the 3-th time, will retry again

[2022-09-28T08:38:38.721Z] got=0 expected=1

[2022-09-28T08:38:38.722Z] command: query-status load_task1 different worker in load stage, previous worker: worker1, current worker: worker2 count: 0 != expected: 1, failed the 4-th time, will retry again

[2022-09-28T08:38:40.704Z] got=0 expected=1

[2022-09-28T08:38:40.704Z] command: query-status load_task1 different worker in load stage, previous worker: worker1, current worker: worker2 count: 0 != expected: 1, failed the 5-th time, will retry again

[2022-09-28T08:38:43.248Z] got=0 expected=1

[2022-09-28T08:38:43.248Z] command: query-status load_task1 different worker in load stage, previous worker: worker1, current worker: worker2 count: 0 != expected: 1, failed the 6-th time, will retry again

[2022-09-28T08:38:45.159Z] got=0 expected=1

[2022-09-28T08:38:45.159Z] command: query-status load_task1 different worker in load stage, previous worker: worker1, current worker: worker2 count: 0 != expected: 1, failed the 7-th time, will retry again

[2022-09-28T08:38:47.699Z] got=0 expected=1

[2022-09-28T08:38:47.699Z] command: query-status load_task1 different worker in load stage, previous worker: worker1, current worker: worker2 count: 0 != expected: 1, failed the 8-th time, will retry again

[2022-09-28T08:38:49.625Z] got=0 expected=1

[2022-09-28T08:38:49.625Z] command: query-status load_task1 different worker in load stage, previous worker: worker1, current worker: worker2 count: 0 != expected: 1, failed the 9-th time, will retry again

[2022-09-28T08:38:52.157Z] {

[2022-09-28T08:38:52.157Z]     "result": true,

[2022-09-28T08:38:52.157Z]     "msg": "",

[2022-09-28T08:38:52.157Z]     "sources": [

[2022-09-28T08:38:52.157Z]         {

[2022-09-28T08:38:52.157Z]             "result": true,

[2022-09-28T08:38:52.157Z]             "msg": "",

[2022-09-28T08:38:52.157Z]             "sourceStatus": {

[2022-09-28T08:38:52.157Z]                 "source": "mysql-replica-01",

[2022-09-28T08:38:52.157Z]                 "worker": "worker2",

[2022-09-28T08:38:52.157Z]                 "result": null,

[2022-09-28T08:38:52.157Z]                 "relayStatus": null

[2022-09-28T08:38:52.157Z]             },

[2022-09-28T08:38:52.157Z]             "subTaskStatus": [

[2022-09-28T08:38:52.157Z]                 {

[2022-09-28T08:38:52.157Z]                     "name": "load_task1",

[2022-09-28T08:38:52.157Z]                     "stage": "Running",

[2022-09-28T08:38:52.157Z]                     "unit": "Sync",

[2022-09-28T08:38:52.157Z]                     "result": null,

[2022-09-28T08:38:52.157Z]                     "unresolvedDDLLockID": "",

[2022-09-28T08:38:52.157Z]                     "sync": {

[2022-09-28T08:38:52.157Z]                         "totalEvents": "0",

[2022-09-28T08:38:52.157Z]                         "totalTps": "0",

[2022-09-28T08:38:52.157Z]                         "recentTps": "0",

[2022-09-28T08:38:52.157Z]                         "masterBinlog": "(dm-integration-test-go1190-9976-swqn3-jxfbn-bin.000001, 2707)",

[2022-09-28T08:38:52.157Z]                         "masterBinlogGtid": "b142695e-3f08-11ed-9650-d6cbfa19d249:1-12",

[2022-09-28T08:38:52.157Z]                         "syncerBinlog": "(dm-integration-test-go1190-9976-swqn3-jxfbn-bin.000001, 2707)",

[2022-09-28T08:38:52.157Z]                         "syncerBinlogGtid": "b142695e-3f08-11ed-9650-d6cbfa19d249:1-12",

[2022-09-28T08:38:52.157Z]                         "blockingDDLs": [

[2022-09-28T08:38:52.157Z]                         ],

[2022-09-28T08:38:52.157Z]                         "unresolvedGroups": [

[2022-09-28T08:38:52.157Z]                         ],

[2022-09-28T08:38:52.157Z]                         "synced": true,

[2022-09-28T08:38:52.157Z]                         "binlogType": "remote",

[2022-09-28T08:38:52.157Z]                         "secondsBehindMaster": "0",

[2022-09-28T08:38:52.157Z]                         "blockDDLOwner": "",

[2022-09-28T08:38:52.157Z]                         "conflictMsg": ""

[2022-09-28T08:38:52.157Z]                     },

[2022-09-28T08:38:52.157Z]                     "validation": null

[2022-09-28T08:38:52.157Z]                 }

[2022-09-28T08:38:52.157Z]             ]

[2022-09-28T08:38:52.157Z]         }

[2022-09-28T08:38:52.157Z]     ]

[2022-09-28T08:38:52.157Z] }

[2022-09-28T08:38:52.157Z] PASS
```
https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test/detail/dm_ghpr_integration_test/9976/pipeline

**Pull request merged**
