### PR TITLE
tests(ticdc): increase runner swap size to stablize tests

### PR DESCRIPTION
**Pull request by zhangyangyu**
### What problem does this PR solve?

Issue Number: ref #5750 

### What is changed and how it works?

Currently debug level would generate 600/700M log. After change to info level, only 6/7M.

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by zhaoxinyu — APPROVED** [review]

**Review by hi-rustin — APPROVED** [review]

**Comment by hi-rustin** [comment]
Thanks for working on this.

**Pull request merged**
