### PR TITLE
unit_test: fix concurrency test cause etcd race

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve?

Issue Number: ref #4159 

### What is changed and how it works?
- execute test serially

### Check List 

Tests 

 - Unit test

```release-note
`None`.
```

### CODE REVIEW

**Review by lance6716 — APPROVED** [review]

**Review by D3Hunter — APPROVED** [review]

**Comment by D3Hunter** [comment]
still has this error 

https://ci.pingcap.net/blue/rest/organizations/jenkins/pipelines/ut-check/runs/4716/nodes/45/steps/49/log/?start=0

**Pull request merged**
