### PR TITLE
sinkv2(ticdc): observe row size in MQ sink

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve?

Issue Number: close https://github.com/pingcap/tiflow/issues/8286

### What is changed and how it works?

observe row size in MQ sink. 

#### Tests 

 - Manual test
 
##### Will it cause performance regression or break compatibility?
No
##### Do you need to update user documentation, design documentation or monitoring documentation?
No
### Release note 

```release-note
Add missing big row metric in MQ sink
```

### CODE REVIEW

**Review by sdojjy — APPROVED** [review]

**Review by zhaoxinyu — APPROVED** [review]

**Comment by hi-rustin** [comment]
Tested locally:
image

**Pull request merged**
