### PR TITLE
error (ticdc): add mysql ddl error blacklist

### LINKED ISSUE #1519: Incompatible DDL can't be cancelled or skipped
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.
  
   1. setup replication from TiDB to MySQL using TiCDC
   2. run the following SQLs in upstream TiDB: `create table t6 (id int primary key, a int);`, `alter table t6 rename column a to d;`

2. What did you expect to see?

   DDL is replicated normally or fast fail

3. What did you see instead?

    owner meets the following error:
    `[ERROR] [changefeed.go:714] ["Execute DDL failed"] [ChangeFeedID=test-cdc-7101] [error="[CDC:ErrMySQLTxnError]Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'column a to d' at line 1"]`

4. Versions of the cluster

    - Upstream TiDB cluster version (execute `SELECT tidb_version();` in a MySQL client):

        master@https://github.com/pingcap/tidb/commit/9f7ed0f44ad8827effa36cf4aca5b3445fe39123

    - TiCDC version (execute `cdc version`):

        master@https://github.com/pingcap/ticdc/commit/9e58fbbc7d377f79512ac1bf34ae09e006097d0a
5. Addition

- The retry timeout is nearly 30min, after changefeed is resumed, the DDL will be retried again.
- The changefeed can't be paused, since in owner, `handleAdminJob` comes after `handleDDL`
- The workaround seems: 1) stop cdc server 2) remove changefeed from etcd; 3) recreate a new changefeed, filter the start-ts of DDL

### PR DESCRIPTION
**Pull request by asddongmen**
### What problem does this PR solve?

Issue Number: close #1519 

### What is changed and how it works?
1. Add a black list for mysql ddl error, when sink encounter these error, it should not retry again.
2. Let owner does not retry changefeed if processor reports an untryable ddl error.

#### Tests 

 - Unit test

### Release note 

```release-note
None
```

### CODE REVIEW

**Review by overvenus — COMMENTED** [review]
Please update release note and add some tests.

**Review by 3AceShowHand — APPROVED** [review]

**Review by nongfushanquan — APPROVED** [review]

**Pull request merged**
